force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/CalculatedDuration__c.field-meta.xml
<CustomField>
    <fullName>CalculatedDuration__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Calculated Duration</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/EstimatedDuration__c.field-meta.xml
<CustomField>
    <fullName>EstimatedDuration__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Estimated Duration</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/RoleSummaryId__c.field-meta.xml
<CustomField>
    <fullName>RoleSummaryId__c</fullName>
    <label>Role Summary</label>
    <referenceTo>TaskRoleSummary__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/TaskRoleSummary__c.object-meta.xml
<CustomObject>
    <label>Task Role Summary</label>
    <nameField>
        <displayFormat>TRS-{00000}</displayFormat>
        <label>Task Role Summary</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Role Summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TaskRoleSummary__c/fields/CalculatedDuration__c.field-meta.xml
<CustomField>
    <fullName>CalculatedDuration__c</fullName>
    <label>Calculated Duration</label>
    <summarizedField>Task__c.CalculatedDuration__c</summarizedField>
    <summaryForeignKey>Task__c.RoleSummaryId__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/EstimatedDuration__c.field-meta.xml
<CustomField>
    <fullName>EstimatedDuration__c</fullName>
    <label>Estimated Duration</label>
    <summarizedField>Task__c.EstimatedDuration__c</summarizedField>
    <summaryForeignKey>Task__c.RoleSummaryId__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/LevelAdjustment__c.field-meta.xml
<CustomField>
    <fullName>LevelAdjustment__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Level Adjustment</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/RolledUpAdjustments__c.field-meta.xml
<CustomField>
    <fullName>RolledUpAdjustments__c</fullName>
    <label>Rolled-Up Adjustments</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/RolledUpCalculatedDuration__c.field-meta.xml
<CustomField>
    <fullName>RolledUpCalculatedDuration__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Rolled-Up Calculated Duration</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/SummaryId__c.field-meta.xml
<CustomField>
    <fullName>SummaryId__c</fullName>
    <label>Summary</label>
    <referenceTo>TaskSummary__c</referenceTo>
    <relationshipName>RoleSummaries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/TaskRoleSummaryId__c.field-meta.xml
<CustomField>
    <fullName>TaskRoleSummaryId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task Role Summary</label>
    <referenceTo>TaskRoleSummary__c</referenceTo>
    <relationshipName>ExtendedTaskRoleSummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/TotalAdjustments__c.field-meta.xml
<CustomField>
    <fullName>TotalAdjustments__c</fullName>
    <formula>RolledUpAdjustments__c + LevelAdjustments__c + LevelAdjustment__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Adjustments</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TaskSummary__c/TaskSummary__c.object-meta.xml
<CustomObject>
    <label>Task Summary</label>
    <nameField>
        <displayFormat>TS-{00000}</displayFormat>
        <label>Task Summary</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TaskSummary__c/fields/TotalAdjustments__c.field-meta.xml
<CustomField>
    <fullName>TotalAdjustments__c</fullName>
    <label>Total Adjustments</label>
    <summarizedField>TaskRoleSummary__c.TotalAdjustments__c</summarizedField>
    <summaryForeignKey>TaskRoleSummary__c.SummaryId__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/TaskRoleSummarySupportTest.cls
/**
 *  Provus Services Quoting
 *  TaskRoleSummarySupportTest
 *  @2021 Provus Inc. All rights reserved.
 */
@IsTest
private class TaskRoleSummarySupportTest extends TestBase {
	static TaskSummary__c newTaskSummary() {
		TaskSummary__c newSummary = new TaskSummary__c();
		CRUDUtility.insertRecords(newSummary);

		return newSummary;
	}

	static TaskRoleSummary__c newTaskRoleSummary(TaskRoleSummary__c parentRecord) {
		TaskRoleSummary__c roleSummary = new TaskRoleSummary__c(
			SummaryId__c = parentRecord.SummaryId__c,
			TaskRoleSummaryId__c = parentRecord.Id
		);
		CRUDUtility.insertRecords(roleSummary);
		return roleSummary;
	}

	static TaskRoleSummary__c newTaskRoleSummary() {
		TaskSummary__c taskSummary = newTaskSummary();
		TaskRoleSummary__c roleSummary = new TaskRoleSummary__c(SummaryId__c = taskSummary.Id);

		CRUDUtility.insertRecords(roleSummary);
		return roleSummary;
	}

	static Task__c newTask(Id roleSummaryId) {
		Task__c task = new Task__c(IsActive__c = true, RoleSummaryId__c = roleSummaryId);
		CRUDUtility.insertRecords(task);
		return task;
	}

	@IsTest
	static void itShouldShouldRollupTasksToParentSummary() {
		TaskRoleSummary__c parentSummary = newTaskRoleSummary();
		TaskRoleSummary__c childSummary = newTaskRoleSummary(parentSummary);

		Task__c task1 = newTask(childSummary.Id);
		task1.CalculatedDuration__c = 100;
		task1.LevelAdjustment__c = 50;
		task1.EstimatedDuration__c = 50;

		Task__c task2 = newTask(childSummary.Id);
		task2.CalculatedDuration__c = 200;
		task2.LevelAdjustment__c = 100;
		task2.EstimatedDuration__c = 100;

		Test.startTest();
		CRUDUtility.updateRecords(new List<Task__c>{ task1, task2 });

		TaskRoleSummary__c testSummary = [
			SELECT Id, RolledUpCalculatedDuration__c, RolledUpAdjustments__c
			FROM TaskRoleSummary__c
			WHERE Id = :parentSummary.Id
			WITH SECURITY_ENFORCED
		];

		System.assertEquals(
			300,
			testSummary.RolledUpCalculatedDuration__c,
			'it should rollup calculated duration to parent'
		);
		System.assertEquals(
			150,
			testSummary.RolledUpAdjustments__c,
			'it should rollup adjustments to parent'
		);
		Test.stopTest();
	}

	@IsTest
	static void itShouldRollupWhenParentAndChildBothChange() {
		TaskRoleSummary__c parentSummary = newTaskRoleSummary();
		TaskRoleSummary__c childSummary = newTaskRoleSummary(parentSummary);

		Task__c task = newTask(childSummary.Id);
		task.CalculatedDuration__c = 100;
		task.LevelAdjustment__c = 50;
		task.EstimatedDuration__c = 50;

		CRUDUtility.updateRecords(task);

		parentSummary.LevelAdjustment__c = 1500;
		childSummary.LevelAdjustment__c = 500;

		Test.startTest();
		// TODO: Fix logic for same updates in the trigger
		CRUDUtility.updateRecords(new List<TaskRoleSummary__c>{ parentSummary });
		CRUDUtility.updateRecords(new List<TaskRoleSummary__c>{ childSummary });

		TaskRoleSummary__c testSummary = [
			SELECT Id, TotalAdjustments__c
			FROM TaskRoleSummary__c
			WHERE Id = :parentSummary.Id
			WITH SECURITY_ENFORCED
		];

		System.assertEquals(
			2050,
			testSummary.TotalAdjustments__c,
			'it should rollup level adjustments to parent'
		);
		Test.stopTest();
	}
	@IsTest
	static void itShouldShouldRollupLevelAdjustmentsToParentSummary() {
		TaskRoleSummary__c parentSummary = newTaskRoleSummary();
		TaskRoleSummary__c childSummary = newTaskRoleSummary(parentSummary);

		Task__c task = newTask(childSummary.Id);
		task.CalculatedDuration__c = 100;
		task.LevelAdjustment__c = 50;
		task.EstimatedDuration__c = 50;

		CRUDUtility.updateRecords(task);

		childSummary.LevelAdjustment__c = 500;

		Test.startTest();
		CRUDUtility.updateRecords(childSummary);

		TaskRoleSummary__c testSummary = [
			SELECT Id, RolledUpCalculatedDuration__c, RolledUpAdjustments__c
			FROM TaskRoleSummary__c
			WHERE Id = :parentSummary.Id
			WITH SECURITY_ENFORCED
		];

		System.assertEquals(
			550,
			testSummary.RolledUpAdjustments__c,
			'it should rollup level adjustments to parent'
		);
		Test.stopTest();
	}
}