force-app/main/default/objects/Adjustment__c/Adjustment__c.object-meta.xml
<CustomObject>
    <label>Adjustment</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Adjustment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Adjustment__c/fields/AppliedBy__c.field-meta.xml
<CustomField>
    <fullName>AppliedBy__c</fullName>
    <label>Applied By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Rule</fullName>
            </value>
            <value>
                <fullName>Promotion</fullName>
            </value>
            <value>
                <fullName>Incentive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Adjustment__c/fields/AppliedTo__c.field-meta.xml
<CustomField>
    <fullName>AppliedTo__c</fullName>
    <label>Applied To</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Cost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Adjustment__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Rule</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Adjustment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Discount Percent</fullName>
            </value>
            <value>
                <fullName>Discount Amount</fullName>
            </value>
            <value>
                <fullName>Markup Percent</fullName>
            </value>
            <value>
                <fullName>Markup Amount</fullName>
            </value>
            <value>
                <fullName>% Discount</fullName>
            </value>
            <value>
                <fullName>% Markup</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AdjustmentDTO.cls
/**
 *  Provus Services Quoting
 *  AdjustmentDTO
 *  @2022 Provus Inc. All rights reserved.
 */
public with sharing class AdjustmentDTO extends BaseDTO {
	public String type;
	public Decimal amount;
	public Decimal sequence;
	public String method;
	public String appliedTo;
	public String appliedBy;
	public Id adjustmentId;

	public AdjustmentDTO() {
	}

	public Adjustment__c getSObject() {
		Adjustment__c adjustmentSO = new Adjustment__c(
			Type__c = this.type,
			Amount__c = this.amount,
			Sequence__c = this.sequence,
			Method__c = this.method,
			AppliedTo__c = this.appliedTo,
			AppliedBy__c = this.appliedBy,
			Id = this.adjustmentId
		);
		return adjustmentSO;
	}
}