force-app/main/default/objects/Adjustment__c/Adjustment__c.object-meta.xml
<CustomObject>
    <label>Adjustment</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Adjustment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Adjustment__c/fields/NamedRangeId__c.field-meta.xml
<CustomField>
    <fullName>NamedRangeId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Named Range</label>
    <referenceTo>NamedRange__c</referenceTo>
    <relationshipLabel>Adjustments</relationshipLabel>
    <relationshipName>Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NamedRange__c/NamedRange__c.object-meta.xml
<CustomObject>
    <label>Named Range</label>
    <nameField>
        <label>Named Range Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Named Ranges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NamedRange__c/fields/NamedRangeTotalId__c.field-meta.xml
<CustomField>
    <fullName>NamedRangeTotalId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Named Range Total</label>
    <referenceTo>NamedRangeTotal__c</referenceTo>
    <relationshipLabel>Named Ranges</relationshipLabel>
    <relationshipName>NamedRanges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NamedRange__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Named Ranges</relationshipLabel>
    <relationshipName>NamedRanges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NamedRangeTotal__c/NamedRangeTotal__c.object-meta.xml
<CustomObject>
    <label>Named Range Total</label>
    <nameField>
        <displayFormat>NRT-{0000000}</displayFormat>
        <label>Named Range Total</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Named Range Totals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NamedRangeTotal__c/fields/NamedRangeId__c.field-meta.xml
<CustomField>
    <fullName>NamedRangeId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Named Range</label>
    <referenceTo>NamedRange__c</referenceTo>
    <relationshipLabel>Named Range Totals</relationshipLabel>
    <relationshipName>NamedRangeTotals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NamedRangeTotal__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipName>CellRangeTotals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/NamedRangeTestsBase.cls
/**
 *  Provus Services Quoting
 *  NamedRangeTestsBase
 *  @2021 Provus Inc. All rights reserved.
 */
public with sharing abstract class NamedRangeTestsBase extends TestBase {
	public static Adjustment__c newAdjustment(Id namedRangeId) {
		Adjustment__c adjustmentSO = new Adjustment__c(NamedRangeId__c = namedRangeId);
		CRUDUtility.insertRecords(adjustmentSO);
		return adjustmentSO;
	}

	public static NamedRange__c newNamedRange() {
		Quote__c testQuote = newQuote();
		NamedRangeTotal__c namedRangeTotalSO = newNamedRangeTotal(testQuote.Id);
		newNamedRange(testQuote.Id, namedRangeTotalSO.Id);
		return NamedRangeFactory.getNamedRangesForQuote(testQuote.Id)[0];
	}

	public static NamedRange__c newNamedRange(Id quoteId, Id namedRangeTotalId) {
		NamedRange__c namedRangeSO = new NamedRange__c(
			NamedRangeTotalId__c = namedRangeTotalId,
			QuoteId__c = quoteId
		);
		CRUDUtility.insertRecords(namedRangeSO);
		return namedRangeSO;
	}

	public static NamedRange.NamedRangeDO newNamedRangeDO() {
		Quote__c testQuote = newQuote();
		NamedRange.NamedRangeDO testNamedRangeDO = new NamedRange.NamedRangeDO();
		testNamedRangeDO.quoteId = testQuote.Id;

		NamedRangeTotal.NamedRangeTotalDO testNamedRangeTotalDO = new NamedRangeTotal.NamedRangeTotalDO();
		testNamedRangeDO.relatedTotal = testNamedRangeTotalDO;
		return testNamedRangeDO;
	}

	public static NamedRangeTotal__c newNamedRangeTotal(Id quoteId) {
		NamedRangeTotal__c namedRangeTotalSO = new NamedRangeTotal__c(QuoteId__c = quoteId);
		CRUDUtility.insertRecords(namedRangeTotalSO);
		return namedRangeTotalSO;
	}
}