force-app/main/default/objects/Adjustment__c/Adjustment__c.object-meta.xml
<CustomObject>
    <label>Adjustment</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Adjustment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Adjustment__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Rule</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Adjustment__c/fields/NamedRangeId__c.field-meta.xml
<CustomField>
    <fullName>NamedRangeId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Named Range</label>
    <referenceTo>NamedRange__c</referenceTo>
    <relationshipLabel>Adjustments</relationshipLabel>
    <relationshipName>Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Adjustment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Discount Percent</fullName>
            </value>
            <value>
                <fullName>Discount Amount</fullName>
            </value>
            <value>
                <fullName>Markup Percent</fullName>
            </value>
            <value>
                <fullName>Markup Amount</fullName>
            </value>
            <value>
                <fullName>% Discount</fullName>
            </value>
            <value>
                <fullName>% Markup</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NamedRange__c/NamedRange__c.object-meta.xml
<CustomObject>
    <label>Named Range</label>
    <nameField>
        <label>Named Range Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Named Ranges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NamedRange__c/fields/NamedRangeTotalId__c.field-meta.xml
<CustomField>
    <fullName>NamedRangeTotalId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Named Range Total</label>
    <referenceTo>NamedRangeTotal__c</referenceTo>
    <relationshipLabel>Named Ranges</relationshipLabel>
    <relationshipName>NamedRanges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NamedRange__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Named Ranges</relationshipLabel>
    <relationshipName>NamedRanges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NamedRange__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User Defined</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Quote Labor</fullName>
            </value>
            <value>
                <fullName>Quote Ancillaries</fullName>
            </value>
            <value>
                <fullName>Quote Item</fullName>
            </value>
            <value>
                <fullName>Quote Period</fullName>
            </value>
            <value>
                <fullName>Quote Period Group</fullName>
            </value>
            <value>
                <fullName>Quote Item Period Group</fullName>
            </value>
            <value>
                <fullName>Quote Section</fullName>
            </value>
            <value>
                <fullName>Project Phase</fullName>
            </value>
            <value>
                <fullName>Quote Item Project Phase</fullName>
            </value>
            <value>
                <fullName>Section Period</fullName>
            </value>
            <value>
                <fullName>Section Phase</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NamedRangeTotal__c/NamedRangeTotal__c.object-meta.xml
<CustomObject>
    <label>Named Range Total</label>
    <nameField>
        <displayFormat>NRT-{0000000}</displayFormat>
        <label>Named Range Total</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Named Range Totals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NamedRangeTotal__c/fields/MarginPercent__c.field-meta.xml
<CustomField>
    <fullName>MarginPercent__c</fullName>
    <label>Margin %</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/NamedRangeTotal__c/fields/NetExtendedCost__c.field-meta.xml
<CustomField>
    <fullName>NetExtendedCost__c</fullName>
    <label>Net Extended Cost</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NamedRangeTotal__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipName>CellRangeTotals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&apos;Quote&apos;</defaultValue>
    <description>Indicates the type of quote.</description>
    <inlineHelpText>Indicates the type of quote.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Collaboration</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Scenario</fullName>
            </value>
            <value>
                <fullName>Template</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QuoteDiscountController.cls
public with sharing class QuoteDiscountController {
	@AuraEnabled
	public static Object getNamedRangeTotals(Id recordId) {
		List<NamedRange__c> namedRanges = [
			SELECT
				ID,
				Name,
				NamedRangeTotalId__c,
				NamedRangeTotalId__r.NetExtendedCost__c,
				NamedRangeTotalId__r.NetExtendedAmount__c,
				NamedRangeTotalId__r.MarginPercent__c,
				(
					SELECT ID, Method__c, Type__c, Amount__c
					FROM Adjustments__r
					WHERE Method__c = :Adjustment.METHOD_INITIAL
					LIMIT 1
				)
			FROM NamedRange__c
			WHERE
				QuoteId__c = :recordId
				AND Name IN (
					:NamedRangeTotal.QUOTE_TOTAL_NAMED_RANGE,
					:NamedRangeTotal.LABOR_AMOUNT_NAMED_RANGE,
					:NamedRangeTotal.ADDON_TOTAL_NAMED_RANGE
				)
			WITH SECURITY_ENFORCED
		];

		Object result = wrapRecords(namedRanges);

		return result;
	}

	@TestVisible
	private static Object wrapRecords(List<NamedRange__c> namedRanges) {
		Map<String, Object> records = new Map<String, Object>();
		for (NamedRange__c namedRange : namedRanges) {
			Map<String, Object> record = new Map<String, Object>();
			record.put('Id', namedRange.Id);
			record.put('Name', namedRange.Name);
			record.put('Category', namedRange.Name);
			record.put('CurrentAmount', nullToZero(namedRange.NamedRangeTotalId__r.NetExtendedAmount__c));
			record.put('CurrentMargin', nullToZero(namedRange.NamedRangeTotalId__r.MarginPercent__c));
			record.put('Cost', nullToZero(namedRange.NamedRangeTotalId__r.NetExtendedCost__c));
			record.put('DiscountPercent', 0);
			record.put('DiscountAmount', 0);
			record.put('NewAmount', nullToZero(namedRange.NamedRangeTotalId__r.NetExtendedAmount__c));
			record.put('NewMargin', nullToZero(namedRange.NamedRangeTotalId__r.MarginPercent__c));
			record.put('Currency', 0);
			if (namedRange.Adjustments__r.size() > 0) {
				record.put('DiscountType', namedRange.Adjustments__r[0].Type__c);
				if (namedRange.Adjustments__r[0].Type__c == Adjustment.TYPE_DISCOUNT_AMOUNT) {
					record.put('DiscountAmount', namedRange.Adjustments__r[0].Amount__c);
				} else if (namedRange.Adjustments__r[0].Type__c == Adjustment.TYPE_DISCOUNT_PERCENT) {
					record.put('DiscountPercent', namedRange.Adjustments__r[0].Amount__c);
				}
				record.put('AdjustmentId', namedRange.Adjustments__r[0].Id);
			}
			records.put(namedRange.Name, record);
		}
		return records;
	}

	@TestVisible
	private static Decimal nullToZero(Decimal input) {
		return input == null ? 0 : input;
	}

	@AuraEnabled
	public static void updateAdjustments(String recordString, Quote__c quote) {
		List<Adjustment__c> adjustments = (List<Adjustment__c>) JSON.deserialize(
			recordString,
			List<Adjustment__c>.class
		);
		CRUDUtility.upsertRecords(adjustments);
		CRUDUtility.upsertRecords(quote);
	}
}