force-app/main/default/objects/Adjustment__c/Adjustment__c.object-meta.xml
<CustomObject>
    <label>Adjustment</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Adjustment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Adjustment__c/fields/AppliedBy__c.field-meta.xml
<CustomField>
    <fullName>AppliedBy__c</fullName>
    <label>Applied By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Rule</fullName>
            </value>
            <value>
                <fullName>Promotion</fullName>
            </value>
            <value>
                <fullName>Incentive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Adjustment__c/fields/AppliedTo__c.field-meta.xml
<CustomField>
    <fullName>AppliedTo__c</fullName>
    <label>Applied To</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Cost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Adjustment__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Rule</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Adjustment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Discount Percent</fullName>
            </value>
            <value>
                <fullName>Discount Amount</fullName>
            </value>
            <value>
                <fullName>Markup Percent</fullName>
            </value>
            <value>
                <fullName>Markup Amount</fullName>
            </value>
            <value>
                <fullName>% Discount</fullName>
            </value>
            <value>
                <fullName>% Markup</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Adjustment.cls
/**
 *  Provus Services Quoting
 *  Adjustment
 *  @2021 Provus Inc. All rights reserved.
 */
public with sharing class Adjustment extends ManagedObject {
	// constants
	public static final String FIELD_APPLIED_TO = 'AppliedTo__c';
	public static final String FIELD_METHOD = 'Method__c';
	public static final String FIELD_TYPE = 'Type__c';

	public static final String SOBJECT_NAME = 'Adjustment__c';

	public static final String TYPE_PERCENT_DISCOUNT = '% Discount';

	public static final String TYPE_DISCOUNT_PERCENT = 'Discount Percent';
	public static final String TYPE_DISCOUNT_AMOUNT = 'Discount Amount';

	public static final String METHOD_INITIAL = 'Initial';

	public static final String APPLIED_TO_PRICE = 'Price';

	public static final String APPLIED_BY_MANUAL = 'Manual';

	public Adjustment(AdjustmentDTO adjustment) {
		super(adjustment);
		this.pSObject = newAdjustmentSO(adjustment);
	}

	public Adjustment(Adjustment__c adjustmentSO) {
		super(adjustmentSO);
		this.baseDTO = newAdjustmentDO(adjustmentSO);
	}

	public static AdjustmentDTO newAdjustmentDO(Adjustment__c adjustmentSO) {
		AdjustmentDTO adjustmentDO = new AdjustmentDTO();
		adjustmentDO.type = adjustmentSO.Type__c;
		adjustmentDO.amount = adjustmentSO.Amount__c;
		adjustmentDO.sequence = adjustmentSO.Sequence__c;
		adjustmentDO.method = adjustmentSO.Method__c;
		adjustmentDO.appliedTo = adjustmentSO.AppliedTo__c;
		adjustmentDO.appliedBy = adjustmentSO.AppliedBy__c;
		adjustmentDO.adjustmentId = adjustmentSO.Id;
		return adjustmentDO;
	}

	private Adjustment__c newAdjustmentSO(AdjustmentDTO adjustmentDO) {
		Adjustment__c adjustmentSO = new Adjustment__c(
			Type__c = adjustmentDO.type,
			Amount__c = adjustmentDO.amount,
			Sequence__c = adjustmentDO.sequence,
			Method__c = adjustmentDO.method,
			AppliedTo__c = adjustmentDO.appliedTo,
			AppliedBy__c = adjustmentDO.appliedBy,
			Id = adjustmentDO.adjustmentId
		);
		return adjustmentSO;
	}
}