force-app/main/default/objects/Adjustment__c/Adjustment__c.object-meta.xml
<CustomObject>
    <label>Adjustment</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Adjustment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Adjustment__c/fields/AppliedBy__c.field-meta.xml
<CustomField>
    <fullName>AppliedBy__c</fullName>
    <label>Applied By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Rule</fullName>
            </value>
            <value>
                <fullName>Promotion</fullName>
            </value>
            <value>
                <fullName>Incentive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Adjustment__c/fields/AppliedTo__c.field-meta.xml
<CustomField>
    <fullName>AppliedTo__c</fullName>
    <label>Applied To</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Cost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Adjustment__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Rule</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Adjustment__c/fields/NamedRangeId__c.field-meta.xml
<CustomField>
    <fullName>NamedRangeId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Named Range</label>
    <referenceTo>NamedRange__c</referenceTo>
    <relationshipLabel>Adjustments</relationshipLabel>
    <relationshipName>Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Adjustment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Discount Percent</fullName>
            </value>
            <value>
                <fullName>Discount Amount</fullName>
            </value>
            <value>
                <fullName>Markup Percent</fullName>
            </value>
            <value>
                <fullName>Markup Amount</fullName>
            </value>
            <value>
                <fullName>% Discount</fullName>
            </value>
            <value>
                <fullName>% Markup</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NamedRange__c/NamedRange__c.object-meta.xml
<CustomObject>
    <label>Named Range</label>
    <nameField>
        <label>Named Range Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Named Ranges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NamedRange__c/fields/NamedRangeTotalId__c.field-meta.xml
<CustomField>
    <fullName>NamedRangeTotalId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Named Range Total</label>
    <referenceTo>NamedRangeTotal__c</referenceTo>
    <relationshipLabel>Named Ranges</relationshipLabel>
    <relationshipName>NamedRanges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NamedRange__c/fields/ProjectPhaseId__c.field-meta.xml
<CustomField>
    <fullName>ProjectPhaseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Phase</label>
    <referenceTo>ProjectPhase__c</referenceTo>
    <relationshipLabel>Named Ranges</relationshipLabel>
    <relationshipName>NamedRanges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NamedRange__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Named Ranges</relationshipLabel>
    <relationshipName>NamedRanges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NamedRange__c/fields/QuoteItemId__c.field-meta.xml
<CustomField>
    <fullName>QuoteItemId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Item</label>
    <referenceTo>QuoteItem__c</referenceTo>
    <relationshipLabel>Named Ranges</relationshipLabel>
    <relationshipName>NamedRanges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NamedRange__c/fields/QuotePeriodGroupId__c.field-meta.xml
<CustomField>
    <fullName>QuotePeriodGroupId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Period Group</label>
    <referenceTo>QuotePeriodGroup__c</referenceTo>
    <relationshipLabel>Named Ranges</relationshipLabel>
    <relationshipName>NamedRanges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NamedRange__c/fields/QuotePeriodId__c.field-meta.xml
<CustomField>
    <fullName>QuotePeriodId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Period</label>
    <referenceTo>QuotePeriod__c</referenceTo>
    <relationshipLabel>Named Ranges</relationshipLabel>
    <relationshipName>NamedRanges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NamedRange__c/fields/QuoteSectionId__c.field-meta.xml
<CustomField>
    <fullName>QuoteSectionId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Section</label>
    <referenceTo>QuoteSection__c</referenceTo>
    <relationshipLabel>Named Ranges</relationshipLabel>
    <relationshipName>NamedRanges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NamedRange__c/fields/RangeSpecJSON__c.field-meta.xml
<CustomField>
    <fullName>RangeSpecJSON__c</fullName>
    <label>Range Spec (JSON)</label>
    <length>40000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NamedRange__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User Defined</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Quote Labor</fullName>
            </value>
            <value>
                <fullName>Quote Ancillaries</fullName>
            </value>
            <value>
                <fullName>Quote Item</fullName>
            </value>
            <value>
                <fullName>Quote Period</fullName>
            </value>
            <value>
                <fullName>Quote Period Group</fullName>
            </value>
            <value>
                <fullName>Quote Item Period Group</fullName>
            </value>
            <value>
                <fullName>Quote Section</fullName>
            </value>
            <value>
                <fullName>Project Phase</fullName>
            </value>
            <value>
                <fullName>Quote Item Project Phase</fullName>
            </value>
            <value>
                <fullName>Section Period</fullName>
            </value>
            <value>
                <fullName>Section Phase</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NamedRangeTotal__c/NamedRangeTotal__c.object-meta.xml
<CustomObject>
    <label>Named Range Total</label>
    <nameField>
        <displayFormat>NRT-{0000000}</displayFormat>
        <label>Named Range Total</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Named Range Totals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NamedRangeTotal__c/fields/MarginPercent__c.field-meta.xml
<CustomField>
    <fullName>MarginPercent__c</fullName>
    <label>Margin %</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/NamedRangeTotal__c/fields/NetExtendedCost__c.field-meta.xml
<CustomField>
    <fullName>NetExtendedCost__c</fullName>
    <label>Net Extended Cost</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NamedRangeTotal__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NamedRangeTotal__c/fields/QuantityUOM__c.field-meta.xml
<CustomField>
    <fullName>QuantityUOM__c</fullName>
    <label>Quantity UOM</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>QuantityUOMs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/NamedRangeTotal__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipName>CellRangeTotals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/QuantityUOMs.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Hour</fullName>
    </customValue>
    <customValue>
        <fullName>Resource</fullName>
    </customValue>
    <masterLabel>Quantity UOMs</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/NamedRangeFactory.cls
/**
 *  Provus Services Quoting
 *  NamedRangeFactory
 *  @2021 Provus Inc. All rights reserved.
 */
public with sharing abstract class NamedRangeFactory {
	public static List<NamedRange__c> getNamedRangesForQuote(Id quoteId) {
		return [
			SELECT
				Id,
				Name,
				ProjectPhaseId__c,
				QuoteId__c,
				QuoteItemId__c,
				QuotePeriodId__c,
				QuotePeriodGroupId__c,
				QuoteSectionId__c,
				RangeSpecJSON__c,
				Type__c,
				NamedRangeTotalId__c,
				NamedRangeTotalId__r.MarginPercent__c,
				NamedRangeTotalId__r.NetExtendedAmount__c,
				NamedRangeTotalId__r.NetExtendedCost__c,
				NamedRangeTotalId__r.Quantity__c,
				NamedRangeTotalId__r.QuantityUOM__c,
				(
					SELECT Id, Amount__c, AppliedBy__c, AppliedTo__c, Method__c, Sequence__c, Type__c
					FROM Adjustments__r
				)
			FROM NamedRange__c
			WHERE QuoteId__c = :quoteId
			WITH SECURITY_ENFORCED
		];
	}
}