force-app/main/default/objects/Adjustment__c/Adjustment__c.object-meta.xml
<CustomObject>
    <label>Adjustment</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Adjustment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NamedRange__c/NamedRange__c.object-meta.xml
<CustomObject>
    <label>Named Range</label>
    <nameField>
        <label>Named Range Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Named Ranges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NamedRange__c/fields/NamedRangeTotalId__c.field-meta.xml
<CustomField>
    <fullName>NamedRangeTotalId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Named Range Total</label>
    <referenceTo>NamedRangeTotal__c</referenceTo>
    <relationshipLabel>Named Ranges</relationshipLabel>
    <relationshipName>NamedRanges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NamedRange__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Named Ranges</relationshipLabel>
    <relationshipName>NamedRanges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NamedRange__c/fields/QuoteItemId__c.field-meta.xml
<CustomField>
    <fullName>QuoteItemId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Item</label>
    <referenceTo>QuoteItem__c</referenceTo>
    <relationshipLabel>Named Ranges</relationshipLabel>
    <relationshipName>NamedRanges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NamedRangeTotal__c/NamedRangeTotal__c.object-meta.xml
<CustomObject>
    <label>Named Range Total</label>
    <nameField>
        <displayFormat>NRT-{0000000}</displayFormat>
        <label>Named Range Total</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Named Range Totals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NamedRangeTotal__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipName>CellRangeTotals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/RateCardId__c.field-meta.xml
<CustomField>
    <fullName>RateCardId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate Card</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(3 OR 1) AND (4 OR 2) AND 5</booleanFilter>
        <errorMessage
		>The Rate Card is expired/inactive during the selected service start date</errorMessage>
        <filterItems>
            <field>$Source.ServiceStartDate__c</field>
            <operation>greaterOrEqual</operation>
            <valueField>RateCard__c.EffectiveDate__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.ServiceStartDate__c</field>
            <operation>lessOrEqual</operation>
            <valueField>RateCard__c.ExpirationDate__c</valueField>
        </filterItems>
        <filterItems>
            <field>RateCard__c.EffectiveDate__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <filterItems>
            <field>RateCard__c.ExpirationDate__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <filterItems>
            <field>RateCard__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>RateCard__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteItem__c/QuoteItem__c.object-meta.xml
<CustomObject>
    <label>Quote Item</label>
    <nameField>
        <displayFormat>QI-{0000000}</displayFormat>
        <label>Quote Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteItem__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QuoteItemCell__c/QuoteItemCell__c.object-meta.xml
<CustomObject>
    <label>Quote Item Cell</label>
    <nameField>
        <displayFormat>QIC-{0000000}</displayFormat>
        <label>Quote Item Cell</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Item Cells</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteItemCell__c/fields/C001__c.field-meta.xml
<CustomField>
    <fullName>C001__c</fullName>
    <label>C001</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteItemCell__c/fields/QuoteItemId__c.field-meta.xml
<CustomField>
    <fullName>QuoteItemId__c</fullName>
    <label>Quote Item</label>
    <referenceTo>QuoteItem__c</referenceTo>
    <relationshipName>QuoteItemCells</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/QuoteItemServiceTest.cls
@IsTest
public with sharing class QuoteItemServiceTest extends QuoteItemTestsBase {
	@IsTest
	static void itShouldInsertNewQuoteItem() {
		QuoteItemDTO testQuoteItemDO = newQuoteItemDO();
		testQuoteItemDO.operationType = BaseDTO.OPERATION_TYPE_INSERT;
		testQuoteItemDO.lineSequence = 50;

		List<QuoteItemDTO> quoteItemDOs = new List<QuoteItemDTO>{ testQuoteItemDO };
		Test.startTest();
		QuoteItemService.commitQuoteItems(testQuoteItemDO.quoteId, quoteItemDOs);

		System.assertNotEquals(null, testQuoteItemDO.quoteItemSO.Id, 'should create new quote item');
		Test.stopTest();
	}

	@IsTest
	static void itShouldDeleteQuoteItem() {
		QuoteItem__c quoteItemSO = newQuoteItemSO();
		QuoteItemDTO quoteItemDO = newQuoteItemDO(quoteItemSO);

		quoteItemDO.operationType = BaseDTO.OPERATION_TYPE_DELETE;

		NamedRangeTotal__c namedRangeTotalSO = new NamedRangeTotal__c(QuoteId__c = quoteItemDO.quoteId);
		CRUDUtility.insertRecords(namedRangeTotalSO);

		NamedRange__c namedRangeSO = new NamedRange__c(
			NamedRangeTotalId__c = namedRangeTotalSO.id,
			QuoteId__c = quoteItemDO.quoteId,
			quoteitemid__c = quoteItemDO.id
		);
		CRUDUtility.insertRecords(namedRangeSO);

		Test.startTest();
		List<QuoteItemDTO> quoteItemDOs = new List<QuoteItemDTO>{ quoteItemDO };
		QuoteItemService.commitQuoteItems(quoteItemDO.quoteId, quoteItemDOs);
		QuoteItem__c testQuoteItemSO = [
			SELECT IsDeleted
			FROM QuoteItem__c
			WHERE Id = :quoteItemSO.Id
			ALL ROWS
		];

		System.assertEquals(true, testQuoteItemSO.IsDeleted, 'should delete quote item');
		Test.stopTest();
	}

	@IsTest
	static void itShouldAssociateNewQuoteItemCellToQuoteItem() {
		QuoteItemDTO quoteItemDO = newQuoteItemDO();
		quoteItemDO.operationType = BaseDTO.OPERATION_TYPE_INSERT;

		Test.startTest();
		List<QuoteItemDTO> quoteItemDOs = new List<QuoteItemDTO>{ quoteItemDO };
		QuoteItemService.commitQuoteItems(quoteItemDO.quoteId, quoteItemDOs);

		QuoteItemCell__c testQuoteItemCell = [
			SELECT Id, QuoteItemId__c
			FROM QuoteItemCell__c
			WHERE Id = :quoteItemDO.quoteItemCellId
		];

		System.assertNotEquals(
			null,
			quoteItemDO.quoteItemCellId,
			'should associate quote item cell id to quote item'
		);
		System.assertNotEquals(null, testQuoteItemCell.Id, 'should insert quote item cell');

		Test.stopTest();
	}

	@IsTest
	static void itShouldAssociateNewAdjustmentToQuoteItem() {
		QuoteItemDTO quoteItemDO = newQuoteItemDO();
		quoteItemDO.operationType = BaseDTO.OPERATION_TYPE_INSERT;
		quoteItemDO.adjustment.type = '% Discount';
		quoteItemDO.adjustment.amount = 100;

		Test.startTest();
		List<QuoteItemDTO> quoteItemDOs = new List<QuoteItemDTO>{ quoteItemDO };
		QuoteItemService.commitQuoteItems(quoteItemDO.quoteId, quoteItemDOs);

		Adjustment__c testAdjustment = [
			SELECT Id
			FROM Adjustment__c
			WHERE Id = :quoteItemDO.adjustmentId
		];

		System.assertNotEquals(
			null,
			quoteItemDO.adjustmentId,
			'should associate adjustment id to quote item'
		);
		System.assertNotEquals(null, testAdjustment.Id, 'should insert adjustment');

		Test.stopTest();
	}

	@IsTest
	static void itShouldUpdateTheQuoteItemCell() {
		QuoteItemDTO quoteItemDO = newQuoteItemDO();
		quoteItemDO.operationType = BaseDTO.OPERATION_TYPE_INSERT;
		update new Quote__c(Id = quoteItemDO.quoteId, RateCardId__c = newRateCard().Id);

		List<QuoteItemDTO> quoteItemDOs = new List<QuoteItemDTO>{ quoteItemDO };
		QuoteItemService.commitQuoteItems(quoteItemDO.quoteId, quoteItemDOs);
		QuoteItemCell__c quoteItemCellSO = new QuoteItemCell__c(
			QuoteItemId__c = quoteItemDO.id,
			C001__c = 1
		);
		insert quoteItemCellSO;

		quoteItemDO.quoteItemSO = QuoteItemServiceSupport.getQuoteItemSOsForQuote(
			quoteItemDO.quoteId
		)[0];
		quoteItemDO.periodValueMap.put('001', 100);
		quoteItemDO.operationType = BaseDTO.OPERATION_TYPE_UPDATE;

		Test.startTest();
		QuoteItemService.commitQuoteItems(quoteItemDO.quoteId, quoteItemDOs);
		QuoteItemCell__c testQuoteItemCell = [
			SELECT Id, QuoteItemId__c, C001__c
			FROM QuoteItemCell__c
			WHERE Id = :quoteItemDO.quoteItemCellId
		];

		System.assertEquals(100, testQuoteItemCell.C001__c, 'should update the quote item cell to 100');
		Test.stopTest();
	}

	@IsTest
	static void itShouldUpdateTheAdjustment() {
		QuoteItemDTO quoteItemDO = newQuoteItemDO();
		quoteItemDO.operationType = BaseDTO.OPERATION_TYPE_INSERT;
		quoteItemDO.adjustment.type = '% Discount';
		quoteItemDO.adjustment.amount = 100;

		QuoteItemService.commitQuoteItems(quoteItemDO.quoteId, new List<QuoteItemDTO>{ quoteItemDO });

		Test.startTest();
		quoteItemDO.adjustment.amount = 200;
		quoteItemDO.operationType = BaseDTO.OPERATION_TYPE_UPDATE;

		QuoteItemService.commitQuoteItems(quoteItemDO.quoteId, new List<QuoteItemDTO>{ quoteItemDO });
		Adjustment__c testAdjustment = [
			SELECT Id, Amount__c
			FROM Adjustment__c
			WHERE Id = :quoteItemDO.adjustmentId
		];

		System.assertEquals(
			200,
			testAdjustment.Amount__c,
			'should update the quote adjustment value to 200'
		);
	}
}