force-app/main/default/objects/Adjustment__c/Adjustment__c.object-meta.xml
<CustomObject>
    <label>Adjustment</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Adjustment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Adjustment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Discount Percent</fullName>
            </value>
            <value>
                <fullName>Discount Amount</fullName>
            </value>
            <value>
                <fullName>Markup Percent</fullName>
            </value>
            <value>
                <fullName>Markup Amount</fullName>
            </value>
            <value>
                <fullName>% Discount</fullName>
            </value>
            <value>
                <fullName>% Markup</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/RateCardId__c.field-meta.xml
<CustomField>
    <fullName>RateCardId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate Card</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(3 OR 1) AND (4 OR 2) AND 5</booleanFilter>
        <errorMessage
		>The Rate Card is expired/inactive during the selected service start date</errorMessage>
        <filterItems>
            <field>$Source.ServiceStartDate__c</field>
            <operation>greaterOrEqual</operation>
            <valueField>RateCard__c.EffectiveDate__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.ServiceStartDate__c</field>
            <operation>lessOrEqual</operation>
            <valueField>RateCard__c.ExpirationDate__c</valueField>
        </filterItems>
        <filterItems>
            <field>RateCard__c.EffectiveDate__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <filterItems>
            <field>RateCard__c.ExpirationDate__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <filterItems>
            <field>RateCard__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>RateCard__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&apos;Quote&apos;</defaultValue>
    <description>Indicates the type of quote.</description>
    <inlineHelpText>Indicates the type of quote.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Collaboration</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Scenario</fullName>
            </value>
            <value>
                <fullName>Template</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteItem__c/QuoteItem__c.object-meta.xml
<CustomObject>
    <label>Quote Item</label>
    <nameField>
        <displayFormat>QI-{0000000}</displayFormat>
        <label>Quote Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteItem__c/fields/AdjustmentId__c.field-meta.xml
<CustomField>
    <fullName>AdjustmentId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Adjustment</label>
    <referenceTo>Adjustment__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteItem__c/fields/LineType__c.field-meta.xml
<CustomField>
    <fullName>LineType__c</fullName>
    <label>Line Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Resource</fullName>
                <default>true</default>
                <label>Resource</label>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteItem__c/fields/NetExtendedAmount__c.field-meta.xml
<CustomField>
    <fullName>NetExtendedAmount__c</fullName>
    <label>Net Extended Amount</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteItem__c/fields/NonBillable__c.field-meta.xml
<CustomField>
    <fullName>NonBillable__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When checked quote item will not be included in billing/pricing</description>
    <inlineHelpText
	>When checked this quote item will not be included in billing/pricing</inlineHelpText>
    <label>Non-billable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteItem__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteItem__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QuoteItem__c/fields/QuoteSectionId__c.field-meta.xml
<CustomField>
    <fullName>QuoteSectionId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Section</label>
    <referenceTo>QuoteSection__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteItem__c/fields/RateCardItemId__c.field-meta.xml
<CustomField>
    <fullName>RateCardItemId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate Card Item</label>
    <referenceTo>RateCardItem__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteItem__c/fields/RoleNameOverride__c.field-meta.xml
<CustomField>
    <fullName>RoleNameOverride__c</fullName>
    <label>Role Name Override</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteItem__c/fields/SectionSequence__c.field-meta.xml
<CustomField>
    <fullName>SectionSequence__c</fullName>
    <label>Section Sequence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/QuoteItemServiceSupport.cls
/**
 *  Provus Services Quoting
 *  QuoteItemServiceSupport
 *  @2021 Provus Inc. All rights reserved.
 */
public with sharing abstract class QuoteItemServiceSupport {
	static final String FIELD_NAME_RADJUSTMENT_ID = SystemUtility.getRName(
		Schema.QuoteItem__c.AdjustmentId__c
	);

	public static List<QuoteItem__c> getQuoteItemSOsForQuote(Id quoteId) {
		Quote__c ctxQuote = [
			SELECT RateCardId__c
			FROM Quote__c
			WHERE Id = :quoteId
			WITH SECURITY_ENFORCED
		];
		CustomMetadataService cmService = new CustomMetadataService();

		// add product default fields
		Set<String> requestedFields = cmService.getProductDefaultFields();
		// add rate card attributes
		RateCardService rtService = new RateCardService(ctxQuote.RateCardId__c);
		requestedFields.addAll(rtService.getAttributes());
		// add quote item default fields
		requestedFields.addAll(cmService.getQuoteItemDefaultFields());

		requestedFields.addAll(
			new Set<String>{
				SObjectUtility.FIELD_ID,
				SObjectUtility.FIELD_NAME,
				Schema.QuoteItem__c.AdjustmentId__c + '',
				Schema.QuoteItem__c.DisplaySequence__c + '',
				Schema.QuoteItem__c.LineType__c + '',
				Schema.QuoteItem__c.ProductId__c + '',
				Schema.QuoteItem__c.QuoteId__c + '',
				Schema.QuoteItem__c.QuoteSectionId__c + '',
				Schema.QuoteItem__c.RateCardItemId__c + '',
				Schema.QuoteItem__c.SectionSequence__c + '',
				Schema.QuoteItem__c.Sequence__c + '',
				Schema.QuoteItem__c.RoleNameOverride__c + '',
				Schema.QuoteItem__c.Quantity__c + '',
				Schema.QuoteItem__c.NetExtendedAmount__c + '',
				Schema.QuoteItem__c.NetExtendedCost__c + '',
				Schema.QuoteItem__c.MarginPercent__c + '',
				Schema.QuoteItem__c.NonBillable__c + '',
				FIELD_NAME_RADJUSTMENT_ID +
				'.' +
				Schema.Adjustment__c.Amount__c,
				FIELD_NAME_RADJUSTMENT_ID +
				'.' +
				Schema.Adjustment__c.Type__c
			}
		);

		// build query string
		String qry = 'SELECT ';

		for (String fld : requestedFields) {
			qry += fld + ', ';
		}

		qry += '(SELECT ';
		qry += SObjectUtility.FIELD_ID;

		for (String fieldName : QuoteItemCell.getPeriodColumns()) {
			qry += ', ' + fieldName;
		}

		qry +=
			' FROM ' +
			SystemUtility.getNamespacePrefix() +
			QuoteItemCell.QUOTE_ITEM_CHILD_RELATIONSHIP +
			')';

		qry += ' FROM ' + SystemUtility.getNamespacePrefix() + QuoteItem.SOBJECT_NAME;
		qry += ' WHERE ' + Schema.QuoteItem__c.QuoteId__c + ' =: quoteId';
		qry += ' WITH SECURITY_ENFORCED';
		qry += ' ORDER BY ' + Schema.QuoteItem__c.Sequence__c + ' ASC';

		return Database.query(String.escapeSingleQuotes(qry));
	}
}