force-app/main/default/objects/Adjustment__c/Adjustment__c.object-meta.xml
<CustomObject>
    <label>Adjustment</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Adjustment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Adjustment__c/fields/NamedRangeId__c.field-meta.xml
<CustomField>
    <fullName>NamedRangeId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Named Range</label>
    <referenceTo>NamedRange__c</referenceTo>
    <relationshipLabel>Adjustments</relationshipLabel>
    <relationshipName>Adjustments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Adjustment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Discount Percent</fullName>
            </value>
            <value>
                <fullName>Discount Amount</fullName>
            </value>
            <value>
                <fullName>Markup Percent</fullName>
            </value>
            <value>
                <fullName>Markup Amount</fullName>
            </value>
            <value>
                <fullName>% Discount</fullName>
            </value>
            <value>
                <fullName>% Markup</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NamedRange__c/NamedRange__c.object-meta.xml
<CustomObject>
    <label>Named Range</label>
    <nameField>
        <label>Named Range Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Named Ranges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NamedRange__c/fields/NamedRangeTotalId__c.field-meta.xml
<CustomField>
    <fullName>NamedRangeTotalId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Named Range Total</label>
    <referenceTo>NamedRangeTotal__c</referenceTo>
    <relationshipLabel>Named Ranges</relationshipLabel>
    <relationshipName>NamedRanges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NamedRange__c/fields/ProjectPhaseId__c.field-meta.xml
<CustomField>
    <fullName>ProjectPhaseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Phase</label>
    <referenceTo>ProjectPhase__c</referenceTo>
    <relationshipLabel>Named Ranges</relationshipLabel>
    <relationshipName>NamedRanges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NamedRange__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Named Ranges</relationshipLabel>
    <relationshipName>NamedRanges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NamedRange__c/fields/QuoteItemId__c.field-meta.xml
<CustomField>
    <fullName>QuoteItemId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Item</label>
    <referenceTo>QuoteItem__c</referenceTo>
    <relationshipLabel>Named Ranges</relationshipLabel>
    <relationshipName>NamedRanges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NamedRange__c/fields/QuotePeriodGroupId__c.field-meta.xml
<CustomField>
    <fullName>QuotePeriodGroupId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Period Group</label>
    <referenceTo>QuotePeriodGroup__c</referenceTo>
    <relationshipLabel>Named Ranges</relationshipLabel>
    <relationshipName>NamedRanges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NamedRange__c/fields/QuotePeriodId__c.field-meta.xml
<CustomField>
    <fullName>QuotePeriodId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Period</label>
    <referenceTo>QuotePeriod__c</referenceTo>
    <relationshipLabel>Named Ranges</relationshipLabel>
    <relationshipName>NamedRanges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NamedRange__c/fields/QuoteSectionId__c.field-meta.xml
<CustomField>
    <fullName>QuoteSectionId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Section</label>
    <referenceTo>QuoteSection__c</referenceTo>
    <relationshipLabel>Named Ranges</relationshipLabel>
    <relationshipName>NamedRanges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NamedRange__c/fields/RangeSpecJSON__c.field-meta.xml
<CustomField>
    <fullName>RangeSpecJSON__c</fullName>
    <label>Range Spec (JSON)</label>
    <length>40000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NamedRange__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User Defined</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Quote Labor</fullName>
            </value>
            <value>
                <fullName>Quote Ancillaries</fullName>
            </value>
            <value>
                <fullName>Quote Item</fullName>
            </value>
            <value>
                <fullName>Quote Period</fullName>
            </value>
            <value>
                <fullName>Quote Period Group</fullName>
            </value>
            <value>
                <fullName>Quote Item Period Group</fullName>
            </value>
            <value>
                <fullName>Quote Section</fullName>
            </value>
            <value>
                <fullName>Project Phase</fullName>
            </value>
            <value>
                <fullName>Quote Item Project Phase</fullName>
            </value>
            <value>
                <fullName>Section Period</fullName>
            </value>
            <value>
                <fullName>Section Phase</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NamedRangeTotal__c/NamedRangeTotal__c.object-meta.xml
<CustomObject>
    <label>Named Range Total</label>
    <nameField>
        <displayFormat>NRT-{0000000}</displayFormat>
        <label>Named Range Total</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Named Range Totals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NamedRangeTotal__c/fields/MarginPercent__c.field-meta.xml
<CustomField>
    <fullName>MarginPercent__c</fullName>
    <label>Margin %</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/NamedRangeTotal__c/fields/NamedRangeId__c.field-meta.xml
<CustomField>
    <fullName>NamedRangeId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Named Range</label>
    <referenceTo>NamedRange__c</referenceTo>
    <relationshipLabel>Named Range Totals</relationshipLabel>
    <relationshipName>NamedRangeTotals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NamedRangeTotal__c/fields/NetExtendedCost__c.field-meta.xml
<CustomField>
    <fullName>NetExtendedCost__c</fullName>
    <label>Net Extended Cost</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NamedRangeTotal__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipName>CellRangeTotals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&apos;Quote&apos;</defaultValue>
    <description>Indicates the type of quote.</description>
    <inlineHelpText>Indicates the type of quote.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Collaboration</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Scenario</fullName>
            </value>
            <value>
                <fullName>Template</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NamedRange.cls
/**
 *  Provus Services Quoting
 *  NamedRange
 *  @2021 Provus Inc. All rights reserved.
 */
public with sharing class NamedRange extends ManagedObject {
	public static final String SOBJECT_NAME = 'NamedRange__c';

	public static final String TYPE_QUOTE = 'Quote';
	public static final String TYPE_QUOTE_ADDONS = 'Quote Ancillaries';
	public static final String TYPE_QUOTE_LABOR = 'Quote Labor';
	public static final String QUOTE_TOTALS_NAME = 'Quote Totals';
	public static final String LABOR_AMOUNT_NAME = 'Labor Amount';
	public static final String ADDON_AMOUNT_NAME = 'Add-Ons Amount';

	private NamedRangeTotal namedRangeTotalMO;
	private List<Adjustment> adjustmentMOs = new List<Adjustment>();

	public class NamedRangeDO extends BaseDTO {
		public String name;
		public Id namedRangeId;
		public Id quoteId;
		public Id quoteItemId;
		public Id quotePeriodId;
		public Id quotePeriodGroupId;
		public Id quoteSectionId;
		public Id projectPhaseId;
		public String type;
		public String rangeSpec;

		public NamedRangeTotal.NamedRangeTotalDO relatedTotal;
		public List<AdjustmentDTO> adjustmentList;
	}

	public NamedRange(NamedRangeDO namedRangeDO) {
		super(namedRangeDO);
		initialize(namedRangeDO);
	}

	public NamedRange(NamedRange__c namedRangeSO) {
		super(newNamedRangeDO(namedRangeSO));
		initialize(namedRangeSO);
	}

	@TestVisible
	private List<Adjustment> getAdjustments() {
		return this.adjustmentMOs;
	}

	@TestVisible
	private NamedRangeTotal getNamedRangeTotal() {
		return this.namedRangeTotalMO;
	}

	public static void commitNamedRanges(List<NamedRange> namedRangesToCommit) {
		List<NamedRange> namedRangesToUpsert = new List<NamedRange>();
		List<NamedRange__c> namedRangesSOsToDelete = new List<NamedRange__c>();
		List<NamedRange__c> namedRangesSOsToUpsert = new List<NamedRange__c>();

		for (NamedRange namedRange : namedRangesToCommit) {
			NamedRange__c namedRangeSO = (NamedRange__c) namedRange.getSObject();
			if (namedRange.isDelete()) {
				namedRangesSOsToDelete.add(namedRangeSO);
			} else {
				namedRangesSOsToUpsert.add(namedRangeSO);
				namedRangesToUpsert.add(namedRange);
			}
		}

		commitNamedRangeTotalsFor(namedRangesToCommit);
		resolveNamedRangeTotalIds(namedRangesToUpsert);

		CRUDUtility.deleteRecords(namedRangesSOsToDelete);
		CRUDUtility.upsertRecords(namedRangesSOsToUpsert);

		resolveNamedRangeIdsForAdjustments(namedRangesToCommit);
		commitAdjustmentsFor(namedRangesToCommit);
	}

	private static void commitNamedRangeTotalsFor(List<NamedRange> namedRanges) {
		List<NamedRangeTotal__c> namedRangeTotalsToDelete = new List<NamedRangeTotal__c>();
		List<NamedRangeTotal__c> namedRangeTotalsToUpsert = new List<NamedRangeTotal__c>();
		List<Quote__c> quotesToUpdate = new List<Quote__c>();

		for (NamedRange namedRange : namedRanges) {
			NamedRangeTotal namedRangeTotal = namedRange.getNamedRangeTotal();
			NamedRangeTotal__c namedRangeTotalSO = (NamedRangeTotal__c) namedRangeTotal.getSObject();

			if (namedRangeTotal.isDelete()) {
				namedRangeTotalsToDelete.add(namedRangeTotalSO);
			} else {
				namedRangeTotalsToUpsert.add(namedRangeTotalSO);
			}

			if (namedRange.isQuoteTotal()) {
				NamedRange__c namedRangeSO = (NamedRange__c) namedRange.getSObject();
				Quote__c quoteSO = new Quote__c(
					Id = namedRangeSO.QuoteId__c,
					TotalAmount__c = namedRangeTotalSO.NetExtendedAmount__c,
					TotalCost__c = namedRangeTotalSO.NetExtendedCost__c,
					MarginPercent__c = namedRangeTotalSO.MarginPercent__c
				);
				quotesToUpdate.add(quoteSO);
			}
		}

		CRUDUtility.deleteRecords(namedRangeTotalsToDelete);
		CRUDUtility.upsertRecords(namedRangeTotalsToUpsert);
		CRUDUtility.updateRecords(quotesToUpdate);
	}

	private static void commitAdjustmentsFor(List<NamedRange> namedRanges) {
		List<Adjustment__c> adjustmentsToDelete = new List<Adjustment__c>();
		List<Adjustment__c> adjustmentsToUpsert = new List<Adjustment__c>();

		for (NamedRange namedRange : namedRanges) {
			List<Adjustment> adjustments = namedRange.getAdjustments();
			for (Adjustment adjustment : adjustments) {
				Adjustment__c adjustmentSO = (Adjustment__c) adjustment.getSObject();
				if (adjustment.isDelete()) {
					adjustmentsToDelete.add(adjustmentSO);
				} else {
					adjustmentsToUpsert.add(adjustmentSO);
				}
			}
		}

		CRUDUtility.deleteRecords(adjustmentsToDelete);
		CRUDUtility.upsertRecords(adjustmentsToUpsert);
	}

	private void initialize(NamedRangeDO namedRangeDO) {
		validate(namedRangeDO);

		NamedRange__c namedRangeSO = newNamedRangeSO(namedRangeDO);
		initialize(namedRangeSO);
	}

	private void initialize(NamedRange__c namedRangeSO) {
		this.pSObject = namedRangeSO;
		NamedRangeDO contextDO = (NamedRangeDO) baseDTO;
		this.namedRangeTotalMO = new NamedRangeTotal(contextDO.quoteId, contextDO.relatedTotal);
		if (contextDO.adjustmentList != null) {
			for (AdjustmentDTO adjustmentDO : contextDO.adjustmentList) {
				Adjustment adjustmentMO = new Adjustment(adjustmentDO);
				this.adjustmentMOs.add(adjustmentMO);
			}
		}
	}

	private void validate(NamedRangeDO namedRangeDO) {
		if (namedRangeDO.relatedTotal == null) {
			throw new ApplicationException('Named Range DO requires a related total.');
		}
	}

	public Boolean isQuoteTotal() {
		NamedRange__c namedRangeSO = (NamedRange__c) getSObject();
		return namedRangeSO.Type__c == TYPE_QUOTE;
	}

	private static NamedRangeDO newNamedRangeDO(NamedRange__c namedRangeSO) {
		NamedRangeDO namedRangeDO = new NamedRangeDO();
		namedRangeDO.name = namedRangeSO.Name;
		namedRangeDO.namedRangeId = namedRangeSO.Id;
		namedRangeDO.quoteId = namedRangeSO.QuoteId__c;
		namedRangeDO.quoteItemId = namedRangeSO.QuoteItemId__c;
		namedRangeDO.quotePeriodId = namedRangeSO.QuotePeriodId__c;
		namedRangeDO.quotePeriodGroupId = namedRangeSO.QuotePeriodGroupId__c;
		namedRangeDO.quoteSectionId = namedRangeSO.QuoteSectionId__c;
		namedRangeDO.projectPhaseId = namedRangeSO.ProjectPhaseId__c;
		namedRangeDO.type = namedRangeSO.Type__c;
		namedRangeDO.rangeSpec = namedRangeSO.RangeSpecJSON__c;
		namedRangeDO.relatedTotal = NamedRangeTotal.newNamedRangeTotalDO(
			namedRangeSO.NamedRangeTotalId__r
		);

		namedRangeDO.adjustmentList = new List<AdjustmentDTO>();
		for (Adjustment__c adjustmentSO : namedRangeSO.Adjustments__r) {
			AdjustmentDTO adjustment = Adjustment.newAdjustmentDO(adjustmentSO);
			namedRangeDO.adjustmentList.add(adjustment);
		}

		return namedRangeDO;
	}

	private NamedRange__c newNamedRangeSO(NamedRangeDO namedRangeDO) {
		NamedRange__c namedRangeSO = new NamedRange__c(
			Name = namedRangeDO.name,
			Id = namedRangeDO.namedRangeId,
			QuoteItemId__c = namedRangeDO.quoteItemId,
			QuotePeriodId__c = namedRangeDO.quotePeriodId,
			QuotePeriodGroupId__c = namedRangeDO.quotePeriodGroupId,
			QuoteSectionId__c = namedRangeDO.quoteSectionId,
			ProjectPhaseId__c = namedRangeDO.projectPhaseId,
			Type__c = namedRangeDO.type,
			RangeSpecJSON__c = namedRangeDO.rangeSpec,
			QuoteId__c = namedRangeDO.quoteId
		);
		return namedRangeSO;
	}

	private static void resolveNamedRangeIdsForAdjustments(List<NamedRange> namedRangeMOs) {
		for (NamedRange namedRange : namedRangeMOs) {
			NamedRange__c namedRangeSO = (NamedRange__c) namedRange.getSObject();
			for (Adjustment adjustmentMO : namedRange.getAdjustments()) {
				Adjustment__c adjustmentSO = (Adjustment__c) adjustmentMO.getSObject();
				adjustmentSO.NamedRangeId__c = namedRangeSO.Id;
			}
		}
	}

	private static void resolveNamedRangeTotalIds(List<NamedRange> namedRangeMOs) {
		for (NamedRange namedRange : namedRangeMOs) {
			NamedRangeTotal namedRangeTotal = namedRange.getNamedRangeTotal();
			NamedRange__c namedRangeSO = (NamedRange__c) namedRange.getSObject();
			NamedRangeTotal__c namedRangeTotalSO = (NamedRangeTotal__c) namedRangeTotal.getSObject();

			namedRangeSO.NamedRangeTotalId__c = namedRangeTotalSO.Id;
		}
	}
}