force-app/main/default/objects/Adjustment__c/Adjustment__c.object-meta.xml
<CustomObject>
    <label>Adjustment</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Adjustment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Adjustment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Discount Percent</fullName>
            </value>
            <value>
                <fullName>Discount Amount</fullName>
            </value>
            <value>
                <fullName>Markup Percent</fullName>
            </value>
            <value>
                <fullName>Markup Amount</fullName>
            </value>
            <value>
                <fullName>% Discount</fullName>
            </value>
            <value>
                <fullName>% Markup</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteItem__c/QuoteItem__c.object-meta.xml
<CustomObject>
    <label>Quote Item</label>
    <nameField>
        <displayFormat>QI-{0000000}</displayFormat>
        <label>Quote Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteItem__c/fields/AdjustmentId__c.field-meta.xml
<CustomField>
    <fullName>AdjustmentId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Adjustment</label>
    <referenceTo>Adjustment__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteItem__c/fields/LineType__c.field-meta.xml
<CustomField>
    <fullName>LineType__c</fullName>
    <label>Line Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Resource</fullName>
                <default>true</default>
                <label>Resource</label>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteItem__c/fields/NonBillable__c.field-meta.xml
<CustomField>
    <fullName>NonBillable__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When checked quote item will not be included in billing/pricing</description>
    <inlineHelpText
	>When checked this quote item will not be included in billing/pricing</inlineHelpText>
    <label>Non-billable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteItem__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteItem__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QuoteItem__c/fields/QuoteSectionId__c.field-meta.xml
<CustomField>
    <fullName>QuoteSectionId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Section</label>
    <referenceTo>QuoteSection__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteItem__c/fields/RateCardItemId__c.field-meta.xml
<CustomField>
    <fullName>RateCardItemId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate Card Item</label>
    <referenceTo>RateCardItem__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteItem__c/fields/SectionSequence__c.field-meta.xml
<CustomField>
    <fullName>SectionSequence__c</fullName>
    <label>Section Sequence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteItemCell__c/QuoteItemCell__c.object-meta.xml
<CustomObject>
    <label>Quote Item Cell</label>
    <nameField>
        <displayFormat>QIC-{0000000}</displayFormat>
        <label>Quote Item Cell</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Item Cells</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteItemCell__c/fields/QuoteItemId__c.field-meta.xml
<CustomField>
    <fullName>QuoteItemId__c</fullName>
    <label>Quote Item</label>
    <referenceTo>QuoteItem__c</referenceTo>
    <relationshipName>QuoteItemCells</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/QuoteItemDTO.cls
/**
 *  Provus Services Quoting
 *  QuoteItemDO
 *  @2021 Provus Inc. All rights reserved.
 */
public class QuoteItemDTO extends BaseDTO {
	public static final String LINE_TYPE_MISCELLANEOUS = 'Miscellaneous';

	public Boolean isMiscellaneous = false;
	public Decimal displaySequence;
	public Decimal lineSequence;
	public Decimal sectionSequence;
	public Id adjustmentId;
	public Id id;
	public Id productId;
	public Id quoteId;
	public Id quoteItemCellId;
	public Id rateCardItemId;
	public Id sectionId;
	public Boolean nonBillable;

	public AdjustmentDTO adjustment = new AdjustmentDTO();

	public QuoteItem__c quoteItemSO;
	public Map<String, Decimal> periodValueMap;

	public static QuoteItemDTO newDO(QuoteItem__c quoteItemSO) {
		QuoteItemDTO newDTO = new QuoteItemDTO();
		newDTO.quoteItemSO = quoteItemSO;
		newDTO.id = quoteItemSO.Id;
		newDTO.quoteId = quoteItemSO.QuoteId__c;
		newDTO.productId = quoteItemSO.ProductId__c;
		newDTO.rateCardItemId = quoteItemSO.RateCardItemId__c;
		newDTO.lineSequence = quoteItemSO.Sequence__c;
		newDTO.sectionSequence = quoteItemSO.SectionSequence__c;
		newDTO.displaySequence = quoteItemSO.DisplaySequence__c;
		newDTO.adjustmentId = quoteItemSO.AdjustmentId__c;
		newDTO.adjustment.type = quoteItemSO.AdjustmentId__r.Type__c;
		newDTO.adjustment.amount = quoteItemSO.AdjustmentId__r.Amount__c;
		newDTO.periodValueMap = new Map<String, Decimal>();
		newDTO.sectionId = quoteItemSO.QuoteSectionId__c;
		newDTO.nonBillable = quoteItemSO.NonBillable__c;

		if (!quoteItemSO.QuoteItemCells__r.isEmpty()) {
			newDTO.quoteItemCellId = quoteItemSO.QuoteItemCells__r[0].Id;
			for (QuoteItemCell__c itemCell : quoteItemSO.QuoteItemCells__r) {
				for (String period : QuoteItemCell.getPeriodColumns()) {
					Decimal periodValue = (Decimal) itemCell.get(period);
					if (periodValue != null) {
						String periodToken = period.removeStartIgnoreCase(QuoteItemCell.PERIOD_FIELD_PREFIX)
							.removeEndIgnoreCase(SObjectUtility.CUSTOM_FIELD_INDICATOR);

						newDTO.periodValueMap.put(periodToken, periodValue);
					}
				}
			}
		}

		return newDTO;
	}

	public void refreshDO() {
		this.id = this.quoteItemSO.Id;
		this.quoteId = this.quoteItemSO.QuoteId__c;
		this.productId = this.quoteItemSO.ProductId__c;
		this.rateCardItemId = this.quoteItemSO.RateCardItemId__c;
		this.lineSequence = this.quoteItemSO.Sequence__c;
		this.nonBillable = this.quoteItemSO.NonBillable__c;
		this.displaySequence = this.quoteItemSO.DisplaySequence__c;
		this.adjustmentId = this.quoteItemSO.AdjustmentId__c;
	}

	public void updateSO() {
		if (this.quoteItemSO == null) {
			this.quoteItemSO = new QuoteItem__c();
		}

		quoteItemSO.Id = this.id;
		if (quoteItemSO.QuoteId__c == null) {
			quoteItemSO.QuoteId__c = this.quoteId;
		}

		quoteItemSO.DisplaySequence__c = this.displaySequence;
		quoteItemSO.ProductId__c = this.productId;
		quoteItemSO.QuoteSectionId__c = this.sectionId;
		quoteItemSO.RateCardItemId__c = this.rateCardItemId;
		quoteItemSO.SectionSequence__c = this.sectionSequence;
		quoteItemSO.Sequence__c = this.lineSequence;

		this.isMiscellaneous = quoteItemSO.LineType__c == LINE_TYPE_MISCELLANEOUS;
	}
}