force-app/main/default/objects/Adjustment__c/Adjustment__c.object-meta.xml
<CustomObject>
    <label>Adjustment</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Adjustment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Adjustment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Discount Percent</fullName>
            </value>
            <value>
                <fullName>Discount Amount</fullName>
            </value>
            <value>
                <fullName>Markup Percent</fullName>
            </value>
            <value>
                <fullName>Markup Amount</fullName>
            </value>
            <value>
                <fullName>% Discount</fullName>
            </value>
            <value>
                <fullName>% Markup</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NamedRange__c/NamedRange__c.object-meta.xml
<CustomObject>
    <label>Named Range</label>
    <nameField>
        <label>Named Range Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Named Ranges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NamedRange__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User Defined</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Quote Labor</fullName>
            </value>
            <value>
                <fullName>Quote Ancillaries</fullName>
            </value>
            <value>
                <fullName>Quote Item</fullName>
            </value>
            <value>
                <fullName>Quote Period</fullName>
            </value>
            <value>
                <fullName>Quote Period Group</fullName>
            </value>
            <value>
                <fullName>Quote Item Period Group</fullName>
            </value>
            <value>
                <fullName>Quote Section</fullName>
            </value>
            <value>
                <fullName>Project Phase</fullName>
            </value>
            <value>
                <fullName>Quote Item Project Phase</fullName>
            </value>
            <value>
                <fullName>Section Period</fullName>
            </value>
            <value>
                <fullName>Section Phase</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NamedRangeTotal__c/NamedRangeTotal__c.object-meta.xml
<CustomObject>
    <label>Named Range Total</label>
    <nameField>
        <displayFormat>NRT-{0000000}</displayFormat>
        <label>Named Range Total</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Named Range Totals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NamedRangeTotal__c/fields/MarginPercent__c.field-meta.xml
<CustomField>
    <fullName>MarginPercent__c</fullName>
    <label>Margin %</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Practice__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Practice__c.field-meta.xml
<CustomField>
    <fullName>Practice__c</fullName>
    <label>Practice</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Practices</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/CurrencyConversionRatio__c.field-meta.xml
<CustomField>
    <fullName>CurrencyConversionRatio__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Currency Conversion Ratio</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/DerivedFromId__c.field-meta.xml
<CustomField>
    <fullName>DerivedFromId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Derived From</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Versions</relationshipLabel>
    <relationshipName>QuoteVersions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Practice__c.field-meta.xml
<CustomField>
    <fullName>Practice__c</fullName>
    <label>Practice</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Practices</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/RateCardId__c.field-meta.xml
<CustomField>
    <fullName>RateCardId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate Card</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(3 OR 1) AND (4 OR 2) AND 5</booleanFilter>
        <errorMessage
		>The Rate Card is expired/inactive during the selected service start date</errorMessage>
        <filterItems>
            <field>$Source.ServiceStartDate__c</field>
            <operation>greaterOrEqual</operation>
            <valueField>RateCard__c.EffectiveDate__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.ServiceStartDate__c</field>
            <operation>lessOrEqual</operation>
            <valueField>RateCard__c.ExpirationDate__c</valueField>
        </filterItems>
        <filterItems>
            <field>RateCard__c.EffectiveDate__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <filterItems>
            <field>RateCard__c.ExpirationDate__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <filterItems>
            <field>RateCard__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>RateCard__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/SectionHierarchy__c.field-meta.xml
<CustomField>
    <fullName>SectionHierarchy__c</fullName>
    <label>Section Hierarchy</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Simple</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/TimePeriod__c.field-meta.xml
<CustomField>
    <fullName>TimePeriod__c</fullName>
    <label>Time Periods</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Months</fullName>
            </value>
            <value>
                <fullName>Days</fullName>
            </value>
            <value>
                <fullName>Weeks</fullName>
            </value>
            <value>
                <fullName>Quarters</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/TimePeriodsGroupMethod__c.field-meta.xml
<CustomField>
    <fullName>TimePeriodsGroupMethod__c</fullName>
    <label>Time Periods Group Method</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>TimePeriod__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Year</fullName>
            </value>
            <value>
                <fullName>Quarter</fullName>
            </value>
            <value>
                <fullName>Month</fullName>
            </value>
            <value>
                <fullName>Week</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&apos;Quote&apos;</defaultValue>
    <description>Indicates the type of quote.</description>
    <inlineHelpText>Indicates the type of quote.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Collaboration</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Scenario</fullName>
            </value>
            <value>
                <fullName>Template</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteItem__c/QuoteItem__c.object-meta.xml
<CustomObject>
    <label>Quote Item</label>
    <nameField>
        <displayFormat>QI-{0000000}</displayFormat>
        <label>Quote Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteItem__c/fields/AdjustmentId__c.field-meta.xml
<CustomField>
    <fullName>AdjustmentId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Adjustment</label>
    <referenceTo>Adjustment__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteItem__c/fields/CurrencyConversionRatio__c.field-meta.xml
<CustomField>
    <fullName>CurrencyConversionRatio__c</fullName>
    <formula>QuoteId__r.CurrencyConversionRatio__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Currency Conversion Ratio</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteItem__c/fields/DerivedFromId__c.field-meta.xml
<CustomField>
    <fullName>DerivedFromId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Derived From</label>
    <referenceTo>QuoteItem__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>QuoteItemVersions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteItem__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteItem__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QuoteItem__c/fields/QuoteSectionId__c.field-meta.xml
<CustomField>
    <fullName>QuoteSectionId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Section</label>
    <referenceTo>QuoteSection__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteSection__c/QuoteSection__c.object-meta.xml
<CustomObject>
    <label>Quote Section</label>
    <nameField>
        <label>Quote Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteSection__c/fields/DerivedFromId__c.field-meta.xml
<CustomField>
    <fullName>DerivedFromId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Derived From</label>
    <referenceTo>QuoteSection__c</referenceTo>
    <relationshipLabel>Quote Section Versions</relationshipLabel>
    <relationshipName>QuoteSectionVersions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Groups.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Salesforce Implementation</fullName>
    </customValue>
    <customValue>
        <fullName>SAP Implementation</fullName>
    </customValue>
    <customValue>
        <fullName>Web &amp; Mobile Apps</fullName>
    </customValue>
    <customValue>
        <fullName>Java</fullName>
    </customValue>
    <customValue>
        <fullName>.Net</fullName>
    </customValue>
    <customValue>
        <fullName>Sales Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>Service Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>SFDC Integration</fullName>
    </customValue>
    <customValue>
        <fullName>SAP C/4 HANA CUSTOMER EXP</fullName>
    </customValue>
    <customValue>
        <fullName>SAP S/4 HANA CLOUD ERP</fullName>
    </customValue>
    <customValue>
        <fullName>SAP SUCCESS FACTORS</fullName>
    </customValue>
    <customValue>
        <fullName>SAP ARIBA</fullName>
    </customValue>
    <customValue>
        <fullName>SAP BUSINESS OBJECTS</fullName>
    </customValue>
    <customValue>
        <fullName>SAP ACTIVATE</fullName>
    </customValue>
    <customValue>
        <fullName>SAP CLOUD PLATFORM Integration</fullName>
    </customValue>
    <customValue>
        <fullName>Oracle Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>Oracle Infrastructure</fullName>
    </customValue>
    <customValue>
        <fullName>Oracle Live</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Web Services Basics</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Computer Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Network Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Storage Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Database Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Analytics Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Application Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Web Services Resources</fullName>
    </customValue>
    <customValue>
        <fullName>AI + Machine Learning</fullName>
    </customValue>
    <customValue>
        <fullName>Analytics</fullName>
    </customValue>
    <customValue>
        <fullName>Blockchain</fullName>
    </customValue>
    <masterLabel>Groups</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Practices.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Custom Development</fullName>
        <label>Web Development</label>
    </customValue>
    <customValue>
        <fullName>Cloud Consulting</fullName>
    </customValue>
    <customValue>
        <fullName>Outsourcing</fullName>
    </customValue>
    <customValue>
        <fullName>AWS</fullName>
    </customValue>
    <customValue>
        <fullName>GCP</fullName>
    </customValue>
    <customValue>
        <fullName>DevOps</fullName>
    </customValue>
    <customValue>
        <fullName>Java</fullName>
    </customValue>
    <customValue>
        <fullName>Python</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>SAP</fullName>
    </customValue>
    <customValue>
        <fullName>SFDC</fullName>
    </customValue>
    <customValue>
        <fullName>Oracle</fullName>
    </customValue>
    <customValue>
        <fullName>CI/CD</fullName>
    </customValue>
    <customValue>
        <fullName>ERP</fullName>
        <isActive>false</isActive>
        <label>ERP</label>
    </customValue>
    <customValue>
        <fullName>CRM</fullName>
        <isActive>false</isActive>
        <label>CRM</label>
    </customValue>
    <masterLabel>Practices</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/QuoteService.cls
/**
 *  Provus Services Quoting
 *  QuoteService
 *  @2021 Provus Inc. All rights reserved.
 */
public with sharing class QuoteService {
	// constants
	public static final String RECORDTYPE_NAME_COLLABORATION = 'Collaboration';
	public static final String RECORDTYPE_NAME_QUOTE = 'Quote';
	public static final String RECORDTYPE_NAME_SCENARIO = 'Scenario';
	public static final String RECORDTYPE_NAME_TEMPLATE = 'Template';

	public static final String STATUS_ACTIVE = 'Active';

	public static final String TIMEPERIOD_MONTHS = 'Months';
	public static final String TIMEPERIODSGROUPMETHOD_YEAR = 'Year';
	public static final String TIMEPERIODSALIGNMENT_CALENDAR = 'Calendar';

	// runtime context
	public Quote__c quoteSO;
	public Id rateCardId;
	public String quotePractice;
	public String quoteGroup;
	public Boolean isScenarioPricePending;
	public Boolean hasAddOns;
	public String currencyCode;
	public Decimal currencyConversionRatio;

	// constructor
	public QuoteService(Id quoteId) {
		Id addOnRecordTypeId = Schema.SObjectType.Product2.getRecordTypeInfosByDeveloperName()
			.get(ProductService.RECORDTYPE_NAME_ANCILLARY)
			.getRecordTypeId();

		QueryRequest queryQuoteItems = new QueryRequest(
			SystemUtility.getInverseRName(Schema.Quote__c.SObjectType, Schema.QuoteItem__c.SObjectType)
		);
		queryQuoteItems.requestedFields = new Set<String>{ SObjectUtility.FIELD_ID };

		queryQuoteItems.setFilterBy(
			new Map<String, String>{
				SystemUtility.getChildRName(
					Schema.QuoteItem__c.ProductId__c,
					Schema.Product2.RecordtypeId
				) => addOnRecordTypeId
			}
		);

		QueryRequest queryRequest = new QueryRequest(Quote__c.SObjectType);
		Set<String> requestedFields = new Set<String>{
			SObjectUtility.FIELD_ID,
			Schema.Quote__c.Type__c + '',
			Schema.Quote__c.Group__c + '',
			Schema.Quote__c.MarginPercent__c + '',
			Schema.Quote__c.Practice__c + '',
			Schema.Quote__c.SectionHierarchy__c + '',
			Schema.Quote__c.RateCardId__c + '',
			Schema.Quote__c.TimePeriod__c + '',
			Schema.Quote__c.TimePeriodsGroupMethod__c + '',
			Schema.Quote__c.TotalAmount__c + '',
			Schema.Quote__c.CurrencyConversionRatio__c + ''
		};

		if (MultiCurrencyService.isMultiCurrencyEnabled()) {
			requestedFields.add(MultiCurrencyService.CURRENCY_ISO_CODE);
		}

		queryRequest.requestedFields = requestedFields;
		queryRequest.setFilterBy(new Map<String, String>{ SObjectUtility.FIELD_ID => quoteId });
		queryRequest.innerQueries = new List<QueryRequest>{ queryQuoteItems };
		List<Quote__c> quotes = (List<Quote__c>) SOQLUtility.querySObject(queryRequest);
		quoteSO = quotes[0];

		currencyConversionRatio = quoteSO.CurrencyConversionRatio__c;
		if (MultiCurrencyService.isMultiCurrencyEnabled()) {
			currencyCode = (String) quoteSO.get(MultiCurrencyService.CURRENCY_ISO_CODE);
		}
		rateCardId = quoteSO.RateCardId__c;
		quotePractice = quoteSO.Practice__c;
		quoteGroup = quoteSO.Group__c;
		isScenarioPricePending = RECORDTYPE_NAME_SCENARIO == quoteSO.Type__c;
		hasAddOns = quoteSO.QuoteItems__r.size() > 0;
	}

	public static Quote__c cloneQuote(Id sourceQuoteId, Set<Id> quoteSectionIds) {
		SObjectType quoteType = Schema.Quote__c.SObjectType;
		QueryRequest queryRequest = new QueryRequest(quoteType);
		queryRequest.requestedFields = SObjectUtility.getFieldsForSObject(quoteType);
		queryRequest.setFilterBy(new Map<String, String>{ SObjectUtility.FIELD_ID => sourceQuoteId });
		List<Quote__c> sourceQuotes = (List<Quote__c>) SOQLUtility.querySObject(queryRequest);

		Quote__c clonedQuote;
		if (sourceQuotes.size() > 0) {
			Quote__c sourceQuote = sourceQuotes[0];
			clonedQuote = sourceQuote.clone(false, true);
			clonedQuote.DerivedFromId__c = sourceQuote.Id;
			clonedQuote.TemplateId__c = null;
			clonedQuote.ServiceId__c = sourceQuote.ServiceId__c;

			CRUDUtility.insertRecords(clonedQuote);
			QuoteService.copyQuoteChildEntities(sourceQuote.Id, clonedQuote.Id, quoteSectionIds);
		}

		return clonedQuote;
	}

	public static Quote__c cloneQuote(Id sourceQuoteId) {
		return cloneQuote(sourceQuoteId, null);
	}

	/**
	 * @param quotes list of quotes
	 */
	public static void applyQuoteTemplateAfter(List<Quote__c> quotes) {
		Map<Id, Set<Id>> quotesByTemplateId = new Map<Id, Set<Id>>();

		// STEP I - Order the Quote Items by their Template Id
		for (Quote__c quote : quotes) {
			if (quote.TemplateId__c != null && quote.Type__c != RECORDTYPE_NAME_COLLABORATION) {
				Set<Id> quotesForTemplate = quotesByTemplateId.get(quote.TemplateId__c);
				if (quotesForTemplate == null) {
					quotesForTemplate = new Set<Id>();
					quotesByTemplateId.put(quote.TemplateId__c, quotesForTemplate);
				}

				quotesForTemplate.add(quote.Id);
			}
		}

		if (!quotesByTemplateId.isEmpty()) {
			copyQuoteChildEntities(quotesByTemplateId, null);
		}
	}

	public static void copyQuoteChildEntities(Id fromQuote, Id toQuote, Set<Id> quoteSectionIds) {
		copyQuoteChildEntities(
			new Map<Id, Set<Id>>{ fromQuote => new Set<Id>{ toQuote } },
			quoteSectionIds
		);
	}

	public static void copyQuoteChildEntities(
		Map<Id, Set<Id>> oldQuoteToNewQuotes,
		Set<Id> quoteSectionIds
	) {
		Map<Id, Map<Id, SObject>> mapQuoteSectionSO = copyQuoteSections(
			oldQuoteToNewQuotes,
			quoteSectionIds
		);

		Map<Id, Map<Id, SObject>> mapQuoteItemSO = copyQuoteItems(
			oldQuoteToNewQuotes,
			mapQuoteSectionSO,
			quoteSectionIds
		);

		Map<Id, Id> newItemIdBySourceItemId = new Map<Id, Id>();
		for (Map<Id, SObject> itemBySourceId : mapQuoteItemSO.values()) {
			for (Id sourceId : itemBySourceId.keySet()) {
				newItemIdBySourceItemId.put(sourceId, itemBySourceId.get(sourceId).Id);
			}
		}
		copyNamedRangeTotals(oldQuoteToNewQuotes, newItemIdBySourceItemId);

		AdjustmentService.AdjustmentCloneInfo adjCloneInfo = new AdjustmentService.AdjustmentCloneInfo(
			mapQuoteItemSO
		);
		Map<Id, Adjustment__c> adjustmentsToInsert = AdjustmentService.getAdjustmentsToInsert(
			adjCloneInfo
		);
		CRUDUtility.insertRecords(adjustmentsToInsert.values());

		AdjustmentService.updateAdjustmentIdOnQuoteItems(adjustmentsToInsert);
		List<QuoteItemCell__c> quoteItemCellsToInsert = AdjustmentService.getQuoteItemCellsToInsert(
			adjCloneInfo
		);
		CRUDUtility.insertRecords(quoteItemCellsToInsert);
	}

	private static Map<Id, Map<Id, SObject>> copyQuoteSections(
		Map<Id, Set<Id>> oldQuoteToNewQuotes,
		Set<Id> quoteSectionIds
	) {
		// TODO: Define a Setting for all applicable objects
		// STEP I - Clone the quote sections from the template to the new quote
		Map<Id, Map<Id, SObject>> newQuoteSections = SystemUtility.cloneChildEntities(
			Schema.QuoteSection__c.SObjectType,
			QuoteSectionService.RELATED_QUOTE_ID,
			oldQuoteToNewQuotes
		);

		List<QuoteSection__c> quoteSectionsToInsert = getQuoteSectionsToInsert(
			newQuoteSections,
			quoteSectionIds
		);

		CRUDUtility.insertRecords(quoteSectionsToInsert);

		return newQuoteSections;
	}

	private static List<QuoteSection__c> getQuoteSectionsToInsert(
		Map<Id, Map<Id, SObject>> newQuoteSections,
		Set<Id> quoteSectionIds
	) {
		List<QuoteSection__c> quoteSectionsToInsert = new List<QuoteSection__c>();
		for (Id targetQuoteId : newQuoteSections.keySet()) {
			for (Id sourceSectionId : newQuoteSections.get(targetQuoteId).keySet()) {
				QuoteSection__c targetSection = (QuoteSection__c) newQuoteSections.get(targetQuoteId)
					.get(sourceSectionId);
				targetSection.DerivedFromId__c = sourceSectionId;

				if (quoteSectionIds != null) {
					if (quoteSectionIds.contains(sourceSectionId)) {
						quoteSectionsToInsert.add(targetSection);
					}
				} else {
					quoteSectionsToInsert.add(targetSection);
				}
			}
		}
		return quoteSectionsToInsert;
	}

	private static Map<Id, Map<Id, SObject>> copyNamedRangeTotals(
		Map<Id, Set<Id>> oldQuoteToNewQuotes,
		Map<Id, Id> newItemIdBySourceItemId
	) {
		Map<Id, Map<Id, SObject>> namedRangeTotals = SystemUtility.cloneChildEntities(
			NamedRangeTotal__c.SObjectType,
			NamedRangeTotal.FIELD_NAME_QUOTE_ID,
			oldQuoteToNewQuotes
		);

		List<NamedRangeTotal__c> namedRangeTotalsToInsert = getNamedRangeTotalsToInsert(
			namedRangeTotals
		);
		CRUDUtility.insertRecords(namedRangeTotalsToInsert);

		List<NamedRange__c> namedRangesToInsert = copyNamedRanges(
			oldQuoteToNewQuotes,
			namedRangeTotals,
			newItemIdBySourceItemId
		);
		CRUDUtility.insertRecords(namedRangesToInsert);

		return namedRangeTotals;
	}

	private static List<NamedRangeTotal__c> getNamedRangeTotalsToInsert(
		Map<Id, Map<Id, SObject>> namedRangeTotals
	) {
		List<NamedRangeTotal__c> namedRangeTotalsToInsert = new List<NamedRangeTotal__c>();
		for (Map<Id, SObject> namedRangeTotalsByOldId : namedRangeTotals.values()) {
			namedRangeTotalsToInsert.addAll((List<NamedRangeTotal__c>) namedRangeTotalsByOldId.values());
		}
		return namedRangeTotalsToInsert;
	}

	private static List<NamedRange__c> copyNamedRanges(
		Map<Id, Set<Id>> oldQuoteToNewQuotes,
		Map<Id, Map<Id, SObject>> namedRangeTotals,
		Map<Id, Id> newItemIdBySourceItemId
	) {
		List<NamedRange__c> namedRangesToInsert = new List<NamedRange__c>();
		Map<Id, Map<Id, SObject>> namedRanges = SystemUtility.cloneChildEntities(
			NamedRange__c.SObjectType,
			Schema.NamedRange__c.QuoteId__c + '',
			oldQuoteToNewQuotes
		);

		if (namedRanges.size() > 0) {
			for (Id oldParentId : namedRanges.keySet()) {
				for (Id oldNamedRangeId : namedRanges.get(oldParentId).keySet()) {
					NamedRange__c namedRange = (NamedRange__c) namedRanges.get(oldParentId)
						.get(oldNamedRangeId);
					NamedRangeTotal__c namedRangeTotal = (NamedRangeTotal__c) namedRangeTotals.get(
							oldParentId
						)
						.get(namedRange.NamedRangeTotalId__c);

					namedRange.QuoteItemId__c = newItemIdBySourceItemId.get(namedRange.QuoteItemId__c);
					namedRange.NamedRangeTotalId__c = namedRangeTotal.Id;
					namedRangesToInsert.add(namedRange);
				}
			}
		}
		return namedRangesToInsert;
	}

	private static Map<Id, Map<Id, SObject>> copyQuoteItems(
		Map<Id, Set<Id>> oldQuoteToNewQuotes,
		Map<Id, Map<Id, SObject>> mapQuoteSectionSO,
		Set<Id> quoteSectionIds
	) {
		Map<String, Set<Id>> filterSetByFieldName = new Map<String, Set<Id>>{
			Schema.QuoteItem__c.QuoteId__c + '' => oldQuoteToNewQuotes.keySet()
		};

		if (quoteSectionIds != null && !quoteSectionIds.isEmpty()) {
			filterSetByFieldName.put(Schema.QuoteItem__c.QuoteSectionId__c + '', quoteSectionIds);
		}

		QueryRequest queryRequest = new QueryRequest(QuoteItem__c.SObjectType);
		queryRequest.requestedFields = SObjectUtility.getFieldsForSObject(QuoteItem__c.SObjectType);
		queryRequest.setFilterBy(filterSetByFieldName);

		// STEP II - Clone the quote line items
		Map<Id, Map<Id, SObject>> newQuoteItems = SystemUtility.cloneChildEntities(
			SOQLUtility.querySObject(queryRequest),
			Schema.QuoteItem__c.QuoteId__c + '',
			oldQuoteToNewQuotes
		);

		for (Map<Id, SObject> clonedItemBySourceId : newQuoteItems.values()) {
			for (Id sourceId : clonedItemBySourceId.keySet()) {
				QuoteItem__c clonedItem = (QuoteItem__c) clonedItemBySourceId.get(sourceId);
				clonedItem.DerivedFromId__c = sourceId;
			}
		}

		List<QuoteItem__c> quoteItemsToInsert = getQuoteItemsToInsert(newQuoteItems, mapQuoteSectionSO);
		CRUDUtility.insertRecords(quoteItemsToInsert);

		return newQuoteItems;
	}

	private static List<QuoteItem__c> getQuoteItemsToInsert(
		Map<Id, Map<Id, SObject>> newQuoteItems,
		Map<Id, Map<Id, SObject>> newQuoteSections
	) {
		// STEP III - Update the quote section id
		Map<Id, Id> newSectionIdBySourceId = new Map<Id, Id>();
		for (Map<Id, SObject> quoteSectionsById : newQuoteSections.values()) {
			for (SObject sectionSO : quoteSectionsById.values()) {
				newSectionIdBySourceId.put(((QuoteSection__c) sectionSO).DerivedFromId__c, sectionSO.Id);
			}
		}
		List<QuoteItem__c> quoteItemsToInsert = new List<QuoteItem__c>();
		for (Map<Id, SObject> quoteItemsByOldId : newQuoteItems.values()) {
			for (Id oldItemId : quoteItemsByOldId.keySet()) {
				QuoteItem__c quoteItem = (QuoteItem__c) quoteItemsByOldId.get(oldItemId);
				quoteItem.QuoteSectionId__c = newSectionIdBySourceId.get(quoteItem.QuoteSectionId__c);
				quoteItemsToInsert.add(quoteItem);
			}
		}
		return quoteItemsToInsert;
	}
}