force-app/main/default/objects/Adjustment__c/Adjustment__c.object-meta.xml
<CustomObject>
    <label>Adjustment</label>
    <nameField>
        <displayFormat>A-{0000000000}</displayFormat>
        <label>Adjustment</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Adjustments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Adjustment__c/fields/AppliedBy__c.field-meta.xml
<CustomField>
    <fullName>AppliedBy__c</fullName>
    <label>Applied By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Rule</fullName>
            </value>
            <value>
                <fullName>Promotion</fullName>
            </value>
            <value>
                <fullName>Incentive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Adjustment__c/fields/AppliedTo__c.field-meta.xml
<CustomField>
    <fullName>AppliedTo__c</fullName>
    <label>Applied To</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>Cost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Adjustment__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
            <value>
                <fullName>Rule</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Adjustment__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Discount Percent</fullName>
            </value>
            <value>
                <fullName>Discount Amount</fullName>
            </value>
            <value>
                <fullName>Markup Percent</fullName>
            </value>
            <value>
                <fullName>Markup Amount</fullName>
            </value>
            <value>
                <fullName>% Discount</fullName>
            </value>
            <value>
                <fullName>% Markup</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NamedRange__c/NamedRange__c.object-meta.xml
<CustomObject>
    <label>Named Range</label>
    <nameField>
        <label>Named Range Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Named Ranges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NamedRange__c/fields/NamedRangeTotalId__c.field-meta.xml
<CustomField>
    <fullName>NamedRangeTotalId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Named Range Total</label>
    <referenceTo>NamedRangeTotal__c</referenceTo>
    <relationshipLabel>Named Ranges</relationshipLabel>
    <relationshipName>NamedRanges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NamedRange__c/fields/ProjectPhaseId__c.field-meta.xml
<CustomField>
    <fullName>ProjectPhaseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Phase</label>
    <referenceTo>ProjectPhase__c</referenceTo>
    <relationshipLabel>Named Ranges</relationshipLabel>
    <relationshipName>NamedRanges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NamedRange__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Named Ranges</relationshipLabel>
    <relationshipName>NamedRanges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NamedRange__c/fields/QuoteItemId__c.field-meta.xml
<CustomField>
    <fullName>QuoteItemId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Item</label>
    <referenceTo>QuoteItem__c</referenceTo>
    <relationshipLabel>Named Ranges</relationshipLabel>
    <relationshipName>NamedRanges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NamedRange__c/fields/QuotePeriodGroupId__c.field-meta.xml
<CustomField>
    <fullName>QuotePeriodGroupId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Period Group</label>
    <referenceTo>QuotePeriodGroup__c</referenceTo>
    <relationshipLabel>Named Ranges</relationshipLabel>
    <relationshipName>NamedRanges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NamedRange__c/fields/QuotePeriodId__c.field-meta.xml
<CustomField>
    <fullName>QuotePeriodId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Period</label>
    <referenceTo>QuotePeriod__c</referenceTo>
    <relationshipLabel>Named Ranges</relationshipLabel>
    <relationshipName>NamedRanges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NamedRange__c/fields/QuoteSectionId__c.field-meta.xml
<CustomField>
    <fullName>QuoteSectionId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Section</label>
    <referenceTo>QuoteSection__c</referenceTo>
    <relationshipLabel>Named Ranges</relationshipLabel>
    <relationshipName>NamedRanges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NamedRange__c/fields/RangeSpecJSON__c.field-meta.xml
<CustomField>
    <fullName>RangeSpecJSON__c</fullName>
    <label>Range Spec (JSON)</label>
    <length>40000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NamedRange__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User Defined</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Quote Labor</fullName>
            </value>
            <value>
                <fullName>Quote Ancillaries</fullName>
            </value>
            <value>
                <fullName>Quote Item</fullName>
            </value>
            <value>
                <fullName>Quote Period</fullName>
            </value>
            <value>
                <fullName>Quote Period Group</fullName>
            </value>
            <value>
                <fullName>Quote Item Period Group</fullName>
            </value>
            <value>
                <fullName>Quote Section</fullName>
            </value>
            <value>
                <fullName>Project Phase</fullName>
            </value>
            <value>
                <fullName>Quote Item Project Phase</fullName>
            </value>
            <value>
                <fullName>Section Period</fullName>
            </value>
            <value>
                <fullName>Section Phase</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NamedRangeTotal__c/NamedRangeTotal__c.object-meta.xml
<CustomObject>
    <label>Named Range Total</label>
    <nameField>
        <displayFormat>NRT-{0000000}</displayFormat>
        <label>Named Range Total</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Named Range Totals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NamedRangeTotal__c/fields/MarginPercent__c.field-meta.xml
<CustomField>
    <fullName>MarginPercent__c</fullName>
    <label>Margin %</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/NamedRangeTotal__c/fields/NetExtendedCost__c.field-meta.xml
<CustomField>
    <fullName>NetExtendedCost__c</fullName>
    <label>Net Extended Cost</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NamedRangeTotal__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NamedRangeTotal__c/fields/QuantityUOM__c.field-meta.xml
<CustomField>
    <fullName>QuantityUOM__c</fullName>
    <label>Quantity UOM</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>QuantityUOMs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/NamedRangeTotal__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipName>CellRangeTotals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QuoteItem__c/QuoteItem__c.object-meta.xml
<CustomObject>
    <label>Quote Item</label>
    <nameField>
        <displayFormat>QI-{0000000}</displayFormat>
        <label>Quote Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteItem__c/fields/AdjustmentId__c.field-meta.xml
<CustomField>
    <fullName>AdjustmentId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Adjustment</label>
    <referenceTo>Adjustment__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteItem__c/fields/NetExtendedAmount__c.field-meta.xml
<CustomField>
    <fullName>NetExtendedAmount__c</fullName>
    <label>Net Extended Amount</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteItem__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QuoteItem__c/fields/QuoteSectionId__c.field-meta.xml
<CustomField>
    <fullName>QuoteSectionId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Section</label>
    <referenceTo>QuoteSection__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteItem__c/fields/SectionSequence__c.field-meta.xml
<CustomField>
    <fullName>SectionSequence__c</fullName>
    <label>Section Sequence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteItemCell__c/QuoteItemCell__c.object-meta.xml
<CustomObject>
    <label>Quote Item Cell</label>
    <nameField>
        <displayFormat>QIC-{0000000}</displayFormat>
        <label>Quote Item Cell</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Item Cells</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteItemCell__c/fields/QuoteItemId__c.field-meta.xml
<CustomField>
    <fullName>QuoteItemId__c</fullName>
    <label>Quote Item</label>
    <referenceTo>QuoteItem__c</referenceTo>
    <relationshipName>QuoteItemCells</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QuoteSection__c/QuoteSection__c.object-meta.xml
<CustomObject>
    <label>Quote Section</label>
    <nameField>
        <label>Quote Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteSection__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Sections</relationshipLabel>
    <relationshipName>QuoteSections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/QuantityUOMs.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Hour</fullName>
    </customValue>
    <customValue>
        <fullName>Resource</fullName>
    </customValue>
    <masterLabel>Quantity UOMs</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/QuoteItemService.cls
/**
 *  Provus Services Quoting
 *  QuoteItemService
 *  @2021 Provus Inc. All rights reserved.
 */
public with sharing abstract class QuoteItemService {
	/**
	 * Gets all quote items for quote
	 * @param   quoteId Id of the quote
	 * @return  List<QuoteItemStruct>
	 */
	public static List<QuoteItemDTO> getQuoteItemsForQuote(Id quoteId) {
		List<QuoteItemDTO> quoteItemDOs = new List<QuoteItemDTO>();
		for (QuoteItem__c quoteItemSO : QuoteItemServiceSupport.getQuoteItemSOsForQuote(quoteId)) {
			QuoteItem quoteItem = new QuoteItem(QuoteItemDTO.newDO(quoteItemSO));
			quoteItemDOs.add((QuoteItemDTO) quoteItem.baseDTO);
		}

		return quoteItemDOs;
	}

	/**
	 * Commit quote items for quote
	 * @param quoteId  Id of the quote
	 * @param quoteItemDTOs list of quote item DOs
	 *
	 * @return list of committed quote items
	 */
	public static List<QuoteItemDTO> commitQuoteItems(Id quoteId, List<QuoteItemDTO> quoteItemDTOs) {
		List<QuoteItemDTO> quoteItemsToCommit = new List<QuoteItemDTO>();
		List<QuoteItemDTO> quoteItemsToDelete = new List<QuoteItemDTO>();
		List<QuoteItem__c> quoteItemSOsToDelete = new List<QuoteItem__c>();
		List<QuoteItem__c> quoteItemSOsToCommit = new List<QuoteItem__c>();

		for (QuoteItemDTO quoteItemDO : quoteItemDTOs) {
			// sync DTO data to the SO object
			quoteItemDO.updateSO();
			if (quoteItemDO.quoteItemSO.Id == null) {
				// non-reparentable master detail field
				quoteItemDO.quoteItemSO.QuoteId__c = quoteId;
			}

			if (!quoteItemDO.isDelete()) {
				quoteItemSOsToCommit.add(quoteItemDO.quoteItemSO);
				quoteItemsToCommit.add(quoteItemDO);
			} else {
				quoteItemSOsToDelete.add(quoteItemDO.quoteItemSO);
				quoteItemsToDelete.add(quoteItemDO);
			}
		}

		commitAdjustmentsFor(quoteItemsToCommit);
		deleteAdjustmentsFor(quoteItemsToDelete);

		CRUDUtility.deleteRecords(quoteItemSOsToDelete);
		CRUDUtility.upsertRecords(quoteItemSOsToCommit);

		commitQuoteItemCellsFor(quoteItemsToCommit);

		for (QuoteItemDTO quoteItemDO : quoteItemDTOs) {
			// update DO fields with SO field values
			quoteItemDO.refreshDO();
		}

		return quoteItemsToCommit;
	}

	/**
	 * Queries and returns the quote items with fields needed for merge for the given
	 * section IDs.
	 * @param sectionIds A list of sections IDs
	 *
	 * @return A list of quote items containing fields needed for merge
	 */
	public static List<QuoteItem__c> getQuoteItemsForMergeFor(Set<Id> sectionIds) {
		String nsPrefix = SystemUtility.getNamespacePrefix();
		String adjustmentFieldRName = SystemUtility.getRName(Schema.QuoteItem__c.AdjustmentId__c);
		String quoteItemObjName = nsPrefix + QuoteItem.SOBJECT_NAME;
		Set<String> fieldSet = SObjectUtility.getCustomFieldsForSObject(quoteItemObjName);
		fieldSet.add(adjustmentFieldRName + '.' + SObjectUtility.FIELD_ID);
		fieldSet.add(adjustmentFieldRName + '.' + Schema.Adjustment__c.Amount__c);
		fieldSet.add(adjustmentFieldRName + '.' + Schema.Adjustment__c.AppliedBy__c);
		fieldSet.add(adjustmentFieldRName + '.' + Schema.Adjustment__c.AppliedTo__c);
		fieldSet.add(adjustmentFieldRName + '.' + Schema.Adjustment__c.Method__c);

		QueryRequest queryRequest = new QueryRequest(quoteItemObjName);
		queryRequest.requestedFields = fieldSet;
		queryRequest.setFilterBy(
			new Map<String, Set<Id>>{ Schema.QuoteItem__c.QuoteSectionId__c + '' => sectionIds }
		);
		return (List<QuoteItem__c>) SOQLUtility.querySObject(queryRequest);
	}

	private static void commitQuoteItemCellsFor(List<QuoteItemDTO> quoteItems) {
		List<QuoteItemCell__c> cellsToUpsert = new List<QuoteItemCell__c>();
		for (QuoteItemDTO ctxDO : quoteItems) {
			QuoteItemCell__c quoteItemCell = new QuoteItemCell__c(
				Id = ctxDO.quoteItemCellId,
				QuoteItemId__c = ctxDO.quoteItemSO.Id
			);

			for (String periodNumber : ctxDO.periodValueMap.keySet()) {
				Decimal periodValue = ctxDO.periodValueMap.get(periodNumber);
				String periodToken = quoteItemCellToken(periodNumber);
				quoteItemCell.put(periodToken, periodValue);
			}

			cellsToUpsert.add(quoteItemCell);
		}

		CRUDUtility.upsertRecords(cellsToUpsert);

		Integer loopIdx = 0;
		for (QuoteItemDTO ctxDO : quoteItems) {
			ctxDO.quoteItemCellId = cellsToUpsert[loopIdx++].Id;
		}
	}

	private static String quoteItemCellToken(String periodNumber) {
		return QuoteItemCell.PERIOD_FIELD_PREFIX + periodNumber + SObjectUtility.CUSTOM_FIELD_INDICATOR;
	}

	/**
	 * Resequences the quote items for the given quote ID.
	 * @param quoteId A quote ID
	 */
	public static void resequenceItemsFor(Id quoteId) {
		Integer nextSequence = 1;
		List<QuoteItem__c> quoteItems = new List<QuoteItem__c>();
		for (QuoteItem__c itemSO : [
			SELECT Id, Sequence__c
			FROM QuoteItem__c
			WHERE QuoteId__c = :quoteId
			WITH SECURITY_ENFORCED
			ORDER BY QuoteSectionId__r.Sequence__c NULLS LAST, SectionSequence__c, Sequence__c
			LIMIT :SOQLConstants.SOQL_QUERY_LIMIT
		]) {
			if (itemSO.Sequence__c != nextSequence) {
				itemSO.Sequence__c = nextSequence;
				quoteItems.add(itemSO);
			}

			nextSequence += 1;
		}

		CRUDUtility.updateRecords(quoteItems);
	}

	private static void commitAdjustmentsFor(List<QuoteItemDTO> quoteItems) {
		List<Adjustment__c> adjustmentsToUpsert = new List<Adjustment__c>();
		for (QuoteItemDTO ctxDO : quoteItems) {
			Adjustment__c adjustmentSO = ctxDO.adjustment.getSObject();
			adjustmentSO.Method__c = Adjustment.METHOD_INITIAL;
			adjustmentsToUpsert.add(adjustmentSO);
			CRUDUtility.upsertRecords(adjustmentsToUpsert);
		}

		// Resolve the Adjustment Id for Quote Items
		Integer loopIdx = 0;
		for (QuoteItemDTO ctxDO : quoteItems) {
			Adjustment__c ctxAdjustment = adjustmentsToUpsert[loopIdx++];
			ctxDO.quoteItemSO.AdjustmentId__c = ctxAdjustment.Id;
			ctxDO.adjustmentId = ctxAdjustment.Id;
		}
	}

	private static void deleteAdjustmentsFor(List<QuoteItemDTO> quoteItems) {
		List<Adjustment__c> adjustmentsToDelete = new List<Adjustment__c>();
		for (QuoteItemDTO ctxDO : quoteItems) {
			if (ctxDO.adjustmentId != null) {
				Adjustment__c adjustmentToDelete = new Adjustment__c();
				adjustmentToDelete.Id = ctxDO.adjustmentId;
				adjustmentsToDelete.add(adjustmentToDelete);
			}
		}

		CRUDUtility.deleteRecords(adjustmentsToDelete);
	}

	public static void deleteQuoteItemNamedRange(List<QuoteItem__c> quoteItemId) {
		List<NamedRange> requestNamedRanges = new List<NamedRange>();
		List<NamedRange__c> namedRangeList = [
			SELECT
				Id,
				Type__c,
				NamedRangeTotalId__c,
				NamedRangeTotalId__r.Id,
				NamedRangeTotalId__r.NetExtendedAmount__c,
				NamedRangeTotalId__r.NetExtendedCost__c,
				NamedRangeTotalId__r.Quantity__c,
				NamedRangeTotalId__r.QuantityUOM__c,
				NamedRangeTotalId__r.MarginPercent__c,
				Name,
				QuoteId__c,
				QuoteItemId__c,
				QuotePeriodId__c,
				QuotePeriodGroupId__c,
				QuoteSectionId__c,
				ProjectPhaseId__c,
				RangeSpecJSON__c
			FROM NamedRange__c
			WHERE QuoteItemId__c IN :quoteItemId
			WITH SECURITY_ENFORCED
			LIMIT :SOQLConstants.SOQL_QUERY_LIMIT
		];

		NamedRange namedRangeDO;
		NamedRange.NamedRangeDO namedRangeDOs;
		for (NamedRange__c namedRangeSO : namedRangeList) {
			namedRangeDO = new NamedRange(namedRangeSO);
			namedRangeDO.baseDTO.operationType = ManagedObject.OPERATION_TYPE_DELETE;
			namedRangeDOs = (NamedRange.NamedRangeDO) namedRangeDO.baseDTO;
			namedRangeDOs.relatedtotal.operationType = ManagedObject.OPERATION_TYPE_DELETE;
			requestNamedRanges.add(new NamedRange(namedRangeDOs));
		}
		NamedRange.commitNamedRanges(requestNamedRanges);
	}
}