force-app/main/default/objects/ScheduleSetting__mdt/ScheduleSetting__mdt.object-meta.xml
<CustomObject>
    <description
	>Provus application settings regarding standard resource sheduling factors such as hours in a standard work week which may vary from one organization to another based on a number of factors</description>
    <label>Schedule Setting</label>
    <pluralLabel>Schedule Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/ScheduleSetting__mdt/fields/StandardDayHours__c.field-meta.xml
<CustomField>
    <fullName>StandardDayHours__c</fullName>
    <description
	>Number of hours in a work day generally considered to be normal for your organization</description>
    <inlineHelpText
	>Number of hours in a work day generally considered to be normal for your organization</inlineHelpText>
    <label>Hours in a standard day</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ScheduleSetting__mdt/fields/StandardMonthHours__c.field-meta.xml
<CustomField>
    <fullName>StandardMonthHours__c</fullName>
    <description
	>Number of hours in a work month generally considered to be normal for your organization</description>
    <inlineHelpText
	>Number of hours in a work month generally considered to be normal for your organization</inlineHelpText>
    <label>Hours in a standard month</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ScheduleSetting__mdt/fields/StandardWeekHours__c.field-meta.xml
<CustomField>
    <fullName>StandardWeekHours__c</fullName>
    <description
	>Number of hours in a work week generally considered to be normal for your organization</description>
    <inlineHelpText
	>Number of hours in a work week generally considered to be normal for your organization</inlineHelpText>
    <label>Hours in a standard week</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ScheduleSetting__mdt/fields/StandardYearHours__c.field-meta.xml
<CustomField>
    <fullName>StandardYearHours__c</fullName>
    <description
	>Number of working hours in a year generally considered to be normal for your organization</description>
    <inlineHelpText
	>Number of working hours in a year generally considered to be normal for your organization</inlineHelpText>
    <label>Hours in a standard year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ScheduleSettingDTO.cls
/**
 *  Provus Services Quoting
 *  ProjectPhaseTest
 *  @2021 Provus Inc. All rights reserved.
 */
public with sharing class ScheduleSettingDTO {
	public ScheduleSetting__mdt sO;
	public Decimal standardDayHours;
	public Decimal standardWeekHours;
	public Decimal standardMonthHours;
	public Decimal standardYearHours;

	public ScheduleSettingDTO() {
	}

	public ScheduleSettingDTO(ScheduleSetting__mdt scheduleSetting) {
		this.sO = scheduleSetting;

		this.standardDayHours = scheduleSetting.StandardDayHours__c;
		this.standardWeekHours = scheduleSetting.StandardWeekHours__c;
		this.standardMonthHours = scheduleSetting.StandardMonthHours__c;
		this.standardYearHours = scheduleSetting.StandardYearHours__c;
	}
}