force-app/main/default/objects/ProjectPhase__c/ProjectPhase__c.object-meta.xml
<CustomObject>
    <label>Project Phase</label>
    <nameField>
        <label>Project Phase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Phases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectPhase__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Project Phases</relationshipLabel>
    <relationshipName>ProjectPhases</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ProjectPhase__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <label>Sequence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuotePeriod__c/QuotePeriod__c.object-meta.xml
<CustomObject>
    <label>Quote Period</label>
    <nameField>
        <label>Quote Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuotePeriod__c/fields/ProjectPhaseId__c.field-meta.xml
<CustomField>
    <fullName>ProjectPhaseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Phase</label>
    <referenceTo>ProjectPhase__c</referenceTo>
    <relationshipLabel>Quote Periods</relationshipLabel>
    <relationshipName>QuotePeriods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuotePeriod__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Periods</relationshipLabel>
    <relationshipName>QuotePeriods</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ProjectPhaseDO.cls
public class ProjectPhaseDO extends BaseDTO {
	public Id id;
	public String name;
	public Id quoteId;
	public Decimal sequence;
	public String description;
	public Date startDate;
	public Date endDate;

	public Id parentProjectPhaseId;
	public String parentProjectName;

	public List<Id> quotePeriodIdList;

	public static BaseDTO newDO(SObject fromSO) {
		ProjectPhase__c projectPhaseSO = (ProjectPhase__c) fromSO;
		ProjectPhaseDO newDO = new ProjectPhaseDO();
		newDO.id = projectPhaseSO.Id;
		newDO.name = projectPhaseSO.Name;
		newDO.quoteId = projectPhaseSO.QuoteId__c;
		newDO.sequence = projectPhaseSO.Sequence__c;
		newDO.description = projectPhaseSO.Description__c;
		newDO.startDate = projectPhaseSO.StartDate__c;
		newDO.endDate = projectPhaseSO.EndDate__c;

		newDO.quotePeriodIdList = new List<Id>();
		for (QuotePeriod__c quotePeriod : projectPhaseSO.QuotePeriods__r) {
			newDO.quotePeriodIdList.add(quotePeriod.Id);
		}

		return newDO;
	}

	public ProjectPhase__c newSO() {
		ProjectPhase__c projectPhaseSO = new ProjectPhase__c(
			Id = this.id,
			Name = this.name,
			QuoteId__c = this.quoteId,
			Sequence__c = this.sequence,
			Description__c = this.description,
			StartDate__c = this.startDate,
			EndDate__c = this.endDate
		);

		return projectPhaseSO;
	}
}