force-app/main/default/objects/ProjectPhase__c/ProjectPhase__c.object-meta.xml
<CustomObject>
    <label>Project Phase</label>
    <nameField>
        <label>Project Phase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Phases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectPhase__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Project Phases</relationshipLabel>
    <relationshipName>ProjectPhases</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ProjectPhaseTestsBase.cls
/**
 *  Provus Services Quoting
 *  ProjectPhaseTestsBase
 *  @2021 Provus Inc. All rights reserved.
 */
public with sharing abstract class ProjectPhaseTestsBase extends TestBase {
	public static ProjectPhase__c newPhase() {
		Quote__c testQuote = newQuote();
		return newPhase(testQuote.Id);
	}

	public static ProjectPhase__c newPhase(Id quoteId) {
		ProjectPhase__c newPhase = new ProjectPhase__c();
		newPhase.Name = 'Test Phase';
		newPhase.QuoteId__c = quoteId;

		CRUDUtility.insertRecords(newPhase);
		return newPhase;
	}

	public static ProjectPhaseDO newPhaseDO() {
		Quote__c testQuote = newQuote();
		return newPhaseDO(testQuote.Id);
	}

	public static ProjectPhaseDO newPhaseDO(Id quoteId) {
		ProjectPhaseDO newDO = new ProjectPhaseDO();
		newDO.quotePeriodIdList = new List<Id>();
		newDO.quoteId = quoteId;
		return newDO;
	}
}