force-app/main/default/objects/ProjectPhase__c/ProjectPhase__c.object-meta.xml
<CustomObject>
    <label>Project Phase</label>
    <nameField>
        <label>Project Phase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Phases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectPhase__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Project Phases</relationshipLabel>
    <relationshipName>ProjectPhases</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ProjectPhase__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <label>Sequence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuotePeriod__c/QuotePeriod__c.object-meta.xml
<CustomObject>
    <label>Quote Period</label>
    <nameField>
        <label>Quote Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuotePeriod__c/fields/ProjectPhaseId__c.field-meta.xml
<CustomField>
    <fullName>ProjectPhaseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Phase</label>
    <referenceTo>ProjectPhase__c</referenceTo>
    <relationshipLabel>Quote Periods</relationshipLabel>
    <relationshipName>QuotePeriods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuotePeriod__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Periods</relationshipLabel>
    <relationshipName>QuotePeriods</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ProjectPhaseDOTest.cls
/**
 *  Provus Services Quoting
 *  ProjectPhaseDOTest
 *  @2021 Provus Inc. All rights reserved.
 */
@IsTest
private class ProjectPhaseDOTest extends ProjectPhaseTestsBase {
	@IsTest
	static void itShouldConstructDOFromSO() {
		ProjectPhase__c newPhaseSO = newPhase();
		newPhaseSO.Name = 'Test Phase';
		newPhaseSO.Sequence__c = 2;
		newPhaseSO.Description__c = 'Testing the description';
		newPhaseSO.StartDate__c = Date.Today();
		newPhaseSO.EndDate__c = Date.Today() + 1;
		CRUDUtility.updateRecords(newPhaseSO);

		QuotePeriod__c testPeriod = newQuotePeriod(newPhaseSO.QuoteId__c);
		testPeriod.ProjectPhaseId__c = newPhaseSO.Id;
		CRUDUtility.updateRecords(testPeriod);

		ProjectPhase__c testPhaseSO = ProjectPhaseFactory.getProjectPhasesForQuote(
			newPhaseSO.QuoteId__c
		)[0];

		Test.startTest();
		ProjectPhaseDO testPhaseDO = (ProjectPhaseDO) ProjectPhaseDO.newDO(testPhaseSO);
		System.assertEquals(testPhaseDO.id, testPhaseSO.Id, 'Id should be copied to the DO');
		System.assertEquals(testPhaseDO.name, testPhaseSO.Name, 'Name should be copied to the DO');
		System.assertEquals(
			testPhaseDO.quoteId,
			testPhaseSO.QuoteId__c,
			'Quote Id should be copied to the DO'
		);
		System.assertEquals(
			testPhaseDO.sequence,
			testPhaseSO.Sequence__c,
			'Sequence should be copied to the DO'
		);
		System.assertEquals(
			testPhaseDO.description,
			testPhaseSO.Description__c,
			'Description should be copied to the DO'
		);
		System.assertEquals(
			testPhaseDO.startDate,
			testPhaseSO.StartDate__c,
			'Start Date should be copied to the DO'
		);
		System.assertEquals(
			testPhaseDO.endDate,
			testPhaseSO.EndDate__c,
			'End Date should be copied to the DO'
		);
		Test.stopTest();
	}

	@IsTest
	static void itShouldConstructSOFromDO() {
		ProjectPhaseDO newDO = newPhaseDO();
		newDO.name = 'Test Phase';
		newDO.sequence = 2;
		newDO.description = 'Testing the description';
		newDO.startDate = Date.Today();
		newDO.endDate = Date.Today() + 1;

		Test.startTest();
		ProjectPhase__c testPhaseSO = newDO.newSO();
		System.assertEquals(testPhaseSO.Name, newDO.name, 'Name should be copied to the DO');
		System.assertEquals(
			testPhaseSO.QuoteId__c,
			newDO.quoteId,
			'Quote Id should be copied to the DO'
		);
		System.assertEquals(
			testPhaseSO.Sequence__c,
			newDO.sequence,
			'Sequence should be copied to the DO'
		);
		System.assertEquals(
			testPhaseSO.Description__c,
			newDO.description,
			'Description should be copied to the DO'
		);
		System.assertEquals(
			testPhaseSO.StartDate__c,
			newDO.startDate,
			'Start Date should be copied to the DO'
		);
		System.assertEquals(
			testPhaseSO.EndDate__c,
			newDO.endDate,
			'End Date should be copied to the DO'
		);
		Test.stopTest();
	}
}