force-app/main/default/objects/ProjectPhase__c/ProjectPhase__c.object-meta.xml
<CustomObject>
    <label>Project Phase</label>
    <nameField>
        <label>Project Phase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Phases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuotePeriod__c/QuotePeriod__c.object-meta.xml
<CustomObject>
    <label>Quote Period</label>
    <nameField>
        <label>Quote Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuotePeriod__c/fields/ProjectPhaseId__c.field-meta.xml
<CustomField>
    <fullName>ProjectPhaseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Phase</label>
    <referenceTo>ProjectPhase__c</referenceTo>
    <relationshipLabel>Quote Periods</relationshipLabel>
    <relationshipName>QuotePeriods</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProjectPhase.cls
/**
 *  Provus Services Quoting
 *  ProjectPhase
 *  @2021 Provus Inc. All rights reserved.
 */
public with sharing class ProjectPhase extends ManagedObject {
	public ProjectPhase(ProjectPhaseDO projectPhaseDO) {
		super(projectPhaseDO);
		this.pSObject = projectPhaseDO.newSO();
	}

	public ProjectPhase(SObject projectPhaseSO) {
		super(ProjectPhaseDO.newDO(projectPhaseSO));
		this.pSObject = projectPhaseSO;
	}

	public static void commitProjectPhases(List<ProjectPhase> projectPhases) {
		List<ProjectPhase> projectPhasesToCommit = new List<ProjectPhase>();
		List<ProjectPhase__c> projectPhaseSOsToCommit = new List<ProjectPhase__c>();
		List<ProjectPhase__c> projectPhasesToDelete = new List<ProjectPhase__c>();
		for (ProjectPhase projectPhase : projectPhases) {
			ProjectPhase__c projectPhaseSO = (ProjectPhase__c) projectPhase.getSObject();

			if (!projectPhase.isDelete()) {
				projectPhaseSOsToCommit.add(projectPhaseSO);
				projectPhasesToCommit.add(projectPhase);
			} else {
				projectPhasesToDelete.add(projectPhaseSO);
			}
		}

		CRUDUtility.deleteRecords(projectPhasesToDelete);
		CRUDUtility.upsertRecords(projectPhaseSOsToCommit);

		updateQuotePeriodsFor(projectPhasesToCommit);
	}

	private static void updateQuotePeriodsFor(List<ProjectPhase> contextPhases) {
		List<QuotePeriod__c> quotePeriodsToUpdate = new List<QuotePeriod__c>();
		for (ProjectPhase phaseMO : contextPhases) {
			for (Id quotePeriodId : phaseMO.getPeriodIds()) {
				ProjectPhase__c projectPhaseSO = (ProjectPhase__c) phaseMO.getSObject();
				QuotePeriod__c periodToUpdate = new QuotePeriod__c();
				periodToUpdate.Id = quotePeriodId;
				periodToUpdate.ProjectPhaseId__c = projectPhaseSO.Id;
				quotePeriodsToUpdate.add(periodToUpdate);
			}
		}

		CRUDUtility.updateRecords(quotePeriodsToUpdate);
	}

	private List<Id> getPeriodIds() {
		return ((ProjectPhaseDO) baseDTO).quotePeriodIdList;
	}
}