force-app/main/default/objects/QuoteItem__c/QuoteItem__c.object-meta.xml
<CustomObject>
    <label>Quote Item</label>
    <nameField>
        <displayFormat>QI-{0000000}</displayFormat>
        <label>Quote Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteItem__c/fields/AdjustmentId__c.field-meta.xml
<CustomField>
    <fullName>AdjustmentId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Adjustment</label>
    <referenceTo>Adjustment__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteItem__c/fields/LineType__c.field-meta.xml
<CustomField>
    <fullName>LineType__c</fullName>
    <label>Line Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Resource</fullName>
                <default>true</default>
                <label>Resource</label>
            </value>
            <value>
                <fullName>Miscellaneous</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteItem__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteItem__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QuoteItem__c/fields/RateCardItemId__c.field-meta.xml
<CustomField>
    <fullName>RateCardItemId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate Card Item</label>
    <referenceTo>RateCardItem__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QuoteItem.cls
/**
 *  Provus Services Quoting
 *  QuoteItem
 *  @2021 Provus Inc. All rights reserved.
 */
public with sharing class QuoteItem extends ManagedObject {
	public static final String SOBJECT_NAME = 'QuoteItem__c';
	public static final String LINE_TYPE_MISCELLANEOUS = 'Miscellaneous';

	public QuoteItem(QuoteItemDTO quoteItemDO) {
		super(quoteItemDO);
		initialize(quoteItemDO);
	}

	private void initialize(QuoteItemDTO ctxDO) {
		// initialized by QuoteItem to avoid cyclical dependencies between QuoteItemDO and QuoteItemCell
		this.pSObject = ctxDO.quoteItemSO;

		if (this.pSObject != null) {
			QuoteItem__c ctxSO = (QuoteItem__c) this.pSObject;
			ctxSO.Id = ctxDO.id;
			if (ctxSO.Id == null) {
				ctxSO.QuoteId__c = ctxDO.quoteId;
			}

			ctxSO.ProductId__c = ctxDO.productId;
			ctxSO.RateCardItemId__c = ctxDO.rateCardItemId;
			ctxSO.Sequence__c = ctxDO.lineSequence;
			ctxSO.DisplaySequence__c = ctxDO.displaySequence;
			ctxSO.AdjustmentId__c = ctxDO.adjustmentId;

			ctxDO.isMiscellaneous = ctxSO.LineType__c == LINE_TYPE_MISCELLANEOUS;
		}
	}
}