force-app/main/default/objects/QuoteItem__c/QuoteItem__c.object-meta.xml
<CustomObject>
    <label>Quote Item</label>
    <nameField>
        <displayFormat>QI-{0000000}</displayFormat>
        <label>Quote Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteItem__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QuoteItem__c/fields/QuoteSectionId__c.field-meta.xml
<CustomField>
    <fullName>QuoteSectionId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Section</label>
    <referenceTo>QuoteSection__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteItem__c/fields/SectionSequence__c.field-meta.xml
<CustomField>
    <fullName>SectionSequence__c</fullName>
    <label>Section Sequence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteSection__c/QuoteSection__c.object-meta.xml
<CustomObject>
    <label>Quote Section</label>
    <nameField>
        <label>Quote Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteSection__c/fields/DisplaySequence__c.field-meta.xml
<CustomField>
    <fullName>DisplaySequence__c</fullName>
    <label>Display Sequence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteSection__c/fields/ParentQuoteSectionId__c.field-meta.xml
<CustomField>
    <fullName>ParentQuoteSectionId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Quote Section</label>
    <referenceTo>QuoteSection__c</referenceTo>
    <relationshipLabel>Child Quote Sections</relationshipLabel>
    <relationshipName>ParentQuoteSections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteSection__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Sections</relationshipLabel>
    <relationshipName>QuoteSections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/QuoteSectionDO.cls
/*
 * Provus Services Quoting
 * Copyright (c) 2021 Provus Inc. All rights reserved.
 */

public with sharing class QuoteSectionDO implements Comparable {
	public Id id;
	public String name;
	public Id quoteId;
	public Decimal sequence;
	public Decimal sectionSequence;
	public Decimal displaySequence;
	public Integer startRow;
	public String description;
	public String operationType;

	public Id parentSectionId;
	public String parentSectionName;
	public List<QuoteSectionDO> childSections = new List<QuoteSectionDO>();

	public List<Id> quoteItemIdList;

	public QuoteSectionDO(QuoteSection__c sectionSO) {
		this.id = sectionSO.Id;
		this.name = sectionSO.Name;
		this.quoteId = sectionSO.QuoteId__c;
		this.sequence = sectionSO.Sequence__c;
		this.displaySequence = sectionSO.DisplaySequence__c;
		this.sectionSequence = sectionSO.SectionSequence__c;
		this.description = sectionSO.Description__c;

		this.parentSectionId = sectionSO.ParentQuoteSectionId__c;
		this.parentSectionName = sectionSO.ParentQuoteSectionId__r.Name;

		List<Id> qteLineIdList = new List<Id>();
		for (QuoteItem__c qteItem : sectionSO.QuoteItems__r) {
			qteLineIdList.add(qteItem.Id);
		}
		if (qteLineIdList.size() > 0) {
			this.quoteItemIdList = qteLineIdList;
			this.startRow = sectionSO.QuoteItems__r[0].SectionSequence__c.intValue();
		}
	}

	public Integer compareTo(Object compareTo) {
		QuoteSectionDO compareToSection = (QuoteSectionDO) compareTo;
		if (this.sequence == compareToSection.sequence) {
			return 0;
		}

		if (this.sequence > compareToSection.sequence) {
			return 1;
		}

		return -1;
	}
}