force-app/main/default/objects/NamedRange__c/NamedRange__c.object-meta.xml
<CustomObject>
    <label>Named Range</label>
    <nameField>
        <label>Named Range Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Named Ranges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NamedRange__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Named Ranges</relationshipLabel>
    <relationshipName>NamedRanges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NamedRange__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User Defined</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Quote Labor</fullName>
            </value>
            <value>
                <fullName>Quote Ancillaries</fullName>
            </value>
            <value>
                <fullName>Quote Item</fullName>
            </value>
            <value>
                <fullName>Quote Period</fullName>
            </value>
            <value>
                <fullName>Quote Period Group</fullName>
            </value>
            <value>
                <fullName>Quote Item Period Group</fullName>
            </value>
            <value>
                <fullName>Quote Section</fullName>
            </value>
            <value>
                <fullName>Project Phase</fullName>
            </value>
            <value>
                <fullName>Quote Item Project Phase</fullName>
            </value>
            <value>
                <fullName>Section Period</fullName>
            </value>
            <value>
                <fullName>Section Phase</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&apos;Quote&apos;</defaultValue>
    <description>Indicates the type of quote.</description>
    <inlineHelpText>Indicates the type of quote.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Collaboration</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Scenario</fullName>
            </value>
            <value>
                <fullName>Template</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NamedRangeServiceTest.cls
/**
 *  Provus Services Quoting
 *  NamedRangeServiceTest
 *  @2021 Provus Inc. All rights reserved.
 */
@IsTest
private class NamedRangeServiceTest extends NamedRangeTestsBase {
	@IsTest
	static void itShouldReturnSuccess() {
		Quote__c testQuote = newQuote();
		NamedRange.NamedRangeDO namedRangeDO = new NamedRange.NamedRangeDO();
		namedRangeDO.quoteId = testQuote.Id;
		namedRangeDO.relatedTotal = new NamedRangeTotal.NamedRangeTotalDO();
		namedRangeDO.operationType = BaseDTO.OPERATION_TYPE_INSERT;

		Test.startTest();
		Boolean result = NamedRangeService.commitNamedRanges(
			JSON.serialize(new List<NamedRange.NamedRangeDO>{ namedRangeDO })
		);
		System.assertEquals(result, true, 'should return success');
		Test.stopTest();
	}

	@IsTest
	static void itShouldGetNamedRangesForQuote() {
		NamedRange__c newNamedRange = newNamedRange();

		Test.startTest();
		List<NamedRange.NamedRangeDO> quoteNamedRanges = NamedRangeService.getNamedRangesForQuote(
			newNamedRange.QuoteId__c
		);
		System.assertEquals(1, quoteNamedRanges.size(), 'should return 1 named range');
		System.assertEquals(
			newNamedRange.Id,
			quoteNamedRanges[0].namedRangeId,
			'should return named range for quote'
		);
		Test.stopTest();
	}

	@IsTest
	static void itShouldGetQuoteTotalNamedRange() {
		NamedRange__c newNamedRange = newNamedRange();
		newNamedRange.Type__c = NamedRange.TYPE_QUOTE;
		CRUDUtility.updateRecords(newNamedRange);

		Test.startTest();
		NamedRange.NamedRangeDO quoteNamedRange = NamedRangeService.getQuoteTotalForQuote(
			newNamedRange.QuoteId__c
		);

		System.assertEquals(
			newNamedRange.Id,
			quoteNamedRange?.namedRangeId,
			'should return quote total named range'
		);
		Test.stopTest();
	}

	@IsTest
	static void itShouldNotGetQuoteTotalNamedRange() {
		NamedRange__c newNamedRange = newNamedRange();

		Test.startTest();
		NamedRange.NamedRangeDO quoteNamedRange = NamedRangeService.getQuoteTotalForQuote(
			newNamedRange.QuoteId__c
		);
		System.assertEquals(null, quoteNamedRange, 'should not return quote total named range');
		Test.stopTest();
	}
}