force-app/main/default/objects/NamedRange__c/NamedRange__c.object-meta.xml
<CustomObject>
    <label>Named Range</label>
    <nameField>
        <label>Named Range Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Named Ranges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NamedRange__c/fields/ProjectPhaseId__c.field-meta.xml
<CustomField>
    <fullName>ProjectPhaseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Phase</label>
    <referenceTo>ProjectPhase__c</referenceTo>
    <relationshipLabel>Named Ranges</relationshipLabel>
    <relationshipName>NamedRanges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NamedRange__c/fields/QuoteItemId__c.field-meta.xml
<CustomField>
    <fullName>QuoteItemId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Item</label>
    <referenceTo>QuoteItem__c</referenceTo>
    <relationshipLabel>Named Ranges</relationshipLabel>
    <relationshipName>NamedRanges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NamedRange__c/fields/QuotePeriodGroupId__c.field-meta.xml
<CustomField>
    <fullName>QuotePeriodGroupId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Period Group</label>
    <referenceTo>QuotePeriodGroup__c</referenceTo>
    <relationshipLabel>Named Ranges</relationshipLabel>
    <relationshipName>NamedRanges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NamedRange__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User Defined</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Quote Labor</fullName>
            </value>
            <value>
                <fullName>Quote Ancillaries</fullName>
            </value>
            <value>
                <fullName>Quote Item</fullName>
            </value>
            <value>
                <fullName>Quote Period</fullName>
            </value>
            <value>
                <fullName>Quote Period Group</fullName>
            </value>
            <value>
                <fullName>Quote Item Period Group</fullName>
            </value>
            <value>
                <fullName>Quote Section</fullName>
            </value>
            <value>
                <fullName>Project Phase</fullName>
            </value>
            <value>
                <fullName>Quote Item Project Phase</fullName>
            </value>
            <value>
                <fullName>Section Period</fullName>
            </value>
            <value>
                <fullName>Section Phase</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProjectPhase__c/ProjectPhase__c.object-meta.xml
<CustomObject>
    <label>Project Phase</label>
    <nameField>
        <label>Project Phase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Phases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteItem__c/QuoteItem__c.object-meta.xml
<CustomObject>
    <label>Quote Item</label>
    <nameField>
        <displayFormat>QI-{0000000}</displayFormat>
        <label>Quote Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteItem__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteItem__c/fields/RoleNameOverride__c.field-meta.xml
<CustomField>
    <fullName>RoleNameOverride__c</fullName>
    <label>Role Name Override</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuotePeriodGroup__c/QuotePeriodGroup__c.object-meta.xml
<CustomObject>
    <label>Quote Period Group</label>
    <nameField>
        <label>Quote Period Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Period Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuotePeriodGroup__c/fields/QuotePeriodGroupId__c.field-meta.xml
<CustomField>
    <fullName>QuotePeriodGroupId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Period Group</label>
    <referenceTo>QuotePeriodGroup__c</referenceTo>
    <relationshipLabel>Quote Period Groups</relationshipLabel>
    <relationshipName>QuotePeriodGroups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QuoteSummaryService.cls
/**
 *  Provus Services Quoting
 *  @2021 Provus Inc. All rights reserved.
 */
public with sharing class QuoteSummaryService {
	public static List<QuoteSummaryDO> getQuoteSummaries(Id quoteId) {
		Map<String, QuoteSummaryDO> summariesByRangeName = generateSummaryDOs(quoteId);

		Map<String, QuoteSummaryDO> mapTotals = generateTotals(summariesByRangeName);
		setPercentageOfTotalFields(mapTotals, summariesByRangeName);
		for (String key : mapTotals.keySet()) {
			summariesByRangeName.put(key, mapTotals.get(key));
		}

		List<QuoteSummaryDO> summaries = summariesByRangeName.values();
		summaries.sort();
		return summaries;
	}

	private static Map<String, QuoteSummaryDO> generateSummaryDOs(Id quoteId) {
		Map<String, QuoteSummaryDO> summariesByRangeName = new Map<String, QuoteSummaryDO>();
		for (NamedRange__c namedRangeSO : NamedRangeService.getNamedRangesForSummaries(quoteId)) {
			String rangeType = getRangeType(namedRangeSO);
			String rangeName = getRangeName(namedRangeSO);

			if (rangeName == null) {
				continue;
			}

			createSummary(summariesByRangeName, namedRangeSO);

			if (rangeType == QuoteSummary.SUMMARYTYPE_ROLE) {
				createOverrideSummary(summariesByRangeName, namedRangeSO);
			}
		}

		return summariesByRangeName;
	}

	private static void createSummary(
		Map<String, QuoteSummaryDO> summariesByRangeName,
		NamedRange__c namedRangeSO
	) {
		String rangeType = getRangeType(namedRangeSO);
		String rangeName = getRangeName(namedRangeSO);
		QuoteSummaryDO summary = summariesByRangeName.get(rangeName);
		if (summary == null) {
			QuoteSummaryDO quoteStruct = new QuoteSummaryDO(rangeType, rangeName);
			quoteStruct.setSummary(namedRangeSO);
			summariesByRangeName.put(rangeName, quoteStruct);
		} else {
			summary.addToSummary(namedRangeSO);
		}
	}

	private static void createOverrideSummary(
		Map<String, QuoteSummaryDO> summariesByRangeName,
		NamedRange__c namedRangeSO
	) {
		String rangeName = getRangeName(namedRangeSO);
		String overrideName = namedRangeSO.Type__c == ProjectPhaseService.NRTYPE_QUOTE_ITEM
			? namedRangeSO.QuoteItemId__r.RoleNameOverride__c
			: null;
		String overrideSummaryName = overrideName != null ? overrideName : rangeName;
		QuoteSummaryDO overrideSummary = summariesByRangeName.get('override_' + overrideSummaryName);

		if (overrideSummary == null) {
			QuoteSummaryDO newSummary = new QuoteSummaryDO(
				QuoteSummary.SUMMARYTYPE_ROLE_OVERRIDE,
				overrideSummaryName
			);
			newSummary.setSummary(namedRangeSO);
			summariesByRangeName.put('override_' + overrideSummaryName, newSummary);
		} else {
			overrideSummary.addToSummary(namedRangeSO);
		}
	}

	private static String getRangeType(NamedRange__c range) {
		if (range.Type__c == ProjectPhaseService.NRTYPE_QUOTE_ITEM) {
			return QuoteSummary.SUMMARYTYPE_ROLE;
		} else if (range.Type__c == ProjectPhaseService.NRTYPE_QUOTE_PERIOD_GROUP) {
			return QuoteSummary.SUMMARYTYPE_PERIOD_GROUP;
		} else if (range.Type__c == ProjectPhaseService.NRTYPE_PROJECT_PHASE) {
			return QuoteSummary.SUMMARYTYPE_PROJECT_PHASE;
		}

		return null;
	}

	private static String getRangeName(NamedRange__c range) {
		if (range.Type__c == ProjectPhaseService.NRTYPE_QUOTE_ITEM) {
			return range.QuoteItemId__r.ProductId__r.Name;
		} else if (range.Type__c == ProjectPhaseService.NRTYPE_QUOTE_PERIOD_GROUP) {
			return range.QuotePeriodGroupId__r.Name;
		} else if (range.Type__c == ProjectPhaseService.NRTYPE_PROJECT_PHASE) {
			return range.ProjectPhaseId__r.Name;
		}

		return null;
	}

	private static Map<String, QuoteSummaryDO> generateTotals(
		Map<String, QuoteSummaryDO> mapQuoteStruct
	) {
		Map<String, QuoteSummaryDO> mapTotals = new Map<String, QuoteSummaryDO>();
		for (QuoteSummaryDO summaryDO : mapQuoteStruct.values()) {
			String summaryType;
			String summaryName;
			if (summaryDO.type == QuoteSummary.SUMMARYTYPE_ROLE) {
				summaryType = QuoteSummary.SUMMARYTYPE_RESOURCE_TOTALS;
				summaryName = System.Label.ResourceRoleTotals;
			} else if (summaryDO.type == QuoteSummary.SUMMARYTYPE_PROJECT_PHASE) {
				summaryType = QuoteSummary.SUMMARYTYPE_PROJECT_PHASE_TOTALS;
				summaryName = System.Label.ProjectPhaseTotals;
			} else if (summaryDO.type == QuoteSummary.SUMMARYTYPE_PERIOD_GROUP) {
				summaryType = QuoteSummary.SUMMARYTYPE_PERIOD_GROUP_TOTALS;
				summaryName = System.Label.PeriodGroupTotals;
			} else if (summaryDO.type == QuoteSummary.SUMMARYTYPE_ROLE_OVERRIDE) {
				summaryType = QuoteSummary.SUMMARYTYPE_RESOURCE_OVERRIDE_TOTALS;
				summaryName = System.Label.ResourceRoleTotals;
			}

			if (summaryName == null) {
				continue;
			}

			if (!mapTotals.containsKey(summaryType)) {
				QuoteSummaryDO quoteStructTotal = new QuoteSummaryDO(summaryType, summaryName);
				quoteStructTotal.setSummary(summaryDO);
				mapTotals.put(summaryType, quoteStructTotal);
			} else {
				mapTotals.get(summaryType).addToSummary(summaryDO);
			}
		}
		return mapTotals;
	}

	private static void setPercentageOfTotalFields(
		Map<String, QuoteSummaryDO> mapTotals,
		Map<String, QuoteSummaryDO> mapQuoteStruct
	) {
		Map<String, QuoteSummaryDO> totalsByType = new Map<String, QuoteSummaryDO>();
		for (QuoteSummaryDO totals : mapTotals.values()) {
			totalsByType.put(totals.type, totals);
		}

		for (QuoteSummaryDO summary : mapQuoteStruct.values()) {
			QuoteSummaryDO totals;
			if (summary.type == QuoteSummary.SUMMARYTYPE_ROLE) {
				totals = totalsByType.get(QuoteSummary.SUMMARYTYPE_RESOURCE_TOTALS);
			} else if (summary.type == QuoteSummary.SUMMARYTYPE_PERIOD_GROUP) {
				totals = totalsByType.get(QuoteSummary.SUMMARYTYPE_PERIOD_GROUP_TOTALS);
			} else if (summary.type == QuoteSummary.SUMMARYTYPE_PROJECT_PHASE) {
				totals = totalsByType.get(QuoteSummary.SUMMARYTYPE_PROJECT_PHASE_TOTALS);
			} else if (summary.type == QuoteSummary.SUMMARYTYPE_ROLE_OVERRIDE) {
				totals = totalsByType.get(QuoteSummary.SUMMARYTYPE_RESOURCE_OVERRIDE_TOTALS);
			}

			if (totals != null) {
				summary.calculatePercentages(totals);
			}
		}
	}
}