force-app/main/default/objects/NamedRange__c/NamedRange__c.object-meta.xml
<CustomObject>
    <label>Named Range</label>
    <nameField>
        <label>Named Range Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Named Ranges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NamedRange__c/fields/NamedRangeTotalId__c.field-meta.xml
<CustomField>
    <fullName>NamedRangeTotalId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Named Range Total</label>
    <referenceTo>NamedRangeTotal__c</referenceTo>
    <relationshipLabel>Named Ranges</relationshipLabel>
    <relationshipName>NamedRanges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NamedRange__c/fields/ProjectPhaseId__c.field-meta.xml
<CustomField>
    <fullName>ProjectPhaseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Phase</label>
    <referenceTo>ProjectPhase__c</referenceTo>
    <relationshipLabel>Named Ranges</relationshipLabel>
    <relationshipName>NamedRanges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NamedRange__c/fields/QuotePeriodGroupId__c.field-meta.xml
<CustomField>
    <fullName>QuotePeriodGroupId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Period Group</label>
    <referenceTo>QuotePeriodGroup__c</referenceTo>
    <relationshipLabel>Named Ranges</relationshipLabel>
    <relationshipName>NamedRanges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NamedRangeTotal__c/NamedRangeTotal__c.object-meta.xml
<CustomObject>
    <label>Named Range Total</label>
    <nameField>
        <displayFormat>NRT-{0000000}</displayFormat>
        <label>Named Range Total</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Named Range Totals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NamedRangeTotal__c/fields/MarginPercent__c.field-meta.xml
<CustomField>
    <fullName>MarginPercent__c</fullName>
    <label>Margin %</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/NamedRangeTotal__c/fields/NetExtendedCost__c.field-meta.xml
<CustomField>
    <fullName>NetExtendedCost__c</fullName>
    <label>Net Extended Cost</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NamedRangeTotal__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProjectPhase__c/ProjectPhase__c.object-meta.xml
<CustomObject>
    <label>Project Phase</label>
    <nameField>
        <label>Project Phase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Phases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectPhase__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <label>Sequence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuotePeriodGroup__c/QuotePeriodGroup__c.object-meta.xml
<CustomObject>
    <label>Quote Period Group</label>
    <nameField>
        <label>Quote Period Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Period Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuotePeriodGroup__c/fields/QuotePeriodGroupId__c.field-meta.xml
<CustomField>
    <fullName>QuotePeriodGroupId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Period Group</label>
    <referenceTo>QuotePeriodGroup__c</referenceTo>
    <relationshipLabel>Quote Period Groups</relationshipLabel>
    <relationshipName>QuotePeriodGroups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QuoteSummaryDO.cls
/**
 *  Provus Services Quoting
 *  @2021 Provus Inc. All rights reserved.
 */
public with sharing class QuoteSummaryDO implements Comparable {
	public Decimal totalAmount;
	public Decimal percentageTotalAmount;
	public Decimal totalCost;
	public Decimal percentageTotalCost;
	public Decimal marginPercent;
	public Decimal percentageMarginPercent;
	public Decimal totalQuantity;
	public Decimal percentageTotalQuantity;
	public Decimal sequence;
	public String type;
	public String rowName;

	public QuoteSummaryDO() {
		this.totalAmount = 0;
		this.percentageTotalAmount = 0;
		this.totalCost = 0;
		this.percentageTotalCost = 0;
		this.marginPercent = 0;
		this.percentageMarginPercent = 0;
		this.totalQuantity = 0;
		this.percentageTotalQuantity = 0;
	}

	public QuoteSummaryDO(String summaryType, String summaryName) {
		this();
		this.type = summaryType;
		this.rowName = summaryName;
	}

	public void setSummary(NamedRange__c namedRangeSO) {
		this.totalAmount = SystemUtility.nullToZero(
			namedRangeSO.NamedRangeTotalId__r.NetExtendedAmount__c
		);
		this.totalCost = SystemUtility.nullToZero(namedRangeSO.NamedRangeTotalId__r.NetExtendedCost__c);
		this.marginPercent = SystemUtility.nullToZero(
			namedRangeSO.NamedRangeTotalId__r.MarginPercent__c
		);
		this.totalQuantity = SystemUtility.nullToZero(namedRangeSO.NamedRangeTotalId__r.Quantity__c);

		if (this.type == QuoteSummary.SUMMARYTYPE_PROJECT_PHASE) {
			this.sequence = namedRangeSO.ProjectPhaseId__r.Sequence__c;
		} else if (this.type == QuoteSummary.SUMMARYTYPE_PERIOD_GROUP) {
			this.sequence = namedRangeSO.QuotePeriodGroupId__r.Sequence__c;
		}
	}

	public void setSummary(QuoteSummaryDO quoteSummaryDO) {
		this.marginPercent = SystemUtility.nullToZero(quoteSummaryDO.marginPercent);
		this.totalQuantity = SystemUtility.nullToZero(quoteSummaryDO.totalQuantity);
		this.totalAmount = SystemUtility.nullToZero(quoteSummaryDO.totalAmount);
		this.totalCost = SystemUtility.nullToZero(quoteSummaryDO.totalCost);

		// percentage of totals should always be 100%
		this.percentageTotalAmount = 1;
		this.percentageTotalCost = 1;
		this.percentageTotalQuantity = 1;
	}

	public void addToSummary(NamedRange__c namedRangeSO) {
		this.totalAmount += SystemUtility.nullToZero(
			namedRangeSO.NamedRangeTotalId__r.NetExtendedAmount__c
		);
		this.totalCost += SystemUtility.nullToZero(
			namedRangeSO.NamedRangeTotalId__r.NetExtendedCost__c
		);
		this.totalQuantity += SystemUtility.nullToZero(namedRangeSO.NamedRangeTotalId__r.Quantity__c);

		this.marginPercent = calculateMargin(this.totalAmount, this.totalCost);
	}

	public void addToSummary(QuoteSummaryDO quoteSummaryDO) {
		this.totalAmount += SystemUtility.nullToZero(quoteSummaryDO.totalAmount);
		this.totalCost += SystemUtility.nullToZero(quoteSummaryDO.totalCost);
		this.totalQuantity += SystemUtility.nullToZero(quoteSummaryDO.totalQuantity);
		this.marginPercent = calculateMargin(this.totalAmount, this.totalCost);
	}

	public void calculatePercentages(QuoteSummaryDO quoteSummaryDO) {
		if (NumericHelper.isNonZero(quoteSummaryDO.totalAmount) && this.totalAmount != null) {
			this.percentageTotalAmount = this.totalAmount / quoteSummaryDO.totalAmount;
		}

		if (NumericHelper.isNonZero(quoteSummaryDO.totalCost) && this.totalCost != null) {
			this.percentageTotalCost = this.totalCost / quoteSummaryDO.totalCost;
		}

		if (NumericHelper.isNonZero(quoteSummaryDO.totalQuantity) && this.totalQuantity != null) {
			this.percentageTotalQuantity = this.totalQuantity / quoteSummaryDO.totalQuantity;
		}
	}

	private Decimal calculateMargin(Decimal revenue, Decimal cost) {
		Decimal safeRevenue = 0;
		Decimal safeCost = 0;
		if (revenue != null) {
			safeRevenue = revenue;
		}

		if (cost != null) {
			safeCost = cost;
		}

		Decimal grossProfit = safeRevenue - safeCost;
		return (grossProfit == 0 || safeRevenue == 0) ? 0 : (grossProfit / safeRevenue);
	}

	public Integer compareTo(Object compareTo) {
		QuoteSummaryDO compareSummary = (QuoteSummaryDO) compareTo;
		if (this.sequence == compareSummary.sequence) {
			return 0;
		}

		if (this.sequence > compareSummary.sequence) {
			return 1;
		}

		return -1;
	}
}