force-app/main/default/objects/NamedRange__c/NamedRange__c.object-meta.xml
<CustomObject>
    <label>Named Range</label>
    <nameField>
        <label>Named Range Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Named Ranges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NamedRange__c/fields/ProjectPhaseId__c.field-meta.xml
<CustomField>
    <fullName>ProjectPhaseId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Phase</label>
    <referenceTo>ProjectPhase__c</referenceTo>
    <relationshipLabel>Named Ranges</relationshipLabel>
    <relationshipName>NamedRanges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NamedRange__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Named Ranges</relationshipLabel>
    <relationshipName>NamedRanges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NamedRange__c/fields/QuotePeriodGroupId__c.field-meta.xml
<CustomField>
    <fullName>QuotePeriodGroupId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Period Group</label>
    <referenceTo>QuotePeriodGroup__c</referenceTo>
    <relationshipLabel>Named Ranges</relationshipLabel>
    <relationshipName>NamedRanges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NamedRange__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User Defined</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Quote Labor</fullName>
            </value>
            <value>
                <fullName>Quote Ancillaries</fullName>
            </value>
            <value>
                <fullName>Quote Item</fullName>
            </value>
            <value>
                <fullName>Quote Period</fullName>
            </value>
            <value>
                <fullName>Quote Period Group</fullName>
            </value>
            <value>
                <fullName>Quote Item Period Group</fullName>
            </value>
            <value>
                <fullName>Quote Section</fullName>
            </value>
            <value>
                <fullName>Project Phase</fullName>
            </value>
            <value>
                <fullName>Quote Item Project Phase</fullName>
            </value>
            <value>
                <fullName>Section Period</fullName>
            </value>
            <value>
                <fullName>Section Phase</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProjectPhase__c/ProjectPhase__c.object-meta.xml
<CustomObject>
    <label>Project Phase</label>
    <nameField>
        <label>Project Phase Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Phases</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ProjectPhase__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Project Phases</relationshipLabel>
    <relationshipName>ProjectPhases</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ProjectPhase__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <label>Sequence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&apos;Quote&apos;</defaultValue>
    <description>Indicates the type of quote.</description>
    <inlineHelpText>Indicates the type of quote.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Collaboration</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Scenario</fullName>
            </value>
            <value>
                <fullName>Template</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuotePeriodGroup__c/QuotePeriodGroup__c.object-meta.xml
<CustomObject>
    <label>Quote Period Group</label>
    <nameField>
        <label>Quote Period Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Period Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuotePeriodGroup__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Period Groups</relationshipLabel>
    <relationshipName>QuotePeriodGroups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QuotePeriodGroup__c/fields/QuotePeriodGroupId__c.field-meta.xml
<CustomField>
    <fullName>QuotePeriodGroupId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Period Group</label>
    <referenceTo>QuotePeriodGroup__c</referenceTo>
    <relationshipLabel>Quote Period Groups</relationshipLabel>
    <relationshipName>QuotePeriodGroups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QuoteSummaryServiceTest.cls
/*
 * Provus Services Quoting
 * Copyright (c) 2021 Provus Inc. All rights reserved.
 */
@IsTest
private class QuoteSummaryServiceTest extends TestBase {
	private static QuotePeriodGroup__c newQuotePeriodGroup(Id quoteId) {
		QuotePeriodGroup__c newQuotePeriodGroup = new QuotePeriodGroup__c();
		newQuotePeriodGroup.QuoteId__c = quoteId;
		CRUDUtility.insertRecords(newQuotePeriodGroup);
		return newQuotePeriodGroup;
	}

	private static NamedRange__c newNamedRange(Id quoteId, String type) {
		NamedRange__c newNamedRange = new NamedRange__c();
		newNamedRange.QuoteId__c = quoteId;
		newNamedRange.Type__c = type;
		CRUDUtility.insertRecords(newNamedRange);
		return newNamedRange;
	}

	private static ProjectPhase__c newProjectPhase(Id quoteId) {
		ProjectPhase__c newProjectPhase = new ProjectPhase__c();
		newProjectPhase.QuoteId__c = quoteId;
		CRUDUtility.insertRecords(newProjectPhase);
		return newProjectPhase;
	}

	@IsTest
	static void shouldOrderPeriodGroupSequence() {
		Quote__c quote = newQuote();
		QuotePeriodGroup__c group2 = newQuotePeriodGroup(quote.Id);
		group2.Name = '2';
		group2.Sequence__c = 2;
		QuotePeriodGroup__c group3 = newQuotePeriodGroup(quote.Id);
		group3.Name = '3';
		group3.Sequence__c = 3;
		QuotePeriodGroup__c group1 = newQuotePeriodGroup(quote.Id);
		group1.Name = '1';
		group1.Sequence__c = 1;

		CRUDUtility.updateRecords(new List<QuotePeriodGroup__c>{ group1, group2, group3 });

		NamedRange__c range1 = newNamedRange(quote.Id, ProjectPhaseService.NRTYPE_QUOTE_PERIOD_GROUP);
		range1.QuotePeriodGroupId__c = group1.Id;
		NamedRange__c range2 = newNamedRange(quote.Id, ProjectPhaseService.NRTYPE_QUOTE_PERIOD_GROUP);
		range2.QuotePeriodGroupId__c = group2.Id;
		NamedRange__c range3 = newNamedRange(quote.Id, ProjectPhaseService.NRTYPE_QUOTE_PERIOD_GROUP);
		range3.QuotePeriodGroupId__c = group3.Id;

		CRUDUtility.updateRecords(new List<NamedRange__c>{ range1, range2, range3 });

		Test.startTest();
		List<QuoteSummaryDO> summaries = QuoteSummaryService.getQuoteSummaries(quote.Id);
		System.assertEquals('1', summaries[0].rowName, 'should be 1');
		System.assertEquals('2', summaries[1].rowName, 'should be 2');
		System.assertEquals('3', summaries[2].rowName, 'should be 3');
		Test.stopTest();
	}

	@IsTest
	static void shouldOrderProjectPhaseSequence() {
		Quote__c quote = newQuote();
		ProjectPhase__c phase2 = newProjectPhase(quote.Id);
		phase2.Name = '2';
		phase2.Sequence__c = 2;
		ProjectPhase__c phase3 = newProjectPhase(quote.Id);
		phase3.Name = '3';
		phase3.Sequence__c = 3;
		ProjectPhase__c phase1 = newProjectPhase(quote.Id);
		phase1.Name = '1';
		phase1.Sequence__c = 1;

		CRUDUtility.updateRecords(new List<ProjectPhase__c>{ phase1, phase2, phase3 });

		NamedRange__c range1 = newNamedRange(quote.Id, ProjectPhaseService.NRTYPE_PROJECT_PHASE);
		range1.ProjectPhaseId__c = phase1.Id;
		NamedRange__c range2 = newNamedRange(quote.Id, ProjectPhaseService.NRTYPE_PROJECT_PHASE);
		range2.ProjectPhaseId__c = phase2.Id;
		NamedRange__c range3 = newNamedRange(quote.Id, ProjectPhaseService.NRTYPE_PROJECT_PHASE);
		range3.ProjectPhaseId__c = phase3.Id;

		CRUDUtility.updateRecords(new List<NamedRange__c>{ range1, range2, range3 });

		Test.startTest();
		List<QuoteSummaryDO> summaries = QuoteSummaryService.getQuoteSummaries(quote.Id);
		System.assertEquals('1', summaries[0].rowName, 'should be 1');
		System.assertEquals('2', summaries[1].rowName, 'should be 2');
		System.assertEquals('3', summaries[2].rowName, 'should be 3');
		Test.stopTest();
	}
}