force-app/main/default/objects/ValueOverride__c/ValueOverride__c.object-meta.xml
<CustomObject>
    <label>Value Override</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Value Override Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Value Overrides</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ValueOverride__c/fields/FieldApiName__c.field-meta.xml
<CustomField>
    <fullName>FieldApiName__c</fullName>
    <description>API name of object being referenced for which to override values with</description>
    <inlineHelpText
	>API name of object being referenced for which to override values with</inlineHelpText>
    <label>Field API Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ValueOverride__c/fields/FieldValue__c.field-meta.xml
<CustomField>
    <fullName>FieldValue__c</fullName>
    <description>Stores override value for specified field</description>
    <inlineHelpText>Stores override value for specified field</inlineHelpText>
    <label>Field Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ValueOverride__c/fields/ObjectOverrideId__c.field-meta.xml
<CustomField>
    <fullName>ObjectOverrideId__c</fullName>
    <description>Lookup to override junction record</description>
    <inlineHelpText>Lookup to override junction record</inlineHelpText>
    <label>Object Override</label>
    <referenceTo>ObjectOverride__c</referenceTo>
    <relationshipLabel>Object Overrides</relationshipLabel>
    <relationshipName>ObjectValueOverrides</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ValueOverrideDTO.cls
/**
 *  Provus Services Quoting
 *  QuoteItem
 *  @2021 Provus Inc. All rights reserved.
 */
public with sharing class ValueOverrideDTO extends BaseDTO {
	public transient ValueOverride__c sO;
	@AuraEnabled
	public Id id { get; set; }
	@AuraEnabled
	public String fieldApiName { get; set; }
	@AuraEnabled
	public String fieldValue { get; set; }
	@AuraEnabled
	public String fieldLabel { get; set; }
	@AuraEnabled
	public String defaultFieldValue { get; set; }
	@AuraEnabled
	public Id objectValueOverrideId { get; set; }

	public ValueOverrideDTO() {
		sO = new ValueOverride__c();
	}

	public ValueOverrideDTO(String fieldApiName, String defaultFieldValue) {
		this.fieldApiName = fieldApiName;
		this.defaultFieldValue = defaultFieldValue;
	}

	public ValueOverrideDTO(ValueOverride__c valueOverrideSO) {
		this.id = valueOverrideSO.Id;
		this.fieldApiName = valueOverrideSO.FieldApiName__c;
		this.fieldValue = valueOverrideSO.FieldValue__c;
		this.objectValueOverrideId = valueOverrideSO.ObjectOverrideId__c;
		this.sO = valueOverrideSO;
	}

	public void refreshDO() {
		id = sO.Id;
		fieldApiName = sO.FieldApiName__c;
		fieldValue = sO.FieldValue__c;
		objectValueOverrideId = sO.ObjectOverrideId__c;
	}

	public void refreshSO() {
		sO.Id = id;
		sO.FieldApiName__c = fieldApiName;
		sO.FieldValue__c = fieldValue;
	}
}