force-app/main/default/objects/QuoteItemCell__c/QuoteItemCell__c.object-meta.xml
<CustomObject>
    <label>Quote Item Cell</label>
    <nameField>
        <displayFormat>QIC-{0000000}</displayFormat>
        <label>Quote Item Cell</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Item Cells</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteItemCell__c/fields/QuoteItemId__c.field-meta.xml
<CustomField>
    <fullName>QuoteItemId__c</fullName>
    <label>Quote Item</label>
    <referenceTo>QuoteItem__c</referenceTo>
    <relationshipName>QuoteItemCells</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/QuoteItemCell.cls
/**
 *  Provus Services Quoting
 *  @2021 Provus Inc. All rights reserved.
 */
public with sharing class QuoteItemCell {
	// constants
	public static final String SOBJECT_NAME = 'QuoteItemCell__c';
	public static final String QUOTE_ITEM_CHILD_RELATIONSHIP = 'QuoteItemCells__r';
	public static final String PERIOD_FIELD_PREFIX = SystemUtility.getNamespacePrefix() + 'c';
	public static final String FIELD_NAME_QUOTE_ITEM_ID = 'QuoteItemId__c';
	// instance variables
	private static List<String> periodColumns;

	public static List<String> getPeriodColumns() {
		if (periodColumns == null) {
			periodColumns = new List<String>();
			for (
				String fieldName : SObjectUtility.getCustomFieldsForSObject(
					Schema.QuoteItemCell__c.SObjectType + ''
				)
			) {
				if (fieldName.startsWith(PERIOD_FIELD_PREFIX.toLowerCase())) {
					periodColumns.add(fieldName);
				}
			}
		}

		return periodColumns;
	}
}