force-app/main/default/objects/ProvusSetup__mdt/ProvusSetup__mdt.object-meta.xml
<CustomObject>
    <description
	>Parent Provus setup metadata entity used to store Provus application-wide specific settings and configuration</description>
    <label>Provus Setup</label>
    <pluralLabel>Provus Setups</pluralLabel>
</CustomObject>

force-app/main/default/objects/ScheduleSetting__mdt/ScheduleSetting__mdt.object-meta.xml
<CustomObject>
    <description
	>Provus application settings regarding standard resource sheduling factors such as hours in a standard work week which may vary from one organization to another based on a number of factors</description>
    <label>Schedule Setting</label>
    <pluralLabel>Schedule Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/ScheduleSetting__mdt/fields/StandardDayHours__c.field-meta.xml
<CustomField>
    <fullName>StandardDayHours__c</fullName>
    <description
	>Number of hours in a work day generally considered to be normal for your organization</description>
    <inlineHelpText
	>Number of hours in a work day generally considered to be normal for your organization</inlineHelpText>
    <label>Hours in a standard day</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ScheduleSetting__mdt/fields/StandardMonthHours__c.field-meta.xml
<CustomField>
    <fullName>StandardMonthHours__c</fullName>
    <description
	>Number of hours in a work month generally considered to be normal for your organization</description>
    <inlineHelpText
	>Number of hours in a work month generally considered to be normal for your organization</inlineHelpText>
    <label>Hours in a standard month</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ScheduleSetting__mdt/fields/StandardWeekHours__c.field-meta.xml
<CustomField>
    <fullName>StandardWeekHours__c</fullName>
    <description
	>Number of hours in a work week generally considered to be normal for your organization</description>
    <inlineHelpText
	>Number of hours in a work week generally considered to be normal for your organization</inlineHelpText>
    <label>Hours in a standard week</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ScheduleSetting__mdt/fields/StandardYearHours__c.field-meta.xml
<CustomField>
    <fullName>StandardYearHours__c</fullName>
    <description
	>Number of working hours in a year generally considered to be normal for your organization</description>
    <inlineHelpText
	>Number of working hours in a year generally considered to be normal for your organization</inlineHelpText>
    <label>Hours in a standard year</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SettingsService.cls
/**
 *  Provus Services Quoting
 *  ProjectPhaseTest
 *  @2021 Provus Inc. All rights reserved.
 */
public with sharing class SettingsService {
	public static final String FIELDNAME_SDAY_HOURS = 'StandardDayHours__c';
	public static final String FIELDNAME_SWEEK_HOURS = 'StandardWeekHours__c';
	public static final String FIELDNAME_SMONTH_HOURS = 'StandardMonthHours__c';
	public static final String FIELDNAME_SYEAR_HOURS = 'StandardYearHours__c';

	/**
	 * @return returns Provus Setup DTO object for consumption by client
	 */
	public static ProvusSetupDTO getProvusSetup() {
		ProvusSetup__mdt setupRecord = ProvusSetup__mdt.getInstance('Standard');
		return new ProvusSetupDTO(setupRecord);
	}

	/**
	 * @return returns Schedule Settings DTO object for consumption by client
	 */
	public static ScheduleSettingDTO getScheduleSettings() {
		ScheduleSetting__mdt scheduleSetting = ScheduleSetting__mdt.getInstance('StandardSchedule');
		return new ScheduleSettingDTO(scheduleSetting);
	}

	public static ScheduleSettingDTO getScheduleSettingsForQuote(Id quoteId) {
		ScheduleSettingDTO scheduleSetting = new ScheduleSettingDTO();
		String objectApiName = SystemUtility.getNamespacePrefix() + 'ScheduleSetting__mdt';
		ObjectOverrideDTO objectOverrideDto = ObjectOverrideController.getObjectOverride(
			quoteId,
			objectApiName
		);
		for (ValueOverrideDTO valueOverrideDto : objectOverrideDto.valueOverrides) {
			// has override value different from default value
			if (valueOverrideDto.fieldApiName.contains(FIELDNAME_SDAY_HOURS)) {
				scheduleSetting.standardDayHours = getFieldValue(valueOverrideDto);
			} else if (valueOverrideDto.fieldApiName.contains(FIELDNAME_SWEEK_HOURS)) {
				scheduleSetting.standardWeekHours = getFieldValue(valueOverrideDto);
			} else if (valueOverrideDto.fieldApiName.contains(FIELDNAME_SMONTH_HOURS)) {
				scheduleSetting.standardMonthHours = getFieldValue(valueOverrideDto);
			} else if (valueOverrideDto.fieldApiName.contains(FIELDNAME_SYEAR_HOURS)) {
				scheduleSetting.standardYearHours = getFieldValue(valueOverrideDto);
			}
		}
		return scheduleSetting;
	}

	private static Decimal getFieldValue(ValueOverrideDTO valueOverrideDto) {
		String hoursValue = '0';

		// if an override value exists use it instead
		if (
			valueOverrideDto.defaultFieldValue != null &&
			valueOverrideDto.fieldValue != null &&
			valueOverrideDto.fieldValue != valueOverrideDto.defaultFieldValue
		) {
			hoursValue = valueOverrideDto.fieldValue;
		} else if (valueOverrideDto.defaultFieldValue != null) {
			hoursValue = valueOverrideDto.defaultFieldValue;
		}

		return Decimal.valueOf(hoursValue);
	}
}