force-app/main/default/objects/ProvusConfiguratorSetting__mdt/ProvusConfiguratorSetting__mdt.object-meta.xml
<CustomObject>
    <label>Provus Configurator Setting</label>
    <pluralLabel>Provus Quoting Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/ProvusConfiguratorSetting__mdt/fields/DisableAutomaticOpportunitySync__c.field-meta.xml
<CustomField>
    <fullName>DisableAutomaticOpportunitySync__c</fullName>
    <defaultValue>false</defaultValue>
    <description
	>Checking this will disable any automatic syncing of quote price updates to their associated opportunities.</description>
    <label>Disable Automatic Opportunity Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProvusConfiguratorSetting__mdt/fields/HiddenFields__c.field-meta.xml
<CustomField>
    <fullName>HiddenFields__c</fullName>
    <label>Hidden Fields</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ProvusConfiguratorSetting__mdt/fields/ProductDefaultFields__c.field-meta.xml
<CustomField>
    <fullName>ProductDefaultFields__c</fullName>
    <label>Product Default Fields</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ProvusConfiguratorSetting__mdt/fields/QuoteItemDefaultFields__c.field-meta.xml
<CustomField>
    <fullName>QuoteItemDefaultFields__c</fullName>
    <label>Quote Item Default Fields</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ProvusConfiguratorSetting__mdt/fields/RequiredFields__c.field-meta.xml
<CustomField>
    <fullName>RequiredFields__c</fullName>
    <label>Required Fields</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ProvusConfiguratorSetting__mdt/fields/UneditableFields__c.field-meta.xml
<CustomField>
    <fullName>UneditableFields__c</fullName>
    <label>Uneditable Fields</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/CustomMetadataService.cls
/**
 *  Provus Services Quoting
 *  CustomMetadataService
 *  @2021 Provus Inc. All rights reserved.
 */
public with sharing class CustomMetadataService {
	public static final String DEFAULT_CUSTOM_METADATA = 'ProvusDefault';

	public static ProvusConfiguratorSetting__mdt defaultCustomMetadata {
		public get {
			if (defaultCustomMetadata == null) {
				defaultCustomMetadata = [
					SELECT
						DisableAutomaticOpportunitySync__c,
						ProductDefaultFields__c,
						QuoteItemDefaultFields__c,
						HiddenFields__c,
						RequiredFields__c,
						UneditableFields__c
					FROM ProvusConfiguratorSetting__mdt
					WHERE DeveloperName = :DEFAULT_CUSTOM_METADATA
					WITH SECURITY_ENFORCED
					LIMIT 1
				];
			}
			return defaultCustomMetadata;
		}
		public set;
	}

	public Set<String> getProductDefaultFields() {
		return fullyQualifiedFieldName(
			SystemUtility.csvToSet(defaultCustomMetadata.ProductDefaultFields__c)
		);
	}

	public Set<String> getQuoteItemDefaultFields() {
		return fullyQualifiedFieldName(
			SystemUtility.csvToSet(defaultCustomMetadata.QuoteItemDefaultFields__c)
		);
	}

	public Set<String> getHiddenFields() {
		return fullyQualifiedFieldName(SystemUtility.csvToSet(defaultCustomMetadata.HiddenFields__c));
	}

	public Set<String> getRequiredFields() {
		return fullyQualifiedFieldName(SystemUtility.csvToSet(defaultCustomMetadata.RequiredFields__c));
	}

	public Set<String> getUneditableFields() {
		return fullyQualifiedFieldName(
			SystemUtility.csvToSet(defaultCustomMetadata.UneditableFields__c)
		);
	}

	private Set<String> fullyQualifiedFieldName(Set<String> fieldNames) {
		Set<String> systemFields = new Set<String>{ 'name', 'id' };
		Set<String> qualifiedFieldNames = new Set<String>();
		String nsPrefix = SystemUtility.getNamespacePrefix();
		for (String fieldName : fieldNames) {
			String qualifiedFieldName = fieldName;
			if (
				!systemFields.contains(fieldName.toLowerCase()) && !fieldName.startsWithIgnoreCase(nsPrefix)
			) {
				qualifiedFieldName = nsPrefix + fieldName;
			}

			qualifiedFieldNames.add(qualifiedFieldName);
		}

		return qualifiedFieldNames;
	}
}