force-app/main/default/objects/Product2/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Practice__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Practice__c.field-meta.xml
<CustomField>
    <fullName>Practice__c</fullName>
    <label>Practice</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Practices</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <label>Product</label>
</RecordType>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/CurrencyConversionRatio__c.field-meta.xml
<CustomField>
    <fullName>CurrencyConversionRatio__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Currency Conversion Ratio</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Practice__c.field-meta.xml
<CustomField>
    <fullName>Practice__c</fullName>
    <label>Practice</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Practices</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/SectionHierarchy__c.field-meta.xml
<CustomField>
    <fullName>SectionHierarchy__c</fullName>
    <label>Section Hierarchy</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Simple</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/TimePeriod__c.field-meta.xml
<CustomField>
    <fullName>TimePeriod__c</fullName>
    <label>Time Periods</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Months</fullName>
            </value>
            <value>
                <fullName>Days</fullName>
            </value>
            <value>
                <fullName>Weeks</fullName>
            </value>
            <value>
                <fullName>Quarters</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/TimePeriodsGroupMethod__c.field-meta.xml
<CustomField>
    <fullName>TimePeriodsGroupMethod__c</fullName>
    <label>Time Periods Group Method</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>TimePeriod__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Year</fullName>
            </value>
            <value>
                <fullName>Quarter</fullName>
            </value>
            <value>
                <fullName>Month</fullName>
            </value>
            <value>
                <fullName>Week</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&apos;Quote&apos;</defaultValue>
    <description>Indicates the type of quote.</description>
    <inlineHelpText>Indicates the type of quote.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Collaboration</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Scenario</fullName>
            </value>
            <value>
                <fullName>Template</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteItem__c/QuoteItem__c.object-meta.xml
<CustomObject>
    <label>Quote Item</label>
    <nameField>
        <displayFormat>QI-{0000000}</displayFormat>
        <label>Quote Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteItem__c/fields/CurrencyConversionRatio__c.field-meta.xml
<CustomField>
    <fullName>CurrencyConversionRatio__c</fullName>
    <formula>QuoteId__r.CurrencyConversionRatio__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Currency Conversion Ratio</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RateCardItem__c/RateCardItem__c.object-meta.xml
<CustomObject>
    <label>Rate Card Item</label>
    <nameField>
        <displayFormat>RCI-{0000000}</displayFormat>
        <label>Rate Card Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Card Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RateCardItem__c/fields/MarginPercent__c.field-meta.xml
<CustomField>
    <fullName>MarginPercent__c</fullName>
    <formula>(UnitPrice__c - UnitCost__c)/UnitPrice__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Margin Percent</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/globalValueSets/Groups.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Salesforce Implementation</fullName>
    </customValue>
    <customValue>
        <fullName>SAP Implementation</fullName>
    </customValue>
    <customValue>
        <fullName>Web &amp; Mobile Apps</fullName>
    </customValue>
    <customValue>
        <fullName>Java</fullName>
    </customValue>
    <customValue>
        <fullName>.Net</fullName>
    </customValue>
    <customValue>
        <fullName>Sales Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>Service Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>SFDC Integration</fullName>
    </customValue>
    <customValue>
        <fullName>SAP C/4 HANA CUSTOMER EXP</fullName>
    </customValue>
    <customValue>
        <fullName>SAP S/4 HANA CLOUD ERP</fullName>
    </customValue>
    <customValue>
        <fullName>SAP SUCCESS FACTORS</fullName>
    </customValue>
    <customValue>
        <fullName>SAP ARIBA</fullName>
    </customValue>
    <customValue>
        <fullName>SAP BUSINESS OBJECTS</fullName>
    </customValue>
    <customValue>
        <fullName>SAP ACTIVATE</fullName>
    </customValue>
    <customValue>
        <fullName>SAP CLOUD PLATFORM Integration</fullName>
    </customValue>
    <customValue>
        <fullName>Oracle Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>Oracle Infrastructure</fullName>
    </customValue>
    <customValue>
        <fullName>Oracle Live</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Web Services Basics</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Computer Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Network Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Storage Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Database Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Analytics Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Application Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Web Services Resources</fullName>
    </customValue>
    <customValue>
        <fullName>AI + Machine Learning</fullName>
    </customValue>
    <customValue>
        <fullName>Analytics</fullName>
    </customValue>
    <customValue>
        <fullName>Blockchain</fullName>
    </customValue>
    <masterLabel>Groups</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Practices.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Custom Development</fullName>
        <label>Web Development</label>
    </customValue>
    <customValue>
        <fullName>Cloud Consulting</fullName>
    </customValue>
    <customValue>
        <fullName>Outsourcing</fullName>
    </customValue>
    <customValue>
        <fullName>AWS</fullName>
    </customValue>
    <customValue>
        <fullName>GCP</fullName>
    </customValue>
    <customValue>
        <fullName>DevOps</fullName>
    </customValue>
    <customValue>
        <fullName>Java</fullName>
    </customValue>
    <customValue>
        <fullName>Python</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>SAP</fullName>
    </customValue>
    <customValue>
        <fullName>SFDC</fullName>
    </customValue>
    <customValue>
        <fullName>Oracle</fullName>
    </customValue>
    <customValue>
        <fullName>CI/CD</fullName>
    </customValue>
    <customValue>
        <fullName>ERP</fullName>
        <isActive>false</isActive>
        <label>ERP</label>
    </customValue>
    <customValue>
        <fullName>CRM</fullName>
        <isActive>false</isActive>
        <label>CRM</label>
    </customValue>
    <masterLabel>Practices</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/QuoteTemplateDO.cls
/**
 *  Provus Services Quoting
 *  @2021 Provus Inc. All rights reserved.
 *
 * Wrapper class which holds quote template which includes:
 * default fields metadata, quote time period and quote period list.
 */
public with sharing class QuoteTemplateDO {
	public Id rateCardId;
	public List<QuotePeriodService.QuotePeriod> quotePeriodList;
	public List<SObjectUtility.SObjectFieldInfo> fieldsList;
	public String groupName;
	public String practiceName;
	public String quoteTimePeriod;
	public String quoteTimePeriodsGroupMethod;
	public String recordType;
	public Boolean hasAddOns = false;
	public Boolean isScenarioPricePending = false;
	public Decimal marginPercent;
	public Decimal totalAmount;
	public ScheduleSettingDTO scheduleSettings;
	public String sectionHierarchy;
	public MultiCurrencyService.CurrencyFields currencyFields;

	public QuoteTemplateDO(Quote__c quoteSO, Id rateCardId) {
		this.fieldsList = getFieldMetadata(rateCardId);
		this.hasAddOns = hasAddOns;
		this.isScenarioPricePending = quoteSO.Type__c == QuoteService.RECORDTYPE_NAME_SCENARIO;
		this.marginPercent = quoteSO.MarginPercent__c;
		this.quotePeriodList = QuotePeriodService.getQuotePeriods(quoteSO.Id);
		this.quoteTimePeriod = quoteSO.TimePeriod__c;
		this.quoteTimePeriodsGroupMethod = quoteSO.TimePeriodsGroupMethod__c;
		this.totalAmount = quoteSO.TotalAmount__c;
		this.recordType = quoteSO.Type__c;
		this.scheduleSettings = SettingsService.getScheduleSettingsForQuote(quoteSO.Id);
		this.sectionHierarchy = quoteSO.SectionHierarchy__c;
		this.rateCardId = rateCardId;
		this.groupName = quoteSO.Group__c;
		this.practiceName = quoteSO.Practice__c;
		this.currencyFields = new MultiCurrencyService.CurrencyFields();
		if (MultiCurrencyService.isMultiCurrencyEnabled()) {
			this.currencyFields.currencyISOCode = (String) quoteSO.get(
				MultiCurrencyService.CURRENCY_ISO_CODE
			);
		} else {
			this.currencyFields.currencyISOCode = UserInfo.getDefaultCurrency();
		}
		this.currencyFields.currencyConversionRatio = quoteSO.CurrencyConversionRatio__c;
	}

	/**
	 * Gets the list of default fields with their types
	 * @return SObjectUtility.SObjectFieldInfo  wrapper for the fields used on the configurator
	 */
	private List<SObjectUtility.SObjectFieldInfo> getFieldMetadata(Id rateCardId) {
		Map<Schema.SObjectType, Set<String>> fieldsBySObject = new Map<Schema.SObjectType, Set<String>>();
		CustomMetadataService cmService = new CustomMetadataService();

		// add product default fields
		fieldsBySObject.put(Product2.SObjectType, cmService.getProductDefaultFields());

		// add rate card item default fields
		Set<String> rateCardItemsFieldSet = new Set<String>();
		RateCardService rtService = new RateCardService(rateCardId);
		rateCardItemsFieldSet.addAll(rtService.getAttributes());
		fieldsBySObject.put(RateCardItem__c.SObjectType, rateCardItemsFieldSet);

		// add quote item default fields
		fieldsBySObject.put(QuoteItem__c.SObjectType, cmService.getQuoteItemDefaultFields());

		List<SObjectUtility.SObjectFieldInfo> fieldStructList = SObjectUtility.getSObjectFields(
			fieldsBySObject
		);

		// add sequences
		Map<String, Decimal> sequenceByAttribute = rtService.getAttributesWithSequence();
		for (SObjectUtility.SObjectFieldInfo fldStruct : fieldStructList) {
			if (fldStruct.sourceObject == (Schema.RateCardItem__c.SObjectType + '')) {
				fldStruct.sequence = sequenceByAttribute.get(fldStruct.fieldName);
			}
		}

		return fieldStructList;
	}
}