force-app/main/default/objects/Product2/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Practice__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Practice__c.field-meta.xml
<CustomField>
    <fullName>Practice__c</fullName>
    <label>Practice</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Practices</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <label>Product</label>
</RecordType>

force-app/main/default/globalValueSets/Groups.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Salesforce Implementation</fullName>
    </customValue>
    <customValue>
        <fullName>SAP Implementation</fullName>
    </customValue>
    <customValue>
        <fullName>Web &amp; Mobile Apps</fullName>
    </customValue>
    <customValue>
        <fullName>Java</fullName>
    </customValue>
    <customValue>
        <fullName>.Net</fullName>
    </customValue>
    <customValue>
        <fullName>Sales Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>Service Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>SFDC Integration</fullName>
    </customValue>
    <customValue>
        <fullName>SAP C/4 HANA CUSTOMER EXP</fullName>
    </customValue>
    <customValue>
        <fullName>SAP S/4 HANA CLOUD ERP</fullName>
    </customValue>
    <customValue>
        <fullName>SAP SUCCESS FACTORS</fullName>
    </customValue>
    <customValue>
        <fullName>SAP ARIBA</fullName>
    </customValue>
    <customValue>
        <fullName>SAP BUSINESS OBJECTS</fullName>
    </customValue>
    <customValue>
        <fullName>SAP ACTIVATE</fullName>
    </customValue>
    <customValue>
        <fullName>SAP CLOUD PLATFORM Integration</fullName>
    </customValue>
    <customValue>
        <fullName>Oracle Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>Oracle Infrastructure</fullName>
    </customValue>
    <customValue>
        <fullName>Oracle Live</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Web Services Basics</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Computer Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Network Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Storage Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Database Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Analytics Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Application Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Web Services Resources</fullName>
    </customValue>
    <customValue>
        <fullName>AI + Machine Learning</fullName>
    </customValue>
    <customValue>
        <fullName>Analytics</fullName>
    </customValue>
    <customValue>
        <fullName>Blockchain</fullName>
    </customValue>
    <masterLabel>Groups</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Practices.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Custom Development</fullName>
        <label>Web Development</label>
    </customValue>
    <customValue>
        <fullName>Cloud Consulting</fullName>
    </customValue>
    <customValue>
        <fullName>Outsourcing</fullName>
    </customValue>
    <customValue>
        <fullName>AWS</fullName>
    </customValue>
    <customValue>
        <fullName>GCP</fullName>
    </customValue>
    <customValue>
        <fullName>DevOps</fullName>
    </customValue>
    <customValue>
        <fullName>Java</fullName>
    </customValue>
    <customValue>
        <fullName>Python</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>SAP</fullName>
    </customValue>
    <customValue>
        <fullName>SFDC</fullName>
    </customValue>
    <customValue>
        <fullName>Oracle</fullName>
    </customValue>
    <customValue>
        <fullName>CI/CD</fullName>
    </customValue>
    <customValue>
        <fullName>ERP</fullName>
        <isActive>false</isActive>
        <label>ERP</label>
    </customValue>
    <customValue>
        <fullName>CRM</fullName>
        <isActive>false</isActive>
        <label>CRM</label>
    </customValue>
    <masterLabel>Practices</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SOQLUtilityTest.cls
/**
 *  Provus Services Quoting
 *  SOQLUtilityTest
 *  @2021 Provus Inc. All rights reserved.
 */
@IsTest
public with sharing class SOQLUtilityTest extends TestBase {
	private static Set<String> requestedFields = new Set<String>{
		SObjectUtility.FIELD_ID,
		SObjectUtility.FIELD_NAME,
		Schema.Product2.Practice__c + '',
		Schema.Product2.Group__c + ''
	};

	@TestSetup
	static void setup() {
		Id productTypeId = SObjectUtility.getRecordTypeIdbyName('Product2', 'Product');
		List<Product2> products = new List<Product2>{
			newProduct('Product #1', productTypeId),
			newProduct('Product #2', productTypeId),
			newProduct('Product #3', productTypeId),
			newProduct('Product #4', productTypeId),
			newProduct('Product #5', productTypeId)
		};
		CRUDUtility.insertRecords(products);
		// price book
		Pricebook2 pricebook = newPriceBook();
		Id standardPricebookId = Test.getStandardPricebookId();
		List<PricebookEntry> pricebookEntries = new List<PricebookEntry>();
		for (Product2 productSO : products) {
			pricebookEntries.add(newPricebookEntry(standardPricebookId, productSO.Id));
			pricebookEntries.add(newPricebookEntry(pricebook.Id, productSO.Id));
		}
		CRUDUtility.insertRecords(pricebookEntries);
	}

	@IsTest
	static void itShouldRetrieveList() {
		Test.startTest();
		QueryRequest queryRequest = new QueryRequest(Schema.SObjectType.Product2.getName());
		queryRequest.requestedFields = requestedFields;
		List<Product2> resultSet = SOQLUtility.querySObject(queryRequest);
		System.assertEquals(5, resultSet.size(), 'We should have 5 products');
		Test.stopTest();
	}

	@IsTest
	static void itShouldRetrieveListWithInnerQuery() {
		Test.startTest();
		QueryRequest queryRequest = new QueryRequest(Schema.SObjectType.Product2.getName());
		queryRequest.requestedFields = requestedFields;
		List<QueryRequest> innerQueries = new List<QueryRequest>();
		// PricebookEntries is the child relationship name
		QueryRequest innerQueryRequest = new QueryRequest('PricebookEntries');
		innerQueryRequest.requestedFields = new Set<String>{ Schema.PricebookEntry.UnitPrice + '' };
		innerQueries.add(innerQueryRequest);
		queryRequest.innerQueries = innerQueries;
		List<Product2> resultSet = SOQLUtility.querySObject(queryRequest);
		System.assertEquals(5, resultSet.size(), 'We should have 5 products');
		Test.stopTest();
	}

	@IsTest
	static void itShouldRetrieveListWithLimit() {
		Test.startTest();
		QueryRequest queryRequest = new QueryRequest(Schema.SObjectType.Product2.getName());
		queryRequest.requestedFields = requestedFields;
		queryRequest.querySize = 2;
		List<Product2> resultSet = SOQLUtility.querySObject(queryRequest);
		System.assertEquals(2, resultSet.size(), 'We should have 2 products');
		Test.stopTest();
	}

	@IsTest
	static void itShouldRetrieveListWithNullOrderByValue() {
		Test.startTest();
		QueryRequest queryRequest = new QueryRequest(Schema.SObjectType.Product2.getName());
		queryRequest.requestedFields = requestedFields;
		queryRequest.fieldBySortOrder = new Map<String, String>{ SObjectUtility.FIELD_NAME => null };
		List<Product2> resultSet = SOQLUtility.querySObject(queryRequest);
		System.assertEquals('Product #1', resultSet[0].Name, 'Product 1 should be the first product');
		Test.stopTest();
	}

	@IsTest
	static void itShouldRetrieveListWithOrderByAsc() {
		Test.startTest();
		QueryRequest queryRequest = new QueryRequest(Schema.SObjectType.Product2.getName());
		queryRequest.requestedFields = requestedFields;
		queryRequest.fieldBySortOrder = new Map<String, String>{
			SObjectUtility.FIELD_NAME => SOQLConstants.SORT_ASC
		};
		List<Product2> resultSet = SOQLUtility.querySObject(queryRequest);
		System.assertEquals('Product #1', resultSet[0].Name, 'Product 1 should be the first product');
		Test.stopTest();
	}

	@IsTest
	static void itShouldRetrieveListWithOrderByDesc() {
		Test.startTest();
		QueryRequest queryRequest = new QueryRequest(Schema.SObjectType.Product2.getName());
		queryRequest.requestedFields = requestedFields;
		queryRequest.fieldBySortOrder = new Map<String, String>{
			SObjectUtility.FIELD_NAME => SOQLConstants.SORT_DESC
		};
		List<Product2> resultSet = SOQLUtility.querySObject(queryRequest);
		System.assertEquals('Product #5', resultSet[0].Name, 'Product 5 should be the first product');
		Test.stopTest();
	}

	@IsTest
	static void itShouldRetrieveListWithSingleFilter() {
		Test.startTest();
		QueryRequest queryRequest = new QueryRequest(Schema.SObjectType.Product2.getName());
		queryRequest.requestedFields = requestedFields;
		queryRequest.setFilterBy(new Map<String, String>{ SObjectUtility.FIELD_NAME => 'Product #3' });
		List<Product2> resultSet = SOQLUtility.querySObject(queryRequest);
		System.assertEquals('Product #3', resultSet[0].Name, 'Name should be Product #3');
		Test.stopTest();
	}

	@IsTest
	static void itShouldRetrieveListWithSingleFilterNullCheck() {
		Test.startTest();
		QueryRequest queryRequest = new QueryRequest(Schema.SObjectType.Product2.getName());
		queryRequest.requestedFields = requestedFields;
		queryRequest.setFilterBy(new Map<String, String>{ Schema.Product2.ProductCode + '' => null });
		List<Product2> resultSet = SOQLUtility.querySObject(queryRequest);
		System.assertEquals(5, resultSet.size(), 'We should have 5 products');
		Test.stopTest();
	}

	@IsTest
	static void itShouldRetrieveListWithSetFilter() {
		Test.startTest();
		Map<Id, Product2> productsByIds = new Map<Id, Product2>(
			[SELECT Id, Name FROM Product2 WHERE Name = 'Product #1' OR Name = 'Product #2']
		);
		QueryRequest queryRequest = new QueryRequest(Schema.SObjectType.Product2.getName());
		queryRequest.requestedFields = requestedFields;
		queryRequest.setFilterBy(
			new Map<String, Set<Id>>{ SObjectUtility.FIELD_ID => productsByIds.keySet() }
		);
		List<Product2> resultSet = SOQLUtility.querySObject(queryRequest);
		System.assertEquals(2, resultSet.size(), 'We should have 2 products');
		System.assertEquals('Product #1', resultSet[0].Name, 'Name should be Product #1');
		System.assertEquals('Product #2', resultSet[1].Name, 'Name should be Product #2');
		Test.stopTest();
	}
}