force-app/main/default/objects/Product2/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Practice__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Practice__c.field-meta.xml
<CustomField>
    <fullName>Practice__c</fullName>
    <label>Practice</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Practices</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <label>Product</label>
</RecordType>

force-app/main/default/objects/RateCardItem__c/RateCardItem__c.object-meta.xml
<CustomObject>
    <label>Rate Card Item</label>
    <nameField>
        <displayFormat>RCI-{0000000}</displayFormat>
        <label>Rate Card Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Card Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RateCardItem__c/fields/LocationCountry__c.field-meta.xml
<CustomField>
    <fullName>LocationCountry__c</fullName>
    <label>Location Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RateCardItem__c/fields/PriceUOM__c.field-meta.xml
<CustomField>
    <fullName>PriceUOM__c</fullName>
    <label>Price UOM</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PriceUOMs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RateCardItem__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Rate Card Items</relationshipLabel>
    <relationshipName>RateCardItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RateCardItem__c/fields/RateCardId__c.field-meta.xml
<CustomField>
    <fullName>RateCardId__c</fullName>
    <label>Rate Card</label>
    <referenceTo>RateCard__c</referenceTo>
    <relationshipLabel>Rate Card Items</relationshipLabel>
    <relationshipName>RateCardItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RateCardItem__c/fields/SkillLevel__c.field-meta.xml
<CustomField>
    <fullName>SkillLevel__c</fullName>
    <label>Skill Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SkillLevels</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>United States</fullName>
    </customValue>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <masterLabel>Countries</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Groups.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Salesforce Implementation</fullName>
    </customValue>
    <customValue>
        <fullName>SAP Implementation</fullName>
    </customValue>
    <customValue>
        <fullName>Web &amp; Mobile Apps</fullName>
    </customValue>
    <customValue>
        <fullName>Java</fullName>
    </customValue>
    <customValue>
        <fullName>.Net</fullName>
    </customValue>
    <customValue>
        <fullName>Sales Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>Service Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>SFDC Integration</fullName>
    </customValue>
    <customValue>
        <fullName>SAP C/4 HANA CUSTOMER EXP</fullName>
    </customValue>
    <customValue>
        <fullName>SAP S/4 HANA CLOUD ERP</fullName>
    </customValue>
    <customValue>
        <fullName>SAP SUCCESS FACTORS</fullName>
    </customValue>
    <customValue>
        <fullName>SAP ARIBA</fullName>
    </customValue>
    <customValue>
        <fullName>SAP BUSINESS OBJECTS</fullName>
    </customValue>
    <customValue>
        <fullName>SAP ACTIVATE</fullName>
    </customValue>
    <customValue>
        <fullName>SAP CLOUD PLATFORM Integration</fullName>
    </customValue>
    <customValue>
        <fullName>Oracle Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>Oracle Infrastructure</fullName>
    </customValue>
    <customValue>
        <fullName>Oracle Live</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Web Services Basics</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Computer Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Network Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Storage Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Database Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Analytics Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Application Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Web Services Resources</fullName>
    </customValue>
    <customValue>
        <fullName>AI + Machine Learning</fullName>
    </customValue>
    <customValue>
        <fullName>Analytics</fullName>
    </customValue>
    <customValue>
        <fullName>Blockchain</fullName>
    </customValue>
    <masterLabel>Groups</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Practices.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Custom Development</fullName>
        <label>Web Development</label>
    </customValue>
    <customValue>
        <fullName>Cloud Consulting</fullName>
    </customValue>
    <customValue>
        <fullName>Outsourcing</fullName>
    </customValue>
    <customValue>
        <fullName>AWS</fullName>
    </customValue>
    <customValue>
        <fullName>GCP</fullName>
    </customValue>
    <customValue>
        <fullName>DevOps</fullName>
    </customValue>
    <customValue>
        <fullName>Java</fullName>
    </customValue>
    <customValue>
        <fullName>Python</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>SAP</fullName>
    </customValue>
    <customValue>
        <fullName>SFDC</fullName>
    </customValue>
    <customValue>
        <fullName>Oracle</fullName>
    </customValue>
    <customValue>
        <fullName>CI/CD</fullName>
    </customValue>
    <customValue>
        <fullName>ERP</fullName>
        <isActive>false</isActive>
        <label>ERP</label>
    </customValue>
    <customValue>
        <fullName>CRM</fullName>
        <isActive>false</isActive>
        <label>CRM</label>
    </customValue>
    <masterLabel>Practices</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/PriceUOMs.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Hourly</fullName>
    </customValue>
    <customValue>
        <fullName>Daily</fullName>
    </customValue>
    <customValue>
        <fullName>Weekly</fullName>
    </customValue>
    <customValue>
        <fullName>Monthly</fullName>
    </customValue>
    <customValue>
        <fullName>Yearly</fullName>
    </customValue>
    <masterLabel>Price UOMs</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/SkillLevels.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>L1</fullName>
    </customValue>
    <customValue>
        <fullName>L2</fullName>
    </customValue>
    <customValue>
        <fullName>L3</fullName>
    </customValue>
    <masterLabel>Skill Levels</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RateCardItemService.cls
/**
 *  Provus Services Quoting
 *  @2021 Provus Inc. All rights reserved.
 */
public with sharing class RateCardItemService {
	// constants
	public static final String SOBJECT_NAME = 'RateCardItem__c';
	public static final String FIELD_NAME_PRODUCT_ID = 'ProductId__c';
	public static final String FIELD_NAME_RATECARD_ID = 'RateCardId__c';
	public static final String FIELD_NAME_LOCATION_DISPLAY_NAME = 'LocationDisplayName__c';
	public static final String FIELD_NAME_LOCATION_COUNTRY = 'LocationCountry__c';
	public static final String FIELD_NAME_UNIT_PRICE = 'UnitPrice__c';
	public static final String FIELD_NAME_UNIT_COST = 'UnitCost__c';
	public static final String FIELD_NAME_PRICE_UOM = 'PriceUOM__c';

	// wrapper for rate card item
	public class RateCardItemStruct {
		public Map<String, String> fieldValueMap;
		public RateCardItemStruct() {
		}
	}

	/**
	 * Gets products from rate card items
	 * @param   quoteId id of quote record
	 * @return  List<RateCardItem__c>
	 */
	public static List<RateCardItem__c> getRateCardItemsProducts(Id quoteId) {
		QuoteService qService = new QuoteService(quoteId);

		return [
			SELECT
				Id,
				ProductId__c,
				ProductId__r.Name,
				ProductId__r.IsActive,
				ProductId__r.Practice__c,
				ProductId__r.Group__c,
				ProductId__r.RecordTypeId
			FROM RateCardItem__c
			WHERE
				RateCardId__c = :qService.rateCardId
				AND ProductId__r.Practice__c = :qService.quotePractice
				AND ProductId__r.Group__c = :qService.quoteGroup
				AND ProductId__r.IsActive = TRUE
			WITH SECURITY_ENFORCED
		];
	}

	/**
	 * Gets all rate card items for a product
	 * @param   quoteId Id of the quote
	 * @param   productId Id of the product
	 * @return  List<RateCardItemStruct>
	 */
	public static List<RateCardItemStruct> getAllRateCardItemsForProduct(Id quoteId, Id productId) {
		List<RateCardItemStruct> rateCardItemList = new List<RateCardItemStruct>();

		// requested fields
		Set<String> rateCardItemsFieldSet = new Set<String>{
			'Id',
			SystemUtility.getNamespacePrefix() + FIELD_NAME_LOCATION_DISPLAY_NAME,
			SystemUtility.getNamespacePrefix() + FIELD_NAME_LOCATION_COUNTRY,
			SystemUtility.getNamespacePrefix() + FIELD_NAME_UNIT_PRICE,
			SystemUtility.getNamespacePrefix() + FIELD_NAME_UNIT_COST,
			SystemUtility.getNamespacePrefix() + FIELD_NAME_PRICE_UOM
		};

		// get attribute fields
		QuoteService qService = new QuoteService(quoteId);
		RateCardService rtService = new RateCardService(qService.rateCardId);
		rateCardItemsFieldSet.addAll(rtService.getAttributes());

		// where clause
		Map<String, String> conditionFieldsMap = new Map<String, String>();
		conditionFieldsMap.put(SystemUtility.getNamespacePrefix() + FIELD_NAME_PRODUCT_ID, productId);
		conditionFieldsMap.put(
			SystemUtility.getNamespacePrefix() + FIELD_NAME_RATECARD_ID,
			qService.rateCardId
		);

		// perform query and put in the result
		QueryRequest queryRequest = new QueryRequest(SystemUtility.getNamespacePrefix() + SOBJECT_NAME);
		queryRequest.requestedFields = rateCardItemsFieldSet;
		queryRequest.setFilterBy(conditionFieldsMap);
		for (RateCardItem__c rci : (List<RateCardItem__c>) SOQLUtility.querySObject(queryRequest)) {
			RateCardItemStruct thisRateCardItem = new RateCardItemStruct();
			Map<String, String> fieldValues = new Map<String, String>();
			for (String fld : rateCardItemsFieldSet) {
				fieldValues.put(fld, String.valueOf(rci.get(fld)));
			}
			thisRateCardItem.fieldValueMap = fieldValues;
			rateCardItemList.add(thisRateCardItem);
		}

		return rateCardItemList;
	}

	public static List<RateCardItem__c> getRateCardItems(Id rateCardId, Set<Id> resourceRoleIds) {
		String relatedProductName = SystemUtility.getChildRName(
			Schema.RateCardItem__c.ProductId__c,
			Schema.RateCardItem__c.ProductId__r.Name
		);
		Set<String> rateCardItemFields = new Set<String>();
		rateCardItemFields.add(Schema.RateCardItem__c.SkillLevel__c + '');
		rateCardItemFields.add(Schema.RateCardItem__c.LocationDisplayName__c + '');
		rateCardItemFields.add(Schema.RateCardItem__c.ProductId__c + '');
		rateCardItemFields.add(relatedProductName);

		Map<String, Set<Id>> rateCardItemConditions = new Map<String, Set<Id>>();
		rateCardItemConditions.put(Schema.RateCardItem__c.ProductId__c + '', resourceRoleIds);
		rateCardItemConditions.put(
			Schema.RateCardItem__c.RateCardId__c + '',
			new Set<Id>{ rateCardId }
		);

		QueryRequest queryRequest = new QueryRequest(Schema.RateCardItem__c.SObjectType);
		queryRequest.requestedFields = rateCardItemFields;
		queryRequest.setFilterBy(rateCardItemConditions);
		queryRequest.fieldBySortOrder = new Map<String, String>{
			relatedProductName => SOQLConstants.SORT_ASC
		};
		return (List<RateCardItem__c>) SOQLUtility.querySObject(queryRequest);
	}
}