force-app/main/default/objects/CollaborationRequest__c/CollaborationRequest__c.object-meta.xml
<CustomObject>
    <label>Collaboration Request</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Collaboration Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collaboration Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CollaborationRequest__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Collaboration Requests</relationshipLabel>
    <relationshipName>CollaborationRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollaborationRequest__c/fields/SectionId__c.field-meta.xml
<CustomField>
    <fullName>SectionId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Section</label>
    <referenceTo>QuoteSection__c</referenceTo>
    <relationshipLabel>Collaboration Requests</relationshipLabel>
    <relationshipName>CollaborationRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollaborationRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Ready to Merge</fullName>
            </value>
            <value>
                <fullName>Merged</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteSection__c/QuoteSection__c.object-meta.xml
<CustomObject>
    <label>Quote Section</label>
    <nameField>
        <label>Quote Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteSection__c/fields/DerivedFromId__c.field-meta.xml
<CustomField>
    <fullName>DerivedFromId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Derived From</label>
    <referenceTo>QuoteSection__c</referenceTo>
    <relationshipLabel>Quote Section Versions</relationshipLabel>
    <relationshipName>QuoteSectionVersions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteSection__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Sections</relationshipLabel>
    <relationshipName>QuoteSections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CollaborationSectionService.cls
/*
 * Provus Services Quoting
 * Copyright (c) 2021 Provus Inc. All rights reserved.
 */
public with sharing class CollaborationSectionService {
	/**
	 * Gets the merge ready section lineage of the given target section IDs.
	 * @param targetSectionIds A list of target section IDs
	 *
	 * @return The lineage sections of the target section IDs
	 */
	public static List<QuoteSection__c> getMergeReadyLineage(List<Id> targetSectionIds) {
		Map<Id, QuoteSection__c> lineageSections = new Map<Id, QuoteSection__c>(
			QuoteSectionService.getSectionLineageFor(targetSectionIds)
		);

		List<CollaborationRequest__c> requests = [
			SELECT SectionId__c
			FROM CollaborationRequest__c
			WHERE
				SectionId__c IN :lineageSections.keySet()
				AND Status__c = :CollaborationRequest.STATUS_READY_TO_MERGE
			WITH SECURITY_ENFORCED
			LIMIT :SOQLConstants.SOQL_QUERY_LIMIT
		];

		List<Id> mergeReadySections = new List<Id>();
		for (CollaborationRequest__c request : requests) {
			mergeReadySections.add(request.SectionId__c);
		}

		return [
			SELECT Id, QuoteId__c, DerivedFromId__c
			FROM QuoteSection__c
			WHERE Id IN :mergeReadySections
			WITH SECURITY_ENFORCED
			LIMIT :SOQLConstants.SOQL_QUERY_LIMIT
		];
	}
}