force-app/main/default/objects/CollaborationRequest__c/CollaborationRequest__c.object-meta.xml
<CustomObject>
    <label>Collaboration Request</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Collaboration Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collaboration Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CollaborationRequest__c/fields/CollaboratorUserId__c.field-meta.xml
<CustomField>
    <fullName>CollaboratorUserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collaborator</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CollaborationRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollaborationRequest__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Collaboration Requests</relationshipLabel>
    <relationshipName>CollaborationRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollaborationRequest__c/fields/SectionId__c.field-meta.xml
<CustomField>
    <fullName>SectionId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Section</label>
    <referenceTo>QuoteSection__c</referenceTo>
    <relationshipLabel>Collaboration Requests</relationshipLabel>
    <relationshipName>CollaborationRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollaborationRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Ready to Merge</fullName>
            </value>
            <value>
                <fullName>Merged</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/DerivedFromId__c.field-meta.xml
<CustomField>
    <fullName>DerivedFromId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Derived From</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Versions</relationshipLabel>
    <relationshipName>QuoteVersions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
                <isActive>false</isActive>
                <label>Archived</label>
            </value>
            <value>
                <fullName>Contract Negotiation</fullName>
                <isActive>false</isActive>
                <label>Contract Negotiation</label>
            </value>
            <value>
                <fullName>Contracted</fullName>
                <isActive>false</isActive>
                <label>Contracted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&apos;Quote&apos;</defaultValue>
    <description>Indicates the type of quote.</description>
    <inlineHelpText>Indicates the type of quote.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Collaboration</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Scenario</fullName>
            </value>
            <value>
                <fullName>Template</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteSection__c/QuoteSection__c.object-meta.xml
<CustomObject>
    <label>Quote Section</label>
    <nameField>
        <label>Quote Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteSection__c/fields/DerivedFromId__c.field-meta.xml
<CustomField>
    <fullName>DerivedFromId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Derived From</label>
    <referenceTo>QuoteSection__c</referenceTo>
    <relationshipLabel>Quote Section Versions</relationshipLabel>
    <relationshipName>QuoteSectionVersions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteSection__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Sections</relationshipLabel>
    <relationshipName>QuoteSections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CollaborationRequestService.cls
/*
 *  Provus Services Quoting
 *  @2021 Provus Inc. All rights reserved.
 */
public with sharing class CollaborationRequestService {
	/**
	 * Returns the outstanding collaboration requests for the given quote ID. An outstanding
	 * request is neither Merged nor Revoked.
	 * @param quoteId A quote ID
	 *
	 * @return A list of outstanding requests
	 */
	public static List<CollaborationRequest__c> getOutstandingRequestsFor(Id quoteId) {
		return [
			SELECT
				Id,
				Name,
				SectionId__c,
				SectionId__r.DerivedFromId__c,
				SectionId__r.QuoteId__c,
				SectionId__r.QuoteId__r.Type__c,
				SectionId__r.Name,
				Status__c,
				CollaboratorUserId__r.Name
			FROM CollaborationRequest__c
			WHERE QuoteId__c = :quoteId AND Status__c != :CollaborationRequest.STATUS_MERGED
			WITH SECURITY_ENFORCED
			LIMIT :SOQLConstants.SOQL_QUERY_LIMIT
		];
	}

	public static List<CollaborationRequest__c> getAssignedRequestsFor(Id quoteId) {
		return [
			SELECT
				Id,
				Name,
				SectionId__c,
				SectionId__r.DerivedFromId__c,
				SectionId__r.QuoteId__c,
				SectionId__r.QuoteId__r.Type__c,
				SectionId__r.Name,
				Status__c,
				CollaboratorUserId__r.Name
			FROM CollaborationRequest__c
			WHERE QuoteId__c = :quoteId AND Status__c = :CollaborationRequest.STATUS_ASSIGNED
			WITH SECURITY_ENFORCED
			LIMIT :SOQLConstants.SOQL_QUERY_LIMIT
		];
	}

	public static List<CollaborationRequest__c> getRevocableRequestsFor(
		Id quoteId,
		List<Id> sectionIds
	) {
		return [
			SELECT
				Id,
				Name,
				SectionId__c,
				SectionId__r.DerivedFromId__c,
				SectionId__r.QuoteId__c,
				SectionId__r.QuoteId__r.Type__c,
				SectionId__r.Name,
				Status__c,
				CollaboratorUserId__r.Name
			FROM CollaborationRequest__c
			WHERE
				QuoteId__c = :quoteId
				AND SectionId__c IN :sectionIds
				AND Status__c IN :CollaborationRequest.REVOCABLE_STATUSES
			WITH SECURITY_ENFORCED
			LIMIT :SOQLConstants.SOQL_QUERY_LIMIT
		];
	}

	/**
	 * Marks the collaboration requests for the given quote ID
	 * as Ready to Merge.
	 * @param sectionIds A list of section IDs
	 */
	public static void markForMerge(List<Id> sectionIds) {
		List<CollaborationRequest__c> updatedRequests = new List<CollaborationRequest__c>();
		for (CollaborationRequest__c collabSO : [
			SELECT Id
			FROM CollaborationRequest__c
			WHERE SectionId__c IN :sectionIds
			WITH SECURITY_ENFORCED
			LIMIT :SOQLConstants.SOQL_QUERY_LIMIT
		]) {
			collabSO.Status__c = CollaborationRequest.STATUS_READY_TO_MERGE;
			updatedRequests.add(collabSO);
		}

		CRUDUtility.updateRecords(updatedRequests);
	}

	/**
	 * Marks the collaboration requests for the given quote ID
	 * as Merged.
	 * @param sectionIds A list of section IDs
	 */
	public static void markAsMerged(List<Id> sectionIds) {
		List<CollaborationRequest__c> updatedRequests = new List<CollaborationRequest__c>();
		for (CollaborationRequest__c collabSO : [
			SELECT Id
			FROM CollaborationRequest__c
			WHERE SectionId__c IN :sectionIds
			WITH SECURITY_ENFORCED
			LIMIT :SOQLConstants.SOQL_QUERY_LIMIT
		]) {
			collabSO.Status__c = CollaborationRequest.STATUS_MERGED;
			updatedRequests.add(collabSO);
		}

		CRUDUtility.updateRecords(updatedRequests);
	}
}