force-app/main/default/objects/CollaborationRequest__c/CollaborationRequest__c.object-meta.xml
<CustomObject>
    <label>Collaboration Request</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Collaboration Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collaboration Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CollaborationRequest__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Collaboration Requests</relationshipLabel>
    <relationshipName>CollaborationRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollaborationRequest__c/fields/SectionId__c.field-meta.xml
<CustomField>
    <fullName>SectionId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Section</label>
    <referenceTo>QuoteSection__c</referenceTo>
    <relationshipLabel>Collaboration Requests</relationshipLabel>
    <relationshipName>CollaborationRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollaborationRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Ready to Merge</fullName>
            </value>
            <value>
                <fullName>Merged</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Estimate__c/Estimate__c.object-meta.xml
<CustomObject>
    <label>Estimate</label>
    <nameField>
        <label>Estimate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estimates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Estimate__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Estimate__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ProductId</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordTypeId</field>
            <operation>equals</operation>
            <value>Product</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Estimates</relationshipLabel>
    <relationshipName>ProductEstimates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Estimate__c/fields/RateCardId__c.field-meta.xml
<CustomField>
    <fullName>RateCardId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate Card</label>
    <referenceTo>RateCard__c</referenceTo>
    <relationshipLabel>Estimates</relationshipLabel>
    <relationshipName>Estimates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <label>Product</label>
</RecordType>

force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <label>Proposal</label>
    <nameField>
        <label>Proposal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/RateCardId__c.field-meta.xml
<CustomField>
    <fullName>RateCardId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate Card</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(3 OR 1) AND (4 OR 2) AND 5</booleanFilter>
        <errorMessage
		>The Rate Card is expired/inactive during the selected service start date</errorMessage>
        <filterItems>
            <field>$Source.ServiceStartDate__c</field>
            <operation>greaterOrEqual</operation>
            <valueField>RateCard__c.EffectiveDate__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.ServiceStartDate__c</field>
            <operation>lessOrEqual</operation>
            <valueField>RateCard__c.ExpirationDate__c</valueField>
        </filterItems>
        <filterItems>
            <field>RateCard__c.EffectiveDate__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <filterItems>
            <field>RateCard__c.ExpirationDate__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <filterItems>
            <field>RateCard__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>RateCard__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/ServiceStartDate__c.field-meta.xml
<CustomField>
    <fullName>ServiceStartDate__c</fullName>
    <label>Service Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
                <isActive>false</isActive>
                <label>Archived</label>
            </value>
            <value>
                <fullName>Contract Negotiation</fullName>
                <isActive>false</isActive>
                <label>Contract Negotiation</label>
            </value>
            <value>
                <fullName>Contracted</fullName>
                <isActive>false</isActive>
                <label>Contracted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuotePeriod__c/QuotePeriod__c.object-meta.xml
<CustomObject>
    <label>Quote Period</label>
    <nameField>
        <label>Quote Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuotePeriod__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Periods</relationshipLabel>
    <relationshipName>QuotePeriods</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QuoteSection__c/QuoteSection__c.object-meta.xml
<CustomObject>
    <label>Quote Section</label>
    <nameField>
        <label>Quote Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteSection__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Sections</relationshipLabel>
    <relationshipName>QuoteSections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RateCard__c/RateCard__c.object-meta.xml
<CustomObject>
    <label>Rate Card</label>
    <nameField>
        <label>Rate Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RateCard__c/fields/AttributeGroupId__c.field-meta.xml
<CustomField>
    <fullName>AttributeGroupId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Attribute Group</label>
    <referenceTo>RateCardAttributeGroup__c</referenceTo>
    <relationshipLabel>Rate Cards</relationshipLabel>
    <relationshipName>RateCards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RateCard__c/fields/EffectiveDate__c.field-meta.xml
<CustomField>
    <fullName>EffectiveDate__c</fullName>
    <label>Effective Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RateCard__c/fields/ExpirationDate__c.field-meta.xml
<CustomField>
    <fullName>ExpirationDate__c</fullName>
    <label>Expiration Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RateCardAttribute__c/RateCardAttribute__c.object-meta.xml
<CustomObject>
    <label>Rate Card Attribute</label>
    <nameField>
        <label>Rate Card Attribute</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Card Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RateCardAttribute__c/fields/AttributeGroupId__c.field-meta.xml
<CustomField>
    <fullName>AttributeGroupId__c</fullName>
    <label>Attribute Group</label>
    <referenceTo>RateCardAttributeGroup__c</referenceTo>
    <relationshipLabel>Attributes</relationshipLabel>
    <relationshipName>RateCardAttributes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RateCardAttribute__c/fields/FieldAPIName__c.field-meta.xml
<CustomField>
    <fullName>FieldAPIName__c</fullName>
    <label>Field API Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RateCardAttribute__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <label>Sequence</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/RateCardAttributeGroup__c/RateCardAttributeGroup__c.object-meta.xml
<CustomObject>
    <label>Rate Card Attribute Group</label>
    <nameField>
        <label>Rate Card Attribute Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Card Attribute Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RateCardItem__c/RateCardItem__c.object-meta.xml
<CustomObject>
    <label>Rate Card Item</label>
    <nameField>
        <displayFormat>RCI-{0000000}</displayFormat>
        <label>Rate Card Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Card Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RateCardItem__c/fields/EffectiveDate__c.field-meta.xml
<CustomField>
    <fullName>EffectiveDate__c</fullName>
    <label>Effective Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RateCardItem__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Rate Card Items</relationshipLabel>
    <relationshipName>RateCardItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RateCardItem__c/fields/RateCardId__c.field-meta.xml
<CustomField>
    <fullName>RateCardId__c</fullName>
    <label>Rate Card</label>
    <referenceTo>RateCard__c</referenceTo>
    <relationshipLabel>Rate Card Items</relationshipLabel>
    <relationshipName>RateCardItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RateCardItem__c/fields/SkillLevel__c.field-meta.xml
<CustomField>
    <fullName>SkillLevel__c</fullName>
    <label>Skill Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SkillLevels</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/SkillLevels.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>L1</fullName>
    </customValue>
    <customValue>
        <fullName>L2</fullName>
    </customValue>
    <customValue>
        <fullName>L3</fullName>
    </customValue>
    <masterLabel>Skill Levels</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestBase.cls
/**
 *  Provus Services Quoting
 *  TestBase
 *  @2021 Provus Inc. All rights reserved.
 */
public with sharing abstract class TestBase {
	static final String NS_PREFIX = SystemUtility.getNamespacePrefix();

	public static String nsPrefix() {
		return NS_PREFIX;
	}

	public static User newUser() {
		Profile profileSO = [SELECT Id FROM Profile WITH SECURITY_ENFORCED LIMIT 1];

		User newUser = new User(
			Username = 'testbase@provus.com',
			LastName = 'TestBase',
			Email = 'testbase@provus.com',
			Alias = 'testbase',
			TimeZoneSidKey = 'America/Los_Angeles',
			LocaleSidKey = 'en_US',
			EmailEncodingKey = 'UTF-8',
			ProfileId = profileSO.Id,
			LanguageLocaleKey = 'en_US'
		);

		CRUDUtility.insertRecords(newUser);
		return newUser;
	}

	public static Quote__c newQuote() {
		return newQuote(null);
	}

	public static Quote__c newQuote(String quoteName) {
		Quote__c newQuote = new Quote__c(Name = quoteName, ServiceStartDate__c = Date.today());
		CRUDUtility.insertRecords(newQuote);
		return newQuote;
	}

	public static QuotePeriod__c newQuotePeriod(Id quoteId) {
		QuotePeriod__c newQuotePeriod = new QuotePeriod__c();
		newQuotePeriod.QuoteId__c = quoteId;
		CRUDUtility.insertRecords(newQuotePeriod);
		return newQuotePeriod;
	}

	public static Proposal__c newProposal() {
		Proposal__c proposalSO = new Proposal__c(Name = 'Test Proposal');
		CRUDUtility.insertRecords(proposalSO);
		return proposalSO;
	}

	public static Opportunity newOpportunity() {
		Opportunity opp = new Opportunity(
			Name = 'Test',
			StageName = 'Test',
			CloseDate = Date.valueOf('2021-12-31')
		);
		CRUDUtility.insertRecords(opp);
		return opp;
	}

	public static Pricebook2 newPricebook() {
		Pricebook2 newPricebook = new Pricebook2(IsActive = true, Name = 'Pricebook');
		CRUDUtility.insertRecords(newPricebook);
		return newPricebook;
	}

	public static PricebookEntry newPricebookEntry(Id pricebookId, Id productId) {
		PricebookEntry newPricebookEntry = new PricebookEntry(
			IsActive = true,
			UnitPrice = 1000,
			Pricebook2Id = pricebookId,
			Product2Id = productId
		);
		return newPricebookEntry;
	}

	public static RateCard__c newRateCard() {
		RateCard__c rateCard = new RateCard__c(
			Name = 'Skill & Resource Location',
			IsActive__c = true,
			ExpirationDate__c = Date.today() + 1,
			EffectiveDate__c = Date.today() - 1
		);
		CRUDUtility.insertRecords(rateCard);
		return rateCard;
	}

	public static RateCardAttributeGroup__c newRateCardAttributeGroup() {
		RateCardAttributeGroup__c rateCardAttributeGroup = new RateCardAttributeGroup__c(
			Name = 'Skill & Resource Location'
		);
		CRUDUtility.insertRecords(rateCardAttributeGroup);
		return rateCardAttributeGroup;
	}

	public static RateCardAttribute__c newRateCardAttribute(Id rateCardAttributeGroupId) {
		RateCardAttribute__c rateCardAttribute = new RateCardAttribute__c(
			AttributeGroupId__c = rateCardAttributeGroupId,
			Sequence__c = 1,
			Name = 'Skill',
			FieldAPIName__c = Schema.RateCardItem__c.SkillLevel__c + ''
		);
		CRUDUtility.insertRecords(rateCardAttribute);
		return rateCardAttribute;
	}

	public static RateCardItem__c newRateCardItem(Id rateCardId, Id productId) {
		RateCardItem__c rateCardItem = new RateCardItem__c(
			IsActive__c = true,
			RateCardId__c = rateCardId,
			ProductId__c = productId
		);
		CRUDUtility.insertRecords(rateCardItem);
		return rateCardItem;
	}

	public static Product2 newProduct(String productName, String recordTypeId) {
		Product2 product = new Product2();
		product.IsActive = true;
		product.Name = productName;
		product.RecordTypeId = recordTypeId;
		return product;
	}

	public static CollaborationRequest__c newCollaborationRequest() {
		CollaborationRequest__c requestSO = new CollaborationRequest__c();
		CRUDUtility.insertRecords(requestSO);
		return requestSO;
	}

	public static QuoteSection__c newQuoteSection(Id quoteId) {
		QuoteSection__c sectionSO = new QuoteSection__c();
		sectionSO.QuoteId__c = quoteId;
		CRUDUtility.insertRecords(sectionSO);
		return sectionSO;
	}

	public static Estimate__c newEstimate() {
		Estimate__c newEstimate = new Estimate__c();
		return newEstimate;
	}

	public static OpportunityLineItem newOpportunityLineItem(
		Id opportunityId,
		Id productId,
		Id pricebookEntryId
	) {
		OpportunityLineItem newOpportunityLineItem = new OpportunityLineItem();
		newOpportunityLineItem.OpportunityId = opportunityId;
		newOpportunityLineItem.Product2Id = productId;
		newOpportunityLineItem.PricebookEntryId = pricebookEntryId;
		newOpportunityLineItem.Quantity = 1;
		newOpportunityLineItem.UnitPrice = 1000;
		return newOpportunityLineItem;
	}

	public static CollaborationRequest__c newCollaborationRequest(Id sectionId, String status) {
		CollaborationRequest__c request = new CollaborationRequest__c(
			SectionId__c = sectionId,
			Status__c = status
		);
		CRUDUtility.insertRecords(request);
		return request;
	}
}