force-app/main/default/objects/CollaborationRequest__c/CollaborationRequest__c.object-meta.xml
<CustomObject>
    <label>Collaboration Request</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Collaboration Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collaboration Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CollaborationRequest__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Collaboration Requests</relationshipLabel>
    <relationshipName>CollaborationRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollaborationRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Ready to Merge</fullName>
            </value>
            <value>
                <fullName>Merged</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
                <isActive>false</isActive>
                <label>Archived</label>
            </value>
            <value>
                <fullName>Contract Negotiation</fullName>
                <isActive>false</isActive>
                <label>Contract Negotiation</label>
            </value>
            <value>
                <fullName>Contracted</fullName>
                <isActive>false</isActive>
                <label>Contracted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EventPublisherTest.cls
/*
 * Provus Services Quoting
 * Copyright (c) 2021 Provus Inc. All rights reserved.
 */
@IsTest
private class EventPublisherTest extends TestBase {
	@TestSetup
	static void setup() {
		TestBase.newQuote();
	}

	@IsTest
	static void testPublish() {
		User userSO = newUser();
		Quote__c quote = [SELECT Id FROM Quote__c LIMIT 1];
		CollaborationRequest__c request = new CollaborationRequest__c(
			QuoteId__c = quote.Id,
			OwnerId = userSO.Id,
			Status__c = CollaborationRequest.STATUS_READY_TO_MERGE
		);

		Test.startTest();
		try {
			EventPublisher.publishQuoteUpdates(new List<CollaborationRequest__c>{ request });
			Test.getEventBus().deliver(); // validates that events have been published
			System.assert(true, 'should deliver event without exception');
		} catch (Exception e) {
			System.assert(false, 'should deliver event without exceptions');
		}
		Test.stopTest();
	}
}