force-app/main/default/objects/CollaborationRequest__c/CollaborationRequest__c.object-meta.xml
<CustomObject>
    <label>Collaboration Request</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Collaboration Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collaboration Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CollaborationRequest__c/fields/CollaboratorUserId__c.field-meta.xml
<CustomField>
    <fullName>CollaboratorUserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collaborator</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CollaborationRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollaborationRequest__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Collaboration Requests</relationshipLabel>
    <relationshipName>CollaborationRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollaborationRequest__c/fields/SectionId__c.field-meta.xml
<CustomField>
    <fullName>SectionId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Section</label>
    <referenceTo>QuoteSection__c</referenceTo>
    <relationshipLabel>Collaboration Requests</relationshipLabel>
    <relationshipName>CollaborationRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollaborationRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Ready to Merge</fullName>
            </value>
            <value>
                <fullName>Merged</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/DerivedFromId__c.field-meta.xml
<CustomField>
    <fullName>DerivedFromId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Derived From</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Versions</relationshipLabel>
    <relationshipName>QuoteVersions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
                <isActive>false</isActive>
                <label>Archived</label>
            </value>
            <value>
                <fullName>Contract Negotiation</fullName>
                <isActive>false</isActive>
                <label>Contract Negotiation</label>
            </value>
            <value>
                <fullName>Contracted</fullName>
                <isActive>false</isActive>
                <label>Contracted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&apos;Quote&apos;</defaultValue>
    <description>Indicates the type of quote.</description>
    <inlineHelpText>Indicates the type of quote.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Collaboration</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Scenario</fullName>
            </value>
            <value>
                <fullName>Template</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteSection__c/QuoteSection__c.object-meta.xml
<CustomObject>
    <label>Quote Section</label>
    <nameField>
        <label>Quote Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteSection__c/fields/DerivedFromId__c.field-meta.xml
<CustomField>
    <fullName>DerivedFromId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Derived From</label>
    <referenceTo>QuoteSection__c</referenceTo>
    <relationshipLabel>Quote Section Versions</relationshipLabel>
    <relationshipName>QuoteSectionVersions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteSection__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Sections</relationshipLabel>
    <relationshipName>QuoteSections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QuoteViewSetting__c/QuoteViewSetting__c.object-meta.xml
<CustomObject>
    <label>Quote View Setting</label>
    <nameField>
        <displayFormat>QVS-{0000000000}</displayFormat>
        <label>Quote View Setting Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote View Settings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteViewSetting__c/fields/CollaboratorUserId__c.field-meta.xml
<CustomField>
    <fullName>CollaboratorUserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collaborator</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ViewSettings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteViewSetting__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote View Settings</relationshipLabel>
    <relationshipName>ViewSettings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QuoteCollaborationController.cls
/**
 *  Provus Services Quoting
 *  @2021 Provus Inc. All rights reserved.
 */
public with sharing class QuoteCollaborationController {
	public final static String ACCESSLEVEL_EDIT = 'Edit';
	public final static String STATUS_ASSIGNED = 'Assigned';
	public final static String STATUS_ACCEPTED = 'Accepted';

	@AuraEnabled(cacheable=true)
	public static List<User> getUsers() {
		return QuoteCollaborationSupport.getUsers();
	}

	@AuraEnabled
	public static String getAvailableQuoteSections(Id quoteId) {
		return JSON.serialize(QuoteCollaborationSupport.getAvailableQuoteSections(quoteId));
	}

	@AuraEnabled
	public static String getCollaborationRequestsForQuote(Id quoteId) {
		return JSON.serialize(CollaborationRequestService.getOutstandingRequestsFor(quoteId));
	}

	@AuraEnabled
	public static Boolean submitInvitationForCollaboration(
		Id userId,
		Id quoteId,
		List<Id> quoteSectionIds
	) {
		QuoteViewSetting__c quoteViewSettingSO = createQuoteViewSetting(userId, quoteId);
		List<CollaborationRequest__c> listCollaborationRequests = createCollaborationRequests(
			quoteId,
			userId,
			quoteSectionIds
		);
		createSharingRecordForQuoteViewSetting(quoteViewSettingSO.Id, userId);
		createSharingRecordsForCollaborationRequest(
			new List<Id>(new Map<Id, CollaborationRequest__c>(listCollaborationRequests).keySet()),
			userId
		);
		QuoteCollaborationSupport.sendEmailToCollaborator(userId, quoteId);
		return true;
	}

	public static QuoteViewSetting__c createQuoteViewSetting(Id userId, Id quoteId) {
		QuoteViewSetting__c quoteViewSettingSO = new QuoteViewSetting__c();
		quoteViewSettingSO.OwnerId = UserInfo.getUserId();
		quoteViewSettingSO.QuoteId__c = quoteId;
		quoteViewSettingSO.CollaboratorUserId__c = userId;

		return (QuoteViewSetting__c) CRUDUtility.insertRecords(quoteViewSettingSO);
	}

	public static List<CollaborationRequest__c> createCollaborationRequests(
		Id quoteId,
		Id userId,
		List<Id> quoteSectionIds
	) {
		List<CollaborationRequest__c> listCollaborationRequests = new List<CollaborationRequest__c>();
		for (Id quoteSectionId : quoteSectionIds) {
			CollaborationRequest__c collaborationRequestSO = new CollaborationRequest__c(
				OwnerId = UserInfo.getUserId(),
				QuoteId__c = quoteId,
				SectionId__c = quoteSectionId,
				CollaboratorUserId__c = userId,
				Status__c = STATUS_ASSIGNED
			);
			listCollaborationRequests.add(collaborationRequestSO);
		}

		return (List<CollaborationRequest__c>) CRUDUtility.insertRecords(listCollaborationRequests);
	}

	public static void createSharingRecordForQuoteViewSetting(Id quoteViewSettingId, Id userId) {
		QuoteViewSetting__Share quoteViewSettingShare = new QuoteViewSetting__Share();
		quoteViewSettingShare.UserOrGroupId = userId;
		quoteViewSettingShare.ParentId = quoteViewSettingId;
		quoteViewSettingShare.AccessLevel = ACCESSLEVEL_EDIT;

		CRUDUtility.insertRecords(quoteViewSettingShare);
	}

	public static void createSharingRecordsForCollaborationRequest(
		List<Id> sectionViewSettingIds,
		Id userId
	) {
		List<CollaborationRequest__Share> listCollaborationRequestsShare = new List<CollaborationRequest__Share>();
		for (Id quoteViewSettingId : sectionViewSettingIds) {
			CollaborationRequest__Share collaborationRequestShare = new CollaborationRequest__Share(
				UserOrGroupId = userId,
				ParentId = quoteViewSettingId,
				AccessLevel = ACCESSLEVEL_EDIT
			);
			listCollaborationRequestsShare.add(collaborationRequestShare);
		}

		CRUDUtility.insertRecords(listCollaborationRequestsShare);
	}

	@AuraEnabled
	public static String createCollaborationQuote(Id userId, Id sourceQuoteId) {
		Quote__c clonedQuoteSO = QuoteCollaborationSupport.getExistingCollaborationQuoteFor(
			userId,
			sourceQuoteId
		);

		if (clonedQuoteSO == null) {
			clonedQuoteSO = cloneQuote(userId, sourceQuoteId);
			CRUDUtility.insertRecords(clonedQuoteSO);
		}

		List<CollaborationRequest__c> sourceQuoteCollaborationRequests = new List<CollaborationRequest__c>();
		List<CollaborationRequest__c> clonedCollaborationRequests = new List<CollaborationRequest__c>();
		Set<Id> sourceQuoteSectionIds = new Set<Id>();

		for (
			CollaborationRequest__c collaborationRequestSO : CollaborationRequestService.getAssignedRequestsFor(
				sourceQuoteId
			)
		) {
			collaborationRequestSO.Status__c = CollaborationRequest.STATUS_ACCEPTED;
			sourceQuoteCollaborationRequests.add(collaborationRequestSO);
			sourceQuoteSectionIds.add(collaborationRequestSO.SectionId__c);
		}

		CRUDUtility.updateRecords(sourceQuoteCollaborationRequests);

		QuoteService.copyQuoteChildEntities(sourceQuoteId, clonedQuoteSO.Id, sourceQuoteSectionIds);

		Map<String, Id> clonedCollaborationRequestToSectionId = new Map<String, Id>();
		for (QuoteSection__c clonedQuoteSectionSO : [
			SELECT Id, Name, QuoteId__c
			FROM QuoteSection__c
			WHERE QuoteId__c = :clonedQuoteSO.Id
			WITH SECURITY_ENFORCED
		]) {
			clonedCollaborationRequestToSectionId.put(clonedQuoteSectionSO.Name, clonedQuoteSectionSO.Id);
		}

		for (CollaborationRequest__c collaborationRequestSO : sourceQuoteCollaborationRequests) {
			CollaborationRequest__c clonedCollaborationRequestSO = new CollaborationRequest__c(
				Status__c = CollaborationRequest.STATUS_ACCEPTED,
				QuoteId__c = clonedQuoteSO.Id,
				CollaboratorUserId__c = collaborationRequestSO.CollaboratorUserId__c,
				SectionId__c = clonedCollaborationRequestToSectionId.get(
						collaborationRequestSO.SectionId__r.Name
					) != null
					? clonedCollaborationRequestToSectionId.get(collaborationRequestSO.SectionId__r.Name)
					: null
			);
			clonedCollaborationRequests.add(clonedCollaborationRequestSO);
		}

		CRUDUtility.insertRecords(clonedCollaborationRequests);

		return String.valueOf(clonedQuoteSO.Id);
	}

	public static Quote__c cloneQuote(Id userId, Id sourceQuoteId) {
		SObjectType objType = Quote__c.SObjectType;
		QueryRequest queryRequest = new QueryRequest(objType);
		queryRequest.requestedFields = SObjectUtility.getFieldsForSObject(objType);
		queryRequest.setFilterBy(new Map<String, String>{ SObjectUtility.FIELD_ID => sourceQuoteId });
		List<Quote__c> sourceQuotes = (List<Quote__c>) SOQLUtility.querySObject(queryRequest);

		Quote__c clonedQuote;
		if (sourceQuotes.size() > 0) {
			Quote__c sourceQuote = sourceQuotes[0];
			clonedQuote = sourceQuote.clone(false, true);
			clonedQuote.OwnerId = userId;
			clonedQuote.Name = QuoteService.RECORDTYPE_NAME_COLLABORATION + ': ' + sourceQuote.Name;
			clonedQuote.DerivedFromId__c = sourceQuote.Id;
			clonedQuote.Type__c = QuoteService.RECORDTYPE_NAME_COLLABORATION;
		}

		return clonedQuote;
	}

	/**
	 * Commits the changes by marking the sections for merge and sending an email to the quote owner
	 * to review.
	 * @param quoteId A collaboration quote ID
	 * @param sectionIds A list of quote section IDs to mark
	 */
	@AuraEnabled
	public static void commitChanges(Id quoteId, List<Id> sectionIds) {
		CollaborationRequestService.markForMerge(sectionIds);
		QuoteCollaborationSupport.sendEmailToQuoteOwner(quoteId);
	}

	/**
	 * Merges the quote items from the given section IDs into their main quotes.
	 * @param quoteId A main quote ID
	 * @param sectionIds A list of section IDs to merge
	 * @return A JSON representation of the quote items
	 */
	@AuraEnabled
	public static String mergeSections(Id quoteId, List<Id> sectionIds) {
		CollaborationMergeService.mergeSections(quoteId, sectionIds);
		return JSON.serialize(QuoteConfiguratorSupport.getQuoteItemsForQuote(quoteId));
	}

	@AuraEnabled
	public static void revokeSections(Id quoteId, List<Id> sectionIds) {
		QuoteCollaborationSupport.revokeSections(quoteId, sectionIds);
	}
}