force-app/main/default/objects/CollaborationRequest__c/CollaborationRequest__c.object-meta.xml
<CustomObject>
    <label>Collaboration Request</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Collaboration Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collaboration Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CollaborationRequest__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Collaboration Requests</relationshipLabel>
    <relationshipName>CollaborationRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollaborationRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Ready to Merge</fullName>
            </value>
            <value>
                <fullName>Merged</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteUpdate__e/QuoteUpdate__e.object-meta.xml
<CustomObject>
    <description>An event that is published when a quote is updated.</description>
    <label>Quote Update</label>
    <pluralLabel>Quote Updates</pluralLabel>
</CustomObject>

force-app/main/default/objects/QuoteUpdate__e/fields/AffectedQuotes__c.field-meta.xml
<CustomField>
    <fullName>AffectedQuotes__c</fullName>
    <description>A comma-separated list of quotes affected by this quote update.</description>
    <label>Affected Quotes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteUpdate__e/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <description>The name of the user who modified the quote.</description>
    <label>User</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EventPublisher.cls
/*
 * Provus Services Quoting
 * Copyright (c) 2021 Provus Inc. All rights reserved.
 */
public with sharing class EventPublisher {
	/**
	 * Publishes a Quote Update event for the given requests. Avoids sending a platform event
	 * for the quote being committed.
	 * @param requests A list of collaboration requests
	 */
	public static void publishQuoteUpdates(List<CollaborationRequest__c> requests) {
		Set<Id> affectedQuoteIds = new Set<Id>();
		for (CollaborationRequest__c request : requests) {
			if (
				request.OwnerId != UserInfo.getUserId() && // don't need to notify self
				CollaborationRequest.NOTIFICATION_STATUSES.contains(request.Status__c)
			) {
				affectedQuoteIds.add(request.QuoteId__c);
			}
		}

		if (affectedQuoteIds.size() == 0) {
			return;
		}

		String collaboratorName = [
			SELECT Name
			FROM User
			WHERE Id = :UserInfo.getUserId()
			WITH SECURITY_ENFORCED
		]
		.Name;

		List<QuoteUpdate__e> events = new List<QuoteUpdate__e>();
		QuoteUpdate__e event = new QuoteUpdate__e(
			AffectedQuotes__c = String.join(new List<Id>(affectedQuoteIds), ','),
			User__c = collaboratorName
		);
		events.add(event);

		if (events.size() > 0) {
			EventBus.publish(events);
		}
	}
}