force-app/main/default/objects/CollaborationRequest__c/CollaborationRequest__c.object-meta.xml
<CustomObject>
    <label>Collaboration Request</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Collaboration Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collaboration Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CollaborationRequest__c/fields/CollaboratorUserId__c.field-meta.xml
<CustomField>
    <fullName>CollaboratorUserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Collaborator</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CollaborationRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollaborationRequest__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Collaboration Requests</relationshipLabel>
    <relationshipName>CollaborationRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollaborationRequest__c/fields/SectionId__c.field-meta.xml
<CustomField>
    <fullName>SectionId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Section</label>
    <referenceTo>QuoteSection__c</referenceTo>
    <relationshipLabel>Collaboration Requests</relationshipLabel>
    <relationshipName>CollaborationRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollaborationRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Ready to Merge</fullName>
            </value>
            <value>
                <fullName>Merged</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
                <isActive>false</isActive>
                <label>Archived</label>
            </value>
            <value>
                <fullName>Contract Negotiation</fullName>
                <isActive>false</isActive>
                <label>Contract Negotiation</label>
            </value>
            <value>
                <fullName>Contracted</fullName>
                <isActive>false</isActive>
                <label>Contracted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteSection__c/QuoteSection__c.object-meta.xml
<CustomObject>
    <label>Quote Section</label>
    <nameField>
        <label>Quote Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteSection__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Sections</relationshipLabel>
    <relationshipName>QuoteSections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CollaborationRequestServiceTest.cls
/*
 * Provus Services Quoting
 * Copyright (c) 2021 Provus Inc. All rights reserved.
 */

@IsTest
private class CollaborationRequestServiceTest extends TestBase {
	@IsTest
	static void itShouldReturnOutstandingRequests() {
		Quote__c quoteSO = newQuote();
		CollaborationRequest__c requestSO1 = newCollaborationRequest();
		requestSO1.Status__c = CollaborationRequest.STATUS_READY_TO_MERGE;
		requestSO1.QuoteId__c = quoteSO.Id;
		CollaborationRequest__c requestSO2 = newCollaborationRequest();
		requestSO2.Status__c = CollaborationRequest.STATUS_MERGED;
		requestSO2.QuoteId__c = quoteSO.Id;
		CRUDUtility.updateRecords(new List<CollaborationRequest__c>{ requestSO1, requestSO2 });

		Test.startTest();
		List<CollaborationRequest__c> requests = CollaborationRequestService.getOutstandingRequestsFor(
			quoteSO.Id
		);
		System.assertEquals(1, requests.size(), 'should be have 1 outstanding request');
		Test.stopTest();
	}

	@IsTest
	static void itShouldReturnRevocableRequests() {
		Quote__c quoteSO = newQuote();
		QuoteSection__c section = newQuoteSection(quoteSO.Id);
		CollaborationRequest__c request1 = newCollaborationRequest();
		request1.Status__c = CollaborationRequest.STATUS_ASSIGNED;
		request1.QuoteId__c = quoteSO.Id;
		request1.SectionId__c = section.Id;
		CollaborationRequest__c request2 = newCollaborationRequest();
		request2.Status__c = CollaborationRequest.STATUS_ACCEPTED;
		request2.QuoteId__c = quoteSO.Id;
		request2.SectionId__c = section.Id;
		CRUDUtility.updateRecords(new List<CollaborationRequest__c>{ request1, request2 });

		Test.startTest();
		List<CollaborationRequest__c> requests = CollaborationRequestService.getRevocableRequestsFor(
			quoteSO.Id,
			new List<Id>{ section.Id }
		);
		System.assertEquals(2, requests.size(), 'should have 2 revocable requests');
		Test.stopTest();
	}

	@IsTest
	static void itShouldReturnAssignedRequests() {
		Quote__c quoteSO = newQuote();
		QuoteSection__c section = newQuoteSection(quoteSO.Id);
		CollaborationRequest__c request1 = newCollaborationRequest();
		request1.Status__c = CollaborationRequest.STATUS_ASSIGNED;
		request1.QuoteId__c = quoteSO.Id;
		request1.SectionId__c = section.Id;
		CollaborationRequest__c request2 = newCollaborationRequest();
		request2.Status__c = CollaborationRequest.STATUS_ACCEPTED;
		request2.QuoteId__c = quoteSO.Id;
		request2.SectionId__c = section.Id;
		CRUDUtility.updateRecords(new List<CollaborationRequest__c>{ request1, request2 });

		Test.startTest();
		List<CollaborationRequest__c> requests = CollaborationRequestService.getAssignedRequestsFor(
			quoteSO.Id
		);
		System.assertEquals(1, requests.size(), 'should have 1 assigned request');
		Test.stopTest();
	}

	@IsTest
	static void itShouldMarkRequestAsReadyToMerge() {
		Quote__c quoteSO = newQuote();
		QuoteSection__c sectionSO = newQuoteSection(quoteSO.Id);
		Id userId = UserInfo.getUserId();
		CollaborationRequest__c requestSO = newCollaborationRequest();
		requestSO.CollaboratorUserId__c = userId;
		requestSO.SectionId__c = sectionSO.Id;
		CRUDUtility.updateRecords(sectionSO);
		CRUDUtility.updateRecords(requestSO);

		Test.startTest();
		CollaborationRequestService.markForMerge(new List<Id>{ sectionSO.Id });
		CollaborationRequest__c updatedRequestSO = [
			SELECT Status__c
			FROM CollaborationRequest__c
			WHERE Id = :requestSO.Id
		];
		System.assertEquals(
			updatedRequestSO.Status__c,
			CollaborationRequest.STATUS_READY_TO_MERGE,
			'should be Ready to Merge'
		);
		Test.stopTest();
	}

	@IsTest
	static void itShouldMarkRequestAsMerged() {
		Quote__c quoteSO = newQuote();
		QuoteSection__c sectionSO = newQuoteSection(quoteSO.Id);
		Id userId = UserInfo.getUserId();
		CollaborationRequest__c requestSO = newCollaborationRequest();
		requestSO.CollaboratorUserId__c = userId;
		requestSO.SectionId__c = sectionSO.Id;
		CRUDUtility.updateRecords(sectionSO);
		CRUDUtility.updateRecords(requestSO);

		Test.startTest();
		CollaborationRequestService.markAsMerged(new List<Id>{ sectionSO.Id });
		CollaborationRequest__c updatedRequestSO = [
			SELECT Status__c
			FROM CollaborationRequest__c
			WHERE Id = :requestSO.Id
		];
		System.assertEquals(
			updatedRequestSO.Status__c,
			CollaborationRequest.STATUS_MERGED,
			'should be Merged'
		);
		Test.stopTest();
	}
}