force-app/main/default/objects/CollaborationRequest__c/CollaborationRequest__c.object-meta.xml
<CustomObject>
    <label>Collaboration Request</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Collaboration Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collaboration Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CollaborationRequest__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Collaboration Requests</relationshipLabel>
    <relationshipName>CollaborationRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollaborationRequest__c/fields/SectionId__c.field-meta.xml
<CustomField>
    <fullName>SectionId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Section</label>
    <referenceTo>QuoteSection__c</referenceTo>
    <relationshipLabel>Collaboration Requests</relationshipLabel>
    <relationshipName>CollaborationRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollaborationRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Ready to Merge</fullName>
            </value>
            <value>
                <fullName>Merged</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/DerivedFromId__c.field-meta.xml
<CustomField>
    <fullName>DerivedFromId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Derived From</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Versions</relationshipLabel>
    <relationshipName>QuoteVersions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
                <isActive>false</isActive>
                <label>Archived</label>
            </value>
            <value>
                <fullName>Contract Negotiation</fullName>
                <isActive>false</isActive>
                <label>Contract Negotiation</label>
            </value>
            <value>
                <fullName>Contracted</fullName>
                <isActive>false</isActive>
                <label>Contracted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteSection__c/QuoteSection__c.object-meta.xml
<CustomObject>
    <label>Quote Section</label>
    <nameField>
        <label>Quote Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteSection__c/fields/DerivedFromId__c.field-meta.xml
<CustomField>
    <fullName>DerivedFromId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Derived From</label>
    <referenceTo>QuoteSection__c</referenceTo>
    <relationshipLabel>Quote Section Versions</relationshipLabel>
    <relationshipName>QuoteSectionVersions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteSection__c/fields/DisplaySequence__c.field-meta.xml
<CustomField>
    <fullName>DisplaySequence__c</fullName>
    <label>Display Sequence</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteSection__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Sections</relationshipLabel>
    <relationshipName>QuoteSections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/QuoteCollaborationSupport.cls
/**
 *  Provus Services Quoting
 *  @2021 Provus Inc. All rights reserved.
 */
public with sharing class QuoteCollaborationSupport {
	public static final String EMAIL_COLLABORATION_REVIEW = 'CollaborationReview';
	public static final String EMAIL_COLLABORATION_INVITE = 'CollaborationInvite';

	public static List<User> getUsers() {
		return UserSupport.getActiveExcludingLoggedInUser();
	}

	/**
	 * retrieve the quote sections which are available for collaboartion
	 * @param quoteId Id of the quote
	 * @return List<QuoteSection__c>
	 */
	public static List<QuoteSection__c> getAvailableQuoteSections(Id quoteId) {
		return [
			SELECT Id, Name, QuoteId__c
			FROM QuoteSection__c
			WHERE
				QuoteId__c = :quoteId
				AND Id NOT IN (
					SELECT SectionId__c
					FROM CollaborationRequest__c
					WHERE
						QuoteId__c = :quoteId
						AND (Status__c = :CollaborationRequest.STATUS_ACCEPTED
						OR Status__c = :CollaborationRequest.STATUS_ASSIGNED)
				)
			WITH SECURITY_ENFORCED
			ORDER BY DisplaySequence__c, SectionSequence__c
			LIMIT :SOQLConstants.SOQL_QUERY_LIMIT
		];
	}

	public static void sendEmailToCollaborator(Id userId, Id quoteId) {
		EmailTemplate templateSO = SystemUtility.getEmailTemplateFor(EMAIL_COLLABORATION_INVITE);

		User userSO = UserSupport.getUserInformation(userId);
		Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
		String[] sendTo = new List<String>{ userSO.Email };
		mail.setToAddresses(sendTo);
		mail.setSubject(templateSO.Subject);

		String componentNSPrefix = !String.isBlank(SystemUtility.getNamespacePrefix())
			? SystemUtility.getNamespacePrefix()
			: 'c__';

		String url = String.format(
			'https://{0}/lightning/cmp/{3}checkoutQuoteSection?c__userId={1}&c__quoteId={2}',
			new List<String>{
				System.URL.getSalesforceBaseUrl().getHost(),
				userId,
				quoteId,
				componentNSPrefix
			}
		);

		mail.setHtmlBody(String.format(templateSO.HtmlValue, new List<String>{ userSO.Name, url }));

		mail.setReplyTo(UserInfo.getUserEmail());
		mail.setSenderDisplayName(UserInfo.getName());
		Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{ mail });
	}

	/**
	 * Sends a ready-for-review email to the quote owner of the given
	 * collaboration quote.
	 * @param quoteId A collaboration quote ID
	 */
	public static void sendEmailToQuoteOwner(Id quoteId) {
		Quote__c sourceQuote = [
			SELECT DerivedFromId__c, DerivedFromId__r.OwnerId
			FROM Quote__c
			WHERE Id = :quoteId
			WITH SECURITY_ENFORCED
		];

		EmailTemplate templateSO = SystemUtility.getEmailTemplateFor(EMAIL_COLLABORATION_REVIEW);

		User ownerUserSO = UserSupport.getUserInformation(sourceQuote.DerivedFromId__r.OwnerId);
		Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
		String[] sendTo = new List<String>{ ownerUserSO.Email };
		mail.setToAddresses(sendTo);
		mail.setSubject(templateSO.Subject);

		String url = String.format(
			'https://{0}/lightning/r/Quote__c/{1}/view',
			new List<String>{ System.URL.getSalesforceBaseUrl().getHost(), sourceQuote.DerivedFromId__c }
		);

		mail.setHtmlBody(
			String.format(templateSO.HtmlValue, new List<String>{ ownerUserSO.Name, url })
		);
		mail.setReplyTo(UserInfo.getUserEmail());
		mail.setSenderDisplayName(UserInfo.getName());
		Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{ mail });
	}

	public static void revokeSections(Id quoteId, List<Id> sectionIds) {
		List<Id> sectionLineageIds = new List<Id>();
		for (QuoteSection__c section : QuoteSectionService.getSectionLineageFor(sectionIds)) {
			sectionLineageIds.add(section.Id);
		}

		List<CollaborationRequest__c> acceptedRequests = CollaborationRequestService.getRevocableRequestsFor(
			quoteId,
			sectionLineageIds
		);
		for (CollaborationRequest__c request : acceptedRequests) {
			request.Status__c = CollaborationRequest.STATUS_REVOKED;
		}

		CRUDUtility.updateRecords(acceptedRequests);
	}

	public static Quote__c getExistingCollaborationQuoteFor(Id userId, Id sourceQuoteId) {
		String childRequestName = SystemUtility.getInverseRName(
			Schema.Quote__c.SObjectType,
			Schema.CollaborationRequest__c.SObjectType
		);
		QueryRequest innerQuery = new QueryRequest(childRequestName);
		innerQuery.requestedFields = new Set<String>{ 'Id' };
		innerQuery.setFilterBy(
			new Map<String, String>{
				Schema.CollaborationRequest__c.Status__c + '' => CollaborationRequest.STATUS_ACCEPTED
			}
		);

		SObjectType objType = Quote__c.SObjectType;
		QueryRequest queryRequest = new QueryRequest(objType);
		queryRequest.requestedFields = SObjectUtility.getFieldsForSObject(objType);
		queryRequest.setFilterBy(
			new Map<String, String>{
				Schema.Quote__c.DerivedFromId__c + '' => sourceQuoteId,
				SObjectUtility.FIELD_OWNER_ID => userId
			}
		);
		queryRequest.innerQueries = new List<QueryRequest>{ innerQuery };
		List<Quote__c> sourceQuotes = (List<Quote__c>) SOQLUtility.querySObject(queryRequest);

		for (Quote__c quote : sourceQuotes) {
			if (quote.CollaborationRequests__r.size() > 0) {
				return quote;
			}
		}

		return null;
	}
}