force-app/main/default/objects/CollaborationRequest__c/CollaborationRequest__c.object-meta.xml
<CustomObject>
    <label>Collaboration Request</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Collaboration Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collaboration Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CollaborationRequest__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Collaboration Requests</relationshipLabel>
    <relationshipName>CollaborationRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollaborationRequest__c/fields/SectionId__c.field-meta.xml
<CustomField>
    <fullName>SectionId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Section</label>
    <referenceTo>QuoteSection__c</referenceTo>
    <relationshipLabel>Collaboration Requests</relationshipLabel>
    <relationshipName>CollaborationRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CollaborationRequest__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Ready to Merge</fullName>
            </value>
            <value>
                <fullName>Merged</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/DerivedFromId__c.field-meta.xml
<CustomField>
    <fullName>DerivedFromId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Derived From</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Versions</relationshipLabel>
    <relationshipName>QuoteVersions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
                <isActive>false</isActive>
                <label>Archived</label>
            </value>
            <value>
                <fullName>Contract Negotiation</fullName>
                <isActive>false</isActive>
                <label>Contract Negotiation</label>
            </value>
            <value>
                <fullName>Contracted</fullName>
                <isActive>false</isActive>
                <label>Contracted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteSection__c/QuoteSection__c.object-meta.xml
<CustomObject>
    <label>Quote Section</label>
    <nameField>
        <label>Quote Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteSection__c/fields/DerivedFromId__c.field-meta.xml
<CustomField>
    <fullName>DerivedFromId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Derived From</label>
    <referenceTo>QuoteSection__c</referenceTo>
    <relationshipLabel>Quote Section Versions</relationshipLabel>
    <relationshipName>QuoteSectionVersions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteSection__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Sections</relationshipLabel>
    <relationshipName>QuoteSections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/QuoteCollaborationSupportTest.cls
/**
 *  Provus Services Quoting
 *  QuoteCollaborationSupportTest
 *  @2021 Provus Inc. All rights reserved.
 */
@isTest
private class QuoteCollaborationSupportTest extends TestBase {
	@IsTest
	static void itShouldSendAnEmailToCollaborator() {
		Test.startTest();
		Id userId = UserInfo.getUserId();
		Quote__c quote = newQuote();
		QuoteCollaborationSupport.sendEmailToCollaborator(userId, quote.Id);
		Integer invocations = Limits.getEmailInvocations();
		Test.stopTest();
		system.assertEquals(1, invocations, 'An email should be sent');
	}

	@IsTest
	static void itShouldSendAnEmailToQuoteOwner() {
		Quote__c mainQuote = newQuote();
		Quote__c quoteSO = newQuote();
		quoteSO.DerivedFromId__c = mainQuote.Id;
		CRUDUtility.updateRecords(quoteSO);

		Test.startTest();
		QuoteCollaborationSupport.sendEmailToQuoteOwner(quoteSO.Id);
		Integer invocations = Limits.getEmailInvocations();
		Test.stopTest();
		System.assertEquals(1, invocations, 'should equal 1');
	}

	@IsTest
	static void itShouldGetQuoteSections() {
		Quote__c quote = newQuote();
		QuoteSection__c section = newQuoteSection(quote.Id);
		CollaborationRequest__c request = newCollaborationRequest();
		request.QuoteId__c = quote.Id;
		request.SectionId__c = section.Id;
		request.Status__c = CollaborationRequest.STATUS_MERGED;

		update request;

		Test.startTest();
		List<QuoteSection__c> quoteSections = QuoteCollaborationSupport.getAvailableQuoteSections(
			quote.Id
		);
		System.assertEquals(1, quoteSections.size(), 'should equal 1');
		Test.stopTest();
	}

	@IsTest
	static void itShouldNotGetAssignedSections() {
		Quote__c quote = newQuote();
		QuoteSection__c section = newQuoteSection(quote.Id);
		CollaborationRequest__c request = newCollaborationRequest();
		request.QuoteId__c = quote.Id;
		request.SectionId__c = section.Id;
		request.Status__c = CollaborationRequest.STATUS_ASSIGNED;

		update request;

		Test.startTest();
		List<QuoteSection__c> quoteSections = QuoteCollaborationSupport.getAvailableQuoteSections(
			quote.Id
		);
		System.assertEquals(0, quoteSections.size(), 'should not return any quote sections');
		Test.stopTest();
	}

	@IsTest
	static void itShouldNotGetAcceptedSections() {
		Quote__c quote = newQuote();
		QuoteSection__c section = newQuoteSection(quote.Id);
		CollaborationRequest__c request = newCollaborationRequest();
		request.QuoteId__c = quote.Id;
		request.SectionId__c = section.Id;
		request.Status__c = CollaborationRequest.STATUS_ACCEPTED;

		update request;

		Test.startTest();
		List<QuoteSection__c> quoteSections = QuoteCollaborationSupport.getAvailableQuoteSections(
			quote.Id
		);
		System.assertEquals(0, quoteSections.size(), 'should not return any quote sections');
		Test.stopTest();
	}

	@IsTest
	static void itShouldRevokeSections() {
		Quote__c quote = newQuote();
		QuoteSection__c section = newQuoteSection(quote.Id);
		CollaborationRequest__c request = newCollaborationRequest();
		request.QuoteId__c = quote.Id;
		request.SectionId__c = section.Id;
		request.Status__c = CollaborationRequest.STATUS_ACCEPTED;

		update request;

		Test.startTest();
		QuoteCollaborationSupport.revokeSections(quote.Id, new List<Id>{ section.Id });
		CollaborationRequest__c result = [
			SELECT Status__c
			FROM CollaborationRequest__c
			WHERE SectionId__c = :section.Id
		];
		System.assertEquals(
			CollaborationRequest.STATUS_REVOKED,
			result.Status__c,
			'should update the status to Revoked'
		);
		Test.stopTest();
	}

	@IsTest
	static void itShouldGetExistingCollaborationQuote() {
		Quote__c quote = newQuote();
		Quote__c sourceQuote = newQuote();
		CollaborationRequest__c request = newCollaborationRequest();
		request.QuoteId__c = quote.Id;
		request.Status__c = CollaborationRequest.STATUS_ACCEPTED;
		quote.DerivedFromId__c = sourceQuote.Id;
		update request;
		update quote;

		Test.startTest();
		Quote__c existingQuote = QuoteCollaborationSupport.getExistingCollaborationQuoteFor(
			UserInfo.getUserId(),
			sourceQuote.Id
		);
		System.assertNotEquals(null, existingQuote, 'should have found an existing quote');
		Test.stopTest();
	}
}