force-app/main/default/objects/ObjectOverride__c/ObjectOverride__c.object-meta.xml
<CustomObject>
    <description>Specified object for override</description>
    <label>Object Override</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Object Override Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Object Overrides</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ObjectOverride__c/fields/OverrideObjectApiName__c.field-meta.xml
<CustomField>
    <fullName>OverrideObjectApiName__c</fullName>
    <description
	>API name of object for who&apos;s field values this object value override record intends to overwrite.</description>
    <inlineHelpText
	>API name of object for who&apos;s field values this object value override record intends to overwrite.</inlineHelpText>
    <label>Override Object API Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteObjectOverride__c/QuoteObjectOverride__c.object-meta.xml
<CustomObject>
    <description>Junction object relating quote to object override record</description>
    <label>Quote Object Override</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Quote Object Override Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Object Overrides</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteObjectOverride__c/fields/ObjectOverrideId__c.field-meta.xml
<CustomField>
    <fullName>ObjectOverrideId__c</fullName>
    <description>Id of Object Override record</description>
    <inlineHelpText>Id of Object Override record</inlineHelpText>
    <label>Object Override</label>
    <referenceTo>ObjectOverride__c</referenceTo>
    <relationshipLabel>Quote Object Overrides</relationshipLabel>
    <relationshipName>QuoteObjectOverrides</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QuoteObjectOverride__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <description>ID of quote record</description>
    <inlineHelpText>ID of quote record</inlineHelpText>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Object Overrides</relationshipLabel>
    <relationshipName>QuoteObjectOverrides</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ScheduleSetting__mdt/ScheduleSetting__mdt.object-meta.xml
<CustomObject>
    <description
	>Provus application settings regarding standard resource sheduling factors such as hours in a standard work week which may vary from one organization to another based on a number of factors</description>
    <label>Schedule Setting</label>
    <pluralLabel>Schedule Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/ScheduleSetting__mdt/fields/StandardWeekHours__c.field-meta.xml
<CustomField>
    <fullName>StandardWeekHours__c</fullName>
    <description
	>Number of hours in a work week generally considered to be normal for your organization</description>
    <inlineHelpText
	>Number of hours in a work week generally considered to be normal for your organization</inlineHelpText>
    <label>Hours in a standard week</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ValueOverride__c/ValueOverride__c.object-meta.xml
<CustomObject>
    <label>Value Override</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Value Override Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Value Overrides</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ValueOverride__c/fields/FieldApiName__c.field-meta.xml
<CustomField>
    <fullName>FieldApiName__c</fullName>
    <description>API name of object being referenced for which to override values with</description>
    <inlineHelpText
	>API name of object being referenced for which to override values with</inlineHelpText>
    <label>Field API Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ValueOverride__c/fields/FieldValue__c.field-meta.xml
<CustomField>
    <fullName>FieldValue__c</fullName>
    <description>Stores override value for specified field</description>
    <inlineHelpText>Stores override value for specified field</inlineHelpText>
    <label>Field Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ValueOverride__c/fields/ObjectOverrideId__c.field-meta.xml
<CustomField>
    <fullName>ObjectOverrideId__c</fullName>
    <description>Lookup to override junction record</description>
    <inlineHelpText>Lookup to override junction record</inlineHelpText>
    <label>Object Override</label>
    <referenceTo>ObjectOverride__c</referenceTo>
    <relationshipLabel>Object Overrides</relationshipLabel>
    <relationshipName>ObjectValueOverrides</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ObjectOverrideControllerTest.cls
/**
 *  Provus Services Quoting
 *  ObjectOverrideControllerTest
 *  @2021 Provus Inc. All rights reserved.
 */
@IsTest
public with sharing class ObjectOverrideControllerTest extends QuoteItemTestsBase {
	static final String SCHEDULE_SETTING_API_NAME = SObjectType.ScheduleSetting__mdt.getName();
	static final String FIELDNAME_STANDARDWEEKHOURS =
		Schema.ScheduleSetting__mdt.StandardWeekHours__c + '';
	static String testOverrideValue1 = 'Test String Value';

	@TestSetup
	static void setup() {
		Quote__c quote = newQuote('Test Override Quote');

		ObjectOverride__c objectValueOverride = new ObjectOverride__c();
		objectValueOverride.OverrideObjectApiName__c = SCHEDULE_SETTING_API_NAME;
		insert objectValueOverride;

		ValueOverride__c valueOverride = new ValueOverride__c();
		valueOverride.FieldApiName__c = FIELDNAME_STANDARDWEEKHOURS;
		valueOverride.ObjectOverrideId__c = objectValueOverride.Id;
		valueOverride.FieldValue__c = testOverrideValue1;
		insert valueOverride;

		QuoteObjectOverride__c quoteObjectOverride = new QuoteObjectOverride__c(
			ObjectOverrideId__c = objectValueOverride.Id,
			QuoteId__c = quote.Id
		);
		insert quoteObjectOverride;
	}

	@IsTest
	static void getObjectOverrideRecordAndVerifyPopulatedProperly() {
		TestData testData = retrieveTestData();

		Test.startTest();

		ObjectOverrideDTO objOverride = ObjectOverrideController.getObjectOverride(
			testData.quote.Id,
			SCHEDULE_SETTING_API_NAME
		);

		System.assertEquals(4, objOverride.valueOverrides.size(), 'should have four value overrides');

		ValueOverrideDTO selectedValueOverride;
		for (ValueOverrideDTO valueOverride : objOverride.valueOverrides) {
			if (valueOverride.fieldApiName == FIELDNAME_STANDARDWEEKHOURS) {
				selectedValueOverride = valueOverride;
				break;
			}
		}
		System.assertEquals(
			testOverrideValue1,
			selectedValueOverride.fieldValue,
			'field value should match inserted one'
		);

		Test.stopTest();
	}

	private static TestData retrieveTestData() {
		TestData testData = new TestData();

		testData.quote = [SELECT Id FROM Quote__c WHERE Name = 'Test Override Quote'];
		testData.quoteObjectOverride = [
			SELECT ObjectOverrideId__c
			FROM QuoteObjectOverride__c
			WHERE QuoteId__c = :testData.quote.Id
		];

		return testData;
	}

	private class TestData {
		public Quote__c quote;
		public QuoteObjectOverride__c quoteObjectOverride;
	}
}