force-app/main/default/objects/ObjectOverride__c/ObjectOverride__c.object-meta.xml
<CustomObject>
    <description>Specified object for override</description>
    <label>Object Override</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Object Override Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Object Overrides</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ObjectOverride__c/fields/OverrideObjectApiName__c.field-meta.xml
<CustomField>
    <fullName>OverrideObjectApiName__c</fullName>
    <description
	>API name of object for who&apos;s field values this object value override record intends to overwrite.</description>
    <inlineHelpText
	>API name of object for who&apos;s field values this object value override record intends to overwrite.</inlineHelpText>
    <label>Override Object API Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProvusConfiguratorSetting__mdt/ProvusConfiguratorSetting__mdt.object-meta.xml
<CustomObject>
    <label>Provus Configurator Setting</label>
    <pluralLabel>Provus Quoting Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/ProvusConfiguratorSetting__mdt/fields/HiddenFields__c.field-meta.xml
<CustomField>
    <fullName>HiddenFields__c</fullName>
    <label>Hidden Fields</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteObjectOverride__c/QuoteObjectOverride__c.object-meta.xml
<CustomObject>
    <description>Junction object relating quote to object override record</description>
    <label>Quote Object Override</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Quote Object Override Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Object Overrides</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteObjectOverride__c/fields/ObjectOverrideId__c.field-meta.xml
<CustomField>
    <fullName>ObjectOverrideId__c</fullName>
    <description>Id of Object Override record</description>
    <inlineHelpText>Id of Object Override record</inlineHelpText>
    <label>Object Override</label>
    <referenceTo>ObjectOverride__c</referenceTo>
    <relationshipLabel>Quote Object Overrides</relationshipLabel>
    <relationshipName>QuoteObjectOverrides</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QuoteObjectOverride__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <description>ID of quote record</description>
    <inlineHelpText>ID of quote record</inlineHelpText>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Object Overrides</relationshipLabel>
    <relationshipName>QuoteObjectOverrides</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ScheduleSetting__mdt/ScheduleSetting__mdt.object-meta.xml
<CustomObject>
    <description
	>Provus application settings regarding standard resource sheduling factors such as hours in a standard work week which may vary from one organization to another based on a number of factors</description>
    <label>Schedule Setting</label>
    <pluralLabel>Schedule Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/ScheduleSetting__mdt/fields/StandardDayHours__c.field-meta.xml
<CustomField>
    <fullName>StandardDayHours__c</fullName>
    <description
	>Number of hours in a work day generally considered to be normal for your organization</description>
    <inlineHelpText
	>Number of hours in a work day generally considered to be normal for your organization</inlineHelpText>
    <label>Hours in a standard day</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ScheduleSetting__mdt/fields/StandardWeekHours__c.field-meta.xml
<CustomField>
    <fullName>StandardWeekHours__c</fullName>
    <description
	>Number of hours in a work week generally considered to be normal for your organization</description>
    <inlineHelpText
	>Number of hours in a work week generally considered to be normal for your organization</inlineHelpText>
    <label>Hours in a standard week</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ValueOverride__c/ValueOverride__c.object-meta.xml
<CustomObject>
    <label>Value Override</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Value Override Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Value Overrides</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ValueOverride__c/fields/FieldApiName__c.field-meta.xml
<CustomField>
    <fullName>FieldApiName__c</fullName>
    <description>API name of object being referenced for which to override values with</description>
    <inlineHelpText
	>API name of object being referenced for which to override values with</inlineHelpText>
    <label>Field API Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ValueOverride__c/fields/FieldValue__c.field-meta.xml
<CustomField>
    <fullName>FieldValue__c</fullName>
    <description>Stores override value for specified field</description>
    <inlineHelpText>Stores override value for specified field</inlineHelpText>
    <label>Field Value</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ValueOverride__c/fields/ObjectOverrideId__c.field-meta.xml
<CustomField>
    <fullName>ObjectOverrideId__c</fullName>
    <description>Lookup to override junction record</description>
    <inlineHelpText>Lookup to override junction record</inlineHelpText>
    <label>Object Override</label>
    <referenceTo>ObjectOverride__c</referenceTo>
    <relationshipLabel>Object Overrides</relationshipLabel>
    <relationshipName>ObjectValueOverrides</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ObjectOverrideServiceTest.cls
/**
 *  Provus Services Quoting
 *  ObjectOverrideServiceTest
 *  @2021 Provus Inc. All rights reserved.
 */
@IsTest
private class ObjectOverrideServiceTest extends QuoteItemTestsBase {
	static final String SCHEDULE_SETTING_API_NAME = SObjectType.ScheduleSetting__mdt.getName();
	static final String PROVUS_CONFIGURATOR_SETTING_API_NAME = SObjectType.ProvusConfiguratorSetting__mdt.getName();
	static final String FIELDNAME_STANDARDWEEKHOURS =
		Schema.ScheduleSetting__mdt.StandardWeekHours__c + '';
	static final String FIELDNAME_STANDARDDAYOURS =
		Schema.ScheduleSetting__mdt.StandardDayHours__c + '';
	static final String FIELDNAME_HIDDENFIELDS =
		Schema.ProvusConfiguratorSetting__mdt.HiddenFields__c + '';
	static String testOverrideValue1 = 'Test String Value';
	static String testOverrideValue2 = 'Test String Value 2';

	@TestSetup
	static void setup() {
		Quote__c quote = newQuote('Test Override Quote');

		ObjectOverride__c objectValueOverride = new ObjectOverride__c();
		objectValueOverride.OverrideObjectApiName__c = SCHEDULE_SETTING_API_NAME;
		insert objectValueOverride;

		ValueOverride__c valueOverride = new ValueOverride__c();
		valueOverride.FieldApiName__c = FIELDNAME_STANDARDWEEKHOURS;
		valueOverride.ObjectOverrideId__c = objectValueOverride.Id;
		valueOverride.FieldValue__c = testOverrideValue1;
		insert valueOverride;

		ValueOverride__c valueOverride2 = new ValueOverride__c();
		valueOverride2.FieldApiName__c = FIELDNAME_STANDARDDAYOURS;
		valueOverride2.ObjectOverrideId__c = objectValueOverride.Id;
		valueOverride2.FieldValue__c = testOverrideValue2;
		insert valueOverride2;

		QuoteObjectOverride__c quoteObjectOverride = new QuoteObjectOverride__c(
			ObjectOverrideId__c = objectValueOverride.Id,
			QuoteId__c = quote.Id
		);
		insert quoteObjectOverride;

		ValueOverride__c valueOverrideSO = new ValueOverride__c();
		valueOverrideSO.FieldApiName__c = FIELDNAME_HIDDENFIELDS;
		valueOverrideSO.FieldValue__c = testOverrideValue1;
		ValueOverrideDTO valueOverrideDto = new ValueOverrideDTO(valueOverrideSO);

		ObjectOverrideDTO objectOverrideDto = new ObjectOverrideDTO(
			PROVUS_CONFIGURATOR_SETTING_API_NAME
		);
		objectOverrideDto.valueOverrides.add(valueOverrideDto);

		ObjectOverrideService.commitObjectOverride(objectOverrideDto);
	}

	@IsTest
	static void getObjectOverrideReturnsObjectOverrideAndTwoFieldValueOverrides() {
		TestData testData = retrieveTestData();

		Test.startTest();

		QuoteObjectOverride__c junctionRecord = ObjectOverrideService.getObjectOverrideId(
			testData.quote.Id,
			SCHEDULE_SETTING_API_NAME
		);

		ObjectOverrideDTO objectOverride = ObjectOverrideService.getObjectOverride(
			junctionRecord.ObjectOverrideId__c
		);

		List<ValueOverrideDTO> valueOverrides = objectOverride.valueOverrides;

		System.assertEquals(
			4,
			valueOverrides.size(),
			'should return four value field override records'
		);

		ValueOverrideDTO valueOverride1 = getOverrideByApiName(
			FIELDNAME_STANDARDDAYOURS,
			valueOverrides
		);
		System.assertNotEquals(null, valueOverride1.id, 'id should not be null');
		System.assertEquals(
			testOverrideValue2,
			valueOverride1.fieldValue,
			'field value should be equal to the test override value 1'
		);
		System.assertEquals('8.0', valueOverride1.defaultFieldValue, 'expect default value of \'8.0\'');
		System.assertEquals(
			'Hours in a standard day',
			valueOverride1.fieldLabel,
			'should return field label of \'Hours in a standard day\''
		);

		ValueOverrideDTO valueOverride2 = getOverrideByApiName(
			FIELDNAME_STANDARDWEEKHOURS,
			valueOverrides
		);
		System.assertNotEquals(null, valueOverride2.id, 'value override record id should not be null');
		System.assertEquals(
			testOverrideValue1,
			valueOverride2.fieldValue,
			'field value should be equal to the test override value 1'
		);

		Test.stopTest();
	}

	@IsTest
	static void commitObjectOverrideWithInvalidApiNameNoDmlTransactionOccurs() {
		String overrideObjectApiName = 'Invalid API Name';

		ObjectOverrideDTO objectOverrideDto = new ObjectOverrideDTO(overrideObjectApiName);

		Test.startTest();

		ObjectOverrideResult validation = ObjectOverrideService.commitObjectOverride(objectOverrideDto);
		System.assertEquals(false, validation.isValid(), 'isValid should return false');
		System.assertEquals(
			1,
			validation.errorMsgs.size(),
			'there should be one validation error message'
		);
		String expectedErrorMessage = Label.InvalidObjectAPIName.replace('{0}', overrideObjectApiName);
		System.assertEquals(
			expectedErrorMessage,
			validation.errorMsgs[0],
			'Expect invalid object API name validation message'
		);

		Test.stopTest();
	}

	@IsTest
	static void commitObjectOverrideWithInvalidFieldApiNameNoDmlTransactionOccurs() {
		String fieldApiName = 'Invalid field API Name';

		ValueOverride__c valueOverrideSO = new ValueOverride__c();
		valueOverrideSO.FieldApiName__c = fieldApiName;
		valueOverrideSO.FieldValue__c = testOverrideValue1;
		ValueOverrideDTO valueOverrideDto = new ValueOverrideDTO(valueOverrideSO);

		ObjectOverrideDTO objectOverrideDto = new ObjectOverrideDTO(
			PROVUS_CONFIGURATOR_SETTING_API_NAME
		);
		objectOverrideDto.valueOverrides.add(valueOverrideDto);

		Test.startTest();

		ObjectOverrideResult validation = ObjectOverrideService.commitObjectOverride(objectOverrideDto);
		System.assertEquals(false, validation.isValid(), 'isValid should return false');
		System.assertEquals(
			1,
			validation.errorMsgs.size(),
			'there should be one validation error message'
		);
		String expectedErrorMessage = Label.InvalidFieldAPIName.replace('{0}', fieldApiName);
		System.assertEquals(
			expectedErrorMessage,
			validation.errorMsgs[0],
			'Expect invalid field API name validation message'
		);

		Test.stopTest();
	}

	@IsTest
	static void commitObjectOverrideWithValidObjectAndFieldApiName() {
		Id objectOverrideId = getObjectOverrideIdByApiName(PROVUS_CONFIGURATOR_SETTING_API_NAME);

		Test.startTest();

		ObjectOverrideDTO objectOverrideDto = ObjectOverrideService.getObjectOverride(objectOverrideId);
		ObjectOverrideResult validation = ObjectOverrideService.commitObjectOverride(objectOverrideDto);

		System.assertEquals(true, validation.isValid(), 'isValid should return false');
		ObjectOverrideDTO objectOverrideDtoFromDb = validation.objectOverrideDtos[0];
		System.assertNotEquals(
			null,
			objectOverrideDtoFromDb.id,
			'id field of DTO object should NOT be null'
		);
		System.assertNotEquals(
			null,
			objectOverrideDtoFromDb.sO.Id,
			'id field of SO object should NOT be null'
		);
		System.assertNotEquals(
			null,
			objectOverrideDtoFromDb.valueOverrides[0].id,
			'id field of DTO value override object should NOT be null'
		);
		System.assertNotEquals(
			null,
			objectOverrideDtoFromDb.valueOverrides[0].sO.Id,
			'id field of SO value override object should NOT be null'
		);

		ObjectOverride__c objectOverrideSO = [
			SELECT
				Id,
				OverrideObjectApiName__c,
				(
					SELECT Id, FieldApiName__c, FieldValue__c, ObjectOverrideId__c
					FROM ObjectValueOverrides__r
				)
			FROM ObjectOverride__c
			WHERE Id = :objectOverrideDtoFromDb.id
		];

		System.assertNotEquals(
			null,
			objectOverrideSO,
			'object override SO exists in DB and is not null'
		);
		System.assertEquals(
			1,
			objectOverrideSO.ObjectValueOverrides__r.size(),
			'list of value override SOs exists in DB and list should have one entry'
		);
		System.assertEquals(
			FIELDNAME_HIDDENFIELDS,
			objectOverrideSO.ObjectValueOverrides__r[0].FieldApiName__c,
			'The object\'s field API name should equal '
		);
		System.assertEquals(
			testOverrideValue1,
			objectOverrideSO.ObjectValueOverrides__r[0].FieldValue__c,
			'make sure the correct field value is committed to the DB'
		);

		Test.stopTest();
	}

	@IsTest
	static void commitObjectOverrideClearValueOverrideListAllRecordsAreDeleted() {
		Test.startTest();

		Id objectOverrideId = getObjectOverrideIdByApiName(PROVUS_CONFIGURATOR_SETTING_API_NAME);

		ObjectOverrideDTO objectOverride = ObjectOverrideService.getObjectOverride(objectOverrideId);
		objectOverride.valueOverrides = new List<ValueOverrideDTO>();

		ObjectOverrideService.commitObjectOverride(objectOverride);

		try {
			// retrieve record
			ObjectOverrideService.getObjectOverride(objectOverrideId);
		} catch (Exception ex) {
			// should be empty/null
			System.assertEquals(
				'System.QueryException',
				ex.getTypeName(),
				'we expect an exception to be thrown of type QueryException'
			);
			System.assertEquals(
				'List has no rows for assignment to SObject',
				ex.getMessage(),
				'we expect error message indicating that a list has no rows for assignment'
			);
		}

		Test.stopTest();
	}

	private static Id getObjectOverrideIdByApiName(String objectApiName) {
		return [SELECT Id FROM ObjectOverride__c WHERE OverrideObjectApiName__c = :objectApiName].Id;
	}

	private static ValueOverrideDTO getOverrideByApiName(
		String fieldApiName,
		List<ValueOverrideDTO> valueOverrides
	) {
		ValueOverrideDTO selectedValueOverride;
		for (ValueOverrideDTO valueOverride : valueOverrides) {
			if (valueOverride.fieldApiName == fieldApiName) {
				selectedValueOverride = valueOverride;
				break;
			}
		}
		return selectedValueOverride;
	}

	private static TestData retrieveTestData() {
		TestData testData = new TestData();

		testData.quote = [SELECT Id FROM Quote__c WHERE Name = 'Test Override Quote'];
		testData.quoteObjectOverride = [
			SELECT ObjectOverrideId__c
			FROM QuoteObjectOverride__c
			WHERE QuoteId__c = :testData.quote.Id
		];

		return testData;
	}

	private class TestData {
		public Quote__c quote;
		public QuoteObjectOverride__c quoteObjectOverride;
	}
}