force-app/main/default/objects/QuoteObjectOverride__c/QuoteObjectOverride__c.object-meta.xml
<CustomObject>
    <description>Junction object relating quote to object override record</description>
    <label>Quote Object Override</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Quote Object Override Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Object Overrides</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteObjectOverride__c/fields/ObjectOverrideId__c.field-meta.xml
<CustomField>
    <fullName>ObjectOverrideId__c</fullName>
    <description>Id of Object Override record</description>
    <inlineHelpText>Id of Object Override record</inlineHelpText>
    <label>Object Override</label>
    <referenceTo>ObjectOverride__c</referenceTo>
    <relationshipLabel>Quote Object Overrides</relationshipLabel>
    <relationshipName>QuoteObjectOverrides</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ObjectOverrideController.cls
/**
 *  Provus Services Quoting
 *  ObjectOverrideController
 *  @2021 Provus Inc. All rights reserved.
 */
public with sharing class ObjectOverrideController {
	@AuraEnabled
	public static ObjectOverrideDTO getObjectOverride(Id quoteId, String overrideObjectApiName) {
		// get object override id from junction object
		QuoteObjectOverride__c quoteObjectOverrideJct = ObjectOverrideService.getObjectOverrideId(
			quoteId,
			overrideObjectApiName
		);

		// get object override object for UI
		ObjectOverrideDTO objectOverrideDto = ObjectOverrideService.getObjectOverride(
			quoteObjectOverrideJct.ObjectOverrideId__c,
			overrideObjectApiName
		);
		objectOverrideDto.junctionRecordId = quoteObjectOverrideJct.Id;
		return objectOverrideDto;
	}

	@AuraEnabled
	public static ObjectOverrideResult commitObjectOverride(
		Id quoteId,
		ObjectOverrideDTO objectOverrideDto
	) {
		ObjectOverrideResult validationResult = ObjectOverrideService.commitObjectOverride(
			objectOverrideDto
		);
		if (objectOverrideDto.junctionRecordId == null) {
			validationResult.objectOverrideDtos[0]
				.junctionRecordId = ObjectOverrideService.insertQuoteObjectOverrideJctRecord(
				quoteId,
				validationResult.objectOverrideDtos[0].id
			);
		}

		return validationResult;
	}
}