force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/RateCardId__c.field-meta.xml
<CustomField>
    <fullName>RateCardId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate Card</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(3 OR 1) AND (4 OR 2) AND 5</booleanFilter>
        <errorMessage
		>The Rate Card is expired/inactive during the selected service start date</errorMessage>
        <filterItems>
            <field>$Source.ServiceStartDate__c</field>
            <operation>greaterOrEqual</operation>
            <valueField>RateCard__c.EffectiveDate__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.ServiceStartDate__c</field>
            <operation>lessOrEqual</operation>
            <valueField>RateCard__c.ExpirationDate__c</valueField>
        </filterItems>
        <filterItems>
            <field>RateCard__c.EffectiveDate__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <filterItems>
            <field>RateCard__c.ExpirationDate__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <filterItems>
            <field>RateCard__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>RateCard__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/ServiceStartDate__c.field-meta.xml
<CustomField>
    <fullName>ServiceStartDate__c</fullName>
    <label>Service Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RateCard__c/RateCard__c.object-meta.xml
<CustomObject>
    <label>Rate Card</label>
    <nameField>
        <label>Rate Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RateCard__c/fields/AssignedToAccountId__c.field-meta.xml
<CustomField>
    <fullName>AssignedToAccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned to Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assigned Rate Cards</relationshipLabel>
    <relationshipName>AssignedRateCards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RateCard__c/fields/AttributeGroupId__c.field-meta.xml
<CustomField>
    <fullName>AttributeGroupId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Attribute Group</label>
    <referenceTo>RateCardAttributeGroup__c</referenceTo>
    <relationshipLabel>Rate Cards</relationshipLabel>
    <relationshipName>RateCards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RateCard__c/fields/EffectiveDate__c.field-meta.xml
<CustomField>
    <fullName>EffectiveDate__c</fullName>
    <label>Effective Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RateCard__c/fields/ExpirationDate__c.field-meta.xml
<CustomField>
    <fullName>ExpirationDate__c</fullName>
    <label>Expiration Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RateCardAttribute__c/RateCardAttribute__c.object-meta.xml
<CustomObject>
    <label>Rate Card Attribute</label>
    <nameField>
        <label>Rate Card Attribute</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Card Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RateCardAttribute__c/fields/AttributeGroupId__c.field-meta.xml
<CustomField>
    <fullName>AttributeGroupId__c</fullName>
    <label>Attribute Group</label>
    <referenceTo>RateCardAttributeGroup__c</referenceTo>
    <relationshipLabel>Attributes</relationshipLabel>
    <relationshipName>RateCardAttributes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RateCardAttribute__c/fields/FieldAPIName__c.field-meta.xml
<CustomField>
    <fullName>FieldAPIName__c</fullName>
    <label>Field API Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RateCardAttribute__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <label>Sequence</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/RateCardService.cls
/**
 *  Provus Services Quoting
 *  @2021 Provus Inc. All rights reserved.
 */
public with sharing class RateCardService {
	// constants
	public static final String SOBJECT_NAME = 'RateCard__c';

	// runtime context
	public static RateCard__c rateCardSO;

	// constructor
	public RateCardService(Id rateCardId) {
		rateCardSO = [
			SELECT Id, AttributeGroupId__c
			FROM RateCard__c
			WHERE Id = :rateCardId
			WITH SECURITY_ENFORCED
			LIMIT 1
		];
	}

	/**
	 * Gets the list of attributes for a rate card
	 * @param
	 * @return Set<String>  list of attributes
	 */
	@AuraEnabled(cacheable=true)
	public static List<String> getAttributesFor(Id rateCardId) {
		Set<String> attributes = new Set<String>();
		for (RateCardAttribute__c att : [
			SELECT FieldAPIName__c, Sequence__c, AttributeGroupId__c
			FROM RateCardAttribute__c
			WHERE
				AttributeGroupId__c IN (SELECT AttributeGroupId__c FROM RateCard__c WHERE Id = :rateCardId)
			WITH SECURITY_ENFORCED
			ORDER BY Sequence__c ASC
		]) {
			attributes.add(att.FieldAPIName__c);
		}
		return new List<String>(attributes);
	}

	/**
	 * Gets the list of attributes for a rate card
	 * @param
	 * @return Set<String>  list of attributes
	 */
	public Set<String> getAttributes() {
		Set<String> attributes = new Set<String>();
		for (RateCardAttribute__c att : [
			SELECT FieldAPIName__c, Sequence__c, AttributeGroupId__c
			FROM RateCardAttribute__c
			WHERE AttributeGroupId__c = :rateCardSO.AttributeGroupId__c
			WITH SECURITY_ENFORCED
			ORDER BY Sequence__c ASC
		]) {
			attributes.add(att.FieldAPIName__c);
		}
		return attributes;
	}

	/**
	 * Gets the list of attributes for a rate card with their sequence
	 * @param
	 * @return Map<String, Decimal>  list of attributes
	 */
	public Map<String, Decimal> getAttributesWithSequence() {
		Map<String, Decimal> attributesWithSequence = new Map<String, Decimal>();
		for (RateCardAttribute__c att : [
			SELECT FieldAPIName__c, Sequence__c, AttributeGroupId__c
			FROM RateCardAttribute__c
			WHERE AttributeGroupId__c = :rateCardSO.AttributeGroupId__c
			WITH SECURITY_ENFORCED
			ORDER BY Sequence__c ASC
		]) {
			attributesWithSequence.put(att.FieldAPIName__c, att.Sequence__c);
		}
		return attributesWithSequence;
	}

	/**
	 * Checks if the rate card associated with a quote is expired or not
	 * @param
	 * @return Boolean true, if ratecard expired else false
	 */
	@AuraEnabled(cacheable=true)
	public static Map<Boolean, String> checkIfRateCardIsExpired(Id quoteId) {
		Map<Boolean, String> rateCardStatusMap = new Map<Boolean, String>();
		Boolean isExpired = true;
		Boolean isValidEffectiveDate;
		Boolean isValidExpirationDate;
		Boolean isActive;
		for (Quote__c quote : [
			SELECT
				Id,
				RateCardId__r.Name,
				AccountId__r.Name,
				RateCardId__r.EffectiveDate__c,
				RateCardId__r.ExpirationDate__c,
				RateCardId__r.IsActive__c,
				ServiceStartDate__c
			FROM Quote__c
			WHERE ID = :quoteId
			WITH SECURITY_ENFORCED
		]) {
			isValidEffectiveDate =
				quote.RateCardId__r.EffectiveDate__c == null ||
				quote.ServiceStartDate__c >= quote.RateCardId__r.EffectiveDate__c;
			isValidExpirationDate =
				quote.RateCardId__r.EffectiveDate__c == null ||
				quote.ServiceStartDate__c <= quote.RateCardId__r.ExpirationDate__c;
			isActive =
				quote.RateCardId__r.IsActive__c && quote.RateCardId__r.ExpirationDate__c >= Date.Today();
			isExpired = !(isValidEffectiveDate && isValidExpirationDate && isActive);
			rateCardStatusMap.put(isExpired, quote.AccountId__r.Name);
		}
		return rateCardStatusMap;
	}

	public static void overrideRateCardFromAssociatedAccount(List<Quote__c> newObjs) {
		Set<Id> accountId = new Set<Id>();
		List<Quote__c> quoteLst = new List<Quote__c>();
		for (Quote__c quote : (List<Quote__c>) newObjs) {
			if (quote.AccountId__c != null) {
				accountId.add(quote.AccountId__c);
				quotelst.add(quote);
			}
		}
		rateCardOverride(accountId, quoteLst);
	}

	public static void rateCardOverride(Set<Id> accountId, List<Quote__c> quoteLst) {
		Map<Id, RateCard__c> acctIdToRtMap = new Map<Id, RateCard__c>();
		for (RateCard__c rtCard : [
			SELECT AssignedToAccountId__c, Id
			FROM RateCard__c
			WHERE AssignedToAccountId__c IN :accountId
			WITH SECURITY_ENFORCED
			ORDER BY CreatedDate ASC
			LIMIT 1
		]) {
			acctIdToRtMap.put(rtCard.AssignedToAccountId__c, rtCard);
		}

		for (Quote__c qte : quoteLst) {
			if (acctIdToRtMap.containskey(qte.AccountId__c)) {
				qte.RateCardId__c = acctIdToRtMap.get(qte.AccountId__c).Id;
			}
		}
	}
}