force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteItem__c/QuoteItem__c.object-meta.xml
<CustomObject>
    <label>Quote Item</label>
    <nameField>
        <displayFormat>QI-{0000000}</displayFormat>
        <label>Quote Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteItem__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/QuoteItemTestsBase.cls
/**
 *  Provus Services Quoting
 *  QuoteItemTestsBase
 *  @2021 Provus Inc. All rights reserved.
 */
public with sharing abstract class QuoteItemTestsBase extends TestBase {
	public static QuoteItem__c newQuoteItemSO() {
		Quote__c testQuote = newQuote();
		QuoteItem__c newQuoteItem = new QuoteItem__c(QuoteId__c = testQuote.Id);
		CRUDUtility.insertRecords(newQuoteItem);
		return newQuoteItem;
	}

	public static QuoteItemDTO newQuoteItemDO(QuoteItem__c quoteItem) {
		QuoteItemDTO newDO = newQuoteItemDO(quoteItem.QuoteId__c);
		newDO.id = quoteItem.Id;
		newDO.quoteItemSO = quoteItem;
		return newDO;
	}

	public static QuoteItemDTO newQuoteItemDO() {
		Quote__c testQuote = newQuote();
		return newQuoteItemDO(testQuote.Id);
	}

	public static QuoteItemDTO newQuoteItemDO(Id quoteId) {
		QuoteItemDTO newQuoteItemDO = new QuoteItemDTO();
		newQuoteItemDO.quoteId = quoteId;
		newQuoteItemDO.lineSequence = 1;
		newQuoteItemDO.displaySequence = 1;
		newQuoteItemDO.quoteItemSO = new QuoteItem__c();
		newQuoteItemDO.periodValueMap = new Map<String, Decimal>();

		return newQuoteItemDO;
	}
}