force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/CurrencyConversionRatio__c.field-meta.xml
<CustomField>
    <fullName>CurrencyConversionRatio__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Currency Conversion Ratio</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/RateCardId__c.field-meta.xml
<CustomField>
    <fullName>RateCardId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate Card</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(3 OR 1) AND (4 OR 2) AND 5</booleanFilter>
        <errorMessage
		>The Rate Card is expired/inactive during the selected service start date</errorMessage>
        <filterItems>
            <field>$Source.ServiceStartDate__c</field>
            <operation>greaterOrEqual</operation>
            <valueField>RateCard__c.EffectiveDate__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.ServiceStartDate__c</field>
            <operation>lessOrEqual</operation>
            <valueField>RateCard__c.ExpirationDate__c</valueField>
        </filterItems>
        <filterItems>
            <field>RateCard__c.EffectiveDate__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <filterItems>
            <field>RateCard__c.ExpirationDate__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <filterItems>
            <field>RateCard__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>RateCard__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteItem__c/QuoteItem__c.object-meta.xml
<CustomObject>
    <label>Quote Item</label>
    <nameField>
        <displayFormat>QI-{0000000}</displayFormat>
        <label>Quote Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteItem__c/fields/AdjustedUnitCost__c.field-meta.xml
<CustomField>
    <fullName>AdjustedUnitCost__c</fullName>
    <label>Adjusted Unit Cost</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteItem__c/fields/AdjustedUnitPrice__c.field-meta.xml
<CustomField>
    <fullName>AdjustedUnitPrice__c</fullName>
    <label>Adjusted Unit Price</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteItem__c/fields/CurrencyConversionRatio__c.field-meta.xml
<CustomField>
    <fullName>CurrencyConversionRatio__c</fullName>
    <formula>QuoteId__r.CurrencyConversionRatio__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Currency Conversion Ratio</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteItem__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QuoteItem__c/fields/UnitCost__c.field-meta.xml
<CustomField>
    <fullName>UnitCost__c</fullName>
    <label>Unit Cost</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteItem__c/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/RateCard__c/RateCard__c.object-meta.xml
<CustomObject>
    <label>Rate Card</label>
    <nameField>
        <label>Rate Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/MultiCurrencyService.cls
/**
 *  Provus Services Quoting
 *  MultiCurrencyService
 *  @2021 Provus Inc. All rights reserved.
 */
public with sharing class MultiCurrencyService {
	public static final String ISO_CODE = 'IsoCode';
	public static final String CURRENCY_ISO_CODE = 'CurrencyIsoCode';
	public static final String CONVERSION_RATE = 'ConversionRate';

	public class CurrencyFields {
		public String currencyISOCode;
		public Decimal currencyConversionRatio;
	}

	public static Boolean isMultiCurrencyEnabled() {
		return UserInfo.isMultiCurrencyOrganization();
	}

	public static void preventCurrencyChange(List<Quote__c> quotes, Map<Id, Quote__c> oldQuotes) {
		for (Quote__c quote : quotes) {
			if (quote.get(CURRENCY_ISO_CODE) != oldQuotes.get(quote.Id).get(CURRENCY_ISO_CODE)) {
				quote.addError(CURRENCY_ISO_CODE, System.Label.QuoteCurrencyValidationMessage);
			}
		}
	}

	public static void assignCurrencyConversionRatio(List<Quote__c> quotes) {
		Map<String, SObject> currencyMap = new Map<String, SObject>();
		for (
			SObject currencyType : Database.query(
				'SELECT Id, IsCorporate, IsoCode, ConversionRate, DecimalPlaces FROM CurrencyType WHERE IsActive = true'
			)
		) {
			currencyMap.put((String) currencyType.get(ISO_CODE), currencyType);
		}

		Set<Id> rateCards = new Set<Id>();
		for (Quote__c quote : quotes) {
			if (quote.RateCardId__c != null) {
				rateCards.add(quote.RateCardId__c);
			}
		}

		if (!rateCards.isEmpty()) {
			QueryRequest queryRequest = new QueryRequest(Schema.RateCard__c.SObjectType);
			queryRequest.requestedFields = new Set<String>{ SObjectUtility.FIELD_ID, CURRENCY_ISO_CODE };
			queryRequest.setFilterBy(new Map<String, Set<Id>>{ SObjectUtility.FIELD_ID => rateCards });
			List<RateCard__c> rateCardRecords = SOQLUtility.querySObject(queryRequest);

			Map<Id, RateCard__c> rateCardMap = new Map<Id, RateCard__c>(rateCardRecords);

			for (Quote__c quote : quotes) {
				if (
					quote.RateCardId__c != null &&
					(String) rateCardMap.get(quote.RateCardId__c).get(CURRENCY_ISO_CODE) !=
					(String) quote.get(CURRENCY_ISO_CODE)
				) {
					quote.CurrencyConversionRatio__c =
						(Decimal) currencyMap.get((String) quote.get(CURRENCY_ISO_CODE)).get(CONVERSION_RATE) /
						(Decimal) currencyMap.get(
								(String) rateCardMap.get(quote.RateCardId__c).get(CURRENCY_ISO_CODE)
							)
							.get(CONVERSION_RATE);
				}
			}
		}
	}

	public static void syncQuoteCurrency(List<QuoteItem__c> quoteItems) {
		Set<Id> quoteIds = new Set<Id>();
		for (QuoteItem__c quoteItem : quoteItems) {
			quoteIds.add(quoteItem.QuoteId__c);
		}

		QueryRequest queryRequest = new QueryRequest(Schema.Quote__c.SObjectType);
		queryRequest.requestedFields = new Set<String>{ SObjectUtility.FIELD_ID, CURRENCY_ISO_CODE };
		queryRequest.setFilterBy(new Map<String, Set<Id>>{ SObjectUtility.FIELD_ID => quoteIds });
		List<Quote__c> quotes = SOQLUtility.querySObject(queryRequest);
		Map<Id, Quote__c> quotesMap = new Map<Id, Quote__c>(quotes);

		for (QuoteItem__c quoteItem : quoteItems) {
			quoteItem.put(
				CURRENCY_ISO_CODE,
				(String) quotesMap.get(quoteItem.QuoteId__c).get(CURRENCY_ISO_CODE)
			);
		}
	}

	public static void updateCurrencyFields(
		List<QuoteItem__c> quoteItems,
		Map<Id, QuoteItem__c> oldQuoteItems
	) {
		List<String> apiNames = new List<String>{
			Schema.QuoteItem__c.UnitCost__c + '',
			Schema.QuoteItem__c.UnitPrice__c + '',
			Schema.QuoteItem__c.AdjustedUnitCost__c + '',
			Schema.QuoteItem__c.AdjustedUnitPrice__c + ''
		};

		for (QuoteItem__c quoteItem : quoteItems) {
			for (String apiName : apiNames) {
				if (
					quoteItem.get(apiName) != oldQuoteItems.get(quoteItem.Id).get(apiName) &&
					oldQuoteItems.get(quoteItem.Id).get(apiName) == null
				) {
					quoteItem.put(
						apiName,
						(Decimal) quoteItem.get(apiName) * quoteItem.CurrencyConversionRatio__c
					);
				}
			}
		}
	}
}