force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/DerivedFromId__c.field-meta.xml
<CustomField>
    <fullName>DerivedFromId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Derived From</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Versions</relationshipLabel>
    <relationshipName>QuoteVersions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/IsPrimary__c.field-meta.xml
<CustomField>
    <fullName>IsPrimary__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
                <isActive>false</isActive>
                <label>Archived</label>
            </value>
            <value>
                <fullName>Contract Negotiation</fullName>
                <isActive>false</isActive>
                <label>Contract Negotiation</label>
            </value>
            <value>
                <fullName>Contracted</fullName>
                <isActive>false</isActive>
                <label>Contracted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&apos;Quote&apos;</defaultValue>
    <description>Indicates the type of quote.</description>
    <inlineHelpText>Indicates the type of quote.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Collaboration</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Scenario</fullName>
            </value>
            <value>
                <fullName>Template</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RelatedQuoteScenariosController.cls
public with sharing class RelatedQuoteScenariosController {
	@AuraEnabled
	public static List<Quote__c> getScenarios(string quoteId) {
		List<Quote__c> quoteRecords = new List<Quote__c>();

		Quote__c recordDetails = [
			SELECT
				Id,
				Name,
				Type__c,
				AccountId__r.Name,
				AccountId__c,
				IsPrimary__c,
				MarginPercent__c,
				TotalAmount__c,
				DerivedFromId__c,
				TotalCost__c,
				CreatedDate
			FROM Quote__c
			WHERE Id = :quoteId
			WITH SECURITY_ENFORCED
		];

		Id queryValue;

		if (
			recordDetails.Type__c == QuoteService.RECORDTYPE_NAME_QUOTE ||
			recordDetails.Type__c == QuoteService.RECORDTYPE_NAME_COLLABORATION
		) {
			queryValue = quoteId;
		} else if (recordDetails.Type__c == QuoteService.RECORDTYPE_NAME_SCENARIO) {
			queryValue = recordDetails.DerivedFromId__c;
			Quote__c originalQuote = [
				SELECT
					Id,
					Name,
					Type__c,
					AccountId__r.Name,
					AccountId__c,
					IsPrimary__c,
					MarginPercent__c,
					TotalAmount__c,
					DerivedFromId__c,
					TotalCost__c,
					CreatedDate
				FROM Quote__c
				WHERE Id = :recordDetails.DerivedFromId__c
				WITH SECURITY_ENFORCED
			];
			quoteRecords.add(originalQuote);
		} else {
			throw new ApplicationException(
				'Quote Type: ' +
				recordDetails.Type__c +
				', does not support scenarios.'
			);
		}
		quoteRecords.AddAll(
			[
				SELECT
					Id,
					Name,
					Type__c,
					AccountId__r.Name,
					AccountId__c,
					IsPrimary__c,
					MarginPercent__c,
					TotalAmount__c,
					DerivedFromId__c,
					TotalCost__c,
					CreatedDate
				FROM Quote__c
				WHERE
					DerivedFromId__c = :queryValue
					AND Id != :quoteId
					AND Status__c = :QuoteService.STATUS_ACTIVE
				WITH SECURITY_ENFORCED
				ORDER BY CreatedDate DESC
			]
		);

		return quoteRecords;
	}
}