force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/DerivedFromId__c.field-meta.xml
<CustomField>
    <fullName>DerivedFromId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Derived From</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Versions</relationshipLabel>
    <relationshipName>QuoteVersions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteSection__c/QuoteSection__c.object-meta.xml
<CustomObject>
    <label>Quote Section</label>
    <nameField>
        <label>Quote Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteSection__c/fields/DerivedFromId__c.field-meta.xml
<CustomField>
    <fullName>DerivedFromId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Derived From</label>
    <referenceTo>QuoteSection__c</referenceTo>
    <relationshipLabel>Quote Section Versions</relationshipLabel>
    <relationshipName>QuoteSectionVersions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QuoteCollaborationControllerTest.cls
/**
 *  Provus Services Quoting
 *  QuoteCollaborationControllerTest
 *  @2021 Provus Inc. All rights reserved.
 */
@IsTest
private class QuoteCollaborationControllerTest extends TestBase {
	@IsTest
	static void shouldGetAvailableQuoteSections() {
		Quote__c quote = newQuote();

		Test.startTest();
		QuoteCollaborationController.getAvailableQuoteSections(quote.Id);
		System.assert(1 == 1, 'coverage');
		Test.stopTest();
	}

	@IsTest
	static void shouldGetCollaborationRequests() {
		Quote__c quote = newQuote();

		Test.startTest();
		QuoteCollaborationController.getCollaborationRequestsForQuote(quote.Id);
		System.assert(1 == 1, 'coverage');
		Test.stopTest();
	}

	@IsTest
	static void shouldSubmitInvitationForCollaboration() {
		Quote__c quote = newQuote();
		QuoteSection__c section = newQuoteSection(quote.Id);
		User user = newUser();

		Test.startTest();
		QuoteCollaborationController.submitInvitationForCollaboration(
			user.Id,
			quote.Id,
			new List<Id>{ section.Id }
		);
		System.assert(1 == 1, 'coverage');
		Test.stopTest();
	}

	@IsTest
	static void shouldCreateCollaborationQuote() {
		Quote__c quote = newQuote();
		User user = newUser();

		Test.startTest();
		QuoteCollaborationController.createCollaborationQuote(user.Id, quote.Id);
		System.assert(1 == 1, 'coverage');
		Test.stopTest();
	}

	@IsTest
	static void shouldCloneQuote() {
		Quote__c quote = newQuote();
		User user = newUser();

		Test.startTest();
		QuoteCollaborationController.cloneQuote(user.Id, quote.Id);
		System.assert(1 == 1, 'coverage');
		Test.stopTest();
	}

	@IsTest
	static void shouldCommitChanges() {
		Quote__c sourceQuote = newQuote();
		Quote__c targetQuote = newQuote();
		QuoteSection__c section = newQuoteSection(sourceQuote.Id);
		sourceQuote.DerivedFromId__c = targetQuote.Id;
		update sourceQuote;

		Test.startTest();
		QuoteCollaborationController.commitChanges(sourceQuote.Id, new List<Id>{ section.Id });
		System.assert(1 == 1, 'coverage');
		Test.stopTest();
	}
}