force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Practice__c.field-meta.xml
<CustomField>
    <fullName>Practice__c</fullName>
    <label>Practice</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Practices</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/ProfitAmount__c.field-meta.xml
<CustomField>
    <fullName>ProfitAmount__c</fullName>
    <label>Profit Amount</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/QuoteDate__c.field-meta.xml
<CustomField>
    <fullName>QuoteDate__c</fullName>
    <label>Quote Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/RateCardId__c.field-meta.xml
<CustomField>
    <fullName>RateCardId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate Card</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(3 OR 1) AND (4 OR 2) AND 5</booleanFilter>
        <errorMessage
		>The Rate Card is expired/inactive during the selected service start date</errorMessage>
        <filterItems>
            <field>$Source.ServiceStartDate__c</field>
            <operation>greaterOrEqual</operation>
            <valueField>RateCard__c.EffectiveDate__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.ServiceStartDate__c</field>
            <operation>lessOrEqual</operation>
            <valueField>RateCard__c.ExpirationDate__c</valueField>
        </filterItems>
        <filterItems>
            <field>RateCard__c.EffectiveDate__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <filterItems>
            <field>RateCard__c.ExpirationDate__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <filterItems>
            <field>RateCard__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>RateCard__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/ServiceEndDate__c.field-meta.xml
<CustomField>
    <fullName>ServiceEndDate__c</fullName>
    <label>Service End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/ServiceId__c.field-meta.xml
<CustomField>
    <fullName>ServiceId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>ServiceQuotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/ServiceStartDate__c.field-meta.xml
<CustomField>
    <fullName>ServiceStartDate__c</fullName>
    <label>Service Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/TimePeriod__c.field-meta.xml
<CustomField>
    <fullName>TimePeriod__c</fullName>
    <label>Time Periods</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Months</fullName>
            </value>
            <value>
                <fullName>Days</fullName>
            </value>
            <value>
                <fullName>Weeks</fullName>
            </value>
            <value>
                <fullName>Quarters</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/TimePeriodsAlignment__c.field-meta.xml
<CustomField>
    <fullName>TimePeriodsAlignment__c</fullName>
    <label>Time Periods Alignment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User Defined Calendar</fullName>
            </value>
            <value>
                <fullName>Calendar</fullName>
            </value>
            <value>
                <fullName>Service Start</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/TimePeriodsGroupMethod__c.field-meta.xml
<CustomField>
    <fullName>TimePeriodsGroupMethod__c</fullName>
    <label>Time Periods Group Method</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>TimePeriod__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Year</fullName>
            </value>
            <value>
                <fullName>Quarter</fullName>
            </value>
            <value>
                <fullName>Month</fullName>
            </value>
            <value>
                <fullName>Week</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/globalValueSets/Groups.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Salesforce Implementation</fullName>
    </customValue>
    <customValue>
        <fullName>SAP Implementation</fullName>
    </customValue>
    <customValue>
        <fullName>Web &amp; Mobile Apps</fullName>
    </customValue>
    <customValue>
        <fullName>Java</fullName>
    </customValue>
    <customValue>
        <fullName>.Net</fullName>
    </customValue>
    <customValue>
        <fullName>Sales Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>Service Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>SFDC Integration</fullName>
    </customValue>
    <customValue>
        <fullName>SAP C/4 HANA CUSTOMER EXP</fullName>
    </customValue>
    <customValue>
        <fullName>SAP S/4 HANA CLOUD ERP</fullName>
    </customValue>
    <customValue>
        <fullName>SAP SUCCESS FACTORS</fullName>
    </customValue>
    <customValue>
        <fullName>SAP ARIBA</fullName>
    </customValue>
    <customValue>
        <fullName>SAP BUSINESS OBJECTS</fullName>
    </customValue>
    <customValue>
        <fullName>SAP ACTIVATE</fullName>
    </customValue>
    <customValue>
        <fullName>SAP CLOUD PLATFORM Integration</fullName>
    </customValue>
    <customValue>
        <fullName>Oracle Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>Oracle Infrastructure</fullName>
    </customValue>
    <customValue>
        <fullName>Oracle Live</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Web Services Basics</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Computer Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Network Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Storage Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Database Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Analytics Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Application Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Web Services Resources</fullName>
    </customValue>
    <customValue>
        <fullName>AI + Machine Learning</fullName>
    </customValue>
    <customValue>
        <fullName>Analytics</fullName>
    </customValue>
    <customValue>
        <fullName>Blockchain</fullName>
    </customValue>
    <masterLabel>Groups</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Practices.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Custom Development</fullName>
        <label>Web Development</label>
    </customValue>
    <customValue>
        <fullName>Cloud Consulting</fullName>
    </customValue>
    <customValue>
        <fullName>Outsourcing</fullName>
    </customValue>
    <customValue>
        <fullName>AWS</fullName>
    </customValue>
    <customValue>
        <fullName>GCP</fullName>
    </customValue>
    <customValue>
        <fullName>DevOps</fullName>
    </customValue>
    <customValue>
        <fullName>Java</fullName>
    </customValue>
    <customValue>
        <fullName>Python</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>SAP</fullName>
    </customValue>
    <customValue>
        <fullName>SFDC</fullName>
    </customValue>
    <customValue>
        <fullName>Oracle</fullName>
    </customValue>
    <customValue>
        <fullName>CI/CD</fullName>
    </customValue>
    <customValue>
        <fullName>ERP</fullName>
        <isActive>false</isActive>
        <label>ERP</label>
    </customValue>
    <customValue>
        <fullName>CRM</fullName>
        <isActive>false</isActive>
        <label>CRM</label>
    </customValue>
    <masterLabel>Practices</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CreateQuoteFromTemplateController.cls
public with sharing class CreateQuoteFromTemplateController {
	@AuraEnabled
	public static Quote__c retrieveQuoteTemplateDetails(Id selectedTemplateId) {
		return [
			SELECT
				Id,
				Name,
				ServiceStartDate__c,
				ServiceEndDate__c,
				AccountId__c,
				OpportunityId__c,
				TimePeriod__c,
				TimePeriodsAlignment__c,
				TimePeriodsGroupMethod__c,
				RateCardId__c,
				Practice__c,
				Group__c,
				MarginPercent__c,
				PriceUOM__c,
				ProfitAmount__c,
				QuoteDate__c,
				ServiceId__c,
				TotalAmount__c,
				TotalCost__c
			FROM Quote__c
			WHERE Id = :selectedTemplateId
			WITH SECURITY_ENFORCED
		];
	}

	@AuraEnabled
	public static String computeNewEndDate(Id selectedTemplateId, String newStartDate) {
		Date newStart = Date.valueOf(newStartDate);

		Quote__c selectedTemplate = [
			SELECT ServiceStartDate__c, ServiceEndDate__c
			FROM Quote__c
			WHERE Id = :selectedTemplateId
			WITH SECURITY_ENFORCED
			LIMIT 1
		];

		Date newEndDate = newStart.addDays(
			selectedTemplate.ServiceStartDate__c.daysBetween(selectedTemplate.ServiceEndDate__c)
		);
		return JSON.serialize(newEndDate);
	}

	@AuraEnabled(cacheable=true)
	public static Opportunity getOpportunityDetails(String opportunityId) {
		Opportunity oppData;
		try {
			QueryRequest queryRequest = new QueryRequest(Schema.SObjectType.Opportunity.getName());
			queryRequest.requestedFields = new Set<String>{ Schema.Opportunity.AccountId + '' };
			queryRequest.setFilterBy(new Map<String, String>{ SObjectUtility.FIELD_ID => opportunityId });
			List<Opportunity> opportunities = SOQLUtility.querySObject(queryRequest);
			if (!opportunities.isEmpty()) {
				oppData = opportunities[0];
			}
		} catch (Exception e) {
			throw new AuraHandledException(e.getMessage());
		}
		return oppData;
	}
}