force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Practice__c.field-meta.xml
<CustomField>
    <fullName>Practice__c</fullName>
    <label>Practice</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Practices</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteItem__c/QuoteItem__c.object-meta.xml
<CustomObject>
    <label>Quote Item</label>
    <nameField>
        <displayFormat>QI-{0000000}</displayFormat>
        <label>Quote Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteItem__c/fields/AdjustedUnitPrice__c.field-meta.xml
<CustomField>
    <fullName>AdjustedUnitPrice__c</fullName>
    <label>Adjusted Unit Price</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteItem__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <description>The billing frequency associated with the recurring price</description>
    <label>Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Custom</fullName>
            </value>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Yearly</fullName>
            </value>
            <value>
                <fullName>Project Start</fullName>
            </value>
            <value>
                <fullName>Project End</fullName>
            </value>
            <value>
                <fullName>Phase End</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteItem__c/fields/PriceMethod__c.field-meta.xml
<CustomField>
    <fullName>PriceMethod__c</fullName>
    <description>The price method</description>
    <label>Price Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Per Head</fullName>
            </value>
            <value>
                <fullName>Flat Price</fullName>
            </value>
            <value>
                <fullName>% of Cost</fullName>
            </value>
            <value>
                <fullName>% of Revenue</fullName>
            </value>
            <value>
                <fullName>Non-Billable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuoteItem__c/fields/PriceMethodMarkdown__c.field-meta.xml
<CustomField>
    <fullName>PriceMethodMarkdown__c</fullName>
    <description>The price factor to apply to the Price Method for % of pricing</description>
    <label>Price Method Markdown</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/QuoteItem__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteItem__c/fields/UnitCost__c.field-meta.xml
<CustomField>
    <fullName>UnitCost__c</fullName>
    <label>Unit Cost</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteItem__c/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/globalValueSets/Groups.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Salesforce Implementation</fullName>
    </customValue>
    <customValue>
        <fullName>SAP Implementation</fullName>
    </customValue>
    <customValue>
        <fullName>Web &amp; Mobile Apps</fullName>
    </customValue>
    <customValue>
        <fullName>Java</fullName>
    </customValue>
    <customValue>
        <fullName>.Net</fullName>
    </customValue>
    <customValue>
        <fullName>Sales Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>Service Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>SFDC Integration</fullName>
    </customValue>
    <customValue>
        <fullName>SAP C/4 HANA CUSTOMER EXP</fullName>
    </customValue>
    <customValue>
        <fullName>SAP S/4 HANA CLOUD ERP</fullName>
    </customValue>
    <customValue>
        <fullName>SAP SUCCESS FACTORS</fullName>
    </customValue>
    <customValue>
        <fullName>SAP ARIBA</fullName>
    </customValue>
    <customValue>
        <fullName>SAP BUSINESS OBJECTS</fullName>
    </customValue>
    <customValue>
        <fullName>SAP ACTIVATE</fullName>
    </customValue>
    <customValue>
        <fullName>SAP CLOUD PLATFORM Integration</fullName>
    </customValue>
    <customValue>
        <fullName>Oracle Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>Oracle Infrastructure</fullName>
    </customValue>
    <customValue>
        <fullName>Oracle Live</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Web Services Basics</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Computer Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Network Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Storage Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Database Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Analytics Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Application Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Web Services Resources</fullName>
    </customValue>
    <customValue>
        <fullName>AI + Machine Learning</fullName>
    </customValue>
    <customValue>
        <fullName>Analytics</fullName>
    </customValue>
    <customValue>
        <fullName>Blockchain</fullName>
    </customValue>
    <masterLabel>Groups</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Practices.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Custom Development</fullName>
        <label>Web Development</label>
    </customValue>
    <customValue>
        <fullName>Cloud Consulting</fullName>
    </customValue>
    <customValue>
        <fullName>Outsourcing</fullName>
    </customValue>
    <customValue>
        <fullName>AWS</fullName>
    </customValue>
    <customValue>
        <fullName>GCP</fullName>
    </customValue>
    <customValue>
        <fullName>DevOps</fullName>
    </customValue>
    <customValue>
        <fullName>Java</fullName>
    </customValue>
    <customValue>
        <fullName>Python</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>SAP</fullName>
    </customValue>
    <customValue>
        <fullName>SFDC</fullName>
    </customValue>
    <customValue>
        <fullName>Oracle</fullName>
    </customValue>
    <customValue>
        <fullName>CI/CD</fullName>
    </customValue>
    <customValue>
        <fullName>ERP</fullName>
        <isActive>false</isActive>
        <label>ERP</label>
    </customValue>
    <customValue>
        <fullName>CRM</fullName>
        <isActive>false</isActive>
        <label>CRM</label>
    </customValue>
    <masterLabel>Practices</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CustomMetadataServiceTest.cls
/**
 *  Provus Services Quoting
 *  CustomMetadataServiceTest
 *  @2021 Provus Inc. All rights reserved.
 */
@isTest
private class CustomMetadataServiceTest {
	@isTest
	static void itShouldGetTheProductDefaultFields() {
		Set<String> productFields = new CustomMetadataService().getProductDefaultFields();
		System.assert(productFields.size() == 4, 'there should be 4 product fields');
		System.assert(productFields.contains('Id'), 'Id should be one of the fields');
		System.assert(productFields.contains('Name'), 'Name should be one of the fields');
		System.assert(
			productFields.contains(Schema.Quote__c.Practice__c + ''),
			'Practice__c should be one of the fields'
		);
		System.assert(
			productFields.contains(Schema.Quote__c.Group__c + ''),
			'Group__c should be one of the fields'
		);
	}

	@isTest
	static void itShouldGetTheQuoteItemItemDefaultFields() {
		Set<String> quoteItemFields = new CustomMetadataService().getQuoteItemDefaultFields();
		System.assert(quoteItemFields.size() == 11, 'there should be 11 quote item fields');
		System.assert(quoteItemFields.contains('Id'), 'Id should be one of the fields');
		System.assert(
			quoteItemFields.contains(Schema.QuoteItem__c.AdjustedUnitPrice__c + ''),
			'AdjustedUnitPrice__c should be one of the fields'
		);
		System.assert(
			quoteItemFields.contains(Schema.QuoteItem__c.Frequency__c + ''),
			'Frequency__c should be one of the fields'
		);
		System.assert(
			quoteItemFields.contains(Schema.QuoteItem__c.MarginPercent__c + ''),
			'MarginPercent__c should be one of the fields'
		);
		System.assert(
			quoteItemFields.contains(Schema.QuoteItem__c.PriceMethod__c + ''),
			'PriceMethod__c should be one of the fields'
		);
		System.assert(
			quoteItemFields.contains(Schema.QuoteItem__c.PriceMethodMarkdown__c + ''),
			'PriceMethodMarkdown__c should be one of the fields'
		);
		System.assert(
			quoteItemFields.contains(Schema.QuoteItem__c.ProductId__c + ''),
			'ProductId__c should be one of the fields'
		);
		System.assert(
			quoteItemFields.contains(Schema.QuoteItem__c.SkillLevel__c + ''),
			'SkillLevel__c should be one of the fields'
		);
		System.assert(
			quoteItemFields.contains(Schema.QuoteItem__c.UnitCost__c + ''),
			'UnitCost__c should be one of the fields'
		);
		System.assert(
			quoteItemFields.contains(Schema.QuoteItem__c.UnitPrice__c + ''),
			'UnitPrice__c should be one of the fields'
		);
	}

	@isTest
	static void itShouldGetTheHiddenFields() {
		Set<String> hiddenFields = new CustomMetadataService().getHiddenFields();
		System.assert(hiddenFields.size() == 0, 'hidden fields should be empty');
	}

	@isTest
	static void itShouldGetTheRequiredFields() {
		Set<String> requiredFields = new CustomMetadataService().getRequiredFields();
		System.assert(requiredFields.size() == 0, 'required fields should be empty');
	}

	@isTest
	static void itShouldGetTheUneditableFields() {
		Set<String> uneditableFields = new CustomMetadataService().getUneditableFields();
		System.assert(uneditableFields.size() == 0, 'uneditable fields should be empty');
	}
}