force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/DerivedFromId__c.field-meta.xml
<CustomField>
    <fullName>DerivedFromId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Derived From</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Versions</relationshipLabel>
    <relationshipName>QuoteVersions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/IsPrimary__c.field-meta.xml
<CustomField>
    <fullName>IsPrimary__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
                <isActive>false</isActive>
                <label>Archived</label>
            </value>
            <value>
                <fullName>Contract Negotiation</fullName>
                <isActive>false</isActive>
                <label>Contract Negotiation</label>
            </value>
            <value>
                <fullName>Contracted</fullName>
                <isActive>false</isActive>
                <label>Contracted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&apos;Quote&apos;</defaultValue>
    <description>Indicates the type of quote.</description>
    <inlineHelpText>Indicates the type of quote.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Collaboration</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Scenario</fullName>
            </value>
            <value>
                <fullName>Template</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MakeScenarioPrimaryController.cls
/**
 *  Provus Services Quoting
 *  MakeScenarioPrimaryController
 *
 *  @2021 Provus Inc. All rights reserved.
 */
public with sharing class MakeScenarioPrimaryController {
	/**
	 * clone Sceanrio to Quote
	 * @param   quoteId Id of the quote
	 * @return  Quote Record Id
	 */
	@AuraEnabled
	public static string cloneScenarioToPrimaryQuote(String scenarioId) {
		Quote__c scenarioRecord = getScenarioRecord(scenarioId);
		Quote__c clonedQuote = cloneToQuoteRecordType(scenarioRecord);
		scenarioRecord.Status__c = 'Inactive';
		CRUDUtility.updateRecords(scenarioRecord);

		Quote__c derviedFromQuote = new Quote__c(
			Id = scenarioRecord.DerivedFromId__c,
			IsPrimary__c = false
		);
		CRUDUtility.updateRecords(derviedFromQuote);
		return clonedQuote.Id;
	}

	/**
	 * clone to Quote RecordType
	 * @param   Quote record
	 * @return  Quote Record of Quote type
	 */
	public static Quote__c cloneToQuoteRecordType(Quote__c scenarioRecord) {
		Quote__c clonedQuote = scenarioRecord.clone(false, false, false, false);
		clonedQuote.IsPrimary__c = true;
		clonedQuote.Type__c = QuoteService.RECORDTYPE_NAME_QUOTE;
		clonedQuote.DerivedFromId__c = null;
		CRUDUtility.insertRecords(clonedQuote);
		QuoteService.copyQuoteChildEntities(scenarioRecord.Id, clonedQuote.Id, null);
		return clonedQuote;
	}

	/**
	 * get Sceanrio record
	 * @param scenarioId Id of the scenario
	 *
	 * @return returns scenario quote record
	 */
	public static Quote__c getScenarioRecord(String scenarioId) {
		QueryRequest queryRequest = new QueryRequest(Schema.Quote__c.SObjectType);
		queryRequest.requestedFields = SObjectUtility.getFieldsForSObject(Schema.Quote__c.SObjectType);
		queryRequest.setFilterBy(new Map<String, String>{ SObjectUtility.FIELD_ID => scenarioId });
		List<Quote__c> scenarioRecords = (List<Quote__c>) SOQLUtility.querySObject(queryRequest);

		return !scenarioRecords.isEmpty() ? scenarioRecords[0] : null;
	}
}