force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/ServiceEndDate__c.field-meta.xml
<CustomField>
    <fullName>ServiceEndDate__c</fullName>
    <label>Service End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/ServiceStartDate__c.field-meta.xml
<CustomField>
    <fullName>ServiceStartDate__c</fullName>
    <label>Service Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/TimePeriod__c.field-meta.xml
<CustomField>
    <fullName>TimePeriod__c</fullName>
    <label>Time Periods</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Months</fullName>
            </value>
            <value>
                <fullName>Days</fullName>
            </value>
            <value>
                <fullName>Weeks</fullName>
            </value>
            <value>
                <fullName>Quarters</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/TimePeriodsAlignment__c.field-meta.xml
<CustomField>
    <fullName>TimePeriodsAlignment__c</fullName>
    <label>Time Periods Alignment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User Defined Calendar</fullName>
            </value>
            <value>
                <fullName>Calendar</fullName>
            </value>
            <value>
                <fullName>Service Start</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/TimePeriodsGroupMethod__c.field-meta.xml
<CustomField>
    <fullName>TimePeriodsGroupMethod__c</fullName>
    <label>Time Periods Group Method</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>TimePeriod__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Year</fullName>
            </value>
            <value>
                <fullName>Quarter</fullName>
            </value>
            <value>
                <fullName>Month</fullName>
            </value>
            <value>
                <fullName>Week</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QuotePeriod__c/QuotePeriod__c.object-meta.xml
<CustomObject>
    <label>Quote Period</label>
    <nameField>
        <label>Quote Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuotePeriod__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Periods</relationshipLabel>
    <relationshipName>QuotePeriods</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QuotePeriodGroup__c/QuotePeriodGroup__c.object-meta.xml
<CustomObject>
    <label>Quote Period Group</label>
    <nameField>
        <label>Quote Period Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Period Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuotePeriodGroup__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Period Groups</relationshipLabel>
    <relationshipName>QuotePeriodGroups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DefaultPeriodService.cls
public with sharing class DefaultPeriodService implements QuotePeriodService.IPeriodService {
	public static ScheduleSettingDTO scheduleSetting;
	static {
		scheduleSetting = SettingsService.getScheduleSettings();
	}

	public Map<QuotePeriodGroup__c, List<QuotePeriod__c>> generatePeriods(Quote__c quoteSO) {
		Id quoteId = quoteSO.Id;
		Date serviceStart = quoteSO.ServiceStartDate__c;
		Date serviceEnd = quoteSO.ServiceEndDate__c;
		String timePeriod = quoteSO.TimePeriod__c;
		String timePeriodAlignment = quoteSO.TimePeriodsAlignment__c;
		String timePeriodGroupMethod = quoteSO.TimePeriodsGroupMethod__c;
		Map<QuotePeriodGroup__c, List<QuotePeriod__c>> periodsByGroup = new Map<QuotePeriodGroup__c, List<QuotePeriod__c>>();
		ITimePeriod timePeriodCalc = TimePeriodFactory.newTimePeriod(timePeriod);
		ITimePeriod periodGroupCalc = TimePeriodFactory.newTimePeriod(timePeriodGroupMethod);

		// can't generate periods when they're not specified
		if (timePeriodCalc == null || periodGroupCalc == null) {
			return periodsByGroup;
		}

		Date groupStartDate = serviceStart;
		Date groupEndDate = periodGroupCalc.calculateGroupEndDate(
			groupStartDate,
			serviceEnd,
			timePeriodAlignment
		);

		Date periodStartDate = serviceStart;
		Date periodEndDate = timePeriodCalc.calculateEndDate(
			periodStartDate,
			serviceEnd,
			timePeriodAlignment
		);

		Integer groupSequence = 1;
		Integer periodSequence = 1;
		while (groupStartDate < serviceEnd) {
			QuotePeriodGroup__c groups = new QuotePeriodGroup__c();
			groups.QuoteId__c = quoteId;
			groups.Sequence__c = groupSequence;
			groups.Name = timePeriodGroupMethod + ' ' + groupSequence;
			groupSequence += 1;

			List<QuotePeriod__c> periods = new List<QuotePeriod__c>();
			while (periodStartDate <= groupEndDate) {
				if (periodSequence > QuotePeriodService.MAX_PERIOD_COUNT) {
					throw new ApplicationException(
						'Currently maximum of ' +
						String.valueOf(QuotePeriodService.MAX_PERIOD_COUNT) +
						' periods is supported.'
					);
				}

				QuotePeriod__c period = new QuotePeriod__c(
					Name = timePeriodCalc.generateName(periodStartDate, periodEndDate, periodSequence),
					QuoteId__c = quoteId,
					Sequence__c = periodSequence,
					StartDate__c = periodStartDate,
					EndDate__c = periodEndDate,
					Term__c = timePeriodCalc.calculateTerm(periodStartDate, periodEndDate)
				);

				periodSequence += 1;
				periods.add(period);

				periodStartDate = periodEndDate.addDays(1);
				periodEndDate = timePeriodCalc.calculateEndDate(periodStartDate, serviceEnd, null);
			}

			periodsByGroup.put(groups, periods);

			groupStartDate = groupEndDate.addDays(1);
			groupEndDate = periodGroupCalc.calculateGroupEndDate(
				groupStartDate,
				serviceEnd,
				timePeriodAlignment
			);
		}
		return periodsByGroup;
	}
}