force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/DerivedFromId__c.field-meta.xml
<CustomField>
    <fullName>DerivedFromId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Derived From</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Versions</relationshipLabel>
    <relationshipName>QuoteVersions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/IsPrimary__c.field-meta.xml
<CustomField>
    <fullName>IsPrimary__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
                <isActive>false</isActive>
                <label>Archived</label>
            </value>
            <value>
                <fullName>Contract Negotiation</fullName>
                <isActive>false</isActive>
                <label>Contract Negotiation</label>
            </value>
            <value>
                <fullName>Contracted</fullName>
                <isActive>false</isActive>
                <label>Contracted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&apos;Quote&apos;</defaultValue>
    <description>Indicates the type of quote.</description>
    <inlineHelpText>Indicates the type of quote.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Collaboration</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Scenario</fullName>
            </value>
            <value>
                <fullName>Template</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <label>Version</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CreateNewScenarioController.cls
/**
 *  Provus Services Quoting
 *  CreateNewScenario
 *
 *  @2021 Provus Inc. All rights reserved.
 */
public with sharing class CreateNewScenarioController {
	// constants
	private static final String REVENUE_ADJUSTMENT = 'Revenue Adjustment';
	private static final String MARGIN_ADJUSTMENT = 'Margin Adjustment';
	private static final String RULE_BASED_ADJUSTMENT = 'Rule-Based Adjustment';

	public class QuoteAdjustment {
		public String type;
		public String name;
		public Integer value;
	}

	/**
	 * Gets Quote details
	 * @param   quoteId Id of the quote
	 * @return  List<Quote__c>
	 */
	@AuraEnabled
	public static List<Quote__c> getQuoteDetails(Id quoteId) {
		Set<String> quoteFields = new Set<String>();
		quoteFields.add(Schema.Quote__c.AccountId__c + '');
		quoteFields.add(
			SystemUtility.getChildRName(Schema.Quote__c.AccountId__c, Schema.Quote__c.AccountId__r.Name)
		);
		quoteFields.add(Schema.Quote__c.MarginPercent__c + '');
		quoteFields.add(Schema.Quote__c.TotalAmount__c + '');

		QueryRequest queryRequest = new QueryRequest(Schema.Quote__c.SObjectType);
		queryRequest.requestedFields = quoteFields;
		queryRequest.setFilterBy(new Map<String, String>{ 'Id' => quoteId });
		List<Quote__c> quotes = (List<Quote__c>) SOQLUtility.querySObject(queryRequest);

		return quotes;
	}

	/**
	 * clone Quote to Scenario
	 * @param quoteId id of the quote
	 * @param adjustment
	 *
	 * @return returns Quote scenario record id
	 */
	@AuraEnabled
	public static String cloneQuoteToScenario(String quoteId, String adjustment) {
		QuoteAdjustment adjustmentDO = new QuoteAdjustment();
		adjustmentDO = (QuoteAdjustment) JSON.deserializeStrict(adjustment, QuoteAdjustment.class);

		Quote__c sourceQuote = [
			SELECT Id, DerivedFromId__c
			FROM Quote__c
			WHERE Id = :quoteId
			WITH SECURITY_ENFORCED
		];
		Quote__c scenarioRecord;
		scenarioRecord = QuoteService.cloneQuote(quoteId);

		scenarioRecord.Name = adjustmentDO.name;
		scenarioRecord.Status__c = 'Active';
		scenarioRecord.Version__c = 1;
		scenarioRecord.Type__c = QuoteService.RECORDTYPE_NAME_SCENARIO;

		scenarioRecord.IsPrimary__c = false;

		if (sourceQuote.DerivedFromId__c != null) {
			scenarioRecord.DerivedFromId__c = sourceQuote.DerivedFromId__c;
		}

		if (adjustmentDO.type.Equals(REVENUE_ADJUSTMENT)) {
			scenarioRecord.TotalAmount__c = Integer.ValueOf(adjustmentDO.value);
			scenarioRecord.MarginPercent__c = null;
		} else if (adjustmentDO.type.Equals(MARGIN_ADJUSTMENT)) {
			scenarioRecord.TotalAmount__c = null;
			scenarioRecord.MarginPercent__c = Integer.ValueOf(adjustmentDO.value);
		}

		CRUDUtility.updateRecords(scenarioRecord);

		return scenarioRecord.Id;
	}
}