force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/RateCardId__c.field-meta.xml
<CustomField>
    <fullName>RateCardId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate Card</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(3 OR 1) AND (4 OR 2) AND 5</booleanFilter>
        <errorMessage
		>The Rate Card is expired/inactive during the selected service start date</errorMessage>
        <filterItems>
            <field>$Source.ServiceStartDate__c</field>
            <operation>greaterOrEqual</operation>
            <valueField>RateCard__c.EffectiveDate__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.ServiceStartDate__c</field>
            <operation>lessOrEqual</operation>
            <valueField>RateCard__c.ExpirationDate__c</valueField>
        </filterItems>
        <filterItems>
            <field>RateCard__c.EffectiveDate__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <filterItems>
            <field>RateCard__c.ExpirationDate__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <filterItems>
            <field>RateCard__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>RateCard__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RateCard__c/RateCard__c.object-meta.xml
<CustomObject>
    <label>Rate Card</label>
    <nameField>
        <label>Rate Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RateCard__c/fields/AttributeGroupId__c.field-meta.xml
<CustomField>
    <fullName>AttributeGroupId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Attribute Group</label>
    <referenceTo>RateCardAttributeGroup__c</referenceTo>
    <relationshipLabel>Rate Cards</relationshipLabel>
    <relationshipName>RateCards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RateCardAttributeGroup__c/RateCardAttributeGroup__c.object-meta.xml
<CustomObject>
    <label>Rate Card Attribute Group</label>
    <nameField>
        <label>Rate Card Attribute Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Card Attribute Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RateCardItem__c/RateCardItem__c.object-meta.xml
<CustomObject>
    <label>Rate Card Item</label>
    <nameField>
        <displayFormat>RCI-{0000000}</displayFormat>
        <label>Rate Card Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Card Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RateCardItem__c/fields/RateCardId__c.field-meta.xml
<CustomField>
    <fullName>RateCardId__c</fullName>
    <label>Rate Card</label>
    <referenceTo>RateCard__c</referenceTo>
    <relationshipLabel>Rate Card Items</relationshipLabel>
    <relationshipName>RateCardItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RateCardItem__c/fields/SkillLevel__c.field-meta.xml
<CustomField>
    <fullName>SkillLevel__c</fullName>
    <label>Skill Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SkillLevels</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/SkillLevels.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>L1</fullName>
    </customValue>
    <customValue>
        <fullName>L2</fullName>
    </customValue>
    <customValue>
        <fullName>L3</fullName>
    </customValue>
    <masterLabel>Skill Levels</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RateCardServiceTest.cls
/**
 *  Provus Services Quoting
 *  RateCardServiceTest
 *  @2021 Provus Inc. All rights reserved.
 */
@isTest
private class RateCardServiceTest extends TestBase {
	@testSetup
	static void setup() {
		RateCardAttributeGroup__c rateCardAttributeGroup = newRateCardAttributeGroup();
		newRateCardAttribute(rateCardAttributeGroup.Id); // create attribute and related it to attribute group
		RateCard__c rateCard = newRateCard();
		rateCard.AttributeGroupId__c = rateCardAttributeGroup.Id;
		update rateCard;
	}

	@IsTest
	static void itShouldGetRateCard() {
		Test.startTest();
		RateCard__c rateCardSO = [
			SELECT Id
			FROM RateCard__c
			WHERE Name = 'Skill & Resource Location'
			LIMIT 1
		];
		RateCardService rateCardService = new RateCardService(rateCardSO.Id);
		System.assertNotEquals(rateCardService, null, 'should not be null');
		Test.stopTest();
	}

	@IsTest
	static void itShouldGetRateCardAttributes() {
		Test.startTest();
		RateCard__c rateCardSO = [
			SELECT Id
			FROM RateCard__c
			WHERE Name = 'Skill & Resource Location'
			WITH SECURITY_ENFORCED
			LIMIT 1
		];
		RateCardService rateCardService = new RateCardService(rateCardSO.Id);
		Set<String> attributes = rateCardService.getAttributes();
		System.assert(
			attributes.contains(Schema.RateCardItem__c.SkillLevel__c + ''),
			'should contain skill level as an attribute'
		);
		Test.stopTest();
	}

	@IsTest
	static void itShouldGetRateCardWithSequence() {
		Test.startTest();
		RateCard__c rateCardSO = [
			SELECT Id
			FROM RateCard__c
			WHERE Name = 'Skill & Resource Location'
			LIMIT 1
		];
		RateCardService rateCardService = new RateCardService(rateCardSO.Id);
		Map<String, Decimal> attributesWithSequence = rateCardService.getAttributesWithSequence();
		System.assertEquals(
			attributesWithSequence.get(Schema.RateCardItem__c.SkillLevel__c + ''),
			1,
			'should be the first attribute'
		);
		Test.stopTest();
	}

	@IsTest
	static void itShouldcheckIfRateCardIsExpired() {
		Test.startTest();
		RateCard__c rateCardSO = [
			SELECT Id
			FROM RateCard__c
			WHERE Name = 'Skill & Resource Location'
			LIMIT 1
		];

		Quote__c quoteSO = newQuote();
		quoteSO.RateCardId__c = rateCardSO.Id;
		Map<Boolean, String> rateCardStatusMap = RateCardService.checkIfRateCardIsExpired(quoteSO.Id);
		System.assertEquals(rateCardStatusMap.size(), 1, 'size should be one');
		Test.stopTest();
	}
}