force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/TemplateId__c.field-meta.xml
<CustomField>
    <fullName>TemplateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Template</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Quote must have a type of template</errorMessage>
        <filterItems>
            <field>Quote__c.Type__c</field>
            <operation>equals</operation>
            <value>Template</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quotes (Template)</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/TimePeriodsAlignment__c.field-meta.xml
<CustomField>
    <fullName>TimePeriodsAlignment__c</fullName>
    <label>Time Periods Alignment</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User Defined Calendar</fullName>
            </value>
            <value>
                <fullName>Calendar</fullName>
            </value>
            <value>
                <fullName>Service Start</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&apos;Quote&apos;</defaultValue>
    <description>Indicates the type of quote.</description>
    <inlineHelpText>Indicates the type of quote.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Collaboration</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Scenario</fullName>
            </value>
            <value>
                <fullName>Template</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CopyAsTemplateControllerTest.cls
/**
 *  Provus Services Quoting
 *  CopyAsTemplateControllerTest
 *  @2021 Provus Inc. All rights reserved.
 */
@IsTest
private class CopyAsTemplateControllerTest extends CopyTestsBase {
	@IsTest
	static void itShouldCopyTheQuoteFields() {
		Quote__c quoteToCopy = newQuote();

		Test.startTest();
		Quote__c copiedQuote = CopyAsTemplateController.copyAsTemplate(quoteToCopy.Id);
		System.assertEquals(
			quoteToCopy.TimePeriodsAlignment__c,
			copiedQuote.TimePeriodsAlignment__c,
			'Time Periods Alignment should be the same'
		);
		Test.stopTest();
	}

	@IsTest
	static void itShouldChangeTheRecordTypeToTemplate() {
		Quote__c quoteToCopy = newQuote();

		Test.startTest();
		Quote__c copiedQuote = CopyAsTemplateController.copyAsTemplate(quoteToCopy.Id);
		System.assertEquals(
			copiedQuote.Type__c,
			QuoteService.RECORDTYPE_NAME_TEMPLATE,
			'Record Type Id should be the same'
		);
		Test.stopTest();
	}

	@IsTest
	static void itShouldSetTheTemplateName() {
		Quote__c quoteToCopy = newQuote();

		Test.startTest();
		Quote__c copiedQuote = CopyAsTemplateController.copyAsTemplate(quoteToCopy.Id);

		quoteToCopy = [SELECT Name FROM Quote__c WHERE Id = :quoteToCopy.Id];
		System.assertEquals(
			copiedQuote.Name,
			'TEMPLATE FROM: ' + quoteToCopy.Name,
			'Name should be "TEMPLATE FROM: name'
		);
		Test.stopTest();
	}

	@IsTest
	static void itShouldClearSpecialFields() {
		Quote__c quoteToCopy = newQuote();
		Quote__c templateQuote = newTemplate();

		Account testAccount = new Account(Name = 'Test Account');
		CRUDUtility.insertRecords(testAccount);

		Opportunity testOpportunity = new Opportunity(Name = 'Test Opportunity', Account = testAccount);
		testOpportunity.CloseDate = System.Today();
		testOpportunity.StageName = 'Prospecting';
		CRUDUtility.insertRecords(testOpportunity);

		quoteToCopy.AccountId__c = testAccount.Id;
		quoteToCopy.OpportunityId__c = testOpportunity.Id;
		quoteToCopy.TemplateId__c = templateQuote.Id;
		quoteToCopy.Type__c = QuoteService.RECORDTYPE_NAME_TEMPLATE;

		CRUDUtility.updateRecords(quoteToCopy);

		Test.startTest();
		Quote__c copiedQuote = CopyAsTemplateController.copyAsTemplate(quoteToCopy.Id);

		System.assertEquals(copiedQuote.AccountId__c, null, 'Account Id should be null');
		System.assertEquals(copiedQuote.OpportunityId__c, null, 'Opportunity Id should be null');
		System.assertEquals(copiedQuote.TemplateId__c, null, 'Template Id should be null');
		Test.stopTest();
	}
}