force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteSection__c/QuoteSection__c.object-meta.xml
<CustomObject>
    <label>Quote Section</label>
    <nameField>
        <label>Quote Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteSection__c/fields/ParentQuoteSectionId__c.field-meta.xml
<CustomField>
    <fullName>ParentQuoteSectionId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Quote Section</label>
    <referenceTo>QuoteSection__c</referenceTo>
    <relationshipLabel>Child Quote Sections</relationshipLabel>
    <relationshipName>ParentQuoteSections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QuoteSectionServiceTest.cls
/*
 * Provus Services Quoting
 * Copyright (c) 2021 Provus Inc. All rights reserved.
 */
@IsTest
private class QuoteSectionServiceTest extends TestBase {
	@IsTest
	static void shouldNestSubsections() {
		Quote__c quoteSO = newQuote();
		QuoteSection__c rootSection = newQuoteSection(quoteSO.Id);
		QuoteSection__c nestedSection = newQuoteSection(quoteSO.Id);
		nestedSection.ParentQuoteSectionId__c = rootSection.Id;
		update nestedSection;

		Test.startTest();
		List<QuoteSectionDO> sections = QuoteSectionService.getQuoteSectionsForQuote(quoteSO.Id);
		System.assert(sections[0].childSections.size() > 0, 'should have a child section');
		Test.stopTest();
	}
}