force-app/main/default/objects/COLARate__c/COLARate__c.object-meta.xml
<CustomObject>
    <label>Cola Rate</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Cola Rate</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cola Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/COLARate__c/fields/RateSheetId__c.field-meta.xml
<CustomField>
    <fullName>RateSheetId__c</fullName>
    <label>Rate Sheet</label>
    <referenceTo>ColaRateSheet__c</referenceTo>
    <relationshipLabel>Cola Rates</relationshipLabel>
    <relationshipName>ColaRates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/COLARate__c/fields/YearOverYearRate__c.field-meta.xml
<CustomField>
    <fullName>YearOverYearRate__c</fullName>
    <label>Year Over Year Rate</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/COLARateSheet__c/COLARateSheet__c.object-meta.xml
<CustomObject>
    <label>Cola Rate Sheet</label>
    <nameField>
        <label>Cola Rate Sheet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cola Rate Sheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/COLARateSheet__c/fields/DerivedFromId__c.field-meta.xml
<CustomField>
    <fullName>DerivedFromId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Derived From</label>
    <referenceTo>ColaRateSheet__c</referenceTo>
    <relationshipLabel>Cola Rate Sheets</relationshipLabel>
    <relationshipName>ColaRateSheets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COLARateSheet__c/fields/YearOverYearRate__c.field-meta.xml
<CustomField>
    <fullName>YearOverYearRate__c</fullName>
    <label>Year Over Year Rate</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/ColaRateSheetCloneControllerTest.cls
@IsTest
private class ColaRateSheetCloneControllerTest extends ColaRateSheetTestBase {
	@TestSetup
	static void setupData() {
		ColaRateSheet__c rateSheet = newColaRateSheet();
		List<Product2> resourceRoles = createResourceRoles();
		createColaRates(rateSheet.Id, resourceRoles);
	}

	@IsTest
	static void itShouldCloneTheColaRateSheet() {
		ColaRateSheet__c colaRateSheet = [
			SELECT Id, Name, YearOverYearRate__c, DerivedFromId__c
			FROM ColaRateSheet__c
			WHERE Name = 'SFDC UT Rate Sheet'
		];

		ColaRateSheetCloneController.ColaRateSheetData cloneData = new ColaRateSheetCloneController.ColaRateSheetData();
		cloneData.name = 'SFDC UT Rate Sheet V1';
		cloneData.yearOverYearRate = 15.00;

		Test.startTest();
		Id clonedColaRateSheetId = ColaRateSheetCloneController.cloneColaRateSheet(
			colaRateSheet.Id,
			JSON.serialize(cloneData)
		);
		Test.stopTest();

		ColaRateSheet__c clonedColaRateSheet = [
			SELECT Id, Name, YearOverYearRate__c, DerivedFromId__c
			FROM ColaRateSheet__c
			WHERE Id = :clonedColaRateSheetId
		];

		System.assert(clonedColaRateSheetId != null, 'should clone Cola Rate Sheet Record');
		System.assertEquals(cloneData.name, clonedColaRateSheet.Name, 'should copy the name');
		System.assertEquals(
			cloneData.yearOverYearRate,
			clonedColaRateSheet.YearOverYearRate__c,
			'should copy the Year Over Year Rate'
		);
		System.assertEquals(
			[SELECT Id FROM ColaRate__c WHERE RateSheetId__c = :colaRateSheet.Id].size(),
			[SELECT Id FROM ColaRate__c WHERE RateSheetId__c = :clonedColaRateSheetId].size(),
			'should clone all the Cola Rates from Cola Rate Sheet'
		);
	}
}