force-app/main/default/objects/COLARate__c/COLARate__c.object-meta.xml
<CustomObject>
    <label>Cola Rate</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Cola Rate</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cola Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/COLARate__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/COLARate__c/fields/RateSheetId__c.field-meta.xml
<CustomField>
    <fullName>RateSheetId__c</fullName>
    <label>Rate Sheet</label>
    <referenceTo>ColaRateSheet__c</referenceTo>
    <relationshipLabel>Cola Rates</relationshipLabel>
    <relationshipName>ColaRates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/COLARate__c/fields/ResourceRoleId__c.field-meta.xml
<CustomField>
    <fullName>ResourceRoleId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Role</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource Role</value>
        </filterItems>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Cola Rates</relationshipLabel>
    <relationshipName>ColaRates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/COLARate__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>States</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/COLARate__c/fields/YearOverYearRate__c.field-meta.xml
<CustomField>
    <fullName>YearOverYearRate__c</fullName>
    <label>Year Over Year Rate</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/COLARateSheet__c/COLARateSheet__c.object-meta.xml
<CustomObject>
    <label>Cola Rate Sheet</label>
    <nameField>
        <label>Cola Rate Sheet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cola Rate Sheets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/COLARateSheet__c/fields/YearOverYearRate__c.field-meta.xml
<CustomField>
    <fullName>YearOverYearRate__c</fullName>
    <label>Year Over Year Rate</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/ResourceRole.recordType-meta.xml
<RecordType>
    <fullName>ResourceRole</fullName>
    <active>true</active>
    <label>Resource Role</label>
</RecordType>

force-app/main/default/globalValueSets/Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>United States</fullName>
    </customValue>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <masterLabel>Countries</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/States.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Andhra Pradesh</fullName>
    </customValue>
    <customValue>
        <fullName>Arunachal Pradesh</fullName>
    </customValue>
    <customValue>
        <fullName>Assam</fullName>
    </customValue>
    <customValue>
        <fullName>BIHAR</fullName>
    </customValue>
    <customValue>
        <fullName>Chandigarh</fullName>
    </customValue>
    <customValue>
        <fullName>Chhattisgarh</fullName>
    </customValue>
    <customValue>
        <fullName>Delhi</fullName>
    </customValue>
    <customValue>
        <fullName>Goa</fullName>
    </customValue>
    <customValue>
        <fullName>Gujarat</fullName>
    </customValue>
    <customValue>
        <fullName>Haryana</fullName>
    </customValue>
    <customValue>
        <fullName>Himachal Pradesh</fullName>
    </customValue>
    <customValue>
        <fullName>Jharkhand</fullName>
    </customValue>
    <customValue>
        <fullName>Karnataka</fullName>
    </customValue>
    <customValue>
        <fullName>Kerala</fullName>
    </customValue>
    <customValue>
        <fullName>Lakshadweep</fullName>
    </customValue>
    <customValue>
        <fullName>Madhya Pradesh</fullName>
    </customValue>
    <customValue>
        <fullName>Maharashtra</fullName>
    </customValue>
    <customValue>
        <fullName>Manipur</fullName>
    </customValue>
    <customValue>
        <fullName>Meghalaya</fullName>
    </customValue>
    <customValue>
        <fullName>Mizoram</fullName>
    </customValue>
    <customValue>
        <fullName>Nagaland</fullName>
    </customValue>
    <customValue>
        <fullName>ORISSA</fullName>
    </customValue>
    <customValue>
        <fullName>Puducherry</fullName>
    </customValue>
    <customValue>
        <fullName>Punjab</fullName>
    </customValue>
    <customValue>
        <fullName>Rajasthan</fullName>
    </customValue>
    <customValue>
        <fullName>Sikkim</fullName>
    </customValue>
    <customValue>
        <fullName>Tamil Nadu</fullName>
    </customValue>
    <customValue>
        <fullName>Tripura</fullName>
    </customValue>
    <customValue>
        <fullName>Uttar Pradesh</fullName>
    </customValue>
    <customValue>
        <fullName>Uttarakhand</fullName>
    </customValue>
    <customValue>
        <fullName>Ohio</fullName>
    </customValue>
    <masterLabel>States</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ColaRateSheetTestBase.cls
/**
 *  Provus Services Quoting
 *  ColaRateSheetTestsBase : This is Tests Base for cola rate sheet Object
 *  @2021 Provus Inc. All rights reserved.
 */
public with sharing abstract class ColaRateSheetTestBase extends TestBase {
	/**
	 * Create a Cola Rate Sheet record.
	 * @return  ColaRateSheet__c : Cloned Cola Rate Sheet Object
	 */
	public static ColaRateSheet__c newColaRateSheet() {
		ColaRateSheet__c rateSheet = new ColaRateSheet__c(
			Name = 'SFDC UT Rate Sheet',
			YearOverYearRate__c = 13.5
		);
		CRUDUtility.insertRecords(rateSheet);
		return rateSheet;
	}

	/**
	 * Creates set of resource roles for Cola Setup.
	 * @return  List<Product2> : List of Resource Roles
	 */
	public static List<Product2> createResourceRoles() {
		Id resourceRoleTypeId = SObjectUtility.getRecordTypeIdbyName('Product2', 'Resource Role');

		List<Product2> resourceRoles = new List<Product2>();
		resourceRoles.add(newProduct('Software Engineer', resourceRoleTypeId));
		resourceRoles.add(newProduct('Project Manager', resourceRoleTypeId));
		resourceRoles.add(newProduct('Configuration Engineer', resourceRoleTypeId));

		CRUDUtility.insertRecords(resourceRoles);
		return resourceRoles;
	}

	/**
	 * Create a Set od Cola Rate records.
	 * @param   Id of the Cola Rate Sheet Record
	 * @param   List<Product2> : List of Cola Rate Sheet Records
	 * @return  List<ColaRate__c> : List of Cola Rates Records
	 */
	public static List<ColaRate__c> createColaRates(
		Id colaRateSheetId,
		List<Product2> resourceRoles
	) {
		Map<String, object> colaRateValues = new Map<String, object>();
		colaRateValues.put('RateSheetId__c', colaRateSheetId);
		colaRateValues.put('Country__c', 'United States');
		colaRateValues.put('State__c', 'Ohio');
		colaRateValues.put('YearOverYearRate__c', 13.5);

		List<ColaRate__c> colaRates = new List<ColaRate__c>();
		for (Product2 resourceRole : resourceRoles) {
			colaRates.add(newColaRate(colaRateValues, resourceRole.Id));
		}

		return (List<ColaRate__c>) CRUDUtility.insertRecords(colaRates);
	}

	/**
	 * Create a cloned Cola Rate Sheet record.
	 * @param   Map<String, Object> of field values for Cola Rate Record
	 * @param   Id of the Cola Rate Sheet Record
	 * @return  String : Id of the Cloned Cola Rate Sheet
	 */
	public static ColaRate__c newColaRate(Map<String, Object> params, Id resourceRoleId) {
		ColaRate__c colaRate = new ColaRate__c(ResourceRoleId__c = resourceRoleId);
		for (String field : params.keySet()) {
			colaRate.put(field, params.get(field));
		}
		return colaRate;
	}
}