force-app/main/default/objects/ActivityGroup__c/ActivityGroup__c.object-meta.xml
<CustomObject>
    <label>Activity Group</label>
    <nameField>
        <label>Activity Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ActivityGroup__c/fields/EstimateId__c.field-meta.xml
<CustomField>
    <fullName>EstimateId__c</fullName>
    <label>Estimate</label>
    <referenceTo>Estimate__c</referenceTo>
    <relationshipLabel>Activity Groups</relationshipLabel>
    <relationshipName>ActivityGroups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Estimate__c/Estimate__c.object-meta.xml
<CustomObject>
    <label>Estimate</label>
    <nameField>
        <label>Estimate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estimates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ActivityGroupServiceTest.cls
/*
 * Provus Services Quoting
 * Copyright (c) 2022 Provus Inc. All rights reserved.
 */
@IsTest
private class ActivityGroupServiceTest {
	@IsTest
	static void shouldReturnApplicableGroups() {
		Estimate__c estimateSO = new Estimate__c();
		CRUDUtility.insertRecords(estimateSO);

		ActivityGroup__c groupSO1 = new ActivityGroup__c(EstimateId__c = estimateSO.Id);
		ActivityGroup__c groupSO2 = new ActivityGroup__c(
			EstimateId__c = estimateSO.Id,
			IsNotApplicable__c = true
		);
		CRUDUtility.insertRecords(new List<ActivityGroup__c>{ groupSO1, groupSO2 });

		Test.startTest();
		List<ActivityGroup__c> groups = ActivityGroupService.getApplicableGroups(estimateSO.Id);
		System.assertEquals(1, groups.size(), 'should return the 1 applicable group');
		Test.stopTest();
	}
}