force-app/main/default/objects/ActivityGroup__c/ActivityGroup__c.object-meta.xml
<CustomObject>
    <label>Activity Group</label>
    <nameField>
        <label>Activity Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ActivityGroup__c/fields/Guidance__c.field-meta.xml
<CustomField>
    <fullName>Guidance__c</fullName>
    <label>Guidance</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ActivityGroupTemplate__c/ActivityGroupTemplate__c.object-meta.xml
<CustomObject>
    <label>Activity Group Template</label>
    <nameField>
        <label>Activity Group Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Group Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ActivityGroupTest.cls
/*
 * Provus Services Quoting
 * Copyright (c) 2022 Provus Inc. All rights reserved.
 */
@IsTest
private class ActivityGroupTest {
	@IsTest
	static void shouldCopyFieldsFromTemplate() {
		ActivityGroupTemplate__c template = new ActivityGroupTemplate__c(
			Name = 'Test',
			Description__c = 'Test',
			Guidance__c = 'Test',
			Sequence__c = 1
		);

		Test.startTest();
		ActivityGroup__c groupSO = ActivityGroup.newSO(template);
		System.assertEquals(template.Name, groupSO.Name, 'should have the same name');
		System.assertEquals(
			template.Description__c,
			groupSO.Description__c,
			'should have the same description'
		);
		System.assertEquals(template.Guidance__c, groupSO.Guidance__c, 'should have the same guidance');
		System.assertEquals(template.Sequence__c, groupSO.Sequence__c, 'should have the same sequence');
		Test.stopTest();
	}
}