force-app/main/default/objects/ActivityGroup__c/ActivityGroup__c.object-meta.xml
<CustomObject>
    <label>Activity Group</label>
    <nameField>
        <label>Activity Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ActivityGroup__c/fields/EstimateId__c.field-meta.xml
<CustomField>
    <fullName>EstimateId__c</fullName>
    <label>Estimate</label>
    <referenceTo>Estimate__c</referenceTo>
    <relationshipLabel>Activity Groups</relationshipLabel>
    <relationshipName>ActivityGroups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ActivityGroup__c/fields/Guidance__c.field-meta.xml
<CustomField>
    <fullName>Guidance__c</fullName>
    <label>Guidance</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ActivityGroupTemplate__c/ActivityGroupTemplate__c.object-meta.xml
<CustomObject>
    <label>Activity Group Template</label>
    <nameField>
        <label>Activity Group Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Group Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ActivityGroupTemplate__c/fields/EstimateTemplateId__c.field-meta.xml
<CustomField>
    <fullName>EstimateTemplateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estimate Template</label>
    <referenceTo>EstimateTemplate__c</referenceTo>
    <relationshipLabel>Activity Groups</relationshipLabel>
    <relationshipName>ActivityGroups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ActivityTemplate__c/ActivityTemplate__c.object-meta.xml
<CustomObject>
    <label>Activity Template</label>
    <nameField>
        <label>Activity Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Estimate__c/Estimate__c.object-meta.xml
<CustomObject>
    <label>Estimate</label>
    <nameField>
        <label>Estimate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estimates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Estimate__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Estimate__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ProductId</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordTypeId</field>
            <operation>equals</operation>
            <value>Product</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Estimates</relationshipLabel>
    <relationshipName>ProductEstimates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Estimate__c/fields/RateCardId__c.field-meta.xml
<CustomField>
    <fullName>RateCardId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate Card</label>
    <referenceTo>RateCard__c</referenceTo>
    <relationshipLabel>Estimates</relationshipLabel>
    <relationshipName>Estimates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Estimate__c/fields/ServiceId__c.field-meta.xml
<CustomField>
    <fullName>ServiceId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.ProductId__c</field>
            <operation>equals</operation>
            <valueField>Product2.AssociatedProductId__c</valueField>
        </filterItems>
        <filterItems>
            <field>Product2.RecordTypeId</field>
            <operation>equals</operation>
            <value>Service</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Estimates</relationshipLabel>
    <relationshipName>ServiceEstimates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EstimateTemplate__c/EstimateTemplate__c.object-meta.xml
<CustomObject>
    <label>Estimate Template</label>
    <nameField>
        <label>Estimate Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estimate Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EstimateTemplate__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordTypeId</field>
            <operation>equals</operation>
            <value>Product</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Estimate Templates</relationshipLabel>
    <relationshipName>ProductEstimateTemplates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EstimateTemplate__c/fields/RateCardId__c.field-meta.xml
<CustomField>
    <fullName>RateCardId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate Card</label>
    <referenceTo>RateCard__c</referenceTo>
    <relationshipLabel>Estimate Templates</relationshipLabel>
    <relationshipName>EstimateTemplates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EstimateTemplate__c/fields/ServiceId__c.field-meta.xml
<CustomField>
    <fullName>ServiceId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.ProductId__c</field>
            <operation>equals</operation>
            <valueField>Product2.AssociatedProductId__c</valueField>
        </filterItems>
        <filterItems>
            <field>Product2.RecordTypeId</field>
            <operation>equals</operation>
            <value>Service</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Estimate Templates</relationshipLabel>
    <relationshipName>ServiceEstimateTemplates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CreateEstimateServiceTest.cls
@IsTest
private class CreateEstimateServiceTest extends EstimatorTestsBase {
	@testSetup
	static void setup() {
		EstimateTemplate__c estimateTemplate = newEstimateTemplate();
		List<ActivityGroupTemplate__c> activityGroupTemplates = createActivityGroupTemplates(
			estimateTemplate.Id
		);
		List<ActivityTemplate__c> activityTemplates = createActivityTemplates(activityGroupTemplates);
		List<Product2> resourceRoles = createResourceRoles();
		createTaskTemplates(activityTemplates, resourceRoles);
	}

	@IsTest
	static void createEstimateFromEstimateTemplateTest() {
		EstimateTemplate__c estimateTemplate = [
			SELECT
				Id,
				Name,
				Description__c,
				Guidance__c,
				IsActive__c,
				RateCardId__c,
				ProductId__c,
				ServiceId__c,
				ServiceId__r.Name
			FROM EstimateTemplate__c
			WHERE Name = 'CLM Development Estimate'
		];

		Test.startTest();
		Estimate__c estimate = Estimate.newSO(estimateTemplate);
		Test.stopTest();

		System.assertEquals(estimateTemplate.Name, estimate.Name, 'Estimate not configured properly');
		System.assertEquals(
			estimateTemplate.Description__c,
			estimate.Description__c,
			'Estimate not configured properly'
		);
	}

	@IsTest
	static void getActivityGroupsFromTemplateTest() {
		EstimateTemplate__c estimateTemplate = [
			SELECT
				Id,
				Name,
				Description__c,
				Guidance__c,
				IsActive__c,
				RateCardId__c,
				ProductId__c,
				ServiceId__c,
				ServiceId__r.Name,
				(
					SELECT Id, Name, Description__c, Guidance__c, Sequence__c
					FROM ActivityGroups__r
					WHERE IsActive__c = TRUE
				)
			FROM EstimateTemplate__c
			WHERE Name = 'CLM Development Estimate'
		];

		Test.startTest();
		Estimate__c estimate = Estimate.newSO(estimateTemplate);
		CRUDUtility.insertRecords(estimate);
		Map<Id, ActivityGroup__c> activitiesByTemplateId = CreateEstimateService.createActivityGroups(
			estimateTemplate.ActivityGroups__r,
			estimate.Id
		);
		Test.stopTest();

		System.assertEquals(
			estimateTemplate.ActivityGroups__r.size(),
			activitiesByTemplateId.values().size(),
			'Activities not configured properly'
		);
	}
}