force-app/main/default/objects/ActivityGroup__c/ActivityGroup__c.object-meta.xml
<CustomObject>
    <label>Activity Group</label>
    <nameField>
        <label>Activity Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ActivityGroup__c/fields/EstimateId__c.field-meta.xml
<CustomField>
    <fullName>EstimateId__c</fullName>
    <label>Estimate</label>
    <referenceTo>Estimate__c</referenceTo>
    <relationshipLabel>Activity Groups</relationshipLabel>
    <relationshipName>ActivityGroups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Estimate__c/Estimate__c.object-meta.xml
<CustomObject>
    <label>Estimate</label>
    <nameField>
        <label>Estimate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estimates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Estimate__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Estimates</relationshipLabel>
    <relationshipName>Estimates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Estimate__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Estimates</relationshipLabel>
    <relationshipName>Estimates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Estimate__c/fields/RateCardId__c.field-meta.xml
<CustomField>
    <fullName>RateCardId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate Card</label>
    <referenceTo>RateCard__c</referenceTo>
    <relationshipLabel>Estimates</relationshipLabel>
    <relationshipName>Estimates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Estimate__c/fields/ServiceId__c.field-meta.xml
<CustomField>
    <fullName>ServiceId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.ProductId__c</field>
            <operation>equals</operation>
            <valueField>Product2.AssociatedProductId__c</valueField>
        </filterItems>
        <filterItems>
            <field>Product2.RecordTypeId</field>
            <operation>equals</operation>
            <value>Service</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Estimates</relationshipLabel>
    <relationshipName>ServiceEstimates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Practice__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Practice__c.field-meta.xml
<CustomField>
    <fullName>Practice__c</fullName>
    <label>Practice</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Practices</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/EstimateId__c.field-meta.xml
<CustomField>
    <fullName>EstimateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estimate</label>
    <referenceTo>Estimate__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Practice__c.field-meta.xml
<CustomField>
    <fullName>Practice__c</fullName>
    <label>Practice</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Practices</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/QuoteDate__c.field-meta.xml
<CustomField>
    <fullName>QuoteDate__c</fullName>
    <label>Quote Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/RateCardId__c.field-meta.xml
<CustomField>
    <fullName>RateCardId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate Card</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(3 OR 1) AND (4 OR 2) AND 5</booleanFilter>
        <errorMessage
		>The Rate Card is expired/inactive during the selected service start date</errorMessage>
        <filterItems>
            <field>$Source.ServiceStartDate__c</field>
            <operation>greaterOrEqual</operation>
            <valueField>RateCard__c.EffectiveDate__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.ServiceStartDate__c</field>
            <operation>lessOrEqual</operation>
            <valueField>RateCard__c.ExpirationDate__c</valueField>
        </filterItems>
        <filterItems>
            <field>RateCard__c.EffectiveDate__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <filterItems>
            <field>RateCard__c.ExpirationDate__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <filterItems>
            <field>RateCard__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>RateCard__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/ServiceId__c.field-meta.xml
<CustomField>
    <fullName>ServiceId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>ServiceQuotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&apos;Quote&apos;</defaultValue>
    <description>Indicates the type of quote.</description>
    <inlineHelpText>Indicates the type of quote.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Collaboration</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Scenario</fullName>
            </value>
            <value>
                <fullName>Template</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <label>Version</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/TaskRoleSummary__c.object-meta.xml
<CustomObject>
    <label>Task Role Summary</label>
    <nameField>
        <displayFormat>TRS-{00000}</displayFormat>
        <label>Task Role Summary</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Role Summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TaskRoleSummary__c/fields/ActivityGroupId__c.field-meta.xml
<CustomField>
    <fullName>ActivityGroupId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity Group</label>
    <referenceTo>ActivityGroup__c</referenceTo>
    <relationshipName>RoleSummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/EstimateId__c.field-meta.xml
<CustomField>
    <fullName>EstimateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estimate</label>
    <referenceTo>Estimate__c</referenceTo>
    <relationshipName>RoleSummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/RolledUpEstimatedDuration__c.field-meta.xml
<CustomField>
    <fullName>RolledUpEstimatedDuration__c</fullName>
    <formula>RolledUpCalculatedDuration__c + RolledUpAdjustments__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rolled-Up Estimated Duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/globalValueSets/Groups.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Salesforce Implementation</fullName>
    </customValue>
    <customValue>
        <fullName>SAP Implementation</fullName>
    </customValue>
    <customValue>
        <fullName>Web &amp; Mobile Apps</fullName>
    </customValue>
    <customValue>
        <fullName>Java</fullName>
    </customValue>
    <customValue>
        <fullName>.Net</fullName>
    </customValue>
    <customValue>
        <fullName>Sales Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>Service Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>SFDC Integration</fullName>
    </customValue>
    <customValue>
        <fullName>SAP C/4 HANA CUSTOMER EXP</fullName>
    </customValue>
    <customValue>
        <fullName>SAP S/4 HANA CLOUD ERP</fullName>
    </customValue>
    <customValue>
        <fullName>SAP SUCCESS FACTORS</fullName>
    </customValue>
    <customValue>
        <fullName>SAP ARIBA</fullName>
    </customValue>
    <customValue>
        <fullName>SAP BUSINESS OBJECTS</fullName>
    </customValue>
    <customValue>
        <fullName>SAP ACTIVATE</fullName>
    </customValue>
    <customValue>
        <fullName>SAP CLOUD PLATFORM Integration</fullName>
    </customValue>
    <customValue>
        <fullName>Oracle Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>Oracle Infrastructure</fullName>
    </customValue>
    <customValue>
        <fullName>Oracle Live</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Web Services Basics</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Computer Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Network Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Storage Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Database Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Analytics Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Application Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Web Services Resources</fullName>
    </customValue>
    <customValue>
        <fullName>AI + Machine Learning</fullName>
    </customValue>
    <customValue>
        <fullName>Analytics</fullName>
    </customValue>
    <customValue>
        <fullName>Blockchain</fullName>
    </customValue>
    <masterLabel>Groups</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Practices.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Custom Development</fullName>
        <label>Web Development</label>
    </customValue>
    <customValue>
        <fullName>Cloud Consulting</fullName>
    </customValue>
    <customValue>
        <fullName>Outsourcing</fullName>
    </customValue>
    <customValue>
        <fullName>AWS</fullName>
    </customValue>
    <customValue>
        <fullName>GCP</fullName>
    </customValue>
    <customValue>
        <fullName>DevOps</fullName>
    </customValue>
    <customValue>
        <fullName>Java</fullName>
    </customValue>
    <customValue>
        <fullName>Python</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>SAP</fullName>
    </customValue>
    <customValue>
        <fullName>SFDC</fullName>
    </customValue>
    <customValue>
        <fullName>Oracle</fullName>
    </customValue>
    <customValue>
        <fullName>CI/CD</fullName>
    </customValue>
    <customValue>
        <fullName>ERP</fullName>
        <isActive>false</isActive>
        <label>ERP</label>
    </customValue>
    <customValue>
        <fullName>CRM</fullName>
        <isActive>false</isActive>
        <label>CRM</label>
    </customValue>
    <masterLabel>Practices</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CreateQuoteFromEstimateController.cls
/**
 *  Provus Services Quoting
 *  CreateQuoteFromEstimateController
 *  @2021 Provus Inc. All rights reserved.
 */
public with sharing class CreateQuoteFromEstimateController {
	@AuraEnabled(cacheable=true)
	public static QuoteDO getEstimateDetails(String estimateId) {
		//Required Fields from estimate
		Set<String> requiredFields = new Set<String>();
		requiredFields.add(Schema.Estimate__c.AccountId__c + '');
		requiredFields.add(Schema.Estimate__c.OpportunityId__c + '');
		requiredFields.add(Schema.Estimate__c.Description__c + '');
		requiredFields.add(Schema.Estimate__c.RateCardId__c + '');
		requiredFields.add(Schema.Estimate__c.ServiceId__c + '');
		requiredFields.add(
			SystemUtility.getRName(Schema.Estimate__c.ServiceId__c) +
			'.' +
			Schema.Product2.Practice__c
		);
		requiredFields.add(
			SystemUtility.getRName(Schema.Estimate__c.ServiceId__c) +
			'.' +
			Schema.Product2.Group__c
		);

		QueryRequest queryRequest = new QueryRequest(Schema.Estimate__c.SObjectType);
		queryRequest.requestedFields = requiredFields;
		queryRequest.setFilterBy(new Map<String, String>{ SObjectUtility.FIELD_ID => estimateId });
		List<Estimate__c> estimates = SOQLUtility.querySObject(queryRequest);

		QuoteDO quoteData;
		if (!estimates.isEmpty()) {
			Estimate__c estimateSO = estimates[0];
			quoteData = CreateQuoteFromEstimateService.getEstimateQuoteDetails(estimateSO);
		}
		return quoteData;
	}

	@AuraEnabled
	public static Date getServiceEndDate(Id estimateId, EndDateArgs endDateArgs) {
		Decimal totalDuration = 0;

		AggregateResult[] groupedRolledUpDurations = [
			SELECT ActivityGroupId__c, MAX(RolledUpEstimatedDuration__c) rolledUp
			FROM TaskRoleSummary__c
			WHERE ActivityGroupId__r.EstimateId__c IN (:estimateId) AND RolledUpEstimatedDuration__c > 0
			WITH SECURITY_ENFORCED
			GROUP BY ActivityGroupId__c
		];

		for (AggregateResult ar : groupedRolledUpDurations) {
			totalDuration += (Decimal) ar.get('rolledUp');
		}

		return DurationCalcs.endDate(totalDuration, endDateArgs);
	}

	@AuraEnabled
	public static Map<String, CreateQuoteFromEstimateService.ResourceRoleDetail> getResourceRoleData(
		String estimateId,
		String rateCardId
	) {
		return CreateQuoteFromEstimateService.getResourceRoles(estimateId, rateCardId);
	}

	@AuraEnabled
	public static Id createQuote(String quoteDetails, String rolePreferences) {
		QuoteDO quoteDate = (QuoteDO) JSON.deserialize(quoteDetails, QuoteDO.class);
		Map<Id, CreateQuoteFromEstimateService.ResourceRolePreferences> rolePrefs = (Map<Id, CreateQuoteFromEstimateService.ResourceRolePreferences>) JSON.deserialize(
			rolePreferences,
			Map<Id, CreateQuoteFromEstimateService.ResourceRolePreferences>.class
		);

		Quote__c quoteSO = QuoteDO.getQuoteFromData(quoteDate);
		quoteSO.QuoteDate__c = System.today();
		quoteSO.Version__c = 1;
		quoteSO.Type__c = QuoteService.RECORDTYPE_NAME_QUOTE;
		CRUDUtility.insertRecords(quoteSO);

		CreateQuoteFromEstimateService.convertEntitiesFromEstimate(quoteSO, rolePrefs);

		return quoteSO.Id;
	}
}