force-app/main/default/objects/ActivityGroup__c/ActivityGroup__c.object-meta.xml
<CustomObject>
    <label>Activity Group</label>
    <nameField>
        <label>Activity Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ActivityGroup__c/fields/EstimateId__c.field-meta.xml
<CustomField>
    <fullName>EstimateId__c</fullName>
    <label>Estimate</label>
    <referenceTo>Estimate__c</referenceTo>
    <relationshipLabel>Activity Groups</relationshipLabel>
    <relationshipName>ActivityGroups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/TaskRoleSummary__c.object-meta.xml
<CustomObject>
    <label>Task Role Summary</label>
    <nameField>
        <displayFormat>TRS-{00000}</displayFormat>
        <label>Task Role Summary</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Role Summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TaskRoleSummary__c/fields/ActivityGroupId__c.field-meta.xml
<CustomField>
    <fullName>ActivityGroupId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity Group</label>
    <referenceTo>ActivityGroup__c</referenceTo>
    <relationshipName>RoleSummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/EstimateId__c.field-meta.xml
<CustomField>
    <fullName>EstimateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estimate</label>
    <referenceTo>Estimate__c</referenceTo>
    <relationshipName>RoleSummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/ResourceRoleId__c.field-meta.xml
<CustomField>
    <fullName>ResourceRoleId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Role</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource Role</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipName>LevelSummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/RolledUpEstimatedDuration__c.field-meta.xml
<CustomField>
    <fullName>RolledUpEstimatedDuration__c</fullName>
    <formula>RolledUpCalculatedDuration__c + RolledUpAdjustments__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rolled-Up Estimated Duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/SummaryLevel__c.field-meta.xml
<CustomField>
    <fullName>SummaryLevel__c</fullName>
    <label>Summary Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Estimate</fullName>
            </value>
            <value>
                <fullName>Activity Group</fullName>
            </value>
            <value>
                <fullName>Activity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TaskRoleSummary.cls
public with sharing class TaskRoleSummary {
	public static final String NAME = 'TaskRoleSummary__c';
	public static final String RESOURCE_ROLE_ID = 'ResourceRoleId__c';
	public static final String ROLLEDUP_ESTIMATED_DURATION = 'RolledUpEstimatedDuration__c';
	public static final String ACTIVITY_GROUP_ID = 'ActivityGroupId__c';
	public static final String RELATED_ACTIVITY_GROUP_NAME = 'ActivityGroupId__r.Name';
	public static final String RELATED_ACTIVITY_GROUP_SEQUENCE = 'ActivityGroupId__r.Sequence__c';
	public static final String RELATED_ACTIVITY_GROUP_ESTIMATE_ID = 'ActivityGroupId__r.EstimateId__c';
	public static final String SUMMARY_LEVEL = 'SummaryLevel__c';
	public static final String ESTIMATE_ID = 'EstimateId__c';
	public static final String ESTIMATE_SUMMARY = 'Estimate';
	public static final String ACTIVITY_GROUP_SUMMARY = 'Activity Group';
}