force-app/main/default/objects/ActivityGroup__c/ActivityGroup__c.object-meta.xml
<CustomObject>
    <label>Activity Group</label>
    <nameField>
        <label>Activity Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CollaborationRequest__c/CollaborationRequest__c.object-meta.xml
<CustomObject>
    <label>Collaboration Request</label>
    <nameField>
        <displayFormat>CR-{00000}</displayFormat>
        <label>Collaboration Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Collaboration Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CollaborationRequest__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Collaboration Requests</relationshipLabel>
    <relationshipName>CollaborationRequests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteItem__c/QuoteItem__c.object-meta.xml
<CustomObject>
    <label>Quote Item</label>
    <nameField>
        <displayFormat>QI-{0000000}</displayFormat>
        <label>Quote Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteItem__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QuoteItem__c/fields/QuoteSectionId__c.field-meta.xml
<CustomField>
    <fullName>QuoteSectionId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Section</label>
    <referenceTo>QuoteSection__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteSection__c/QuoteSection__c.object-meta.xml
<CustomObject>
    <label>Quote Section</label>
    <nameField>
        <label>Quote Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteSection__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Sections</relationshipLabel>
    <relationshipName>QuoteSections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/TaskRoleSummary__c.object-meta.xml
<CustomObject>
    <label>Task Role Summary</label>
    <nameField>
        <displayFormat>TRS-{00000}</displayFormat>
        <label>Task Role Summary</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Role Summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TaskRoleSummary__c/fields/ActivityGroupId__c.field-meta.xml
<CustomField>
    <fullName>ActivityGroupId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity Group</label>
    <referenceTo>ActivityGroup__c</referenceTo>
    <relationshipName>RoleSummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SystemUtilityTest.cls
/**
 *  Provus Services Quoting
 *  SystemUtilityTest
 *  @2021 Provus Inc. All rights reserved.
 */

@isTest
private class SystemUtilityTest extends TestBase {
	@isTest
	static void itShouldReturnthePackageNamespace() {
		String pkgNameSpace = SystemUtility.getNamespacePrefix();
		System.assertNotEquals(
			null,
			pkgNameSpace,
			'namespace should be defined as any value (including empty space)'
		);
	}

	@isTest
	static void itShouldSplitUniqueStrings() {
		String commaString = 'Test1,    Test1, Test2';
		Set<String> stringSet = SystemUtility.csvToSet(commaString);

		System.assertEquals(stringSet.size(), 2, 'there should only be 2 unique values');
		System.assert(stringSet.contains('Test1'), 'Test1 should be one of the values');
		System.assert(stringSet.contains('Test2'), 'Test2 should be one of the values');
	}

	@isTest
	static void itShouldTrimTheWhitespace() {
		String commaString = 'Test1,       Test2,Test3     , Test4';
		Set<String> stringSet = SystemUtility.csvToSet(commaString);

		System.assertEquals(stringSet.size(), 4, 'there should only be 4 unique values');
		System.assert(stringSet.contains('Test1'), 'Test1 should be one of the values');
		System.assert(stringSet.contains('Test2'), 'Test2 should be one of the values');
		System.assert(stringSet.contains('Test3'), 'Test3 should be one of the values');
		System.assert(stringSet.contains('Test4'), 'Test4 should be one of the values');
	}

	@IsTest
	static void shouldReturnInverseName() {
		Test.startTest();
		System.assertNotEquals(
			'',
			SystemUtility.getInverseRName(
				Schema.Quote__c.SObjectType,
				Schema.CollaborationRequest__c.SObjectType
			),
			'should return a relationship'
		);
		Test.stopTest();
	}

	@IsTest
	static void itShouldGiveChildRelationshipName() {
		Test.startTest();
		String childRName = SystemUtility.getChildRName(
			Schema.TaskRoleSummary__c.ActivityGroupId__c,
			Schema.ActivityGroup__c.Sequence__c
		);
		String nsPrefix = SystemUtility.getNamespacePrefix();
		String expectedChildRName = nsPrefix + 'ActivityGroupId__r.' + nsPrefix + 'Sequence__c';
		System.assertEquals(
			expectedChildRName,
			childRName,
			'it should return the full child relationship field name'
		);
		Test.stopTest();
	}

	@IsTest
	static void itShouldCopyTheItems() {
		Quote__c quoteSO = newQuote();
		QuoteSection__c sectionSO1 = newQuoteSection(quoteSO.Id);
		QuoteSection__c sectionSO2 = newQuoteSection(quoteSO.Id);

		QuoteItem__c quoteItemSO1 = new QuoteItem__c(
			QuoteId__c = quoteSO.Id,
			QuoteSectionId__c = sectionSO1.Id
		);
		QuoteItem__c quoteItemSO2 = new QuoteItem__c(
			QuoteId__c = quoteSO.Id,
			QuoteSectionId__c = sectionSO2.Id
		);
		CRUDUtility.insertRecords(new List<QuoteItem__c>{ quoteItemSO1, quoteItemSO2 });

		Test.startTest();
		Quote__c clonedQuote = QuoteService.cloneQuote(quoteSO.Id, new Set<Id>());
		List<QuoteItem__c> items = [
			SELECT Id, QuoteSectionId__c
			FROM QuoteItem__c
			WHERE QuoteId__c = :clonedQuote.Id
		];

		System.assert(items.size() == 2, 'should copy all items when quote section set is empty');
		Test.stopTest();
	}
}