force-app/main/default/objects/Activity__c/Activity__c.object-meta.xml
<CustomObject>
    <label>Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity__c/fields/ActivityGroupId__c.field-meta.xml
<CustomField>
    <fullName>ActivityGroupId__c</fullName>
    <label>Activity Group</label>
    <referenceTo>ActivityGroup__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/EstimateId__c.field-meta.xml
<CustomField>
    <fullName>EstimateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estimate</label>
    <referenceTo>Estimate__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/IsNotApplicable__c.field-meta.xml
<CustomField>
    <fullName>IsNotApplicable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Not Applicable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/SummaryId__c.field-meta.xml
<CustomField>
    <fullName>SummaryId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Summary</label>
    <referenceTo>TaskSummary__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ActivityGroup__c/ActivityGroup__c.object-meta.xml
<CustomObject>
    <label>Activity Group</label>
    <nameField>
        <label>Activity Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ActivityGroup__c/fields/EstimateId__c.field-meta.xml
<CustomField>
    <fullName>EstimateId__c</fullName>
    <label>Estimate</label>
    <referenceTo>Estimate__c</referenceTo>
    <relationshipLabel>Activity Groups</relationshipLabel>
    <relationshipName>ActivityGroups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ActivityGroup__c/fields/SummaryId__c.field-meta.xml
<CustomField>
    <fullName>SummaryId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Summary</label>
    <referenceTo>TaskSummary__c</referenceTo>
    <relationshipLabel>Activity Groups</relationshipLabel>
    <relationshipName>ActivityGroups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ActivityGroup__c/fields/TotalCalculatedDuration__c.field-meta.xml
<CustomField>
    <fullName>TotalCalculatedDuration__c</fullName>
    <formula>SummaryId__r.TotalCalculatedDuration__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Calculated Duration</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Estimate__c/Estimate__c.object-meta.xml
<CustomObject>
    <label>Estimate</label>
    <nameField>
        <label>Estimate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estimates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Estimate__c/fields/SummaryId__c.field-meta.xml
<CustomField>
    <fullName>SummaryId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Summary</label>
    <referenceTo>TaskSummary__c</referenceTo>
    <relationshipLabel>Estimates</relationshipLabel>
    <relationshipName>Estimates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Estimate__c/fields/TemplateId__c.field-meta.xml
<CustomField>
    <fullName>TemplateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estimate Template</label>
    <referenceTo>EstimateTemplate__c</referenceTo>
    <relationshipLabel>Estimates</relationshipLabel>
    <relationshipName>Estimates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/ActivityGroupId__c.field-meta.xml
<CustomField>
    <fullName>ActivityGroupId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity Group</label>
    <referenceTo>ActivityGroup__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/ActivityId__c.field-meta.xml
<CustomField>
    <fullName>ActivityId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity</label>
    <referenceTo>Activity__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/EstimateId__c.field-meta.xml
<CustomField>
    <fullName>EstimateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estimate</label>
    <referenceTo>Estimate__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/TemplateId__c.field-meta.xml
<CustomField>
    <fullName>TemplateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task Template</label>
    <referenceTo>TaskTemplate__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TaskParameterTemplate__c/TaskParameterTemplate__c.object-meta.xml
<CustomObject>
    <label>Task Parameter Template</label>
    <nameField>
        <label>Task Parameter Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Parameter Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TaskParameterTemplate__c/fields/DataType__c.field-meta.xml
<CustomField>
    <fullName>DataType__c</fullName>
    <label>Data Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Checkbox</fullName>
            </value>
            <value>
                <fullName>Integer</fullName>
            </value>
            <value>
                <fullName>Integer Tiers</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TaskParameterValue__c/TaskParameterValue__c.object-meta.xml
<CustomObject>
    <label>Task Parameter Value</label>
    <nameField>
        <displayFormat>TPV-{00000}</displayFormat>
        <label>Task Parameter Value</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Parameter Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TaskParameterValue__c/fields/IntegerValue__c.field-meta.xml
<CustomField>
    <fullName>IntegerValue__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Integer Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TaskParameterValue__c/fields/TaskId__c.field-meta.xml
<CustomField>
    <fullName>TaskId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task</label>
    <referenceTo>Task__c</referenceTo>
    <relationshipName>ParameterValues</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TaskParameterValue__c/fields/TemplateId__c.field-meta.xml
<CustomField>
    <fullName>TemplateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task Parameter Template</label>
    <referenceTo>TaskParameterTemplate__c</referenceTo>
    <relationshipName>TaskParameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TaskParameterValueTemplate__c/TaskParameterValueTemplate__c.object-meta.xml
<CustomObject>
    <label>Task Parameter Value Template</label>
    <nameField>
        <displayFormat>TPVT-{00000}</displayFormat>
        <label>Task Parameter Value Template</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Parameter Value Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TaskParameterValueTemplate__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <label>Label</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TaskParameterValueTemplate__c/fields/PerUnitDuration__c.field-meta.xml
<CustomField>
    <fullName>PerUnitDuration__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Per Unit Duration</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/TaskRoleSummary__c.object-meta.xml
<CustomObject>
    <label>Task Role Summary</label>
    <nameField>
        <displayFormat>TRS-{00000}</displayFormat>
        <label>Task Role Summary</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Role Summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TaskRoleSummary__c/fields/ActivityId__c.field-meta.xml
<CustomField>
    <fullName>ActivityId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity</label>
    <referenceTo>Activity__c</referenceTo>
    <relationshipName>RoleSummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/EstimateId__c.field-meta.xml
<CustomField>
    <fullName>EstimateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estimate</label>
    <referenceTo>Estimate__c</referenceTo>
    <relationshipName>RoleSummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/SummaryId__c.field-meta.xml
<CustomField>
    <fullName>SummaryId__c</fullName>
    <label>Summary</label>
    <referenceTo>TaskSummary__c</referenceTo>
    <relationshipName>RoleSummaries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/SummaryLevel__c.field-meta.xml
<CustomField>
    <fullName>SummaryLevel__c</fullName>
    <label>Summary Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Estimate</fullName>
            </value>
            <value>
                <fullName>Activity Group</fullName>
            </value>
            <value>
                <fullName>Activity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/TotalCalculatedDuration__c.field-meta.xml
<CustomField>
    <fullName>TotalCalculatedDuration__c</fullName>
    <formula>RolledUpCalculatedDuration__c + CalculatedDuration__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Calculated Duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TaskSummary__c/TaskSummary__c.object-meta.xml
<CustomObject>
    <label>Task Summary</label>
    <nameField>
        <displayFormat>TS-{00000}</displayFormat>
        <label>Task Summary</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TaskSummary__c/fields/TotalCalculatedDuration__c.field-meta.xml
<CustomField>
    <fullName>TotalCalculatedDuration__c</fullName>
    <label>Total Calculated Duration</label>
    <summarizedField>TaskRoleSummary__c.TotalCalculatedDuration__c</summarizedField>
    <summaryForeignKey>TaskRoleSummary__c.SummaryId__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/EstimateTreeControllerTest.cls
/**
 *  Provus Services Quoting
 *  EstimateTreeGridClassTest
 *  @2021 Provus Inc. All rights reserved.
 */
@IsTest
private class EstimateTreeControllerTest {
	@testSetup
	static void setup() {
		EstimateTemplate__c estimateTemplate = TestDataFactory.createEstimateTemplate(
			'EstimateTemplate',
			true,
			null
		);
		insert estimateTemplate;

		ActivityGroupTemplate__c activityGroupTemplate = TestDataFactory.createActivityGroupTemplate(
			'activityGroup1',
			true,
			estimateTemplate.Id
		);
		insert activityGroupTemplate;

		ActivityTemplate__c activityTemplate = TestDataFactory.createActivityTemplate(
			'activityTemplate1',
			true,
			activityGroupTemplate.Id
		);
		insert activityTemplate;

		TaskTemplate__c taskTemplate = TestDataFactory.createTaskTemplate(
			'task1',
			true,
			activityTemplate.Id
		);
		insert taskTemplate;

		TaskParameterTemplate__c taskParamTemplate = TestDataFactory.createTaskParamTemplate(
			'Taskparamtemp',
			true,
			taskTemplate.Id
		);
		taskParamTemplate.DataType__c = 'Picklist';
		insert taskParamTemplate;

		TaskParameterValueTemplate__c taskParamValueTemplate = TestDataFactory.createTaskParamValueTemplate(
			taskParamTemplate.Id
		);
		taskParamValueTemplate.Label__c = 'Yes';
		taskParamValueTemplate.PerUnitDuration__c = 10;
		insert taskParamValueTemplate;

		Id recordTypeId = Schema.SObjectType.Product2.getRecordTypeInfosByName()
			.get('Resource Role')
			.getRecordTypeId();
		Product2 resource = TestDataFactory.createResource('Software Engineer', recordTypeId);

		Estimate__c estimate = TestDataFactory.createEstimate('Estimate1', true);
		insert estimate;

		ActivityGroup__c activityGroup = TestDataFactory.createActivityGroup('ActivityGroup');
		activityGroup.EstimateId__c = estimate.Id;
		insert activityGroup;

		Activity__c activity = TestDataFactory.createActivity('Activity', activityGroup.Id);
		activity.EstimateId__c = estimate.Id;
		insert activity;

		TaskSummary__c taskSummaryforActivity = TestDataFactory.createTaskSummary();
		insert taskSummaryforActivity;

		TaskSummary__c taskSummaryforEstimate = TestDataFactory.createTaskSummary();
		insert taskSummaryforEstimate;

		TaskSummary__c taskSummaryforActivityGroup = TestDataFactory.createTaskSummary();
		insert taskSummaryforActivityGroup;

		activity.SummaryId__c = taskSummaryforActivity.Id;
		update activity;

		estimate.SummaryId__c = taskSummaryforEstimate.Id;
		update estimate;

		activityGroup.SummaryId__c = taskSummaryforActivityGroup.Id;
		update activityGroup;

		TaskRoleSummary__c taskRoleSummary = TestDataFactory.createTaskRoleSummaryForActivity(
			activity.Id,
			'Activity',
			taskSummaryforActivity.Id
		);
		insert taskRoleSummary;

		TaskRoleSummary__c taskRoleSummaryEstimate = TestDataFactory.createTaskRoleSummaryForEstimate(
			estimate.Id,
			'Estimate',
			taskSummaryforEstimate.Id
		);
		insert taskRoleSummaryEstimate;

		Task__c task = TestDataFactory.createTask(activity.Id, resource.Id, taskRoleSummary.Id);
		insert task;

		TaskParameterValue__c taskParamValue = new TaskParameterValue__c();
		taskParamValue.TaskId__c = task.Id;
		taskParamValue.IntegerValue__c = 10;
		taskParamValue.TemplateId__c = taskParamTemplate.Id;
		insert taskParamValue;
	}

	@IsTest
	static void testMethod1() {
		Id estimateId = [SELECT Id FROM Estimate__c LIMIT 1].Id;
		List<Object> objlst = (List<Object>) EstimateTreeController.getRecords(estimateId);
		Map<String, object> firstRecord = (Map<String, object>) objlst[0];
		system.assertEquals(
			'ActivityGroup',
			String.valueof(firstRecord.get('ActivityGroupName')),
			'Activity Group Name Matching'
		);
	}

	@IsTest
	static void testMethod2() {
		EstimateTreeController.updateTask([SELECT Id FROM Task__c LIMIT 1], null);
		system.assertEquals(
			[SELECT Id FROM Activity__c LIMIT 1]
			.Id,
			[SELECT Id, ActivityId__c FROM Task__c LIMIT 1]
			.ActivityId__c,
			'Task Activity is Matching'
		);
	}

	@IsTest
	static void testMethod3() {
		List<TaskRoleSummary__c> resourceRecords = (List<TaskRoleSummary__c>) EstimateTreeController.getSummaryRecords(
			[SELECT ID FROM Activity__c LIMIT 1]
			.Id,
			'Activity'
		);
		system.assertEquals(resourceRecords[0].TotalCalculatedDuration__c, 0, 'Duration Matching');
	}

	@IsTest
	static void testMethod4() {
		map<string, object> taskDetails = EstimateTreeTaskSupport.taskDetails(
			[SELECT ID FROM Task__c LIMIT 1]
			.Id
		);
		system.assertEquals(Boolean.valueof(taskDetails.get('beforeExists')), false, 'Task Exists');
	}

	@IsTest
	static void testMethod5() {
		List<TaskParameterValue__c> resourceRecords = (List<TaskParameterValue__c>) EstimateTreeController.getSourceSummary(
			[SELECT ID FROM Estimate__c LIMIT 1]
			.Id
		);
		system.assertEquals(resourceRecords.size(), 0, 'No Params Exists');
	}

	@IsTest
	static void testMethod6() {
		map<string, Object> taskDetails = (map<string, Object>) EstimateTreeController.getTaskDetails(
			[SELECT ID FROM Task__c LIMIT 1]
			.Id
		);
		system.assertEquals(taskDetails.containsKey('TaskDetails'), true, 'Task Details  Exists');
	}

	@IsTest
	static void testMethod7() {
		EstimateTreeController.updateNotApplicableField(
			[SELECT ID FROM Activity__c LIMIT 1]
			.Id,
			true,
			'Activity'
		);
		EstimateTreeController.updateNotApplicableField(
			[SELECT ID FROM ActivityGroup__c LIMIT 1]
			.Id,
			true,
			'ActivityGroup'
		);
		system.assertEquals(
			[SELECT ID, IsNotApplicable__c FROM Activity__c LIMIT 1]
			.IsNotApplicable__c,
			true,
			'Not Applicable value Updated'
		);
	}

	@IsTest
	static void testMethod8() {
		List<TaskRoleSummary__c> taskRoleSummaryList = [
			SELECT
				Id,
				SummaryLevel__c,
				ActivityId__c,
				EstimateId__c,
				ActivityGroupId__c,
				ResourceRoleId__c,
				LevelAdjustment__c
			FROM TaskRoleSummary__c
		];
		for (TaskRoleSummary__c taskRoleSummary : taskRoleSummaryList) {
			TaskRoleSummary__c taskRoleSummaryClone = taskRoleSummary.clone(false, false, false, false);
			EstimateTreeController.createSummaryRecords(
				taskRoleSummaryClone,
				taskRoleSummary.SummaryLevel__c
			);
		}
		system.assertEquals(
			5,
			[SELECT ID FROM TaskRoleSummary__c].size(),
			'No of Task Role Summary Matches'
		);
	}
}