force-app/main/default/objects/Activity__c/Activity__c.object-meta.xml
<CustomObject>
    <label>Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity__c/fields/EstimateId__c.field-meta.xml
<CustomField>
    <fullName>EstimateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estimate</label>
    <referenceTo>Estimate__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ActivityGroup__c/ActivityGroup__c.object-meta.xml
<CustomObject>
    <label>Activity Group</label>
    <nameField>
        <label>Activity Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ActivityGroup__c/fields/EstimateId__c.field-meta.xml
<CustomField>
    <fullName>EstimateId__c</fullName>
    <label>Estimate</label>
    <referenceTo>Estimate__c</referenceTo>
    <relationshipLabel>Activity Groups</relationshipLabel>
    <relationshipName>ActivityGroups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Estimate__c/Estimate__c.object-meta.xml
<CustomObject>
    <label>Estimate</label>
    <nameField>
        <label>Estimate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estimates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Estimate__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ProductId</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordTypeId</field>
            <operation>equals</operation>
            <value>Product</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Estimates</relationshipLabel>
    <relationshipName>ProductEstimates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Estimate__c/fields/RateCardId__c.field-meta.xml
<CustomField>
    <fullName>RateCardId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate Card</label>
    <referenceTo>RateCard__c</referenceTo>
    <relationshipLabel>Estimates</relationshipLabel>
    <relationshipName>Estimates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Practice__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Practice__c.field-meta.xml
<CustomField>
    <fullName>Practice__c</fullName>
    <label>Practice</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Practices</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Service.recordType-meta.xml
<RecordType>
    <fullName>Service</fullName>
    <active>true</active>
    <label>Service</label>
</RecordType>

force-app/main/default/objects/RateCard__c/RateCard__c.object-meta.xml
<CustomObject>
    <label>Rate Card</label>
    <nameField>
        <label>Rate Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RateCardItem__c/RateCardItem__c.object-meta.xml
<CustomObject>
    <label>Rate Card Item</label>
    <nameField>
        <displayFormat>RCI-{0000000}</displayFormat>
        <label>Rate Card Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Card Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RateCardItem__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Rate Card Items</relationshipLabel>
    <relationshipName>RateCardItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RateCardItem__c/fields/RateCardId__c.field-meta.xml
<CustomField>
    <fullName>RateCardId__c</fullName>
    <label>Rate Card</label>
    <referenceTo>RateCard__c</referenceTo>
    <relationshipLabel>Rate Card Items</relationshipLabel>
    <relationshipName>RateCardItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Groups.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Salesforce Implementation</fullName>
    </customValue>
    <customValue>
        <fullName>SAP Implementation</fullName>
    </customValue>
    <customValue>
        <fullName>Web &amp; Mobile Apps</fullName>
    </customValue>
    <customValue>
        <fullName>Java</fullName>
    </customValue>
    <customValue>
        <fullName>.Net</fullName>
    </customValue>
    <customValue>
        <fullName>Sales Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>Service Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>SFDC Integration</fullName>
    </customValue>
    <customValue>
        <fullName>SAP C/4 HANA CUSTOMER EXP</fullName>
    </customValue>
    <customValue>
        <fullName>SAP S/4 HANA CLOUD ERP</fullName>
    </customValue>
    <customValue>
        <fullName>SAP SUCCESS FACTORS</fullName>
    </customValue>
    <customValue>
        <fullName>SAP ARIBA</fullName>
    </customValue>
    <customValue>
        <fullName>SAP BUSINESS OBJECTS</fullName>
    </customValue>
    <customValue>
        <fullName>SAP ACTIVATE</fullName>
    </customValue>
    <customValue>
        <fullName>SAP CLOUD PLATFORM Integration</fullName>
    </customValue>
    <customValue>
        <fullName>Oracle Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>Oracle Infrastructure</fullName>
    </customValue>
    <customValue>
        <fullName>Oracle Live</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Web Services Basics</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Computer Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Network Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Storage Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Database Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Analytics Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Application Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Web Services Resources</fullName>
    </customValue>
    <customValue>
        <fullName>AI + Machine Learning</fullName>
    </customValue>
    <customValue>
        <fullName>Analytics</fullName>
    </customValue>
    <customValue>
        <fullName>Blockchain</fullName>
    </customValue>
    <customValue>
        <fullName>Software</fullName>
    </customValue>
    <masterLabel>Groups</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Practices.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Custom Development</fullName>
        <label>Web Development</label>
    </customValue>
    <customValue>
        <fullName>Cloud Consulting</fullName>
    </customValue>
    <customValue>
        <fullName>Outsourcing</fullName>
    </customValue>
    <customValue>
        <fullName>AWS</fullName>
    </customValue>
    <customValue>
        <fullName>GCP</fullName>
    </customValue>
    <customValue>
        <fullName>DevOps</fullName>
    </customValue>
    <customValue>
        <fullName>Java</fullName>
    </customValue>
    <customValue>
        <fullName>Python</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>SAP</fullName>
    </customValue>
    <customValue>
        <fullName>SFDC</fullName>
    </customValue>
    <customValue>
        <fullName>Oracle</fullName>
    </customValue>
    <customValue>
        <fullName>CI/CD</fullName>
    </customValue>
    <customValue>
        <fullName>ERP</fullName>
        <isActive>false</isActive>
        <label>ERP</label>
    </customValue>
    <customValue>
        <fullName>CRM</fullName>
        <isActive>false</isActive>
        <label>CRM</label>
    </customValue>
    <masterLabel>Practices</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CustomLookupControllerTest.cls
/**
 * @description       : This is a test class for CustomLookupController
 * @author            : Vikrant kumar
 * @group             :
 * @last modified on  : 08-25-2021
 * @last modified by  : Vikrant kumar
 **/
@IsTest
private class CustomLookupControllerTest extends TestBase {
	static final String SERVICE_PRODUCT_PRACTICE = 'Architect';
	static final String SERVICE_PRODUCT_GROUP = 'Software';
	//Below is a method with @testsetup annotation, the name can be anything like setup(), oneTimeData(), etc.
	@TestSetup
	static void setup() {
		RateCard__c rateCard = newRateCard();
		rateCard.Name = 'RateCard';
		CRUDUtility.updateRecords(rateCard);
		RateCard__c rateCard2 = newRateCard();
		rateCard2.Name = 'RateCard2';
		CRUDUtility.updateRecords(rateCard2);
		Map<String, RecordTypeInfo> describeRecordInfos = Schema.SObjectType.Product2.getRecordTypeInfosByName();
		Id recordTypeId = describeRecordInfos.get('Resource Role').getRecordTypeId();
		Id servicePrdTypeId = describeRecordInfos.get('Service').getRecordTypeId();
		Product2 architectProduct = TestDataFactory.createResource('Architect', servicePrdTypeId);
		architectProduct.Practice__c = SERVICE_PRODUCT_PRACTICE;
		architectProduct.Group__c = SERVICE_PRODUCT_GROUP;
		List<Product2> prdLst = new List<Product2>{
			TestDataFactory.createResource('Software Engineer', recordTypeId),
			TestDataFactory.createResource('Project Manager', recordTypeId),
			architectProduct
		};
		CRUDUtility.insertRecords(prdLst);
		RateCardItem__c rateCardItem = new RateCardItem__c();
		rateCardItem.RateCardId__c = rateCard.Id;
		rateCardItem.ProductId__c = prdLst[0].Id;
		CRUDUtility.insertRecords(rateCardItem);
		RateCardItem__c rateCardItem2 = new RateCardItem__c();
		rateCardItem2.RateCardId__c = rateCard2.Id;
		rateCardItem2.ProductId__c = prdLst[2].Id;
		CRUDUtility.insertRecords(rateCardItem2);
		Estimate__c est = TestDataFactory.createEstimate('CLMEstimate', true);
		CRUDUtility.insertRecords(est);
		ActivityGroup__c ag = TestDataFactory.createActivityGroup('AcitivityGroup');
		ag.EstimateId__c = est.Id;
		CRUDUtility.insertRecords(ag);
		Activity__c act = TestDataFactory.createActivity(ag.Id);
		CRUDUtility.insertRecords(act);
	}

	@IsTest
	static void testMethod1() {
		Map<String, String> paramMap = new Map<String, String>{
			'objectName' => 'Product2',
			'filterField' => 'Name',
			'searchString' => 'Software',
			'value' => 'Test',
			'hierarchylevel' => 'Task',
			'hierarchylevelId' => [SELECT Id FROM Estimate__c LIMIT 1]
			.Id,
			'rateCard' => [SELECT Id FROM RateCard__c LIMIT 1]
			.Id
		};

		CustomLookupController.fetchRecords(paramMap);

		paramMap.put('searchString', 'Software Engineer');
		paramMap.put('hierarchylevel', 'Estimate');
		CustomLookupController.fetchRecords(paramMap);

		SObject obj = CustomLookupController.fetchDefaultRecord(
			[SELECT Id FROM RateCard__c LIMIT 1]
			.Id,
			'RateCard__c'
		);
		System.assertEquals('RateCard', String.valueOf(obj.get('Name')), 'Success');
	}

	@IsTest
	static void fetchRecordsFilterCriteriaForNonExistingPracticeTypeExpectEmptyRecordResult() {
		Map<String, String> paramMap = new Map<String, String>{
			'objectName' => 'Product2',
			'filterField' => 'Name',
			'filterCriteria' => 'ProductId__r.Practice__c = \'Architype\'', // no records with practice architype exist
			'searchString' => 'Architect',
			'value' => 'Test',
			'hierarchylevel' => 'Task',
			'rateCard' => [SELECT Id FROM RateCard__c WHERE Name = 'RateCard2' LIMIT 1]
			.Id
		};

		List<CustomLookupController.RecordsData> emptyRecordsData = new List<CustomLookupController.RecordsData>();
		List<CustomLookupController.RecordsData> recordsData = CustomLookupController.fetchRecords(
			paramMap
		);
		System.assertEquals(
			emptyRecordsData,
			recordsData,
			'expect records data to not exist and equal null'
		);
	}

	@IsTest
	static void fetchRecordsFilterCriteriaForExistingPracticeTypeExpectRecord() {
		Map<String, String> paramMap = new Map<String, String>{
			'objectName' => 'Product2',
			'filterField' => 'Name',
			'filterCriteria' => 'ProductId__r.Practice__c = \'' +
			SERVICE_PRODUCT_PRACTICE +
			'\'', // records exists with practice Architect
			'searchString' => 'Architect',
			'value' => 'Test',
			'hierarchylevel' => 'Task',
			'rateCard' => [SELECT Id FROM RateCard__c WHERE Name = 'RateCard2' LIMIT 1]
			.Id
		};

		List<CustomLookupController.RecordsData> recordsData = CustomLookupController.fetchRecords(
			paramMap
		);
		System.assertEquals(1, recordsData.size(), 'expect records data to return one result');
		System.assertEquals(
			'Architect',
			recordsData[0].label,
			'expect the dropdown entry label to be \'Architect\''
		);
	}
}