force-app/main/default/objects/Activity__c/Activity__c.object-meta.xml
<CustomObject>
    <label>Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity__c/fields/ActivityGroupId__c.field-meta.xml
<CustomField>
    <fullName>ActivityGroupId__c</fullName>
    <label>Activity Group</label>
    <referenceTo>ActivityGroup__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/EstimateId__c.field-meta.xml
<CustomField>
    <fullName>EstimateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estimate</label>
    <referenceTo>Estimate__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/IsNotApplicable__c.field-meta.xml
<CustomField>
    <fullName>IsNotApplicable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Not Applicable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Path__c.field-meta.xml
<CustomField>
    <fullName>Path__c</fullName>
    <formula>TEXT(ActivityGroupId__r.Sequence__c)+&apos;.&apos;+ TEXT(Sequence__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Path</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ActivityGroup__c/ActivityGroup__c.object-meta.xml
<CustomObject>
    <label>Activity Group</label>
    <nameField>
        <label>Activity Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ActivityGroup__c/fields/EstimateId__c.field-meta.xml
<CustomField>
    <fullName>EstimateId__c</fullName>
    <label>Estimate</label>
    <referenceTo>Estimate__c</referenceTo>
    <relationshipLabel>Activity Groups</relationshipLabel>
    <relationshipName>ActivityGroups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ActivityGroup__c/fields/Guidance__c.field-meta.xml
<CustomField>
    <fullName>Guidance__c</fullName>
    <label>Guidance</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/ActivityGroupId__c.field-meta.xml
<CustomField>
    <fullName>ActivityGroupId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity Group</label>
    <referenceTo>ActivityGroup__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/ActivityId__c.field-meta.xml
<CustomField>
    <fullName>ActivityId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity</label>
    <referenceTo>Activity__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/AdjustmentReason__c.field-meta.xml
<CustomField>
    <fullName>AdjustmentReason__c</fullName>
    <label>Adjustment Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/CalculatedDuration__c.field-meta.xml
<CustomField>
    <fullName>CalculatedDuration__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Calculated Duration</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/EstimatedDuration__c.field-meta.xml
<CustomField>
    <fullName>EstimatedDuration__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Estimated Duration</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/EstimateId__c.field-meta.xml
<CustomField>
    <fullName>EstimateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estimate</label>
    <referenceTo>Estimate__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Path__c.field-meta.xml
<CustomField>
    <fullName>Path__c</fullName>
    <formula
	>TEXT(ActivityId__r.ActivityGroupId__r.Sequence__c) +&apos;.&apos; + TEXT(ActivityId__r.Sequence__c) +&apos;.&apos; +  TEXT(Sequence__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Path</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/ResourceRoleId__c.field-meta.xml
<CustomField>
    <fullName>ResourceRoleId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Role</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource Role</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/TemplateId__c.field-meta.xml
<CustomField>
    <fullName>TemplateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task Template</label>
    <referenceTo>TaskTemplate__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TaskParameterTemplate__c/TaskParameterTemplate__c.object-meta.xml
<CustomObject>
    <label>Task Parameter Template</label>
    <nameField>
        <label>Task Parameter Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Parameter Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TaskParameterTemplate__c/fields/DataType__c.field-meta.xml
<CustomField>
    <fullName>DataType__c</fullName>
    <label>Data Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Checkbox</fullName>
            </value>
            <value>
                <fullName>Integer</fullName>
            </value>
            <value>
                <fullName>Integer Tiers</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TaskParameterTemplate__c/fields/TaskTemplateId__c.field-meta.xml
<CustomField>
    <fullName>TaskTemplateId__c</fullName>
    <label>Task Template</label>
    <referenceTo>TaskTemplate__c</referenceTo>
    <relationshipLabel>Parameters</relationshipLabel>
    <relationshipName>Parameters</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TaskParameterValue__c/TaskParameterValue__c.object-meta.xml
<CustomObject>
    <label>Task Parameter Value</label>
    <nameField>
        <displayFormat>TPV-{00000}</displayFormat>
        <label>Task Parameter Value</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Parameter Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TaskParameterValue__c/fields/BooleanValue__c.field-meta.xml
<CustomField>
    <fullName>BooleanValue__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Boolean Value</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TaskParameterValue__c/fields/IntegerValue__c.field-meta.xml
<CustomField>
    <fullName>IntegerValue__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Integer Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TaskParameterValue__c/fields/TaskId__c.field-meta.xml
<CustomField>
    <fullName>TaskId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task</label>
    <referenceTo>Task__c</referenceTo>
    <relationshipName>ParameterValues</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TaskParameterValue__c/fields/TemplateId__c.field-meta.xml
<CustomField>
    <fullName>TemplateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task Parameter Template</label>
    <referenceTo>TaskParameterTemplate__c</referenceTo>
    <relationshipName>TaskParameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TaskParameterValueTemplate__c/TaskParameterValueTemplate__c.object-meta.xml
<CustomObject>
    <label>Task Parameter Value Template</label>
    <nameField>
        <displayFormat>TPVT-{00000}</displayFormat>
        <label>Task Parameter Value Template</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Parameter Value Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TaskParameterValueTemplate__c/fields/EstimatedDuration__c.field-meta.xml
<CustomField>
    <fullName>EstimatedDuration__c</fullName>
    <label>Estimated Duration</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TaskParameterValueTemplate__c/fields/FromValue__c.field-meta.xml
<CustomField>
    <fullName>FromValue__c</fullName>
    <label>From Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TaskParameterValueTemplate__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <label>Label</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TaskParameterValueTemplate__c/fields/PerUnitDuration__c.field-meta.xml
<CustomField>
    <fullName>PerUnitDuration__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Per Unit Duration</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TaskParameterValueTemplate__c/fields/TaskParameterTemplateId__c.field-meta.xml
<CustomField>
    <fullName>TaskParameterTemplateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task Parameter Template</label>
    <referenceTo>TaskParameterTemplate__c</referenceTo>
    <relationshipLabel>Parameter Values</relationshipLabel>
    <relationshipName>ParameterValues</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TaskParameterValueTemplate__c/fields/ToValue__c.field-meta.xml
<CustomField>
    <fullName>ToValue__c</fullName>
    <label>To Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/EstimateTreeTaskSupport.cls
/*
 * Provus Services Quoting
 * Copyright (c) 2022 Provus Inc. All rights reserved.
 */
public with sharing class EstimateTreeTaskSupport {
	public static Map<String, Object> getTaskDetails(String taskId) {
		Map<String, Object> finalMp = new Map<String, Object>();
		List<Object> dataFields = new List<Object>();
		List<TaskParameterValue__c> taskParameterValues = [
			SELECT
				Id,
				TemplateId__c,
				BooleanValue__c,
				IntegerValue__c,
				TextValue__c,
				TaskId__r.Name,
				TaskId__r.ActivityId__r.Name,
				TaskId__r.ActivityId__r.ActivityGroupId__r.Name
			FROM TaskParameterValue__c
			WHERE TaskId__c = :taskId
			WITH SECURITY_ENFORCED
		];
		Map<Id, TaskParameterValue__c> taskParameterValueMap = new Map<Id, TaskParameterValue__c>();
		if (!taskParameterValues.isEmpty()) {
			taskParameterValueMap = (Map<Id, TaskParameterValue__c>) SystemUtility.keyByIdType(
				taskParameterValues,
				Schema.TaskParameterValue__c.TemplateId__c
			);
		}

		//Querying the taskparameters..it contains the field definition info
		for (TaskParameterTemplate__c taskParameterTemplate : [
			SELECT
				Id,
				TaskTemplateId__c,
				DataType__c,
				Name,
				Guidance__c,
				(
					SELECT Id, Name, Label__c, PerUnitDuration__c, FromValue__c, ToValue__c
					FROM ParameterValues__r
					ORDER BY Sequence__c ASC
				)
			FROM TaskParameterTemplate__c
			WHERE Id IN :taskParameterValueMap.keySet() AND IsActive__c = TRUE
			WITH SECURITY_ENFORCED
			ORDER BY Sequence__c ASC
		]) {
			dataFields.add(createTaskParams(taskParameterTemplate, taskParameterValueMap));
		}
		//taskId
		finalMp.put('TaskDetails', taskDetails(taskId));
		finalMp.put('TaskParams', dataFields);
		return finalMp;
	}

	private static Map<String, Object> createTaskParams(
		TaskParameterTemplate__c taskParameterTemplate,
		Map<Id, TaskParameterValue__c> taskParameterValueMap
	) {
		Map<String, Object> mapObject = new Map<String, Object>();
		mapObject.put(EstimatorConstants.DATA_TYPE, taskParameterTemplate.DataType__c);
		EstimateTreeSupport.processObject(taskParameterTemplate, mapObject, taskParameterValueMap);
		mapObject.put('FieldId', taskParameterTemplate.Id);
		mapObject.put('FieldName', taskParameterTemplate.Name);
		mapObject.put('Description', taskParameterTemplate.Guidance__c);
		mapObject.put(
			'PicklistValue',
			taskParameterValueMap.get(taskParameterTemplate.Id).TextValue__c
		);
		mapObject.put(
			'isIntegerTiers',
			taskParameterTemplate.DataType__c == 'Integer Tiers' ? true : false
		);
		mapObject.put('isNumberField', taskParameterTemplate.DataType__c == 'Integer' ? true : false);
		mapObject.put('isPickList', taskParameterTemplate.DataType__c == 'Picklist' ? true : false);
		mapObject.put('isBoolean', taskParameterTemplate.DataType__c == 'Checkbox' ? true : false);
		if (taskParameterTemplate.ParameterValues__r != null) {
			processTemplateValues(
				taskParameterTemplate.ParameterValues__r,
				mapObject,
				taskParameterTemplate
			);
		}
		return mapObject;
	}

	@TestVisible
	private static Map<String, Object> taskDetails(String taskId) {
		Task__c tk = [
			SELECT Id, Path__c, EstimateId__c
			FROM Task__c
			WHERE Id = :taskId
			WITH SECURITY_ENFORCED
		];
		Integer agSeq = Integer.valueof(tk.Path__c.split('\\.')[0]);
		Integer prvSeq = agSeq - 2;
		Integer nxtSeq = agSeq + 2;
		Map<Id, Task__c> activityTasks = new Map<Id, Task__c>(
			[
				SELECT
					Id,
					Path__c,
					Name,
					TemplateId__c,
					ActivityId__r.Name,
					ActivityId__r.ActivityGroupId__r.Name,
					IsNotApplicable__c,
					CalculatedDuration__c,
					LevelAdjustment__c,
					EstimatedDuration__c,
					ResourceRoleId__r.Name,
					AdjustmentReason__c
				FROM Task__c
				WHERE
					EstimateId__c = :tk.EstimateId__c
					AND ActivityId__r.ActivityGroupId__r.Sequence__c >= :prvSeq
					AND ActivityId__r.ActivityGroupId__r.Sequence__c <= :nxtSeq
				WITH SECURITY_ENFORCED
				ORDER BY Path__c ASC
			]
		);
		List<Id> tskIIds = new List<Id>(activityTasks.keySet());
		Map<String, Object> mpTask = new Map<String, Object>();
		Integer indx = tskIIds.indexOf(Id.valueOf(taskId));
		if (indx == 0) {
			mpTask = EstimateTreeSupport.taskDetailObject(activityTasks.get(taskId));
			mpTask.put('beforeExists', false);
			mpTask.put('afterExists', tskIIds.size() == 1 ? false : true);
			mpTask.put('beforeTaskId', '');
			mpTask.put('afterTaskId', tskIIds.size() == 1 ? '' : tskIIds[indx + 1]);
		} else if (indx == tskIIds.size() - 1) {
			mpTask = EstimateTreeSupport.taskDetailObject(activityTasks.get(taskId));
			mpTask.put('beforeExists', true);
			mpTask.put('afterExists', false);
			mpTask.put('beforeTaskId', tskIIds[indx - 1]);
			mpTask.put('afterTaskId', '');
		} else {
			mpTask = EstimateTreeSupport.taskDetailObject(activityTasks.get(taskId));
			mpTask.put('beforeExists', true);
			mpTask.put('afterExists', true);
			mpTask.put('beforeTaskId', tskIIds[indx - 1]);
			mpTask.put('afterTaskId', tskIIds[indx + 1]);
		}
		return mpTask;
	}

	private static void processTemplateValues(
		List<TaskParameterValueTemplate__c> taskParamRecords,
		Map<String, Object> mps,
		TaskParameterTemplate__c tp
	) {
		List<Object> tpaLst = new List<Object>();
		Map<String, String> picklistLabelValues = new Map<String, String>();
		for (TaskParameterValueTemplate__c tpv : taskParamRecords) {
			if (tp.DataType__c == 'Picklist') {
				Map<String, String> mpval = new Map<String, String>();
				mpval.put('label', tpv.Label__c);
				mpval.put('value', String.valueOf(tpv.PerUnitDuration__c));
				tpaLst.add(mpval);
				picklistLabelValues.put(tpv.Label__c, String.valueOf(tpv.PerUnitDuration__c));
			} else if (tp.DataType__c == 'Integer' || tp.DataType__c == 'Checkbox') {
				mps.put('Multiplier', tpv.PerUnitDuration__c);
			} else if (tp.DataType__c == 'Integer Tiers') {
				mps.put('IntegerTiers', tp.ParameterValues__r);
			}
		}
		if (tp.DataType__c == 'Picklist') {
			mps.put(
				'selectedValue',
				picklistLabelValues.containsKey(String.valueOf(mps.get('PicklistValue')))
					? picklistLabelValues.get(String.valueOf(mps.get('PicklistValue')))
					: ''
			);
		}
		mps.put('PicklistValues', tpaLst);
	}
}