force-app/main/default/objects/Activity__c/Activity__c.object-meta.xml
<CustomObject>
    <label>Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity__c/fields/ActivityGroupId__c.field-meta.xml
<CustomField>
    <fullName>ActivityGroupId__c</fullName>
    <label>Activity Group</label>
    <referenceTo>ActivityGroup__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/EstimateId__c.field-meta.xml
<CustomField>
    <fullName>EstimateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estimate</label>
    <referenceTo>Estimate__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/SummaryId__c.field-meta.xml
<CustomField>
    <fullName>SummaryId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Summary</label>
    <referenceTo>TaskSummary__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ActivityGroup__c/ActivityGroup__c.object-meta.xml
<CustomObject>
    <label>Activity Group</label>
    <nameField>
        <label>Activity Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ActivityGroup__c/fields/EstimateId__c.field-meta.xml
<CustomField>
    <fullName>EstimateId__c</fullName>
    <label>Estimate</label>
    <referenceTo>Estimate__c</referenceTo>
    <relationshipLabel>Activity Groups</relationshipLabel>
    <relationshipName>ActivityGroups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ActivityGroup__c/fields/SummaryId__c.field-meta.xml
<CustomField>
    <fullName>SummaryId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Summary</label>
    <referenceTo>TaskSummary__c</referenceTo>
    <relationshipLabel>Activity Groups</relationshipLabel>
    <relationshipName>ActivityGroups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Estimate__c/Estimate__c.object-meta.xml
<CustomObject>
    <label>Estimate</label>
    <nameField>
        <label>Estimate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estimates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Estimate__c/fields/SummaryId__c.field-meta.xml
<CustomField>
    <fullName>SummaryId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Summary</label>
    <referenceTo>TaskSummary__c</referenceTo>
    <relationshipLabel>Estimates</relationshipLabel>
    <relationshipName>Estimates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <label>Product</label>
</RecordType>

force-app/main/default/objects/TaskRoleSummary__c/TaskRoleSummary__c.object-meta.xml
<CustomObject>
    <label>Task Role Summary</label>
    <nameField>
        <displayFormat>TRS-{00000}</displayFormat>
        <label>Task Role Summary</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Role Summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TaskRoleSummary__c/fields/ActivityGroupId__c.field-meta.xml
<CustomField>
    <fullName>ActivityGroupId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity Group</label>
    <referenceTo>ActivityGroup__c</referenceTo>
    <relationshipName>RoleSummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/EstimateId__c.field-meta.xml
<CustomField>
    <fullName>EstimateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estimate</label>
    <referenceTo>Estimate__c</referenceTo>
    <relationshipName>RoleSummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/LevelAdjustment__c.field-meta.xml
<CustomField>
    <fullName>LevelAdjustment__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Level Adjustment</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/SummaryId__c.field-meta.xml
<CustomField>
    <fullName>SummaryId__c</fullName>
    <label>Summary</label>
    <referenceTo>TaskSummary__c</referenceTo>
    <relationshipName>RoleSummaries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/SummaryLevel__c.field-meta.xml
<CustomField>
    <fullName>SummaryLevel__c</fullName>
    <label>Summary Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Estimate</fullName>
            </value>
            <value>
                <fullName>Activity Group</fullName>
            </value>
            <value>
                <fullName>Activity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TaskSummary__c/TaskSummary__c.object-meta.xml
<CustomObject>
    <label>Task Summary</label>
    <nameField>
        <displayFormat>TS-{00000}</displayFormat>
        <label>Task Summary</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EstimateTreeSummarySupportTest.cls
/*
 * Provus Services Quoting
 * Copyright (c) 2022 Provus Inc. All rights reserved.
 */
@IsTest
private class EstimateTreeSummarySupportTest extends TestBase {
	static TaskSummary__c newTaskSummary() {
		TaskSummary__c newSummary = new TaskSummary__c();
		CRUDUtility.insertRecords(newSummary);

		return newSummary;
	}

	@IsTest
	static void shouldCreateLineageFromActivity() {
		TaskSummary__c summarySO = newTaskSummary();
		Estimate__c estimateSO = new Estimate__c(SummaryId__c = summarySO.Id);
		CRUDUtility.insertRecords(estimateSO);
		ActivityGroup__c groupSO = new ActivityGroup__c(
			EstimateId__c = estimateSO.Id,
			SummaryId__c = summarySO.Id
		);
		CRUDUtility.insertRecords(groupSO);
		Activity__c activitySO = new Activity__c(
			EstimateId__c = estimateSO.Id,
			ActivityGroupId__c = groupSO.Id,
			SummaryId__c = summarySO.Id
		);
		CRUDUtility.insertRecords(activitySO);

		Id productTypeId = SObjectUtility.getRecordTypeIdbyName('Product2', 'Product');
		Product2 productSO = newProduct('Test Product', productTypeId);

		Test.startTest();
		EstimateTreeSummarySupport.createRoleSummaryLineageForActivity(activitySO.Id, productSO.Id, 8);
		TaskRoleSummary__c activitySummarySO = [
			SELECT LevelAdjustment__c
			FROM TaskRoleSummary__c
			WHERE SummaryLevel__c = 'Activity'
		];
		System.assertEquals(
			3,
			EstimateTreeSummarySupport.getRoleSummaryLineageForActivity(activitySO.Id, productSO.Id)
				.size(),
			'should have 3 task role summaries (estimate, group, activity)'
		);
		System.assert(activitySummarySO.LevelAdjustment__c == 8, 'should persist the level adjustment');
		Test.stopTest();
	}

	@IsTest
	static void shouldCreateLineageFromActivityGroup() {
		TaskSummary__c summarySO = newTaskSummary();
		Estimate__c estimateSO = new Estimate__c(SummaryId__c = summarySO.Id);
		CRUDUtility.insertRecords(estimateSO);
		ActivityGroup__c groupSO = new ActivityGroup__c(
			EstimateId__c = estimateSO.Id,
			SummaryId__c = summarySO.Id
		);
		CRUDUtility.insertRecords(groupSO);

		Id productTypeId = SObjectUtility.getRecordTypeIdbyName('Product2', 'Product');
		Product2 productSO = newProduct('Test Product', productTypeId);

		Test.startTest();
		EstimateTreeSummarySupport.createRoleSummaryLineageForActivityGroup(
			groupSO.Id,
			productSO.Id,
			8
		);
		TaskRoleSummary__c groupSummarySO = [
			SELECT LevelAdjustment__c
			FROM TaskRoleSummary__c
			WHERE SummaryLevel__c = 'Activity Group'
		];
		System.assertEquals(
			2,
			EstimateTreeSummarySupport.getRoleSummaryLineageForActivityGroup(groupSO.Id, productSO.Id)
				.size(),
			'should have 2 task role summaries (estimate, group)'
		);
		System.assert(groupSummarySO.LevelAdjustment__c == 8, 'should persist the level adjustment');
		Test.stopTest();
	}
}