force-app/main/default/objects/Activity__c/Activity__c.object-meta.xml
<CustomObject>
    <label>Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity__c/fields/EstimateId__c.field-meta.xml
<CustomField>
    <fullName>EstimateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estimate</label>
    <referenceTo>Estimate__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ActivityGroup__c/ActivityGroup__c.object-meta.xml
<CustomObject>
    <label>Activity Group</label>
    <nameField>
        <label>Activity Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ActivityGroup__c/fields/EstimateId__c.field-meta.xml
<CustomField>
    <fullName>EstimateId__c</fullName>
    <label>Estimate</label>
    <referenceTo>Estimate__c</referenceTo>
    <relationshipLabel>Activity Groups</relationshipLabel>
    <relationshipName>ActivityGroups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Estimate__c/Estimate__c.object-meta.xml
<CustomObject>
    <label>Estimate</label>
    <nameField>
        <label>Estimate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estimates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/EstimateId__c.field-meta.xml
<CustomField>
    <fullName>EstimateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estimate</label>
    <referenceTo>Estimate__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/TaskRoleSummary__c.object-meta.xml
<CustomObject>
    <label>Task Role Summary</label>
    <nameField>
        <displayFormat>TRS-{00000}</displayFormat>
        <label>Task Role Summary</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Role Summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TaskRoleSummary__c/fields/EstimateId__c.field-meta.xml
<CustomField>
    <fullName>EstimateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estimate</label>
    <referenceTo>Estimate__c</referenceTo>
    <relationshipName>RoleSummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TaskSummary__c/TaskSummary__c.object-meta.xml
<CustomObject>
    <label>Task Summary</label>
    <nameField>
        <displayFormat>TS-{00000}</displayFormat>
        <label>Task Summary</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/EstimateClonerTest.cls
/**
 *  Provus Services Quoting
 *  EstimateClonerTest
 *  @2021 Provus Inc. All rights reserved.
 */
@IsTest
private class EstimateClonerTest {
	@testSetup
	static void setup() {
		Id recordTypeId = Schema.SObjectType.Product2.getRecordTypeInfosByName()
			.get('Resource Role')
			.getRecordTypeId();
		Product2 resource = TestDataFactory.createResource('Software Engineer', recordTypeId);

		Estimate__c estimate = TestDataFactory.createEstimate('Estimate1', true);
		insert estimate;

		ActivityGroup__c activityGroup = TestDataFactory.createActivityGroup('ActivityGroup');
		activityGroup.EstimateId__c = estimate.Id;
		insert activityGroup;

		Activity__c activity = TestDataFactory.createActivity('Activity', activityGroup.Id);
		insert activity;

		TaskSummary__c taskSummary = TestDataFactory.createTaskSummary();
		insert taskSummary;

		TaskRoleSummary__c taskRoleSummary = TestDataFactory.createTaskRoleSummaryForActivity(
			activity.Id,
			'Activity',
			taskSummary.Id
		);
		insert taskRoleSummary;

		Task__c task = TestDataFactory.createTask(activity.Id, resource.Id, taskRoleSummary.Id);
		insert task;
	}

	@IsTest
	static void testMethod1() {
		String clonedEstimateId = EstimateCloner.createEstimateClone(
			[SELECT Id FROM Estimate__c LIMIT 1]
			.Id,
			'ClonedEstimate'
		);
		system.assertEquals(
			'ClonedEstimate',
			[SELECT Id, Name FROM Estimate__c WHERE ID = :clonedEstimateId]
			.Name,
			'Estimate Cloned Successfully'
		);
	}
}