force-app/main/default/objects/Activity__c/Activity__c.object-meta.xml
<CustomObject>
    <label>Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity__c/fields/ActivityGroupId__c.field-meta.xml
<CustomField>
    <fullName>ActivityGroupId__c</fullName>
    <label>Activity Group</label>
    <referenceTo>ActivityGroup__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/EstimateId__c.field-meta.xml
<CustomField>
    <fullName>EstimateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estimate</label>
    <referenceTo>Estimate__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/SummaryId__c.field-meta.xml
<CustomField>
    <fullName>SummaryId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Summary</label>
    <referenceTo>TaskSummary__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ActivityGroup__c/ActivityGroup__c.object-meta.xml
<CustomObject>
    <label>Activity Group</label>
    <nameField>
        <label>Activity Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ActivityGroup__c/fields/EstimateId__c.field-meta.xml
<CustomField>
    <fullName>EstimateId__c</fullName>
    <label>Estimate</label>
    <referenceTo>Estimate__c</referenceTo>
    <relationshipLabel>Activity Groups</relationshipLabel>
    <relationshipName>ActivityGroups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ActivityGroup__c/fields/SummaryId__c.field-meta.xml
<CustomField>
    <fullName>SummaryId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Summary</label>
    <referenceTo>TaskSummary__c</referenceTo>
    <relationshipLabel>Activity Groups</relationshipLabel>
    <relationshipName>ActivityGroups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ActivityGroup__c/fields/TotalCalculatedDuration__c.field-meta.xml
<CustomField>
    <fullName>TotalCalculatedDuration__c</fullName>
    <formula>SummaryId__r.TotalCalculatedDuration__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Calculated Duration</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ActivityGroup__c/fields/TotalEstimatedDuration__c.field-meta.xml
<CustomField>
    <fullName>TotalEstimatedDuration__c</fullName>
    <formula>SummaryId__r.TotalEstimatedDuration__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Estimated Duration</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Estimate__c/Estimate__c.object-meta.xml
<CustomObject>
    <label>Estimate</label>
    <nameField>
        <label>Estimate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estimates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Estimate__c/fields/SummaryId__c.field-meta.xml
<CustomField>
    <fullName>SummaryId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Summary</label>
    <referenceTo>TaskSummary__c</referenceTo>
    <relationshipLabel>Estimates</relationshipLabel>
    <relationshipName>Estimates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Estimate__c/fields/TotalAdjustments__c.field-meta.xml
<CustomField>
    <fullName>TotalAdjustments__c</fullName>
    <formula>SummaryId__r.TotalAdjustments__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Adjustments</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/TaskRoleSummary__c.object-meta.xml
<CustomObject>
    <label>Task Role Summary</label>
    <nameField>
        <displayFormat>TRS-{00000}</displayFormat>
        <label>Task Role Summary</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Role Summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TaskRoleSummary__c/fields/ActivityGroupId__c.field-meta.xml
<CustomField>
    <fullName>ActivityGroupId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity Group</label>
    <referenceTo>ActivityGroup__c</referenceTo>
    <relationshipName>RoleSummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/ActivityId__c.field-meta.xml
<CustomField>
    <fullName>ActivityId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity</label>
    <referenceTo>Activity__c</referenceTo>
    <relationshipName>RoleSummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/EstimateId__c.field-meta.xml
<CustomField>
    <fullName>EstimateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estimate</label>
    <referenceTo>Estimate__c</referenceTo>
    <relationshipName>RoleSummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/LevelAdjustment__c.field-meta.xml
<CustomField>
    <fullName>LevelAdjustment__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Level Adjustment</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/ResourceRoleId__c.field-meta.xml
<CustomField>
    <fullName>ResourceRoleId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Role</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource Role</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipName>LevelSummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/SummaryId__c.field-meta.xml
<CustomField>
    <fullName>SummaryId__c</fullName>
    <label>Summary</label>
    <referenceTo>TaskSummary__c</referenceTo>
    <relationshipName>RoleSummaries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/SummaryLevel__c.field-meta.xml
<CustomField>
    <fullName>SummaryLevel__c</fullName>
    <label>Summary Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Estimate</fullName>
            </value>
            <value>
                <fullName>Activity Group</fullName>
            </value>
            <value>
                <fullName>Activity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/TaskRoleSummaryId__c.field-meta.xml
<CustomField>
    <fullName>TaskRoleSummaryId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task Role Summary</label>
    <referenceTo>TaskRoleSummary__c</referenceTo>
    <relationshipName>ExtendedTaskRoleSummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/TotalAdjustments__c.field-meta.xml
<CustomField>
    <fullName>TotalAdjustments__c</fullName>
    <formula>RolledUpAdjustments__c + LevelAdjustments__c + LevelAdjustment__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Adjustments</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/TotalCalculatedDuration__c.field-meta.xml
<CustomField>
    <fullName>TotalCalculatedDuration__c</fullName>
    <formula>RolledUpCalculatedDuration__c + CalculatedDuration__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Calculated Duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/TotalEstimatedDuration__c.field-meta.xml
<CustomField>
    <fullName>TotalEstimatedDuration__c</fullName>
    <formula>TotalCalculatedDuration__c + TotalAdjustments__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Estimated Duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/EstimateTreeSummarySupport.cls
/*
 * Provus Services Quoting
 * Copyright (c) 2022 Provus Inc. All rights reserved.
 */
public with sharing class EstimateTreeSummarySupport {
	public static void createRoleSummaryLineageForActivity(
		Id activityId,
		Id resourceRoleId,
		Decimal levelAdjustment
	) {
		TaskRoleSummary__c estimateSummary;
		TaskRoleSummary__c groupSummary;

		Activity__c activitySO = [
			SELECT
				EstimateId__c,
				SummaryId__c,
				EstimateId__r.SummaryId__c,
				ActivityGroupId__c,
				ActivityGroupId__r.SummaryId__c
			FROM Activity__c
			WHERE Id = :activityId
			WITH SECURITY_ENFORCED
		];

		for (
			TaskRoleSummary__c summary : getRoleSummaryLineageForActivity(activityId, resourceRoleId)
		) {
			if (estimateSummary != null && groupSummary != null) {
				break;
			}

			if (summary.SummaryLevel__c == EstimatorConstants.ESTIMATE) {
				estimateSummary = summary;
			} else if (summary.SummaryLevel__c == EstimatorConstants.ACTIVITY_GROUP) {
				groupSummary = summary;
			}
		}

		if (estimateSummary == null) {
			estimateSummary = new TaskRoleSummary__c(
				ResourceRoleId__c = resourceRoleId,
				EstimateId__c = activitySO.EstimateId__c,
				SummaryId__c = activitySO.EstimateId__r.SummaryId__c,
				SummaryLevel__c = EstimatorConstants.ESTIMATE
			);

			CRUDUtility.insertRecords(estimateSummary);
		}

		if (groupSummary == null) {
			groupSummary = new TaskRoleSummary__c(
				ResourceRoleId__c = resourceRoleId,
				ActivityGroupId__c = activitySO.ActivityGroupId__c,
				SummaryId__c = activitySO.ActivityGroupId__r.SummaryId__c,
				SummaryLevel__c = EstimatorConstants.ACTIVITY_GROUP,
				TaskRoleSummaryId__c = estimateSummary.Id
			);

			CRUDUtility.insertRecords(groupSummary);
		}

		TaskRoleSummary__c activitySummary = new TaskRoleSummary__c(
			ResourceRoleId__c = resourceRoleId,
			ActivityId__c = activityId,
			SummaryId__c = activitySO.SummaryId__c,
			SummaryLevel__c = EstimatorConstants.ACTIVITY,
			TaskRoleSummaryId__c = groupSummary.Id
		);

		CRUDUtility.insertRecords(activitySummary);

		activitySummary.LevelAdjustment__c = levelAdjustment;
		CRUDUtility.upsertRecords(activitySummary);
	}

	public static void createRoleSummaryLineageForActivityGroup(
		Id groupId,
		Id resourceRoleId,
		Decimal levelAdjustment
	) {
		TaskRoleSummary__c estimateSummary;

		ActivityGroup__c groupSO = [
			SELECT EstimateId__c, SummaryId__c, EstimateId__r.SummaryId__c
			FROM ActivityGroup__c
			WHERE Id = :groupId
			WITH SECURITY_ENFORCED
		];

		for (
			TaskRoleSummary__c summary : getRoleSummaryLineageForActivityGroup(groupId, resourceRoleId)
		) {
			if (summary.SummaryLevel__c == EstimatorConstants.ESTIMATE) {
				estimateSummary = summary;
				break;
			}
		}

		if (estimateSummary == null) {
			estimateSummary = new TaskRoleSummary__c(
				ResourceRoleId__c = resourceRoleId,
				EstimateId__c = groupSO.EstimateId__c,
				SummaryId__c = groupSO.EstimateId__r.SummaryId__c,
				SummaryLevel__c = EstimatorConstants.ESTIMATE
			);
			CRUDUtility.insertRecords(estimateSummary);
		}

		TaskRoleSummary__c groupSummarySO = new TaskRoleSummary__c(
			ResourceRoleId__c = resourceRoleId,
			ActivityGroupId__c = groupId,
			SummaryId__c = groupSO.SummaryId__c,
			SummaryLevel__c = EstimatorConstants.ACTIVITY_GROUP,
			TaskRoleSummaryId__c = estimateSummary.Id
		);

		CRUDUtility.insertRecords(groupSummarySO);

		groupSummarySO.LevelAdjustment__c = levelAdjustment;
		CRUDUtility.updateRecords(groupSummarySO);
	}

	public static List<TaskRoleSummary__c> getRoleSummaryLineageForActivity(
		Id activityId,
		Id resourceRoleId
	) {
		Activity__c actSO = [
			SELECT ActivityGroupId__c, EstimateId__c
			FROM Activity__c
			WHERE Id = :activityId
			WITH SECURITY_ENFORCED
		];

		return [
			SELECT Id, SummaryLevel__c
			FROM TaskRoleSummary__c
			WHERE
				(ActivityId__c = :activityId
				OR ActivityGroupId__c = :actSO.ActivityGroupId__c
				OR EstimateId__c = :actSO.EstimateId__c)
				AND ResourceRoleId__c = :resourceRoleId
			WITH SECURITY_ENFORCED
		];
	}

	public static List<TaskRoleSummary__c> getRoleSummaryLineageForActivityGroup(
		Id activityGroupId,
		Id resourceRoleId
	) {
		ActivityGroup__c groupSO = [
			SELECT EstimateId__c
			FROM ActivityGroup__c
			WHERE Id = :activityGroupId
			WITH SECURITY_ENFORCED
		];

		return [
			SELECT Id, SummaryLevel__c
			FROM TaskRoleSummary__c
			WHERE
				(ActivityGroupId__c = :activityGroupId
				OR EstimateId__c = :groupSO.EstimateId__c)
				AND ResourceRoleId__c = :resourceRoleId
			WITH SECURITY_ENFORCED
		];
	}

	public static Object getSummaryRecords(String recordId, String type) {
		if (type == 'Activity') {
			return [
				SELECT
					Id,
					ResourceRole__c,
					ResourceRoleId__r.Name,
					TotalCalculatedDuration__c,
					TotalAdjustments__c,
					LevelAdjustment__c,
					TotalEstimatedDuration__c
				FROM TaskRoleSummary__c
				WHERE ActivityId__c = :recordId
				WITH SECURITY_ENFORCED
			];
		} else if (type == EstimateTreeSupport.ACTIVITY_GROUP) {
			return [
				SELECT
					Id,
					ResourceRole__c,
					ResourceRoleId__r.Name,
					TotalCalculatedDuration__c,
					TotalAdjustments__c,
					LevelAdjustment__c,
					TotalEstimatedDuration__c
				FROM TaskRoleSummary__c
				WHERE ActivityGroupId__c = :recordId
				WITH SECURITY_ENFORCED
			];
		} else if (type == 'Estimate') {
			return [
				SELECT
					Id,
					ResourceRole__c,
					ResourceRoleId__r.Name,
					TotalCalculatedDuration__c,
					TotalAdjustments__c,
					LevelAdjustment__c,
					TotalEstimatedDuration__c
				FROM TaskRoleSummary__c
				WHERE EstimateId__c = :recordId
				WITH SECURITY_ENFORCED
			];
		} else {
			return null;
		}
	}

	public static void createSummaryRecords(TaskRoleSummary__c taskRoleSummary, String typeof) {
		Id summaryId;
		String summaryLevel;
		if (typeof == EstimatorConstants.ESTIMATE) {
			summaryLevel = EstimatorConstants.ESTIMATE;
			summaryId = [
				SELECT Id, SummaryId__c
				FROM Estimate__c
				WHERE Id = :taskRoleSummary.EstimateId__c
			]
			.SummaryId__c;
			taskRoleSummary.SummaryId__c = summaryId;
			taskRoleSummary.SummaryLevel__c = summaryLevel;
			CRUDUtility.insertRecords(taskRoleSummary);
		} else if (typeof == EstimateTreeSupport.ACTIVITY_GROUP) {
			EstimateTreeSummarySupport.createRoleSummaryLineageForActivityGroup(
				taskRoleSummary.ActivityGroupId__c,
				taskRoleSummary.ResourceRoleId__c,
				taskRoleSummary.LevelAdjustment__c
			);
		} else if (typeof == EstimatorConstants.ACTIVITY) {
			EstimateTreeSummarySupport.createRoleSummaryLineageForActivity(
				taskRoleSummary.ActivityId__c,
				taskRoleSummary.ResourceRoleId__c,
				taskRoleSummary.LevelAdjustment__c
			);
		}
	}
}