force-app/main/default/objects/Activity__c/Activity__c.object-meta.xml
<CustomObject>
    <label>Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity__c/fields/ActivityGroupId__c.field-meta.xml
<CustomField>
    <fullName>ActivityGroupId__c</fullName>
    <label>Activity Group</label>
    <referenceTo>ActivityGroup__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/EstimateId__c.field-meta.xml
<CustomField>
    <fullName>EstimateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estimate</label>
    <referenceTo>Estimate__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/IsNotApplicable__c.field-meta.xml
<CustomField>
    <fullName>IsNotApplicable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Not Applicable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Path__c.field-meta.xml
<CustomField>
    <fullName>Path__c</fullName>
    <formula>TEXT(ActivityGroupId__r.Sequence__c)+&apos;.&apos;+ TEXT(Sequence__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Path</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ActivityGroup__c/ActivityGroup__c.object-meta.xml
<CustomObject>
    <label>Activity Group</label>
    <nameField>
        <label>Activity Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ActivityGroup__c/fields/EstimateId__c.field-meta.xml
<CustomField>
    <fullName>EstimateId__c</fullName>
    <label>Estimate</label>
    <referenceTo>Estimate__c</referenceTo>
    <relationshipLabel>Activity Groups</relationshipLabel>
    <relationshipName>ActivityGroups</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ActivityGroup__c/fields/TotalCalculatedDuration__c.field-meta.xml
<CustomField>
    <fullName>TotalCalculatedDuration__c</fullName>
    <formula>SummaryId__r.TotalCalculatedDuration__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Calculated Duration</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ActivityGroup__c/fields/TotalEstimatedDuration__c.field-meta.xml
<CustomField>
    <fullName>TotalEstimatedDuration__c</fullName>
    <formula>SummaryId__r.TotalEstimatedDuration__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Estimated Duration</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/ActivityGroupId__c.field-meta.xml
<CustomField>
    <fullName>ActivityGroupId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity Group</label>
    <referenceTo>ActivityGroup__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/ActivityId__c.field-meta.xml
<CustomField>
    <fullName>ActivityId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity</label>
    <referenceTo>Activity__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/AdjustmentReason__c.field-meta.xml
<CustomField>
    <fullName>AdjustmentReason__c</fullName>
    <label>Adjustment Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/CalculatedDuration__c.field-meta.xml
<CustomField>
    <fullName>CalculatedDuration__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Calculated Duration</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/EstimatedDuration__c.field-meta.xml
<CustomField>
    <fullName>EstimatedDuration__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Estimated Duration</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/EstimateId__c.field-meta.xml
<CustomField>
    <fullName>EstimateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estimate</label>
    <referenceTo>Estimate__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Path__c.field-meta.xml
<CustomField>
    <fullName>Path__c</fullName>
    <formula
	>TEXT(ActivityId__r.ActivityGroupId__r.Sequence__c) +&apos;.&apos; + TEXT(ActivityId__r.Sequence__c) +&apos;.&apos; +  TEXT(Sequence__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Path</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/ResourceRoleId__c.field-meta.xml
<CustomField>
    <fullName>ResourceRoleId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Role</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource Role</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/RoleSummaryId__c.field-meta.xml
<CustomField>
    <fullName>RoleSummaryId__c</fullName>
    <label>Role Summary</label>
    <referenceTo>TaskRoleSummary__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/TemplateId__c.field-meta.xml
<CustomField>
    <fullName>TemplateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task Template</label>
    <referenceTo>TaskTemplate__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TaskParameterValue__c/TaskParameterValue__c.object-meta.xml
<CustomObject>
    <label>Task Parameter Value</label>
    <nameField>
        <displayFormat>TPV-{00000}</displayFormat>
        <label>Task Parameter Value</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Parameter Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TaskParameterValue__c/fields/BooleanValue__c.field-meta.xml
<CustomField>
    <fullName>BooleanValue__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Boolean Value</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TaskParameterValue__c/fields/TemplateId__c.field-meta.xml
<CustomField>
    <fullName>TemplateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task Parameter Template</label>
    <referenceTo>TaskParameterTemplate__c</referenceTo>
    <relationshipName>TaskParameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/TaskRoleSummary__c.object-meta.xml
<CustomObject>
    <label>Task Role Summary</label>
    <nameField>
        <displayFormat>TRS-{00000}</displayFormat>
        <label>Task Role Summary</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Role Summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TaskRoleSummary__c/fields/ActivityGroupId__c.field-meta.xml
<CustomField>
    <fullName>ActivityGroupId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity Group</label>
    <referenceTo>ActivityGroup__c</referenceTo>
    <relationshipName>RoleSummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/ActivityId__c.field-meta.xml
<CustomField>
    <fullName>ActivityId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity</label>
    <referenceTo>Activity__c</referenceTo>
    <relationshipName>RoleSummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/CalculatedDuration__c.field-meta.xml
<CustomField>
    <fullName>CalculatedDuration__c</fullName>
    <label>Calculated Duration</label>
    <summarizedField>Task__c.CalculatedDuration__c</summarizedField>
    <summaryForeignKey>Task__c.RoleSummaryId__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/EstimatedDuration__c.field-meta.xml
<CustomField>
    <fullName>EstimatedDuration__c</fullName>
    <label>Estimated Duration</label>
    <summarizedField>Task__c.EstimatedDuration__c</summarizedField>
    <summaryForeignKey>Task__c.RoleSummaryId__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/EstimateId__c.field-meta.xml
<CustomField>
    <fullName>EstimateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estimate</label>
    <referenceTo>Estimate__c</referenceTo>
    <relationshipName>RoleSummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/LevelAdjustment__c.field-meta.xml
<CustomField>
    <fullName>LevelAdjustment__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Level Adjustment</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/ResourceRoleId__c.field-meta.xml
<CustomField>
    <fullName>ResourceRoleId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Role</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource Role</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipName>LevelSummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/TotalAdjustments__c.field-meta.xml
<CustomField>
    <fullName>TotalAdjustments__c</fullName>
    <formula>RolledUpAdjustments__c + LevelAdjustments__c + LevelAdjustment__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Adjustments</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/TotalCalculatedDuration__c.field-meta.xml
<CustomField>
    <fullName>TotalCalculatedDuration__c</fullName>
    <formula>RolledUpCalculatedDuration__c + CalculatedDuration__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Calculated Duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/TotalEstimatedDuration__c.field-meta.xml
<CustomField>
    <fullName>TotalEstimatedDuration__c</fullName>
    <formula>TotalCalculatedDuration__c + TotalAdjustments__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Estimated Duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TaskTemplate__c/TaskTemplate__c.object-meta.xml
<CustomObject>
    <label>Task Template</label>
    <nameField>
        <label>Task Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TaskTemplate__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TaskTemplate__c/fields/Path__c.field-meta.xml
<CustomField>
    <fullName>Path__c</fullName>
    <formula>ActivityTemplateId__r.Path__c+&apos;.&apos;+ TEXT(Sequence__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Path</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TaskTemplate__c/fields/ResourceRoleId__c.field-meta.xml
<CustomField>
    <fullName>ResourceRoleId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Role</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource Role</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Task Templates</relationshipLabel>
    <relationshipName>TaskTemplates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EstimateTreeController.cls
/*
 * Provus Services Quoting
 * Copyright (c) 2022 Provus Inc. All rights reserved.
 */
public with sharing class EstimateTreeController {
	//This method is used for fetching the tree structure..
	@AuraEnabled(Cacheable=true)
	public static Object getRecords(String estimateId) {
		List<ActivityGroup__c> activityGroups = [
			SELECT
				Id,
				Name,
				Sequence__c,
				TotalCalculatedDuration__c,
				TotalAdjustments__c,
				TotalEstimatedDuration__c,
				TotalLevelAdjustments__c,
				IsNotApplicable__c
			FROM ActivityGroup__c
			WHERE EstimateId__c = :estimateId
			WITH SECURITY_ENFORCED
			ORDER BY Sequence__c ASC
		];
		//Querying the Activity, Tasks..
		Map<Id, List<Activity__c>> activityGroupActivityMap = mapActivitiesByGroupId(activityGroups);

		//Querying the Summary role records at the Activitygroup level for the Resources..
		Map<Id, String> roleSumMp = roleSummaryMap(estimateId);

		//Forming the JSON structure.
		List<String> gridExpanedIds = new List<String>();
		List<Object> objlst = new List<Object>();
		for (ActivityGroup__c ag : activityGroups) {
			//Building the Activity Groups
			Map<String, Object> aGmp = new Map<String, Object>();
			aGmp.put('Type', EstimateTreeSupport.ACTIVITY_GROUP);
			aGmp.put(EstimateTreeSupport.ACTIVITY_GROUP, ag.Sequence__c + ' ' + ag.Name);
			aGmp.put('ActivityGroupName', ag.Name);
			aGmp.put('ActivityGroupId', ag.Id);
			aGmp.put('EstimatedDuration', ag.TotalEstimatedDuration__c);
			aGmp.put('AdjustedDuration', ag.TotalAdjustments__c);
			aGmp.put('levelAdjustments', ag.TotalLevelAdjustments__c);
			aGmp.put('CalculatedDuration', ag.TotalCalculatedDuration__c);
			aGmp.put('IconType', 'standard:work_type_group');
			aGmp.put('NotApplicable', ag.IsNotApplicable__c);
			aGmp.put('ActionbuttonTitle', 'Resource Summary');
			aGmp.put('ActionIcon', 'action:share_poll');
			gridExpanedIds.add(ag.Id);
			if (activityGroupActivityMap.containsKey(ag.Id)) {
				aGmp.put(
					'_children',
					EstimateTreeSupport.createActivityAndTask(
						activityGroupActivityMap.get(ag.Id),
						gridExpanedIds,
						roleSumMp
					)
				);
			}
			if (roleSumMp.containsKey(ag.Id)) {
				aGmp.put('Resourcerole', roleSumMp.get(ag.Id));
			}
			objlst.add(aGmp);
		}
		for (Object obj : objlst) {
			Map<String, Object> agmp = (Map<String, Object>) obj;
			agmp.put('gridExpandedIds', gridExpanedIds);
			break;
		}
		return objlst;
	}

	@TestVisible
	private static Map<Id, List<Activity__c>> mapActivitiesByGroupId(
		List<ActivityGroup__c> activityGroups
	) {
		Map<Id, List<Activity__c>> activityGroupActivityMap = new Map<Id, List<Activity__c>>();

		for (Activity__c activity : [
			SELECT
				Id,
				ActivityGroupId__r.Name,
				Path__c,
				IsNotApplicable__c,
				TotalCalculatedDuration__c,
				TotalLevelAdjustments__c,
				TotalAdjustments__c,
				TotalEstimatedDuration__c,
				Name,
				(
					SELECT
						Id,
						Name,
						TemplateId__c,
						Path__c,
						AdjustmentReason__c,
						IsNotApplicable__c,
						LevelAdjustment__c,
						CalculatedDuration__c,
						EstimatedDuration__c,
						ResourceRoleId__r.Name
					FROM Tasks__r
					WHERE IsActive__c = TRUE
					ORDER BY Sequence__c ASC
				)
			FROM Activity__c
			WHERE ActivityGroupId__c IN :activityGroups
			WITH SECURITY_ENFORCED
			ORDER BY Sequence__c ASC
		]) {
			List<Activity__c> activities = activityGroupActivityMap.get(activity.ActivityGroupId__r.Id);
			if (activities == null) {
				activities = new List<Activity__c>();
				activityGroupActivityMap.put(activity.ActivityGroupId__r.Id, activities);
			}

			activities.add(activity);
		}

		return activityGroupActivityMap;
	}

	@TestVisible
	private static Map<Id, String> roleSummaryMap(Id estimateId) {
		Map<Id, String> roleByGroupId = new Map<Id, String>();

		for (TaskRoleSummary__c summary : [
			SELECT Id, ActivityGroupId__c, ActivityId__c, ResourceRoleId__r.Name
			FROM TaskRoleSummary__c
			WHERE EstimateId__c = :estimateId
			WITH SECURITY_ENFORCED
		]) {
			putRoleActivityGroup(roleByGroupId, summary);
			putRoleActivity(roleByGroupId, summary);
		}

		return roleByGroupId;
	}

	private static void putRoleActivityGroup(
		Map<Id, String> roleByGroupId,
		TaskRoleSummary__c summary
	) {
		if (!roleByGroupId.containsKey(summary.ActivityGroupId__c)) {
			roleByGroupId.put(summary.ActivityGroupId__c, summary.ResourceRoleId__r.Name);
		} else {
			roleByGroupId.put(
				summary.ActivityGroupId__c,
				roleByGroupId.get(summary.ActivityGroupId__c) +
				',' +
				summary.ResourceRoleId__r.Name
			);
		}
	}

	private static void putRoleActivity(Map<Id, String> roleSumMap, TaskRoleSummary__c rlsum) {
		if (!roleSumMap.containsKey(rlsum.ActivityId__c)) {
			roleSumMap.put(rlsum.ActivityId__c, rlsum.ResourceRoleId__r.Name);
		} else {
			roleSumMap.put(
				rlsum.ActivityId__c,
				roleSumMap.get(rlsum.ActivityId__c) +
				',' +
				rlsum.ResourceRoleId__r.Name
			);
		}
	}

	//This method is used for Updating of Task and Value record..
	@AuraEnabled
	public static void updateTask(Task__c tsk, List<TaskParameterValue__c> taskParams) {
		CRUDUtility.updateRecords(tsk);
		if (taskParams != null) {
			CRUDUtility.updateRecords(taskParams);
		}
	}
	//This method is used for getting the Summary by role records at the estimate,Activitygroup and activity level..
	@AuraEnabled
	public static Object getSummaryRecords(String recordId, String type) {
		return EstimateTreeSummarySupport.getSummaryRecords(recordId, type);
	}

	//Query the Scope of the Estimate..
	@AuraEnabled
	public static List<TaskParameterValue__c> getSourceSummary(String estimateId) {
		List<TaskParameterValue__c> tpvLst = [
			SELECT
				Id,
				BooleanValue__c,
				IntegerValue__c,
				TextValue__c,
				TemplateId__r.Name,
				TemplateId__r.DataType__c,
				TaskId__c,
				TaskId__r.IsNotApplicable__c,
				TaskId__r.Name,
				TaskId__r.ActivityId__r.Name,
				TaskId__r.ActivityId__r.ActivityGroupId__r.Name,
				TaskId__r.EstimatedDuration__c,
				Name
			FROM TaskParameterValue__c
			WHERE TaskId__r.EstimateId__c = :estimateId
			WITH SECURITY_ENFORCED
			ORDER BY TaskId__r.Path__c ASC
		];
		return tpvLst;
	}
	//When UpdateNotApplicable is checked at the ActivityGroup or Activity Level..
	@AuraEnabled
	public static void updateNotApplicableField(String recordId, Boolean notApplicable, String type) {
		if (type == EstimateTreeSupport.ACTIVITY_GROUP) {
			EstimateTreeSupport.notApplicableForActivityGroup(recordId, notApplicable, type);
		} else if (type == 'Activity') {
			EstimateTreeSupport.notApplicableForActivity(recordId, notApplicable, type);
		}
	}

	//This method is invoked when Edit task is invoked from the task row.
	@AuraEnabled
	public static Map<String, Object> getTaskDetails(String taskId) {
		return EstimateTreeTaskSupport.getTaskDetails(taskId);
	}

	//Create a level Summary Record..
	@AuraEnabled
	public static void createSummaryRecords(TaskRoleSummary__c summaryRecord, String typeof) {
		EstimateTreeSummarySupport.createSummaryRecords(summaryRecord, typeof);
	}
}