force-app/main/default/objects/Activity__c/Activity__c.object-meta.xml
<CustomObject>
    <label>Activity</label>
    <nameField>
        <label>Activity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Activity__c/fields/ActivityGroupId__c.field-meta.xml
<CustomField>
    <fullName>ActivityGroupId__c</fullName>
    <label>Activity Group</label>
    <referenceTo>ActivityGroup__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/IsNotApplicable__c.field-meta.xml
<CustomField>
    <fullName>IsNotApplicable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Not Applicable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Activity__c/fields/Path__c.field-meta.xml
<CustomField>
    <fullName>Path__c</fullName>
    <formula>TEXT(ActivityGroupId__r.Sequence__c)+&apos;.&apos;+ TEXT(Sequence__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Path</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ActivityGroup__c/ActivityGroup__c.object-meta.xml
<CustomObject>
    <label>Activity Group</label>
    <nameField>
        <label>Activity Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ActivityGroup__c/fields/TotalCalculatedDuration__c.field-meta.xml
<CustomField>
    <fullName>TotalCalculatedDuration__c</fullName>
    <formula>SummaryId__r.TotalCalculatedDuration__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Calculated Duration</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ActivityGroup__c/fields/TotalEstimatedDuration__c.field-meta.xml
<CustomField>
    <fullName>TotalEstimatedDuration__c</fullName>
    <formula>SummaryId__r.TotalEstimatedDuration__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Estimated Duration</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/ResourceRole.recordType-meta.xml
<RecordType>
    <fullName>ResourceRole</fullName>
    <active>true</active>
    <label>Resource Role</label>
</RecordType>

force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/ActivityGroupId__c.field-meta.xml
<CustomField>
    <fullName>ActivityGroupId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity Group</label>
    <referenceTo>ActivityGroup__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/ActivityId__c.field-meta.xml
<CustomField>
    <fullName>ActivityId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity</label>
    <referenceTo>Activity__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/AdjustmentReason__c.field-meta.xml
<CustomField>
    <fullName>AdjustmentReason__c</fullName>
    <label>Adjustment Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/CalculatedDuration__c.field-meta.xml
<CustomField>
    <fullName>CalculatedDuration__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Calculated Duration</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/EstimatedDuration__c.field-meta.xml
<CustomField>
    <fullName>EstimatedDuration__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Estimated Duration</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/Path__c.field-meta.xml
<CustomField>
    <fullName>Path__c</fullName>
    <formula
	>TEXT(ActivityId__r.ActivityGroupId__r.Sequence__c) +&apos;.&apos; + TEXT(ActivityId__r.Sequence__c) +&apos;.&apos; +  TEXT(Sequence__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Path</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/ResourceRoleId__c.field-meta.xml
<CustomField>
    <fullName>ResourceRoleId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Role</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource Role</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/RoleSummaryId__c.field-meta.xml
<CustomField>
    <fullName>RoleSummaryId__c</fullName>
    <label>Role Summary</label>
    <referenceTo>TaskRoleSummary__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/TemplateId__c.field-meta.xml
<CustomField>
    <fullName>TemplateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task Template</label>
    <referenceTo>TaskTemplate__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TaskParameterTemplate__c/TaskParameterTemplate__c.object-meta.xml
<CustomObject>
    <label>Task Parameter Template</label>
    <nameField>
        <label>Task Parameter Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Parameter Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TaskParameterTemplate__c/fields/DataType__c.field-meta.xml
<CustomField>
    <fullName>DataType__c</fullName>
    <label>Data Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Checkbox</fullName>
            </value>
            <value>
                <fullName>Integer</fullName>
            </value>
            <value>
                <fullName>Integer Tiers</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TaskParameterValue__c/TaskParameterValue__c.object-meta.xml
<CustomObject>
    <label>Task Parameter Value</label>
    <nameField>
        <displayFormat>TPV-{00000}</displayFormat>
        <label>Task Parameter Value</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Parameter Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TaskParameterValue__c/fields/BooleanValue__c.field-meta.xml
<CustomField>
    <fullName>BooleanValue__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Boolean Value</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TaskParameterValue__c/fields/IntegerValue__c.field-meta.xml
<CustomField>
    <fullName>IntegerValue__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Integer Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TaskParameterValue__c/fields/TaskId__c.field-meta.xml
<CustomField>
    <fullName>TaskId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task</label>
    <referenceTo>Task__c</referenceTo>
    <relationshipName>ParameterValues</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TaskParameterValue__c/fields/TemplateId__c.field-meta.xml
<CustomField>
    <fullName>TemplateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task Parameter Template</label>
    <referenceTo>TaskParameterTemplate__c</referenceTo>
    <relationshipName>TaskParameters</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/TaskRoleSummary__c.object-meta.xml
<CustomObject>
    <label>Task Role Summary</label>
    <nameField>
        <displayFormat>TRS-{00000}</displayFormat>
        <label>Task Role Summary</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Role Summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TaskRoleSummary__c/fields/ActivityGroupId__c.field-meta.xml
<CustomField>
    <fullName>ActivityGroupId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity Group</label>
    <referenceTo>ActivityGroup__c</referenceTo>
    <relationshipName>RoleSummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/ActivityId__c.field-meta.xml
<CustomField>
    <fullName>ActivityId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Activity</label>
    <referenceTo>Activity__c</referenceTo>
    <relationshipName>RoleSummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/CalculatedDuration__c.field-meta.xml
<CustomField>
    <fullName>CalculatedDuration__c</fullName>
    <label>Calculated Duration</label>
    <summarizedField>Task__c.CalculatedDuration__c</summarizedField>
    <summaryForeignKey>Task__c.RoleSummaryId__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/EstimatedDuration__c.field-meta.xml
<CustomField>
    <fullName>EstimatedDuration__c</fullName>
    <label>Estimated Duration</label>
    <summarizedField>Task__c.EstimatedDuration__c</summarizedField>
    <summaryForeignKey>Task__c.RoleSummaryId__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/LevelAdjustment__c.field-meta.xml
<CustomField>
    <fullName>LevelAdjustment__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Level Adjustment</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/ResourceRoleId__c.field-meta.xml
<CustomField>
    <fullName>ResourceRoleId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Role</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource Role</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipName>LevelSummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/TotalAdjustments__c.field-meta.xml
<CustomField>
    <fullName>TotalAdjustments__c</fullName>
    <formula>RolledUpAdjustments__c + LevelAdjustments__c + LevelAdjustment__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Adjustments</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/TotalCalculatedDuration__c.field-meta.xml
<CustomField>
    <fullName>TotalCalculatedDuration__c</fullName>
    <formula>RolledUpCalculatedDuration__c + CalculatedDuration__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Calculated Duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/TotalEstimatedDuration__c.field-meta.xml
<CustomField>
    <fullName>TotalEstimatedDuration__c</fullName>
    <formula>TotalCalculatedDuration__c + TotalAdjustments__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Estimated Duration</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/EstimateTreeSupport.cls
/*
 * Provus Services Quoting
 * Copyright (c) 2022 Provus Inc. All rights reserved.
 */
public with sharing class EstimateTreeSupport {
	public static final String ACTIVITY_GROUP = 'ActivityGroup';

	public static Object createActivityAndTask(
		List<Activity__c> activityList,
		List<String> gridExpanedIds,
		Map<Id, String> roleSumMp
	) {
		List<Object> activityGroupChildren = new List<Object>();
		for (Activity__c activity : activityList) {
			Map<String, Object> activityMap = processActivity(activity, gridExpanedIds);
			List<Object> taskObj = new List<Object>();
			if (activity.Tasks__r != null) {
				for (Task__c task : activity.Tasks__r) {
					//Building the Task
					taskObj.add(processTask(task, gridExpanedIds));
				}
			}
			if (roleSumMp.containsKey(activity.Id)) {
				activityMap.put('Resourcerole', roleSumMp.get(activity.Id));
			}
			activityMap.put('_children', taskObj);
			activityGroupChildren.add(activityMap);
		}
		return activityGroupChildren;
	}

	private static Map<String, Object> processActivity(
		Activity__c activity,
		List<String> gridExpanedIds
	) {
		Map<String, Object> activityMap = new Map<String, Object>();
		//Building the Activities
		activityMap.put('Type', 'Activity');
		activityMap.put(ACTIVITY_GROUP, activity.Path__c + ' ' + activity.Name);
		activityMap.put('ActivityGroupName', activity.Name);
		activityMap.put('ActivityGroupId', activity.Id);
		activityMap.put('EstimatedDuration', activity.TotalEstimatedDuration__c);
		activityMap.put('AdjustedDuration', activity.TotalAdjustments__c);
		activityMap.put('levelAdjustments', activity.TotalLevelAdjustments__c);
		activityMap.put('CalculatedDuration', activity.TotalCalculatedDuration__c);
		activityMap.put('IconType', 'standard:work_type');
		activityMap.put('NotApplicable', activity.IsNotApplicable__c);
		activityMap.put('ActionbuttonTitle', 'Resource Summary');
		activityMap.put('ActionIcon', 'action:share_poll');
		gridExpanedIds.add(activity.Id);
		return activityMap;
	}

	private static Map<String, Object> processTask(Task__c task, List<String> gridExpanedIds) {
		Map<String, Object> taskMap = new Map<String, Object>();
		taskMap.put('Type', 'Task');
		taskMap.put(ACTIVITY_GROUP, task.Path__c + ' ' + task.Name);
		taskMap.put('ActivityGroupName', task.Name);
		taskMap.put('ActivityGroupId', task.Id);
		taskMap.put('AdjustmentReason', task.AdjustmentReason__c);
		taskMap.put(
			'EstimatedDuration',
			task.EstimatedDuration__c != null ? task.EstimatedDuration__c : 0
		);
		taskMap.put('levelAdjustments', task.LevelAdjustment__c != null ? task.LevelAdjustment__c : 0);
		taskMap.put(
			'CalculatedDuration',
			task.CalculatedDuration__c != null ? task.CalculatedDuration__c : 0
		);
		taskMap.put('Resourcerole', task.ResourceRoleId__r.Name);
		taskMap.put('IconType', 'standard:task');
		taskMap.put('NotTouched', task.EstimatedDuration__c == 0 ? 'utility:warning' : '');
		if (task.IsNotApplicable__c) {
			taskMap.put('NotTouched', '');
		}
		taskMap.put('TaskTemplateId', task.TemplateId__c);
		taskMap.put('NotApplicable', task.IsNotApplicable__c);
		taskMap.put('ActionbuttonTitle', 'Edit Task');
		taskMap.put('ActionIcon', 'action:edit');
		gridExpanedIds.add(task.Id);
		return taskMap;
	}

	public static void notApplicableForActivity(String recordId, Boolean notApplicable, String type) {
		Activity__c at = new Activity__c();
		at.Id = recordId;
		at.IsNotApplicable__c = notApplicable;
		CRUDUtility.updateRecords(at);
		Id activityGrpId;
		List<Task__c> tklst = [
			SELECT
				Id,
				ActivityId__r.ActivityGroupId__c,
				IsNotApplicable__c,
				CalculatedDuration__c,
				LevelAdjustment__c,
				EstimatedDuration__c
			FROM Task__c
			WHERE ActivityId__c = :recordId
			WITH SECURITY_ENFORCED
		];
		for (Task__c tk : tklst) {
			activityGrpId = tk.ActivityId__r.ActivityGroupId__c;
			tk.IsNotApplicable__c = notApplicable;
			if (notApplicable) {
				tk.CalculatedDuration__c = 0;
				tk.LevelAdjustment__c = 0;
				tk.EstimatedDuration__c = 0;
			}
		}
		CRUDUtility.updateRecords(tklst);
		if (!notApplicable) {
			ActivityGroup__c ag = new ActivityGroup__c();
			ag.Id = activityGrpId;
			ag.IsNotApplicable__c = notApplicable;
			CRUDUtility.updateRecords(ag);
		}
		if (notApplicable) {
			List<TaskRoleSummary__c> actSumRllst = [
				SELECT Id, LevelAdjustment__c
				FROM TaskRoleSummary__c
				WHERE ActivityId__c = :recordId
				WITH SECURITY_ENFORCED
			];
			for (TaskRoleSummary__c asm : actSumRllst) {
				asm.LevelAdjustment__c = 0;
			}
			CRUDUtility.updateRecords(actSumRllst);
		}
	}

	public static void notApplicableForActivityGroup(
		String recordId,
		Boolean notApplicable,
		String type
	) {
		ActivityGroup__c ag = new ActivityGroup__c();
		ag.Id = recordId;
		ag.IsNotApplicable__c = notApplicable;
		CRUDUtility.updateRecords(ag);
		List<Activity__c> actLst = [
			SELECT Id, IsNotApplicable__c
			FROM Activity__c
			WHERE ActivityGroupId__c = :recordId
			WITH SECURITY_ENFORCED
		];
		for (Activity__c tk : actLst) {
			tk.IsNotApplicable__c = notApplicable;
		}
		CRUDUtility.updateRecords(actLst);
		List<Task__c> tklst = [
			SELECT Id, IsNotApplicable__c, CalculatedDuration__c, LevelAdjustment__c, EstimatedDuration__c
			FROM Task__c
			WHERE ActivityId__r.ActivityGroupId__c = :recordId
			WITH SECURITY_ENFORCED
		];
		for (Task__c tk : tklst) {
			tk.IsNotApplicable__c = notApplicable;
			if (notApplicable) {
				tk.CalculatedDuration__c = 0;
				tk.LevelAdjustment__c = 0;
				tk.EstimatedDuration__c = 0;
			}
		}
		CRUDUtility.updateRecords(tklst);
		if (notApplicable) {
			List<TaskRoleSummary__c> agrGrpSumlst = [
				SELECT Id, LevelAdjustment__c
				FROM TaskRoleSummary__c
				WHERE ActivityGroupId__c = :recordId
				WITH SECURITY_ENFORCED
			];
			for (TaskRoleSummary__c agSum : agrGrpSumlst) {
				agSum.LevelAdjustment__c = 0;
			}
			CRUDUtility.updateRecords(agrGrpSumlst);
			List<TaskRoleSummary__c> actSumRllst = [
				SELECT Id, LevelAdjustment__c
				FROM TaskRoleSummary__c
				WHERE ActivityId__r.ActivityGroupId__c = :recordId
				WITH SECURITY_ENFORCED
			];
			for (TaskRoleSummary__c asm : actSumRllst) {
				asm.LevelAdjustment__c = 0;
			}
			CRUDUtility.updateRecords(actSumRllst);
		}
	}

	public static Map<String, Object> taskDetailObject(Task__c tk) {
		Map<String, Object> tskMp = new Map<String, Object>();
		tskMp.put('Type', 'Task');
		tskMp.put(EstimateTreeSupport.ACTIVITY_GROUP, tk.Path__c + ' ' + tk.Name);
		tskMp.put('ActivityGroupName', tk.Name);
		tskMp.put('ActivityGroupId', tk.Id);
		tskMp.put('AdjustmentReason', tk.AdjustmentReason__c);
		tskMp.put('EstimatedDuration', tk.EstimatedDuration__c != null ? tk.EstimatedDuration__c : 0);
		tskMp.put('AdjustedDuration', tk.LevelAdjustment__c != null ? tk.LevelAdjustment__c : 0);
		tskMp.put(
			'CalculatedDuration',
			tk.CalculatedDuration__c != null ? tk.CalculatedDuration__c : 0
		);
		tskMp.put('Resourcerole', tk.ResourceRoleId__r.Name);
		tskMp.put('TaskTemplateId', tk.TemplateId__c);
		tskMp.put('NotApplicable', tk.IsNotApplicable__c);
		tskMp.put('Level2', tk.ActivityId__r.Name);
		tskMp.put('Level1', tk.ActivityId__r.ActivityGroupId__r.Name);
		return tskMp;
	}

	public static void processObject(
		TaskParameterTemplate__c taskParameterTemplate,
		Map<String, Object> mapObject,
		Map<Id, TaskParameterValue__c> taskParameterValueMap
	) {
		if (taskParameterValueMap.containsKey(taskParameterTemplate.Id)) {
			mapObject.put('TaskParameterValueId', taskParameterValueMap.get(taskParameterTemplate.Id).Id);
			if (taskParameterTemplate.DataType__c == EstimatorConstants.INTEGER_DATATYPE) {
				mapObject.put(
					'selectedValue',
					taskParameterValueMap.get(taskParameterTemplate.Id).IntegerValue__c != null
						? taskParameterValueMap.get(taskParameterTemplate.Id).IntegerValue__c
						: 0
				);
			}
			if (taskParameterTemplate.DataType__c == 'checkbox') {
				mapObject.put(
					'selectedValue',
					taskParameterValueMap.get(taskParameterTemplate.Id).BooleanValue__c
				);
			}
			if (taskParameterTemplate.DataType__c == 'Integer Tiers') {
				mapObject.put(
					'selectedValue',
					taskParameterValueMap.get(taskParameterTemplate.Id).IntegerValue__c
				);
			}
			mapObject.put('TaskName', taskParameterValueMap.get(taskParameterTemplate.Id).TaskId__r.Name);
			mapObject.put(
				'ActivityName',
				taskParameterValueMap.get(taskParameterTemplate.Id).TaskId__r.ActivityId__r.Name
			);
			mapObject.put(
				'ActivityGroupName',
				taskParameterValueMap.get(taskParameterTemplate.Id)
					.TaskId__r.ActivityId__r.ActivityGroupId__r.Name
			);
		}
	}
}