force-app/main/default/objects/NamedRangeTotal__c/NamedRangeTotal__c.object-meta.xml
<CustomObject>
    <label>Named Range Total</label>
    <nameField>
        <displayFormat>NRT-{0000000}</displayFormat>
        <label>Named Range Total</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Named Range Totals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NamedRangeTotal__c/fields/MarginPercent__c.field-meta.xml
<CustomField>
    <fullName>MarginPercent__c</fullName>
    <label>Margin %</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/NamedRangeTotal__c/fields/NetExtendedCost__c.field-meta.xml
<CustomField>
    <fullName>NetExtendedCost__c</fullName>
    <label>Net Extended Cost</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NamedRangeTotal__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NamedRangeTotal__c/fields/QuantityUOM__c.field-meta.xml
<CustomField>
    <fullName>QuantityUOM__c</fullName>
    <label>Quantity UOM</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>QuantityUOMs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/NamedRangeTotal__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipName>CellRangeTotals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/QuantityUOMs.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Hour</fullName>
    </customValue>
    <customValue>
        <fullName>Resource</fullName>
    </customValue>
    <masterLabel>Quantity UOMs</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/NamedRangeTotalTest.cls
/**
 *  Provus Services Quoting
 *  NamedRangeTotalTest
 *  @2021 Provus Inc. All rights reserved.
 */
@isTest
public with sharing class NamedRangeTotalTest extends TestBase {
	@IsTest
	static void itShouldConstructAdjustmentFromDO() {
		Quote__c testQuote = newQuote();
		NamedRangeTotal.NamedRangeTotalDO namedRangeTotalDO = new NAmedRangeTotal.NamedRangeTotalDO();
		namedRangeTotalDO.totalAmount = 200;
		namedRangeTotalDO.totalCost = 100;
		namedRangeTotalDO.marginPercent = 100;
		namedRangeTotalDO.totalQuantity = 1;

		Test.startTest();
		NamedRangeTotal namedRangeTotalMO = new NamedRangeTotal(testQuote.Id, namedRangeTotalDO);
		NamedRangeTotal__c namedRangeTotalSO = (NamedRangeTotal__c) namedRangeTotalMO.getSObject();
		System.assertNotEquals(namedRangeTotalMO, null, 'should not be null');
		System.assertEquals(
			namedRangeTotalSO.NetExtendedAmount__c,
			namedRangeTotalDO.totalAmount,
			'should copy the total revenue'
		);
		System.assertEquals(
			namedRangeTotalSO.NetExtendedCost__c,
			namedRangeTotalDO.totalCost,
			'should copy the total cost'
		);
		System.assertEquals(
			namedRangeTotalSO.Quantity__c,
			namedRangeTotalDO.totalQuantity,
			'should copy the total quantity'
		);
		System.assertEquals(
			namedRangeTotalSO.MarginPercent__c,
			namedRangeTotalDO.marginPercent,
			'should copy the margin percent'
		);
		Test.stopTest();
	}

	@IsTest
	static void itShouldCreateADOFromSO() {
		Quote__c testQuote = newQuote();
		NamedRangeTotal__c namedRangeTotalSO = new NamedRangeTotal__c(
			NetExtendedAmount__c = 200,
			NetExtendedCost__c = 100,
			MarginPercent__c = 100,
			Quantity__c = 1,
			QuantityUOM__c = 'Hour',
			QuoteId__c = testQuote.Id
		);
		CRUDUtility.insertRecords(namedRangeTotalSO);

		Test.startTest();
		NamedRangeTotal.NamedRangeTotalDO namedRangeTotalDO = NamedRangeTotal.newNamedRangeTotalDO(
			namedRangeTotalSO
		);
		System.assertEquals(
			namedRangeTotalDO.totalAmount,
			namedRangeTotalSO.NetExtendedAmount__c,
			'should copy the total revenue'
		);
		System.assertEquals(
			namedRangeTotalDO.totalCost,
			namedRangeTotalSO.NetExtendedCost__c,
			'should copy the total cost'
		);
		System.assertEquals(
			namedRangeTotalDO.totalQuantity,
			namedRangeTotalSO.Quantity__c,
			'should copy the total quantity'
		);
		System.assertEquals(
			namedRangeTotalDO.marginPercent,
			namedRangeTotalSO.MarginPercent__c,
			'should copy the margin percent'
		);
		System.assertEquals(
			namedRangeTotalDO.quantityUOM,
			namedRangeTotalSO.QuantityUOM__c,
			'should copy the quantity uom'
		);
		Test.stopTest();
	}
}