force-app/main/default/objects/NamedRangeTotal__c/NamedRangeTotal__c.object-meta.xml
<CustomObject>
    <label>Named Range Total</label>
    <nameField>
        <displayFormat>NRT-{0000000}</displayFormat>
        <label>Named Range Total</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Named Range Totals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NamedRangeTotal__c/fields/MarginPercent__c.field-meta.xml
<CustomField>
    <fullName>MarginPercent__c</fullName>
    <label>Margin %</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/NamedRangeTotal__c/fields/NetExtendedCost__c.field-meta.xml
<CustomField>
    <fullName>NetExtendedCost__c</fullName>
    <label>Net Extended Cost</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NamedRangeTotal__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NamedRangeTotal__c/fields/QuantityUOM__c.field-meta.xml
<CustomField>
    <fullName>QuantityUOM__c</fullName>
    <label>Quantity UOM</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>QuantityUOMs</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/NamedRangeTotal__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipName>CellRangeTotals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/QuantityUOMs.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Hour</fullName>
    </customValue>
    <customValue>
        <fullName>Resource</fullName>
    </customValue>
    <masterLabel>Quantity UOMs</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/NamedRangeTotal.cls
/**
 *  Provus Services Quoting
 *  NamedRangeTotal
 *  @2021 Provus Inc. All rights reserved.
 */
public with sharing class NamedRangeTotal extends ManagedObject {
	// constants
	public static final String SOBJECT_NAME = 'NamedRangeTotal__c';
	public static final String FIELD_NAME_QUOTE_ID = 'QuoteId__c';
	public static final String QUOTE_TOTAL_NAMED_RANGE = 'Quote Totals';
	public static final String LABOR_AMOUNT_NAMED_RANGE = 'Labor Amount';
	public static final String ADDON_TOTAL_NAMED_RANGE = 'Add-Ons Amount';

	public class NamedRangeTotalDO extends BaseDTO {
		public Decimal totalAmount;
		public Decimal totalCost;
		public Decimal marginPercent;
		public Decimal totalQuantity;
		public String quantityUOM;
		public Id namedRangeTotalId;
	}

	public NamedRangeTotal(Id quoteId, NamedRangeTotalDO namedRangeTotalDO) {
		super(namedRangeTotalDO);
		this.pSObject = newNamedRangeTotalSO(quoteId, namedRangeTotalDO);
	}

	public static NamedRangeTotalDO newNamedRangeTotalDO(NamedRangeTotal__c namedRangeTotalSO) {
		NamedRangeTotalDO namedRangeTotalDO = new NamedRangeTotalDO();
		namedRangeTotalDO.namedRangeTotalId = namedRangeTotalSO.Id;
		namedRangeTotalDO.totalAmount = namedRangeTotalSO.NetExtendedAmount__c;
		namedRangeTotalDO.totalCost = namedRangeTotalSO.NetExtendedCost__c;
		namedRangeTotalDO.totalQuantity = namedRangeTotalSO.Quantity__c;
		namedRangeTotalDO.quantityUOM = namedRangeTotalSO.QuantityUOM__c;
		namedRangeTotalDO.marginPercent = namedRangeTotalSO.MarginPercent__c;
		return namedRangeTotalDO;
	}

	private NamedRangeTotal__c newNamedRangeTotalSO(Id quoteId, NamedRangeTotalDO namedRangeTotalDO) {
		NamedRangeTotal__c namedRangeTotalSO = new NamedRangeTotal__c(
			NetExtendedAmount__c = namedRangeTotalDO.totalAmount,
			NetExtendedCost__c = namedRangeTotalDO.totalCost,
			MarginPercent__c = namedRangeTotalDO.marginPercent,
			Quantity__c = namedRangeTotalDO.totalQuantity,
			QuantityUOM__c = namedRangeTotalDO.quantityUOM,
			Id = namedRangeTotalDO.namedRangeTotalId,
			QuoteId__c = quoteId
		);
		return namedRangeTotalSO;
	}
}