force-app/main/default/objects/Opportunity/fields/ProposalId__c.field-meta.xml
<CustomField>
    <fullName>ProposalId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proposal</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityProductServiceQuote__c/OpportunityProductServiceQuote__c.object-meta.xml
<CustomObject>
    <label>Opportunity Product Service Quote</label>
    <nameField>
        <label>Product</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Product Service Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityProductServiceQuote__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Product Service Quotes</relationshipLabel>
    <relationshipName>OpportunityProductOpportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityProductServiceQuote__c/fields/ServiceQuoteId__c.field-meta.xml
<CustomField>
    <fullName>ServiceQuoteId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Opportunity Product Service Quotes</relationshipLabel>
    <relationshipName>OpportunityProductServiceQuote</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Proposal__c/Proposal__c.object-meta.xml
<CustomObject>
    <label>Proposal</label>
    <nameField>
        <label>Proposal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Proposal__c/fields/ExpectedStartDate__c.field-meta.xml
<CustomField>
    <fullName>ExpectedStartDate__c</fullName>
    <label>Expected Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/ProposalId__c.field-meta.xml
<CustomField>
    <fullName>ProposalId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Proposal</label>
    <referenceTo>Proposal__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CreateProposalService.cls
/**
 *  Provus Services Quoting
 *  @2021 Provus Inc. All rights reserved.
 */
public with sharing class CreateProposalService {
	public static Proposal__c generateProposal(Opportunity opportunitySO) {
		Proposal__c proposalSO = null;
		Id proposalId = opportunitySO.ProposalId__c;
		if (proposalId == null) {
			proposalSO = new Proposal__c(
				Name = 'Proposal for ' + opportunitySO.Name,
				ExpectedStartDate__c = Date.today()
			);
			CRUDUtility.insertRecords(proposalSO);
		} else {
			proposalSO = [
				SELECT Id, Name
				FROM Proposal__c
				WHERE ID = :proposalId
				WITH SECURITY_ENFORCED
				LIMIT 1
			];
		}
		return proposalSO;
	}

	public static Opportunity associateProposalIdToOpportunity(
		Opportunity opportunitySO,
		ID proposalId
	) {
		if (opportunitySO.ProposalId__c == null) {
			opportunitySO.ProposalId__c = proposalId;
			CRUDUtility.updateRecords(opportunitySO);
		}
		return opportunitySO;
	}

	public static List<Quote__c> associateProposalIdToOpportunityServiceQuotes(
		Opportunity opportunitySO,
		ID proposalId
	) {
		List<Quote__c> serviceQuotes = [
			SELECT Id, ProposalId__c
			FROM Quote__c
			WHERE
				Id IN (
					SELECT ServiceQuoteId__c
					FROM OpportunityProductServiceQuote__c
					WHERE OpportunityId__c = :opportunitySO.Id
				)
			WITH SECURITY_ENFORCED
		];
		for (Quote__c serviceQuote : serviceQuotes) {
			if (serviceQuote.ProposalId__c == null) {
				serviceQuote.ProposalId__c = proposalId;
			}
		}
		CRUDUtility.updateRecords(serviceQuotes);
		return serviceQuotes;
	}

	public static CustomClass.ActionCallbackResponse createQuotesForProposal(Proposal__c proposalSO) {
		CustomClass.ActionCallbackResponse response = new CustomClass.ActionCallbackResponse();
		DefaultProposalCallback.Errors error = new DefaultProposalCallback.Errors();
		response.error = error;
		response.isSuccess = proposalSO != null;
		return response;
	}
}