force-app/main/default/objects/Product2/recordTypes/Ancillary.recordType-meta.xml
<RecordType>
    <fullName>Ancillary</fullName>
    <active>true</active>
    <label>Ancillary</label>
</RecordType>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
                <isActive>false</isActive>
                <label>Archived</label>
            </value>
            <value>
                <fullName>Contract Negotiation</fullName>
                <isActive>false</isActive>
                <label>Contract Negotiation</label>
            </value>
            <value>
                <fullName>Contracted</fullName>
                <isActive>false</isActive>
                <label>Contracted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SObjectUtilityTest.cls
/**
 *  Provus Services Quoting
 *  SObjectUtilityTest
 *  @2021 Provus Inc. All rights reserved.
 */
@isTest
public with sharing class SObjectUtilityTest extends TestBase {
	@isTest
	static void itShouldReturnPicklistValues() {
		Test.startTest();
		List<String> picklistValues = SObjectUtility.getPicklistValuesFor(
			Schema.Quote__c.Status__c.getDescribe().getPickListValues()
		);
		Test.stopTest();

		System.assert(picklistValues.size() > 0, 'picklist values not returend properly');
	}

	@isTest
	static void itShouldReturnObjectFields() {
		Test.startTest();
		Set<String> fields = SObjectUtility.getFieldsForSObject(Quote__c.sObjectType);
		Test.stopTest();

		System.assert(fields.size() > 0, 'returned fields are empty');
	}

	@isTest
	static void itShouldReturnAncillaryRecordTypeId() {
		Test.startTest();
		Id recordId = SObjectUtility.getRecordTypeIdbyName('Product2', 'Ancillary');
		Test.stopTest();

		Id ancillaryRecordId = Schema.SObjectType.Product2.getRecordTypeInfosByName()
			.get('Ancillary')
			.getRecordTypeId();

		System.assertEquals(ancillaryRecordId, recordId, 'record id is not correct');
	}
}