force-app/main/default/objects/Product2/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <label>Product</label>
</RecordType>

force-app/main/default/objects/Product2/recordTypes/Service.recordType-meta.xml
<RecordType>
    <fullName>Service</fullName>
    <active>true</active>
    <label>Service</label>
</RecordType>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/RateCardId__c.field-meta.xml
<CustomField>
    <fullName>RateCardId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate Card</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(3 OR 1) AND (4 OR 2) AND 5</booleanFilter>
        <errorMessage
		>The Rate Card is expired/inactive during the selected service start date</errorMessage>
        <filterItems>
            <field>$Source.ServiceStartDate__c</field>
            <operation>greaterOrEqual</operation>
            <valueField>RateCard__c.EffectiveDate__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.ServiceStartDate__c</field>
            <operation>lessOrEqual</operation>
            <valueField>RateCard__c.ExpirationDate__c</valueField>
        </filterItems>
        <filterItems>
            <field>RateCard__c.EffectiveDate__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <filterItems>
            <field>RateCard__c.ExpirationDate__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <filterItems>
            <field>RateCard__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>RateCard__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RateCard__c/RateCard__c.object-meta.xml
<CustomObject>
    <label>Rate Card</label>
    <nameField>
        <label>Rate Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RateCardItem__c/RateCardItem__c.object-meta.xml
<CustomObject>
    <label>Rate Card Item</label>
    <nameField>
        <displayFormat>RCI-{0000000}</displayFormat>
        <label>Rate Card Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Card Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RateCardItem__c/fields/RateCardId__c.field-meta.xml
<CustomField>
    <fullName>RateCardId__c</fullName>
    <label>Rate Card</label>
    <referenceTo>RateCard__c</referenceTo>
    <relationshipLabel>Rate Card Items</relationshipLabel>
    <relationshipName>RateCardItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RateCardItemServiceTest.cls
/**
 *  Provus Services Quoting
 *  RateCardItemServiceTest
 *  @2021 Provus Inc. All rights reserved.
 */

@isTest
private class RateCardItemServiceTest extends TestBase {
	@testSetup
	static void setup() {
		Product2 product = new Product2(Name = 'SLA: Silver', ProductCode = 'SL9040', IsActive = true);
		CRUDUtility.insertRecords(product);

		RateCard__c rateCard = newRateCard();
		newRateCardItem(rateCard.Id, product.Id);

		Quote__c quote = newQuote();
		quote.Name = 'Rate Card Item Service Test';
		quote.RateCardId__c = rateCard.Id;
		CRUDUtility.updateRecords(quote);
	}

	@isTest
	static void itShouldGetProductsFromQuote() {
		Test.startTest();
		Quote__c quote = [SELECT Id FROM Quote__c WHERE Name = 'Rate Card Item Service Test' LIMIT 1];
		List<RateCardItem__c> rateCardItems = RateCardItemService.getRateCardItemsProducts(quote.Id);
		System.assertEquals(1, rateCardItems.size(), 'expect to have 1 product');
		Test.stopTest();
	}

	@isTest
	static void itShouldGetRateCardItemForProduct() {
		Test.startTest();
		Quote__c quote = [SELECT Id FROM Quote__c WHERE Name = 'Rate Card Item Service Test' LIMIT 1];
		Product2 prod = [SELECT Id FROM Product2 WHERE Name = 'SLA: Silver' LIMIT 1];
		List<RateCardItemService.RateCardItemStruct> rateCardItems = RateCardItemService.getAllRateCardItemsForProduct(
			quote.Id,
			prod.Id
		);
		System.assertEquals(1, rateCardItems.size(), 'expect to have 1 product');
		Test.stopTest();
	}

	@isTest
	static void itShouldGetRateCardItem() {
		Test.startTest();
		RateCard__c rateCard = [
			SELECT Id
			FROM RateCard__c
			WHERE Name = 'Skill & Resource Location'
			LIMIT 1
		];
		Product2 prod = [SELECT Id FROM Product2 WHERE Name = 'SLA: Silver' LIMIT 1];
		List<RateCardItem__c> rateCardItems = RateCardItemService.getRateCardItems(
			rateCard.Id,
			new Set<Id>{ prod.Id }
		);
		System.assertEquals(1, rateCardItems.size(), 'expect to have 1 product');
		Test.stopTest();
	}
}