force-app/main/default/objects/Product2/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <label>Product</label>
</RecordType>

force-app/main/default/objects/Product2/recordTypes/Service.recordType-meta.xml
<RecordType>
    <fullName>Service</fullName>
    <active>true</active>
    <label>Service</label>
</RecordType>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteItem__c/QuoteItem__c.object-meta.xml
<CustomObject>
    <label>Quote Item</label>
    <nameField>
        <displayFormat>QI-{0000000}</displayFormat>
        <label>Quote Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteItem__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteItem__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QuoteItem__c/fields/QuoteSectionId__c.field-meta.xml
<CustomField>
    <fullName>QuoteSectionId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Section</label>
    <referenceTo>QuoteSection__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteItemCell__c/QuoteItemCell__c.object-meta.xml
<CustomObject>
    <label>Quote Item Cell</label>
    <nameField>
        <displayFormat>QIC-{0000000}</displayFormat>
        <label>Quote Item Cell</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Item Cells</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteItemCell__c/fields/QuoteItemId__c.field-meta.xml
<CustomField>
    <fullName>QuoteItemId__c</fullName>
    <label>Quote Item</label>
    <referenceTo>QuoteItem__c</referenceTo>
    <relationshipName>QuoteItemCells</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QuoteSection__c/QuoteSection__c.object-meta.xml
<CustomObject>
    <label>Quote Section</label>
    <nameField>
        <label>Quote Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quote Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteSection__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Sections</relationshipLabel>
    <relationshipName>QuoteSections</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/QuoteItemCellServiceTest.cls
/*
 * Provus Services Quoting
 * Copyright (c) 2021 Provus Inc. All rights reserved.
 */
@IsTest
private with sharing class QuoteItemCellServiceTest extends TestBase {
	@TestSetup
	static void setup() {
		Quote__c quoteSO = newQuote();
		quoteSO.Name = 'Quote Item Cell Service Test';
		CRUDUtility.updateRecords(quoteSO);

		Id productTypeId = SObjectUtility.getRecordTypeIdbyName('Product2', 'Product');
		Product2 productSO = newProduct('Main Product', productTypeId);
		CRUDUtility.insertRecords(productSO);

		QuoteSection__c quoteSectionSO = newQuoteSection(quoteSO.Id);
		QuoteItem__c quoteItemSO = new QuoteItem__c();
		quoteItemSO.QuoteId__c = quoteSO.Id;
		quoteItemSO.QuoteSectionId__c = quoteSectionSO.Id;
		quoteItemSO.ProductId__c = productSO.Id;
		quoteItemSO.Sequence__c = 1;
		CRUDUtility.insertRecords(quoteItemSO);

		QuoteItemCell__c itemCellSO = new QuoteItemCell__c();
		itemCellSO.QuoteItemId__c = quoteItemSO.Id;
		CRUDUtility.insertRecords(itemCellSO);
	}

	@IsTest
	static void itShouldGetQuoteItemCells() {
		Test.startTest();
		List<QuoteItem__c> quoteItems = [
			SELECT Id, QuoteId__c, QuoteId__r.Name
			FROM QuoteItem__c
			WHERE QuoteId__r.Name = 'Quote Item Cell Service Test'
		];
		Set<Id> quoteItemIds = new Set<Id>();
		for (QuoteItem__c quoteItemSO : quoteItems) {
			quoteItemIds.add(quoteItemSO.Id);
		}
		List<QuoteItemCell__c> itemCells = QuoteItemCellService.getCellsForMergeFor(quoteItemIds);
		System.assert(!itemCells.isEmpty(), 'should have quote items');
		Test.stopTest();
	}

	@IsTest
	static void itShouldCreateQuoteCellItem() {
		Test.startTest();
		QuoteItem__c quoteItemSO = [
			SELECT Id, QuoteId__c, ProductId__c, QuoteSectionId__c, Sequence__c, QuoteId__r.Name
			FROM QuoteItem__c
			WHERE QuoteId__r.Name = 'Quote Item Cell Service Test'
			LIMIT 1
		];
		Product2 productSO = [SELECT Id FROM Product2 WHERE Name = 'Main Product' LIMIT 1];
		Map<String, Decimal> durationByRole = new Map<String, Decimal>{ productSO.Id + '-1' => 12 };
		Decimal itemDuration = durationByRole.get(productSO.Id + '-1');

		Decimal itemPeriodSpan = DurationCalcs.itemPeriodSpan('Months', itemDuration);

		QuoteItemCell__c itemCellSO = QuoteItemCellService.createQuoteItemCell(
				itemPeriodSpan,
				quoteItemSO,
				1
			)
			.quoteItemCell;
		System.assert(itemCellSO != null, 'it should have created quote item cell succesfully');

		Test.stopTest();
	}
}