force-app/main/default/objects/ActivityGroupTemplate__c/ActivityGroupTemplate__c.object-meta.xml
<CustomObject>
    <label>Activity Group Template</label>
    <nameField>
        <label>Activity Group Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Group Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ActivityTemplate__c/ActivityTemplate__c.object-meta.xml
<CustomObject>
    <label>Activity Template</label>
    <nameField>
        <label>Activity Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Estimate__c/Estimate__c.object-meta.xml
<CustomObject>
    <label>Estimate</label>
    <nameField>
        <label>Estimate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estimates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Estimate__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ProductId</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordTypeId</field>
            <operation>equals</operation>
            <value>Product</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Estimates</relationshipLabel>
    <relationshipName>ProductEstimates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Estimate__c/fields/RateCardId__c.field-meta.xml
<CustomField>
    <fullName>RateCardId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate Card</label>
    <referenceTo>RateCard__c</referenceTo>
    <relationshipLabel>Estimates</relationshipLabel>
    <relationshipName>Estimates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EstimateTemplate__c/EstimateTemplate__c.object-meta.xml
<CustomObject>
    <label>Estimate Template</label>
    <nameField>
        <label>Estimate Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estimate Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EstimateTemplate__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordTypeId</field>
            <operation>equals</operation>
            <value>Product</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Estimate Templates</relationshipLabel>
    <relationshipName>ProductEstimateTemplates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EstimateTemplate__c/fields/RateCardId__c.field-meta.xml
<CustomField>
    <fullName>RateCardId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate Card</label>
    <referenceTo>RateCard__c</referenceTo>
    <relationshipLabel>Estimate Templates</relationshipLabel>
    <relationshipName>EstimateTemplates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/EstimateId__c.field-meta.xml
<CustomField>
    <fullName>EstimateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estimate</label>
    <referenceTo>Estimate__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/QuoteDate__c.field-meta.xml
<CustomField>
    <fullName>QuoteDate__c</fullName>
    <label>Quote Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/RateCardId__c.field-meta.xml
<CustomField>
    <fullName>RateCardId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate Card</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(3 OR 1) AND (4 OR 2) AND 5</booleanFilter>
        <errorMessage
		>The Rate Card is expired/inactive during the selected service start date</errorMessage>
        <filterItems>
            <field>$Source.ServiceStartDate__c</field>
            <operation>greaterOrEqual</operation>
            <valueField>RateCard__c.EffectiveDate__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.ServiceStartDate__c</field>
            <operation>lessOrEqual</operation>
            <valueField>RateCard__c.ExpirationDate__c</valueField>
        </filterItems>
        <filterItems>
            <field>RateCard__c.EffectiveDate__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <filterItems>
            <field>RateCard__c.ExpirationDate__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <filterItems>
            <field>RateCard__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>RateCard__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&apos;Quote&apos;</defaultValue>
    <description>Indicates the type of quote.</description>
    <inlineHelpText>Indicates the type of quote.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Collaboration</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Scenario</fullName>
            </value>
            <value>
                <fullName>Template</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Version__c.field-meta.xml
<CustomField>
    <fullName>Version__c</fullName>
    <label>Version</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteItem__c/QuoteItem__c.object-meta.xml
<CustomObject>
    <label>Quote Item</label>
    <nameField>
        <displayFormat>QI-{0000000}</displayFormat>
        <label>Quote Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteItem__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteItem__c/fields/QuoteId__c.field-meta.xml
<CustomField>
    <fullName>QuoteId__c</fullName>
    <label>Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quote Items</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QuoteItemCell__c/QuoteItemCell__c.object-meta.xml
<CustomObject>
    <label>Quote Item Cell</label>
    <nameField>
        <displayFormat>QIC-{0000000}</displayFormat>
        <label>Quote Item Cell</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Item Cells</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteItemCell__c/fields/C001__c.field-meta.xml
<CustomField>
    <fullName>C001__c</fullName>
    <label>C001</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteItemCell__c/fields/QuoteItemId__c.field-meta.xml
<CustomField>
    <fullName>QuoteItemId__c</fullName>
    <label>Quote Item</label>
    <referenceTo>QuoteItem__c</referenceTo>
    <relationshipName>QuoteItemCells</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RateCard__c/RateCard__c.object-meta.xml
<CustomObject>
    <label>Rate Card</label>
    <nameField>
        <label>Rate Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TaskRoleSummary__c/TaskRoleSummary__c.object-meta.xml
<CustomObject>
    <label>Task Role Summary</label>
    <nameField>
        <displayFormat>TRS-{00000}</displayFormat>
        <label>Task Role Summary</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Role Summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TaskRoleSummary__c/fields/EstimateId__c.field-meta.xml
<CustomField>
    <fullName>EstimateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estimate</label>
    <referenceTo>Estimate__c</referenceTo>
    <relationshipName>RoleSummaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/LevelAdjustment__c.field-meta.xml
<CustomField>
    <fullName>LevelAdjustment__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Level Adjustment</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TaskRoleSummary__c/fields/SummaryLevel__c.field-meta.xml
<CustomField>
    <fullName>SummaryLevel__c</fullName>
    <label>Summary Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Estimate</fullName>
            </value>
            <value>
                <fullName>Activity Group</fullName>
            </value>
            <value>
                <fullName>Activity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CreateQuoteFromEstimateServiceTest.cls
/**
 *  Provus Services Quoting
 *  @2021 Provus Inc. All rights reserved.
 */
@IsTest
private class CreateQuoteFromEstimateServiceTest extends EstimatorTestsBase {
	@TestSetup
	static void setup() {
		List<Product2> resourceRoles = createResourceRoles();
		RateCard__c rateCard = newRateCardWithItems(resourceRoles);
		EstimateTemplate__c estimateTemplate = newEstimateTemplate();
		estimateTemplate.RateCardId__c = rateCard.Id;
		update estimateTemplate;
		List<ActivityGroupTemplate__c> activityGroupTemplates = createActivityGroupTemplates(
			estimateTemplate.Id
		);
		List<ActivityTemplate__c> activityTemplates = createActivityTemplates(activityGroupTemplates);

		createTaskTemplates(activityTemplates, resourceRoles);
		CreateEstimateController.createEstimateFromTemplate(estimateTemplate.Id);
	}

	@IsTest
	static void itShouldAssignQuoteItems() {
		Test.startTest();
		Quote__c quoteSO = createQuoteFromEstimate('Months');
		List<QuoteItem__c> quoteItems = [
			SELECT Id, ProductId__r.Name
			FROM QuoteItem__c
			WHERE QuoteId__c = :quoteSO.Id
			ORDER BY Sequence__c
		];
		System.assert(!quoteItems.isEmpty(), 'quote items should exist for quote');
		System.assert(
			quoteItems[0].ProductId__r.Name == 'Software Engineer' &&
			quoteItems[1].ProductId__r.Name == 'Project Manager',
			'quote item creation should follow task order'
		);
		Test.stopTest();
	}

	static Quote__c createQuoteFromEstimate(String timePeriod) {
		Estimate__c estimateObj = [
			SELECT Id, RateCardId__c
			FROM Estimate__c
			WHERE Name = 'CLM Development Estimate'
		];
		Map<String, CreateQuoteFromEstimateService.ResourceRoleDetail> resourceRoleByName = CreateQuoteFromEstimateController.getResourceRoleData(
			estimateObj.Id,
			estimateObj.RateCardId__c
		);
		QuoteDO quoteResult = CreateQuoteFromEstimateController.getEstimateDetails(estimateObj.Id);

		quoteResult.serviceStartDate = System.today();
		quoteResult.serviceEndDate = System.today().addYears(1);
		quoteResult.timePeriod = timePeriod;
		quoteResult.timePeriodsGroupMethod = 'Year';
		quoteResult.timePeriodsAlignment = 'Calendar';

		Map<Id, CreateQuoteFromEstimateService.ResourceRolePreferences> rolePrefs = new Map<Id, CreateQuoteFromEstimateService.ResourceRolePreferences>();
		for (String roleName : resourceRoleByName.keySet()) {
			CreateQuoteFromEstimateService.ResourceRolePreferences rolePref = new CreateQuoteFromEstimateService.ResourceRolePreferences();
			rolePref.role = roleName;
			rolePref.location = 'India/Bangalore';
			rolePref.skillLevel = 'L1';
			rolePrefs.put(roleName, rolePref);
		}

		Quote__c quoteSO = QuoteDO.getQuoteFromData(quoteResult);
		quoteSO.QuoteDate__c = System.today();
		quoteSO.Version__c = 1;
		quoteSO.Type__c = QuoteService.RECORDTYPE_NAME_QUOTE;
		CRUDUtility.insertRecords(quoteSO);
		List<TaskRoleSummary__c> roleSummaries = new List<TaskRoleSummary__c>();
		for (TaskRoleSummary__c roleSummary : [
			SELECT Id
			FROM TaskRoleSummary__c
			WHERE SummaryLevel__c = 'Activity Group'
		]) {
			roleSummary.LevelAdjustment__c = 1;
			roleSummaries.add(roleSummary);
		}

		CRUDUtility.updateRecords(roleSummaries);
		CreateQuoteFromEstimateService.convertEntitiesFromEstimate(quoteSO, rolePrefs);
		return quoteSO;
	}

	@IsTest
	static void shouldGetResourceRoles() {
		Test.startTest();
		Quote__c quoteSO = createQuoteFromEstimate('Months');
		Map<String, CreateQuoteFromEstimateService.ResourceRoleDetail> resourceRolesByProductId = CreateQuoteFromEstimateService.getResourceRoles(
			quoteSO.EstimateId__c,
			quoteSO.RateCardId__c
		);
		System.assert(resourceRolesByProductId.size() > 0, 'should have resource roles');
		for (
			CreateQuoteFromEstimateService.ResourceRoleDetail detail : resourceRolesByProductId.values()
		) {
			System.assert(detail.sequence != null, 'should have a sequence');
		}
		Test.stopTest();
	}

	@IsTest
	static void itShouldSetQuoteItemCellsForMonths() {
		Test.startTest();
		Quote__c quoteSO = createQuoteFromEstimate('Months');
		List<QuoteItem__c> quoteItems = [
			SELECT Id, (SELECT C001__c FROM QuoteItemCells__r)
			FROM QuoteItem__c
			WHERE QuoteId__c = :quoteSO.Id
		];
		System.assert(
			quoteItems[0].QuoteItemCells__r[0].C001__c > 0,
			'quote item cell should be non-zero'
		);
		Test.stopTest();
	}

	@IsTest
	static void itShouldSetQuoteItemCellsForDays() {
		Test.startTest();
		Quote__c quoteSO = createQuoteFromEstimate('Days');
		List<QuoteItem__c> quoteItems = [
			SELECT Id, (SELECT C001__c FROM QuoteItemCells__r)
			FROM QuoteItem__c
			WHERE QuoteId__c = :quoteSO.Id
		];
		System.assert(
			quoteItems[0].QuoteItemCells__r[0].C001__c > 0,
			'quote item cell should be non-zero'
		);
		Test.stopTest();
	}

	@IsTest
	static void itShouldSetQuoteItemCellsForWeeks() {
		Test.startTest();
		Quote__c quoteSO = createQuoteFromEstimate('Weeks');
		List<QuoteItem__c> quoteItems = [
			SELECT Id, (SELECT C001__c FROM QuoteItemCells__r)
			FROM QuoteItem__c
			WHERE QuoteId__c = :quoteSO.Id
		];
		System.assert(
			quoteItems[0].QuoteItemCells__r[0].C001__c > 0,
			'quote item cell should be non-zero'
		);
		Test.stopTest();
	}
}