force-app/main/default/objects/ActivityGroupTemplate__c/ActivityGroupTemplate__c.object-meta.xml
<CustomObject>
    <label>Activity Group Template</label>
    <nameField>
        <label>Activity Group Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Group Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ActivityGroupTemplate__c/fields/EstimateTemplateId__c.field-meta.xml
<CustomField>
    <fullName>EstimateTemplateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estimate Template</label>
    <referenceTo>EstimateTemplate__c</referenceTo>
    <relationshipLabel>Activity Groups</relationshipLabel>
    <relationshipName>ActivityGroups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ActivityTemplate__c/ActivityTemplate__c.object-meta.xml
<CustomObject>
    <label>Activity Template</label>
    <nameField>
        <label>Activity Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ActivityTemplate__c/fields/ActivityGroupTemplateId__c.field-meta.xml
<CustomField>
    <fullName>ActivityGroupTemplateId__c</fullName>
    <label>Activity Group Template</label>
    <referenceTo>ActivityGroupTemplate__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ActivityTemplate__c/fields/Path__c.field-meta.xml
<CustomField>
    <fullName>Path__c</fullName>
    <formula
	>TEXT(Sequence__c) +&apos;.&apos;+ TEXT(ActivityGroupTemplateId__r.Sequence__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Path</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task__c/Task__c.object-meta.xml
<CustomObject>
    <label>Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Task__c/fields/Path__c.field-meta.xml
<CustomField>
    <fullName>Path__c</fullName>
    <formula
	>TEXT(ActivityId__r.ActivityGroupId__r.Sequence__c) +&apos;.&apos; + TEXT(ActivityId__r.Sequence__c) +&apos;.&apos; +  TEXT(Sequence__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Path</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/ResourceRoleId__c.field-meta.xml
<CustomField>
    <fullName>ResourceRoleId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Role</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource Role</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Task__c/fields/TemplateId__c.field-meta.xml
<CustomField>
    <fullName>TemplateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task Template</label>
    <referenceTo>TaskTemplate__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TaskParameterTemplate__c/TaskParameterTemplate__c.object-meta.xml
<CustomObject>
    <label>Task Parameter Template</label>
    <nameField>
        <label>Task Parameter Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Parameter Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TaskParameterTemplate__c/fields/DataType__c.field-meta.xml
<CustomField>
    <fullName>DataType__c</fullName>
    <label>Data Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Checkbox</fullName>
            </value>
            <value>
                <fullName>Integer</fullName>
            </value>
            <value>
                <fullName>Integer Tiers</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TaskParameterTemplate__c/fields/TaskTemplateId__c.field-meta.xml
<CustomField>
    <fullName>TaskTemplateId__c</fullName>
    <label>Task Template</label>
    <referenceTo>TaskTemplate__c</referenceTo>
    <relationshipLabel>Parameters</relationshipLabel>
    <relationshipName>Parameters</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TaskParameterValueTemplate__c/TaskParameterValueTemplate__c.object-meta.xml
<CustomObject>
    <label>Task Parameter Value Template</label>
    <nameField>
        <displayFormat>TPVT-{00000}</displayFormat>
        <label>Task Parameter Value Template</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Parameter Value Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TaskParameterValueTemplate__c/fields/FromValue__c.field-meta.xml
<CustomField>
    <fullName>FromValue__c</fullName>
    <label>From Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TaskParameterValueTemplate__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <label>Label</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TaskParameterValueTemplate__c/fields/PerUnitDuration__c.field-meta.xml
<CustomField>
    <fullName>PerUnitDuration__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Per Unit Duration</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TaskParameterValueTemplate__c/fields/TaskParameterTemplateId__c.field-meta.xml
<CustomField>
    <fullName>TaskParameterTemplateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Task Parameter Template</label>
    <referenceTo>TaskParameterTemplate__c</referenceTo>
    <relationshipLabel>Parameter Values</relationshipLabel>
    <relationshipName>ParameterValues</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TaskParameterValueTemplate__c/fields/ToValue__c.field-meta.xml
<CustomField>
    <fullName>ToValue__c</fullName>
    <label>To Value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TaskTemplate__c/TaskTemplate__c.object-meta.xml
<CustomObject>
    <label>Task Template</label>
    <nameField>
        <label>Task Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TaskTemplate__c/fields/ActivityTemplateId__c.field-meta.xml
<CustomField>
    <fullName>ActivityTemplateId__c</fullName>
    <label>Activity Template</label>
    <referenceTo>ActivityTemplate__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TaskTemplate__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TaskTemplate__c/fields/Path__c.field-meta.xml
<CustomField>
    <fullName>Path__c</fullName>
    <formula>ActivityTemplateId__r.Path__c+&apos;.&apos;+ TEXT(Sequence__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Path</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TaskTemplate__c/fields/ResourceRoleId__c.field-meta.xml
<CustomField>
    <fullName>ResourceRoleId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Role</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource Role</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Task Templates</relationshipLabel>
    <relationshipName>TaskTemplates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EstimateTemplateCreator.cls
/*
 * Provus Services Quoting
 * Copyright (c) 2022 Provus Inc. All rights reserved.
 */
public with sharing class EstimateTemplateCreator {
	@Auraenabled
	public static object getActivityGroups(String estimateTemplateId) {
		return [
			SELECT Id, IsActive__c, Sequence__c, Guidance__c, Name, EstimateTemplateId__c
			FROM ActivityGroupTemplate__c
			WHERE EstimateTemplateId__c = :estimateTemplateId
			WITH SECURITY_ENFORCED
			ORDER BY Sequence__c ASC
		];
	}

	@Auraenabled
	public static object getActivities(String activityGroupTemplateId) {
		return [
			SELECT IsActive__c, Sequence__c, Guidance__c, Name, ActivityGroupTemplateId__c
			FROM ActivityTemplate__c
			WHERE ActivityGroupTemplateId__c = :activityGroupTemplateId
			WITH SECURITY_ENFORCED
			ORDER BY Sequence__c ASC
		];
	}

	@Auraenabled
	public static object getTasks(String activityTemplateId) {
		return [
			SELECT IsActive__c, Sequence__c, Guidance__c, Name, ActivityTemplateId__c, ResourceRoleId__c
			FROM TaskTemplate__c
			WHERE ActivityTemplateId__c = :activityTemplateId
			WITH SECURITY_ENFORCED
			ORDER BY Sequence__c ASC
		];
	}

	@Auraenabled
	public static object getTaskParams(String taskTemplateId) {
		return [
			SELECT
				IsActive__c,
				Name,
				Sequence__c,
				DataType__c,
				Guidance__c,
				Description__c,
				TaskTemplateId__c
			FROM TaskParameterTemplate__c
			WHERE TaskTemplateId__c = :taskTemplateId
			WITH SECURITY_ENFORCED
			ORDER BY Sequence__c ASC
		];
	}

	@Auraenabled
	public static object getTaskParamValues(String taskParamsTemplateId) {
		return [
			SELECT
				Label__c,
				PerUnitDuration__c,
				FromValue__c,
				ToValue__c,
				Sequence__c,
				TaskParameterTemplateId__r.Datatype__c
			FROM TaskParameterValueTemplate__c
			WHERE TaskParameterTemplateId__c = :taskParamsTemplateId
			WITH SECURITY_ENFORCED
			ORDER BY Sequence__c ASC
		];
	}

	@Auraenabled
	public static String upsertTaskParamsValues(
		TaskParameterTemplate__c taskParamTemplateRecord,
		List<TaskParameterValueTemplate__c> taskParamValues
	) {
		if (string.valueof(taskParamTemplateRecord.Id).startsWith(EstimatorConstants.RECORD)) {
			taskParamTemplateRecord.Id = null;
		}
		upsert taskParamTemplateRecord;
		for (TaskParameterValueTemplate__c tpVt : taskParamValues) {
			if (string.valueof(tpVt.Id).startsWith(EstimatorConstants.RECORD)) {
				tpVt.Id = null;
			}
			tpVt.TaskParameterTemplateId__c = taskParamTemplateRecord.Id;
		}
		CRUDUtility.upsertRecords(taskParamValues);
		return 'Success';
	}

	@Auraenabled
	public static void deleteRecords(List<Id> removeRecordIds) {
		List<sObject> records = new List<sObject>();
		for (Id removeRecordId : removeRecordIds) {
			records.add(removeRecordId.getSobjectType().newSobject(removeRecordId));
		}
		CRUDUtility.deleteRecords(records);
	}

	@Auraenabled
	public static String saveRecords(string recordString, string typeOf) {
		if (typeOf == EstimatorConstants.ACTIVITYGROUP_TEMPLATES) {
			List<ActivityGroupTemplate__c> ags = (List<ActivityGroupTemplate__c>) JSON.deserialize(
				recordString,
				List<ActivityGroupTemplate__c>.class
			);
			CRUDUtility.upsertRecords(ags);
		} else if (typeOf == EstimatorConstants.ACTIVITY_TEMPLATES) {
			List<ActivityTemplate__c> activityTemplates = (List<ActivityTemplate__c>) JSON.deserialize(
				recordString,
				List<ActivityTemplate__c>.class
			);
			CRUDUtility.upsertRecords(activityTemplates);
		} else if (typeOf == EstimatorConstants.TASK_TEMPLATES) {
			List<TaskTemplate__c> taskTemplates = (List<TaskTemplate__c>) JSON.deserialize(
				recordString,
				List<TaskTemplate__c>.class
			);
			CRUDUtility.upsertRecords(taskTemplates);
		} else if (typeOf == EstimatorConstants.TASK_PARAMETERS) {
			List<TaskParameterTemplate__c> taskParameters = (List<TaskParameterTemplate__c>) JSON.deserialize(
				recordString,
				List<TaskParameterTemplate__c>.class
			);
			CRUDUtility.upsertRecords(taskParameters);
		}
		return 'Success';
	}

	@AuraEnabled(cacheable=true)
	public static object getTemplateStructure(String estimateId) {
		List<ActivityGroupTemplate__c> activityGroupTemplateList = [
			SELECT Id, IsActive__c, Sequence__c, Name
			FROM ActivityGroupTemplate__c
			WHERE EstimateTemplateId__c = :estimateId
			WITH SECURITY_ENFORCED
			ORDER BY Sequence__c ASC
		];
		List<ActivityTemplate__c> activityTemplates = [
			SELECT
				Id,
				Name,
				ActivityGroupTemplateId__c,
				Path__c,
				(SELECT Id, Name, Path__c, ResourceRoleId__r.Name FROM Tasks__r ORDER BY Path__c ASC)
			FROM ActivityTemplate__c
			WHERE ActivityGroupTemplateId__c IN :activityGroupTemplateList
			WITH SECURITY_ENFORCED
			ORDER BY Path__c ASC
		];
		map<Id, List<ActivityTemplate__c>> activityTemplatesMP = new Map<Id, List<ActivityTemplate__c>>();
		for (ActivityTemplate__c at : activityTemplates) {
			if (!activityTemplatesMP.containskey(at.ActivityGroupTemplateId__c)) {
				activityTemplatesMP.put(at.ActivityGroupTemplateId__c, new List<ActivityTemplate__c>());
			}
			activityTemplatesMP.get(at.ActivityGroupTemplateId__c).add(at);
		}
		List<string> gridExpanedIds = new List<string>();
		List<Object> objlst = new List<Object>();
		for (ActivityGroupTemplate__c activityGroupTemplate : activityGroupTemplateList) {
			map<string, object> activityGroupTemplateMap = new Map<string, object>();
			activityGroupTemplateMap.put(EstimatorConstants.TYPE, 'ActivityGroupTemplate');
			activityGroupTemplateMap.put(
				'ActivityGroup',
				activityGroupTemplate.Sequence__c +
				' ' +
				activityGroupTemplate.Name
			);
			activityGroupTemplateMap.put('ActivityGroupName', activityGroupTemplate.Name);
			activityGroupTemplateMap.put('ActivityGroupId', activityGroupTemplate.Id);
			activityGroupTemplateMap.put(EstimatorConstants.ACTION_ICON, 'standard:work_type');
			activityGroupTemplateMap.put(EstimatorConstants.ICON_TYPE, 'standard:work_type_group');
			activityGroupTemplateMap.put(EstimatorConstants.ACTION_LABEL, 'Add/Edit Activities');
			gridExpanedIds.add(activityGroupTemplate.Id);
			if (activityTemplatesMP.containskey(activityGroupTemplate.Id)) {
				List<Object> activityTaskStructure = createActivityTemplates(
					activityTemplatesMP.get(activityGroupTemplate.Id),
					gridExpanedIds,
					activityGroupTemplate
				);
				activityGroupTemplateMap.put(EstimatorConstants.CHILDREN, activityTaskStructure);
			}
			objlst.add(activityGroupTemplateMap);
		}
		for (object obj : objlst) {
			map<string, object> mapRecord = (map<string, object>) obj;
			mapRecord.put('gridExpandedIds', gridExpanedIds);
			break;
		}
		return objlst;
	}

	@TestVisible
	private static List<Object> createActivityTemplates(
		List<ActivityTemplate__c> activityTemplateslist,
		List<String> gridExpanedIds,
		ActivityGroupTemplate__c activityGroupTemplate
	) {
		List<Object> activityTaskObject = new List<object>();
		for (ActivityTemplate__c activityTemplate : activityTemplateslist) {
			map<string, object> activityTemplateMap = new Map<string, object>();
			activityTemplateMap.put(EstimatorConstants.TYPE, 'ActivityTemplate');
			activityTemplateMap.put(
				'ActivityGroup',
				activityTemplate.Path__c +
				' ' +
				activityTemplate.Name
			);
			activityTemplateMap.put('ActivityGroupName', activityTemplate.Name);
			activityTemplateMap.put('ActivityGroupId', activityTemplate.Id);
			activityTemplateMap.put('ActionIcon', 'standard:task');
			activityTemplateMap.put('IconType', 'standard:work_type');
			activityTemplateMap.put('Actionlabel', 'Add/Edit Tasks');
			activityTemplateMap.put(
				EstimatorConstants.PARENT_LABEL,
				activityGroupTemplate.Name +
				'/ ' +
				activityTemplate.Name
			);
			gridExpanedIds.add(activityTemplate.Id);
			List<Object> taskObj = new List<object>();
			if (activityTemplate.Tasks__r != null) {
				for (TaskTemplate__c taskTemplate : activityTemplate.Tasks__r) {
					map<string, object> taskTemplateMap = new Map<string, object>();
					taskTemplateMap.put(EstimatorConstants.TYPE, 'TaskTemplate');
					taskTemplateMap.put('ActivityGroup', taskTemplate.Path__c + ' ' + taskTemplate.Name);
					taskTemplateMap.put('ActivityGroupName', taskTemplate.Name);
					taskTemplateMap.put('ActivityGroupId', taskTemplate.Id);
					taskTemplateMap.put('ResourceName', taskTemplate.ResourceRoleId__r.Name);
					taskTemplateMap.put('ActionIcon', 'action:edit');
					taskTemplateMap.put('IconType', 'standard:task');
					taskTemplateMap.put('Actionlabel', 'Add/Edit Task Parameters');
					taskTemplateMap.put(
						EstimatorConstants.PARENT_LABEL,
						activityGroupTemplate.Name +
						'/ ' +
						activityTemplate.Name +
						'/ ' +
						taskTemplate.Name
					);
					gridExpanedIds.add(taskTemplate.Id);
					taskObj.add(taskTemplateMap);
				}
				activityTemplateMap.put(EstimatorConstants.CHILDREN, taskObj);
			}
			activityTaskObject.add(activityTemplateMap);
		}
		return activityTaskObject;
	}
}