force-app/main/default/objects/ActivityGroupTemplate__c/ActivityGroupTemplate__c.object-meta.xml
<CustomObject>
    <label>Activity Group Template</label>
    <nameField>
        <label>Activity Group Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Group Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ActivityTemplate__c/ActivityTemplate__c.object-meta.xml
<CustomObject>
    <label>Activity Template</label>
    <nameField>
        <label>Activity Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ActivityTemplate__c/fields/ActivityGroupTemplateId__c.field-meta.xml
<CustomField>
    <fullName>ActivityGroupTemplateId__c</fullName>
    <label>Activity Group Template</label>
    <referenceTo>ActivityGroupTemplate__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EstimateTemplate__c/EstimateTemplate__c.object-meta.xml
<CustomObject>
    <label>Estimate Template</label>
    <nameField>
        <label>Estimate Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estimate Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EstimateTemplate__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordTypeId</field>
            <operation>equals</operation>
            <value>Product</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Estimate Templates</relationshipLabel>
    <relationshipName>ProductEstimateTemplates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EstimateTemplate__c/fields/RateCardId__c.field-meta.xml
<CustomField>
    <fullName>RateCardId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate Card</label>
    <referenceTo>RateCard__c</referenceTo>
    <relationshipLabel>Estimate Templates</relationshipLabel>
    <relationshipName>EstimateTemplates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RateCardItem__c/RateCardItem__c.object-meta.xml
<CustomObject>
    <label>Rate Card Item</label>
    <nameField>
        <displayFormat>RCI-{0000000}</displayFormat>
        <label>Rate Card Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Card Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RateCardItem__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Rate Card Items</relationshipLabel>
    <relationshipName>RateCardItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RateCardItem__c/fields/RateCardId__c.field-meta.xml
<CustomField>
    <fullName>RateCardId__c</fullName>
    <label>Rate Card</label>
    <referenceTo>RateCard__c</referenceTo>
    <relationshipLabel>Rate Card Items</relationshipLabel>
    <relationshipName>RateCardItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RateCardItem__c/fields/SkillLevel__c.field-meta.xml
<CustomField>
    <fullName>SkillLevel__c</fullName>
    <label>Skill Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SkillLevels</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ResourceDefault__c/ResourceDefault__c.object-meta.xml
<CustomObject>
    <label>Resource Default</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Resource Default Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resource Defaults</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ResourceDefault__c/fields/EstimateId__c.field-meta.xml
<CustomField>
    <fullName>EstimateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estimate</label>
    <referenceTo>Estimate__c</referenceTo>
    <relationshipLabel>Resource Defaults</relationshipLabel>
    <relationshipName>EstimateResourceDefaults</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ResourceDefault__c/fields/EstimateTemplateId__c.field-meta.xml
<CustomField>
    <fullName>EstimateTemplateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estimate Template</label>
    <referenceTo>EstimateTemplate__c</referenceTo>
    <relationshipLabel>Resource Defaults</relationshipLabel>
    <relationshipName>EstimateTemplateResourceDefaults</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ResourceDefault__c/fields/FieldAPIName__c.field-meta.xml
<CustomField>
    <fullName>FieldAPIName__c</fullName>
    <label>Field API Name</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ResourceDefault__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Resource Defaults</relationshipLabel>
    <relationshipName>ResourceDefaults</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ResourceDefault__c/fields/TextValue__c.field-meta.xml
<CustomField>
    <fullName>TextValue__c</fullName>
    <label>Text Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TaskTemplate__c/TaskTemplate__c.object-meta.xml
<CustomObject>
    <label>Task Template</label>
    <nameField>
        <label>Task Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TaskTemplate__c/fields/ActivityTemplateId__c.field-meta.xml
<CustomField>
    <fullName>ActivityTemplateId__c</fullName>
    <label>Activity Template</label>
    <referenceTo>ActivityTemplate__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TaskTemplate__c/fields/ResourceRoleId__c.field-meta.xml
<CustomField>
    <fullName>ResourceRoleId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Role</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource Role</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Task Templates</relationshipLabel>
    <relationshipName>TaskTemplates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/SkillLevels.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>L1</fullName>
    </customValue>
    <customValue>
        <fullName>L2</fullName>
    </customValue>
    <customValue>
        <fullName>L3</fullName>
    </customValue>
    <masterLabel>Skill Levels</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ResourceDefaults.cls
/**
 *  Provus Services Quoting
 *  ResourceDefaults
 *  @2021 Provus Inc. All rights reserved.
 */
public with sharing class ResourceDefaults {
	// constants
	public static final String SKILL_LEVEL_FIELD = Schema.RateCardItem__c.SkillLevel__c + '';
	public static final String FIELD_NAME_LOCATION_DISPLAY_NAME =
		Schema.RateCardItem__c.LocationDisplayName__c + '';

	@AuraEnabled
	public static Map<String, ResourceRoleDetail> getResourceRoleData(String estimateTemplateId) {
		Map<String, ResourceRoleDetail> resourceDefaultsByProductId = getResourceRoles(
			estimateTemplateId
		);
		return resourceDefaultsByProductId;
	}

	public static Map<String, ResourceRoleDetail> getResourceRoles(Id estimateTemplateId) {
		Map<String, ResourceRoleDetail> resourceDefaultsByProductId = new Map<String, ResourceRoleDetail>();
		Set<Id> resourceRoleIds = getResourceIds(estimateTemplateId);
		EstimateTemplate__c templateSO = [
			SELECT RateCardId__c
			FROM EstimateTemplate__c
			WHERE Id = :estimateTemplateId
			WITH SECURITY_ENFORCED
		];

		List<RateCardItem__c> rateCardItems = RateCardItemService.getRateCardItems(
			templateSO.RateCardId__c,
			resourceRoleIds
		);

		Map<String, ResourceDefault__c> resourceByProductAttribute = getResourceDefaults(
			estimateTemplateId
		);

		for (RateCardItem__c rateCardItem : rateCardItems) {
			if (!resourceDefaultsByProductId.containsKey(rateCardItem.ProductId__c)) {
				ResourceRoleDetail roleStruct = new ResourceRoleDetail();
				roleStruct.resourceRoleName = rateCardItem.ProductId__r.Name;
				roleStruct.skillLevelByLocation = new Map<String, List<String>>{
					rateCardItem.SkillLevel__c => new List<String>{ rateCardItem.LocationDisplayName__c }
				};

				roleStruct.defaultSkill = resourceByProductAttribute.get(
						rateCardItem.ProductId__c + SKILL_LEVEL_FIELD
					)
					?.TextValue__c;
				roleStruct.defaultLocation = resourceByProductAttribute.get(
						rateCardItem.ProductId__c + FIELD_NAME_LOCATION_DISPLAY_NAME
					)
					?.TextValue__c;
				roleStruct.resourceDefaultSkillId = resourceByProductAttribute.get(
						rateCardItem.ProductId__c + SKILL_LEVEL_FIELD
					)
					?.Id;
				roleStruct.resourceDefaultLocationId = resourceByProductAttribute.get(
						rateCardItem.ProductId__c + FIELD_NAME_LOCATION_DISPLAY_NAME
					)
					?.Id;

				resourceDefaultsByProductId.put(rateCardItem.ProductId__c, roleStruct);
			} else {
				ResourceRoleDetail roleStruct = resourceDefaultsByProductId.get(rateCardItem.ProductId__c);
				if (!roleStruct.skillLevelByLocation.containsKey(rateCardItem.SkillLevel__c)) {
					roleStruct.skillLevelByLocation
						.put(
							rateCardItem.SkillLevel__c,
							new List<String>{ rateCardItem.LocationDisplayName__c }
						);
				} else {
					roleStruct.skillLevelByLocation
						.get(rateCardItem.SkillLevel__c)
						.add(rateCardItem.LocationDisplayName__c);
				}
			}
		}

		return resourceDefaultsByProductId;
	}

	public class ResourceRoleDetail {
		@AuraEnabled
		public String resourceRoleName;
		@AuraEnabled
		public Map<String, List<String>> skillLevelByLocation;
		@AuraEnabled
		public String defaultSkill;
		@AuraEnabled
		public String defaultLocation;
		@AuraEnabled
		public String resourceDefaultSkillId;
		@AuraEnabled
		public String resourceDefaultLocationId;
	}

	private static Map<String, ResourceDefault__c> getResourceDefaults(Id estimateTemplateId) {
		Map<String, ResourceDefault__c> resourceByProductAttribute = new Map<String, ResourceDefault__c>();
		for (ResourceDefault__c resourceDefault : [
			SELECT Id, FieldAPIName__c, TextValue__c, ProductId__c, EstimateId__c, EstimateTemplateId__c
			FROM ResourceDefault__c
			WHERE EstimateTemplateId__c = :estimateTemplateId
			WITH SECURITY_ENFORCED
			LIMIT :SOQLConstants.SOQL_QUERY_LIMIT
		]) {
			resourceByProductAttribute.put(
				resourceDefault.ProductId__c + resourceDefault.FieldAPIName__c,
				resourceDefault
			);
		}

		return resourceByProductAttribute;
	}

	private static Set<Id> getResourceIds(Id estimateTemplateId) {
		Set<Id> resourceIds = new Set<Id>();

		for (TaskTemplate__c taskTemplate : [
			SELECT Id, ResourceRoleId__c
			FROM TaskTemplate__c
			WHERE
				ActivityTemplateId__r.ActivityGroupTemplateId__r.EstimateTemplateId__c = :estimateTemplateId
			WITH SECURITY_ENFORCED
			LIMIT :SOQLConstants.SOQL_QUERY_LIMIT
		]) {
			resourceIds.add(taskTemplate.ResourceRoleId__c);
		}

		return resourceIds;
	}

	@AuraEnabled
	public static void saveResourceDefaults(String resourceDefaultRecords) {
		List<ResourceDefault__c> resourceDefaults = (List<ResourceDefault__c>) JSON.deserialize(
			resourceDefaultRecords,
			List<ResourceDefault__c>.class
		);

		CRUDUtility.upsertRecords(resourceDefaults);
	}
}