force-app/main/default/objects/ActivityGroupTemplate__c/ActivityGroupTemplate__c.object-meta.xml
<CustomObject>
    <label>Activity Group Template</label>
    <nameField>
        <label>Activity Group Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Group Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ActivityGroupTemplate__c/fields/EstimateTemplateId__c.field-meta.xml
<CustomField>
    <fullName>EstimateTemplateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estimate Template</label>
    <referenceTo>EstimateTemplate__c</referenceTo>
    <relationshipLabel>Activity Groups</relationshipLabel>
    <relationshipName>ActivityGroups</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ActivityTemplate__c/ActivityTemplate__c.object-meta.xml
<CustomObject>
    <label>Activity Template</label>
    <nameField>
        <label>Activity Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ActivityTemplate__c/fields/ActivityGroupTemplateId__c.field-meta.xml
<CustomField>
    <fullName>ActivityGroupTemplateId__c</fullName>
    <label>Activity Group Template</label>
    <referenceTo>ActivityGroupTemplate__c</referenceTo>
    <relationshipLabel>Activities</relationshipLabel>
    <relationshipName>Activities</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/EstimateTemplate__c/EstimateTemplate__c.object-meta.xml
<CustomObject>
    <label>Estimate Template</label>
    <nameField>
        <label>Estimate Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estimate Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/EstimateTemplate__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordTypeId</field>
            <operation>equals</operation>
            <value>Product</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Estimate Templates</relationshipLabel>
    <relationshipName>ProductEstimateTemplates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/EstimateTemplate__c/fields/RateCardId__c.field-meta.xml
<CustomField>
    <fullName>RateCardId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate Card</label>
    <referenceTo>RateCard__c</referenceTo>
    <relationshipLabel>Estimate Templates</relationshipLabel>
    <relationshipName>EstimateTemplates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RateCard__c/RateCard__c.object-meta.xml
<CustomObject>
    <label>Rate Card</label>
    <nameField>
        <label>Rate Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rate Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RateCard__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>2048</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RateCardItem__c/RateCardItem__c.object-meta.xml
<CustomObject>
    <label>Rate Card Item</label>
    <nameField>
        <displayFormat>RCI-{0000000}</displayFormat>
        <label>Rate Card Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rate Card Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RateCardItem__c/fields/LocationCountry__c.field-meta.xml
<CustomField>
    <fullName>LocationCountry__c</fullName>
    <label>Location Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/RateCardItem__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Rate Card Items</relationshipLabel>
    <relationshipName>RateCardItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RateCardItem__c/fields/RateCardId__c.field-meta.xml
<CustomField>
    <fullName>RateCardId__c</fullName>
    <label>Rate Card</label>
    <referenceTo>RateCard__c</referenceTo>
    <relationshipLabel>Rate Card Items</relationshipLabel>
    <relationshipName>RateCardItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RateCardItem__c/fields/SkillLevel__c.field-meta.xml
<CustomField>
    <fullName>SkillLevel__c</fullName>
    <label>Skill Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SkillLevels</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TaskTemplate__c/TaskTemplate__c.object-meta.xml
<CustomObject>
    <label>Task Template</label>
    <nameField>
        <label>Task Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Task Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TaskTemplate__c/fields/ActivityTemplateId__c.field-meta.xml
<CustomField>
    <fullName>ActivityTemplateId__c</fullName>
    <label>Activity Template</label>
    <referenceTo>ActivityTemplate__c</referenceTo>
    <relationshipLabel>Tasks</relationshipLabel>
    <relationshipName>Tasks</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TaskTemplate__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TaskTemplate__c/fields/ResourceRoleId__c.field-meta.xml
<CustomField>
    <fullName>ResourceRoleId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resource Role</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordTypeId</field>
            <operation>equals</operation>
            <value>Resource Role</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Task Templates</relationshipLabel>
    <relationshipName>TaskTemplates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>United States</fullName>
    </customValue>
    <customValue>
        <fullName>India</fullName>
    </customValue>
    <customValue>
        <fullName>Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>Albania</fullName>
    </customValue>
    <customValue>
        <fullName>Algeria</fullName>
    </customValue>
    <customValue>
        <fullName>American Samoa</fullName>
    </customValue>
    <customValue>
        <fullName>Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>Angola</fullName>
    </customValue>
    <customValue>
        <fullName>Anguilla</fullName>
    </customValue>
    <customValue>
        <fullName>Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>Aruba</fullName>
    </customValue>
    <customValue>
        <fullName>Australia</fullName>
    </customValue>
    <customValue>
        <fullName>Austria</fullName>
    </customValue>
    <customValue>
        <fullName>Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>Belize</fullName>
    </customValue>
    <customValue>
        <fullName>Benin</fullName>
    </customValue>
    <customValue>
        <fullName>Bermuda</fullName>
    </customValue>
    <customValue>
        <fullName>Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>Bonaire, Sint Eustatius and Saba</fullName>
    </customValue>
    <customValue>
        <fullName>Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>Botswana</fullName>
    </customValue>
    <masterLabel>Countries</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/SkillLevels.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>L1</fullName>
    </customValue>
    <customValue>
        <fullName>L2</fullName>
    </customValue>
    <customValue>
        <fullName>L3</fullName>
    </customValue>
    <masterLabel>Skill Levels</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/EstimatorTestsBase.cls
/**
 *  Provus Services Quoting
 *  EstimatorTestsBase
 *  @2021 Provus Inc. All rights reserved.
 */
public with sharing abstract class EstimatorTestsBase extends TestBase {
	public static final String GUIDANCE = 'sample guidance for test';
	public static final String DESCRIPTION = 'sample description for test';

	public static EstimateTemplate__c newEstimateTemplate() {
		//Estimate Template Configuration Values
		Map<String, String> estimateTemplateValues = new Map<String, String>();
		estimateTemplateValues.put('Guidance__c', GUIDANCE);
		estimateTemplateValues.put('Description__c', DESCRIPTION);
		estimateTemplateValues.put('Name', 'CLM Development Estimate');

		EstimateTemplate__c estimateTemplate = newEstimateTemplate(estimateTemplateValues);

		CRUDUtility.insertRecords(estimateTemplate);
		return estimateTemplate;
	}

	public static List<ActivityGroupTemplate__c> createActivityGroupTemplates(Id estimateTemplateId) {
		//Activity Group Template Configuration Values
		Map<String, String> activityGroupValues = new Map<String, String>();
		activityGroupValues.put('Guidance__c', GUIDANCE);
		activityGroupValues.put('Description__c', DESCRIPTION);
		activityGroupValues.put('EstimateTemplateId__c', (String) estimateTemplateId);

		List<ActivityGroupTemplate__c> activityGroupTemplates = new List<ActivityGroupTemplate__c>();
		ActivityGroupTemplate__c activityGroupTemp1 = newActivityGroupTemplate(
			'Initiation',
			activityGroupValues,
			1
		);
		ActivityGroupTemplate__c activityGroupTemp2 = newActivityGroupTemplate(
			'Design',
			activityGroupValues,
			2
		);
		activityGroupTemplates.add(activityGroupTemp1);
		activityGroupTemplates.add(activityGroupTemp2);

		CRUDUtility.insertRecords(activityGroupTemplates);
		return activityGroupTemplates;
	}

	public static List<ActivityTemplate__c> createActivityTemplates(
		List<ActivityGroupTemplate__c> activityGroupTemplates
	) {
		Map<String, String> activityTemplateValues = new Map<String, String>();
		activityTemplateValues.put('Guidance__c', GUIDANCE);
		activityTemplateValues.put('Description__c', DESCRIPTION);
		activityTemplateValues.put('ActivityGroupTemplateId__c', (String) activityGroupTemplates[0].Id);

		List<ActivityTemplate__c> activityTemplates = new List<ActivityTemplate__c>();
		ActivityTemplate__c activityTemplate1 = newActivityTemplate(
			'Kick-Off',
			activityTemplateValues,
			1
		);
		activityTemplateValues.put('ActivityGroupTemplateId__c', (String) activityGroupTemplates[1].Id);
		ActivityTemplate__c activityTemplate2 = newActivityTemplate(
			'JIRA Setup',
			activityTemplateValues,
			1
		);
		activityTemplates.add(activityTemplate1);
		activityTemplates.add(activityTemplate2);

		CRUDUtility.insertRecords(activityTemplates);
		return activityTemplates;
	}

	public static List<TaskTemplate__c> createTaskTemplates(
		List<ActivityTemplate__c> activityTemplates,
		List<Product2> resourceRoles
	) {
		//Task Template Configuration values
		Map<String, String> taskTemplateValues = new Map<String, String>();
		taskTemplateValues.put('ResourceRoleId__c', (String) resourceRoles[0].Id);
		taskTemplateValues.put('Guidance__c', GUIDANCE);
		taskTemplateValues.put('Description__c', DESCRIPTION);
		taskTemplateValues.put('ActivityTemplateId__c', (String) activityTemplates[0].Id);

		List<TaskTemplate__c> taskTemplates = new List<TaskTemplate__c>();
		TaskTemplate__c taskTemplate1 = newTaskTemplate('Kick-Off', taskTemplateValues, 1);
		taskTemplateValues.put('ActivityTemplateId__c', (String) activityTemplates[1].Id);
		taskTemplateValues.put('ResourceRoleId__c', (String) resourceRoles[1].Id);
		TaskTemplate__c taskTemplate2 = newTaskTemplate('JIRA Process Setup', taskTemplateValues, 1);

		taskTemplates.add(taskTemplate1);
		taskTemplates.add(taskTemplate2);
		CRUDUtility.insertRecords(taskTemplates);
		return taskTemplates;
	}

	public static List<Product2> createResourceRoles() {
		Id resourceRoleTypeId = SObjectUtility.getRecordTypeIdbyName('Product2', 'Resource Role');

		List<Product2> resourceRoles = new List<Product2>();
		resourceRoles.add(newProduct('Software Engineer', resourceRoleTypeId));
		resourceRoles.add(newProduct('Project Manager', resourceRoleTypeId));
		resourceRoles.add(newProduct('Configuration Engineer', resourceRoleTypeId));

		CRUDUtility.insertRecords(resourceRoles);
		return resourceRoles;
	}

	public static EstimateTemplate__c newEstimateTemplate(Map<String, String> fieldValues) {
		EstimateTemplate__c estimateTemplate = new EstimateTemplate__c();
		estimateTemplate.IsActive__c = true;

		for (String field : fieldValues.keySet()) {
			estimateTemplate.put(field, fieldValues.get(field));
		}

		return estimateTemplate;
	}

	public static ActivityGroupTemplate__c newActivityGroupTemplate(
		String activityGroupTemplateName,
		Map<String, String> fieldValues,
		Integer sequence
	) {
		ActivityGroupTemplate__c activityGroupTemplate = new ActivityGroupTemplate__c();
		activityGroupTemplate.IsActive__c = true;
		activityGroupTemplate.Sequence__c = sequence;
		activityGroupTemplate.Name = activityGroupTemplateName;

		for (String field : fieldValues.keySet()) {
			activityGroupTemplate.put(field, fieldValues.get(field));
		}

		return activityGroupTemplate;
	}

	public static ActivityTemplate__c newActivityTemplate(
		String activityTemplateName,
		Map<String, String> fieldValues,
		Integer sequence
	) {
		ActivityTemplate__c activityTemplate = new ActivityTemplate__c();
		activityTemplate.IsActive__c = true;
		activityTemplate.Sequence__c = sequence;
		activityTemplate.Name = activityTemplateName;

		for (String field : fieldValues.keySet()) {
			activityTemplate.put(field, fieldValues.get(field));
		}

		return activityTemplate;
	}

	public static TaskTemplate__c newTaskTemplate(
		String taskTemplateName,
		Map<String, String> fieldValues,
		Integer sequence
	) {
		TaskTemplate__c taskTemplate = new TaskTemplate__c();
		taskTemplate.IsActive__c = true;
		taskTemplate.Sequence__c = sequence;
		taskTemplate.Name = taskTemplateName;

		for (String field : fieldValues.keySet()) {
			taskTemplate.put(field, fieldValues.get(field));
		}

		return taskTemplate;
	}

	public static RateCardItem__c newRateCardItem(
		Map<String, Object> rateCardItemValues,
		Id productId
	) {
		RateCardItem__c rateCardItem = new RateCardItem__c(
			IsActive__c = true,
			ProductId__c = productId
		);
		for (String field : rateCardItemValues.keySet()) {
			rateCardItem.put(field, rateCardItemValues.get(field));
		}

		return rateCardItem;
	}

	public static RateCard__c newRateCardWithItems(List<Product2> resourceRoles) {
		RateCard__c rateCard = newRateCard();
		Map<String, Object> rateCardItemValues = new Map<String, Object>();
		rateCardItemValues.put('RateCardId__c', (String) rateCard.Id);
		//rateCardItemValues.add('ProductId__c', role.Id);
		rateCardItemValues.put('LocationCountry__c', 'United States');
		rateCardItemValues.put('SkillLevel__c', 'L1');
		rateCardItemValues.put('LocationDisplayName__c', 'United States/California');

		List<RateCardItem__c> rateCardItems = new List<RateCardItem__c>();
		for (Product2 role : resourceRoles) {
			rateCardItems.add(newRateCardItem(rateCardItemValues, role.Id));
		}

		rateCardItemValues.put('SkillLevel__c', 'L2');
		for (Product2 role : resourceRoles) {
			rateCardItems.add(newRateCardItem(rateCardItemValues, role.Id));
		}

		if (!rateCardItems.isEmpty()) {
			CRUDUtility.insertRecords(rateCardItems);
		}

		return rateCard;
	}
}