force-app/main/default/objects/Estimate__c/Estimate__c.object-meta.xml
<CustomObject>
    <label>Estimate</label>
    <nameField>
        <label>Estimate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estimates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Estimate__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Estimates</relationshipLabel>
    <relationshipName>Estimates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Estimate__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Estimates</relationshipLabel>
    <relationshipName>Estimates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Estimate__c/fields/ServiceId__c.field-meta.xml
<CustomField>
    <fullName>ServiceId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.ProductId__c</field>
            <operation>equals</operation>
            <valueField>Product2.AssociatedProductId__c</valueField>
        </filterItems>
        <filterItems>
            <field>Product2.RecordTypeId</field>
            <operation>equals</operation>
            <value>Service</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Estimates</relationshipLabel>
    <relationshipName>ServiceEstimates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Estimate__c/fields/TemplateId__c.field-meta.xml
<CustomField>
    <fullName>TemplateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estimate Template</label>
    <referenceTo>EstimateTemplate__c</referenceTo>
    <relationshipLabel>Estimates</relationshipLabel>
    <relationshipName>Estimates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Product.recordType-meta.xml
<RecordType>
    <fullName>Product</fullName>
    <active>true</active>
    <label>Product</label>
</RecordType>

force-app/main/default/objects/Product2/recordTypes/Service.recordType-meta.xml
<RecordType>
    <fullName>Service</fullName>
    <active>true</active>
    <label>Service</label>
</RecordType>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/EstimateId__c.field-meta.xml
<CustomField>
    <fullName>EstimateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estimate</label>
    <referenceTo>Estimate__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/ServiceId__c.field-meta.xml
<CustomField>
    <fullName>ServiceId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>ServiceQuotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/TemplateId__c.field-meta.xml
<CustomField>
    <fullName>TemplateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Template</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Quote must have a type of template</errorMessage>
        <filterItems>
            <field>Quote__c.Type__c</field>
            <operation>equals</operation>
            <value>Template</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Quotes (Template)</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <defaultValue>&apos;Quote&apos;</defaultValue>
    <description>Indicates the type of quote.</description>
    <inlineHelpText>Indicates the type of quote.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Collaboration</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Scenario</fullName>
            </value>
            <value>
                <fullName>Template</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ServiceRecommendationsControllerTest.cls
/**
 *  Provus Services Quoting
 *  ServiceRecommendationsControllerTest
 *  @2021 Provus Inc. All rights reserved.
 */
@isTest
public with sharing class ServiceRecommendationsControllerTest extends ServiceRecommendationsTestsBase {
	private static final String PRODUCT_MAIN_PRODUCT = 'Main Product';
	private static final String PRODUCT_SERVICE_PRODUCT = 'Service Product';
	private static final String QUOTE_TEMPLATE_NAME = 'Test Quote Template';

	@testSetup
	static void setup() {
		setupData();
		createProductOpportunityLineItem();
	}

	@isTest
	static void itShouldGetServiceRecommendations() {
		Test.startTest();
		Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'Test' LIMIT 1];
		Map<Id, ServiceRecommendationsController.ServiceRecommendation> serviceRecommendations = ServiceRecommendationsController.getServiceRecommendations(
			opp.Id
		);
		System.assertEquals(1, serviceRecommendations.size(), 'There is 1 service recommendation');
		Test.stopTest();
	}

	@isTest
	static void itShouldGetNoServiceRecommendations() {
		Test.startTest();
		Opportunity opp = newOpportunity();
		Map<Id, ServiceRecommendationsController.ServiceRecommendation> serviceRecommendations = ServiceRecommendationsController.getServiceRecommendations(
			opp.Id
		);
		System.assertEquals(0, serviceRecommendations.size(), 'There are no service recommendation');
		Test.stopTest();
	}

	@isTest
	static void itShouldAddServiceRecommendations() {
		Test.startTest();
		Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'Test' LIMIT 1];
		Product2 product = [SELECT Id, Name FROM Product2 WHERE Name = :PRODUCT_MAIN_PRODUCT];
		Product2 service = [SELECT Id, Name FROM Product2 WHERE Name = :PRODUCT_SERVICE_PRODUCT];
		ServiceRecommendationsController.ServiceOpportunity serviceOpportunity = ServiceRecommendationsController.addServiceToOpportunity(
			opp.Id,
			service.Id,
			product.Id
		);
		System.assert(serviceOpportunity.success, 'Service recommendation was added successfully');
		Test.stopTest();
	}

	@isTest
	static void itShouldFailServiceRecommendationsForMissingEstimate() {
		Test.startTest();
		Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'Test' LIMIT 1];
		Product2 product = [SELECT Id, Name FROM Product2 WHERE Name = :PRODUCT_MAIN_PRODUCT];
		Product2 service = [SELECT Id, Name FROM Product2 WHERE Name = :PRODUCT_SERVICE_PRODUCT];
		Estimate__c estimate = [SELECT Id FROM Estimate__c WHERE ServiceId__c = :service.Id LIMIT 1];
		delete estimate;
		// ignore initial setup data
		List<Quote__c> quotes = [SELECT Id FROM Quote__c WHERE ServiceId__c = :service.Id];
		delete quotes;
		ServiceRecommendationsController.ServiceOpportunity serviceOpportunity = ServiceRecommendationsController.addServiceToOpportunity(
			opp.Id,
			service.Id,
			product.Id
		);
		System.assert(
			!serviceOpportunity.success,
			'It should have failed to return any service recommendations'
		);
		Test.stopTest();
	}

	@isTest
	static void itShouldGenerateFromQuoteTemplateForServiceRecommendations() {
		Test.startTest();
		Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'Test' LIMIT 1];
		Product2 product = [SELECT Id, Name FROM Product2 WHERE Name = :PRODUCT_MAIN_PRODUCT];
		Product2 service = [SELECT Id, Name FROM Product2 WHERE Name = :PRODUCT_SERVICE_PRODUCT];
		Estimate__c estimate = [SELECT Id FROM Estimate__c WHERE ServiceId__c = :service.Id LIMIT 1];
		Quote__c quoteSO = [
			SELECT Id, Name, Type__c
			FROM Quote__c
			WHERE EstimateId__c = :estimate.Id
			LIMIT 1
		];

		Quote__c quoteTemplate = QuoteService.cloneQuote(quoteSO.Id);
		quoteTemplate.Type__c = QuoteService.RECORDTYPE_NAME_TEMPLATE;
		quoteTemplate.Name = 'TEMPLATE FROM: ' + quoteSO.Name;
		quoteTemplate.AccountId__c = null;
		quoteTemplate.OpportunityId__c = null;
		quoteTemplate.TemplateId__c = null;
		update quoteTemplate;
		delete quoteSO;
		ServiceRecommendationsController.ServiceOpportunity serviceOpportunity = ServiceRecommendationsController.addServiceToOpportunity(
			opp.Id,
			service.Id,
			product.Id
		);
		System.assert(
			serviceOpportunity.success,
			'It should have created a quote and associated to opportunity for a quote template'
		);
		Test.stopTest();
	}

	@isTest
	static void itShouldGenerateFromQuoteTemplateForServiceRecommendationsWithNoEstimate() {
		Test.startTest();
		Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'Test' LIMIT 1];
		Product2 product = [SELECT Id, Name FROM Product2 WHERE Name = :PRODUCT_MAIN_PRODUCT];
		Product2 service = [SELECT Id, Name FROM Product2 WHERE Name = :PRODUCT_SERVICE_PRODUCT];
		Estimate__c estimate = [SELECT Id FROM Estimate__c WHERE ServiceId__c = :service.Id LIMIT 1];
		Quote__c quoteSO = [
			SELECT Id, Name, Type__c
			FROM Quote__c
			WHERE EstimateId__c = :estimate.Id
			LIMIT 1
		];
		quoteSO.Type__c = 'Template';
		update quoteSO;

		Quote__c quoteTemplate = QuoteService.cloneQuote(quoteSO.Id);
		quoteTemplate.ServiceId__c = service.Id;
		quoteTemplate.Type__c = QuoteService.RECORDTYPE_NAME_TEMPLATE;
		quoteTemplate.Name = 'TEMPLATE FROM: ' + quoteSO.Name;
		quoteTemplate.AccountId__c = null;
		quoteTemplate.OpportunityId__c = null;
		quoteTemplate.TemplateId__c = null;
		update quoteTemplate;
		delete estimate;
		delete quoteSO;
		ServiceRecommendationsController.ServiceOpportunity serviceOpportunity = ServiceRecommendationsController.addServiceToOpportunity(
			opp.Id,
			service.Id,
			product.Id
		);
		System.assert(
			serviceOpportunity.success,
			'It should have created a quote and associated to opportunity for a quote template'
		);
		Test.stopTest();
	}

	@isTest
	static void itShouldGenerateFromEstimateForServiceRecommendations() {
		Test.startTest();
		Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'Test' LIMIT 1];
		Product2 product = [SELECT Id, Name FROM Product2 WHERE Name = :PRODUCT_MAIN_PRODUCT];
		Product2 service = [SELECT Id, Name FROM Product2 WHERE Name = :PRODUCT_SERVICE_PRODUCT];
		Estimate__c estimate = [SELECT Id FROM Estimate__c WHERE ServiceId__c = :service.Id LIMIT 1];
		Quote__c quote = [SELECT Id FROM Quote__c WHERE EstimateId__c = :estimate.Id LIMIT 1];
		delete quote;
		ServiceRecommendationsController.ServiceOpportunity serviceOpportunity = ServiceRecommendationsController.addServiceToOpportunity(
			opp.Id,
			service.Id,
			product.Id
		);
		System.assert(
			serviceOpportunity.success,
			'It should have created a quote and associated to opportunity for an estimate'
		);
		Test.stopTest();
	}

	@isTest
	static void itShouldGenerateFromUniqueEstimatesForServiceRecommendations() {
		Test.startTest();
		Opportunity opp = [SELECT Id FROM Opportunity WHERE Name = 'Test' LIMIT 1];
		Product2 product = [SELECT Id, Name FROM Product2 WHERE Name = :PRODUCT_MAIN_PRODUCT];
		Product2 service = [SELECT Id, Name FROM Product2 WHERE Name = :PRODUCT_SERVICE_PRODUCT];
		ServiceRecommendationsController.ServiceOpportunity serviceOpportunity = ServiceRecommendationsController.addServiceToOpportunity(
			opp.Id,
			service.Id,
			product.Id
		);

		Opportunity opp2 = newOpportunity();
		opp2.Name = 'Test2';
		update opp2;
		ServiceRecommendationsController.ServiceOpportunity serviceOpportunity2 = ServiceRecommendationsController.addServiceToOpportunity(
			opp2.Id,
			service.Id,
			product.Id
		);

		System.assertNotEquals(
			serviceOpportunity.opportunityProductServiceQuote.ServiceQuoteId__c,
			serviceOpportunity2.opportunityProductServiceQuote.ServiceQuoteId__c,
			'Quotes should be unique from each other'
		);

		Test.stopTest();
	}
}