force-app/main/default/objects/Estimate__c/Estimate__c.object-meta.xml
<CustomObject>
    <label>Estimate</label>
    <nameField>
        <label>Estimate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estimates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Estimate__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Estimates</relationshipLabel>
    <relationshipName>Estimates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Estimate__c/fields/Default__c.field-meta.xml
<CustomField>
    <fullName>Default__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Default</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Estimate__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Estimates</relationshipLabel>
    <relationshipName>Estimates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Estimate__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ProductId</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.RecordTypeId</field>
            <operation>equals</operation>
            <value>Product</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Estimates</relationshipLabel>
    <relationshipName>ProductEstimates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Estimate__c/fields/RateCardId__c.field-meta.xml
<CustomField>
    <fullName>RateCardId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate Card</label>
    <referenceTo>RateCard__c</referenceTo>
    <relationshipLabel>Estimates</relationshipLabel>
    <relationshipName>Estimates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Estimate__c/fields/ServiceId__c.field-meta.xml
<CustomField>
    <fullName>ServiceId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.ProductId__c</field>
            <operation>equals</operation>
            <valueField>Product2.AssociatedProductId__c</valueField>
        </filterItems>
        <filterItems>
            <field>Product2.RecordTypeId</field>
            <operation>equals</operation>
            <value>Service</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Estimates</relationshipLabel>
    <relationshipName>ServiceEstimates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityProductServiceQuote__c/OpportunityProductServiceQuote__c.object-meta.xml
<CustomObject>
    <label>Opportunity Product Service Quote</label>
    <nameField>
        <label>Product</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Opportunity Product Service Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OpportunityProductServiceQuote__c/fields/EstimateId__c.field-meta.xml
<CustomField>
    <fullName>EstimateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estimate</label>
    <referenceTo>Estimate__c</referenceTo>
    <relationshipLabel>Opportunity Product Service Quotes</relationshipLabel>
    <relationshipName>OpportunityProductEstimate</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityProductServiceQuote__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Product Service Quotes</relationshipLabel>
    <relationshipName>OpportunityProductOpportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityProductServiceQuote__c/fields/ProductId__c.field-meta.xml
<CustomField>
    <fullName>ProductId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Opportunity Product Service Quotes (Product)</relationshipLabel>
    <relationshipName>OpportunityProductProduct</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityProductServiceQuote__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunity Product Service Quotes</relationshipLabel>
    <relationshipName>OpportunityProductProduct</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityProductServiceQuote__c/fields/ServiceId__c.field-meta.xml
<CustomField>
    <fullName>ServiceId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Opportunity Product Service Quotes</relationshipLabel>
    <relationshipName>OpportunityProductService</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityProductServiceQuote__c/fields/ServiceQuoteId__c.field-meta.xml
<CustomField>
    <fullName>ServiceQuoteId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Quote</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>Opportunity Product Service Quotes</relationshipLabel>
    <relationshipName>OpportunityProductServiceQuote</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Practice__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Practice__c.field-meta.xml
<CustomField>
    <fullName>Practice__c</fullName>
    <label>Practice</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Practices</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>Quote</label>
    <nameField>
        <label>Quote Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/EstimateId__c.field-meta.xml
<CustomField>
    <fullName>EstimateId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Estimate</label>
    <referenceTo>Estimate__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Group__c.field-meta.xml
<CustomField>
    <fullName>Group__c</fullName>
    <label>Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Groups</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/IsPrimary__c.field-meta.xml
<CustomField>
    <fullName>IsPrimary__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Practice__c.field-meta.xml
<CustomField>
    <fullName>Practice__c</fullName>
    <label>Practice</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Practices</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/RateCardId__c.field-meta.xml
<CustomField>
    <fullName>RateCardId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate Card</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(3 OR 1) AND (4 OR 2) AND 5</booleanFilter>
        <errorMessage
		>The Rate Card is expired/inactive during the selected service start date</errorMessage>
        <filterItems>
            <field>$Source.ServiceStartDate__c</field>
            <operation>greaterOrEqual</operation>
            <valueField>RateCard__c.EffectiveDate__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.ServiceStartDate__c</field>
            <operation>lessOrEqual</operation>
            <valueField>RateCard__c.ExpirationDate__c</valueField>
        </filterItems>
        <filterItems>
            <field>RateCard__c.EffectiveDate__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <filterItems>
            <field>RateCard__c.ExpirationDate__c</field>
            <operation>equals</operation>
            <value />
        </filterItems>
        <filterItems>
            <field>RateCard__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>RateCard__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/ServiceId__c.field-meta.xml
<CustomField>
    <fullName>ServiceId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>ServiceQuotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/TotalAmount__c.field-meta.xml
<CustomField>
    <fullName>TotalAmount__c</fullName>
    <label>Total Amount</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/globalValueSets/Groups.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Salesforce Implementation</fullName>
    </customValue>
    <customValue>
        <fullName>SAP Implementation</fullName>
    </customValue>
    <customValue>
        <fullName>Web &amp; Mobile Apps</fullName>
    </customValue>
    <customValue>
        <fullName>Java</fullName>
    </customValue>
    <customValue>
        <fullName>.Net</fullName>
    </customValue>
    <customValue>
        <fullName>Sales Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>Service Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>Marketing Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>SFDC Integration</fullName>
    </customValue>
    <customValue>
        <fullName>SAP C/4 HANA CUSTOMER EXP</fullName>
    </customValue>
    <customValue>
        <fullName>SAP S/4 HANA CLOUD ERP</fullName>
    </customValue>
    <customValue>
        <fullName>SAP SUCCESS FACTORS</fullName>
    </customValue>
    <customValue>
        <fullName>SAP ARIBA</fullName>
    </customValue>
    <customValue>
        <fullName>SAP BUSINESS OBJECTS</fullName>
    </customValue>
    <customValue>
        <fullName>SAP ACTIVATE</fullName>
    </customValue>
    <customValue>
        <fullName>SAP CLOUD PLATFORM Integration</fullName>
    </customValue>
    <customValue>
        <fullName>Oracle Cloud</fullName>
    </customValue>
    <customValue>
        <fullName>Oracle Infrastructure</fullName>
    </customValue>
    <customValue>
        <fullName>Oracle Live</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Web Services Basics</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Computer Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Network Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Storage Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Database Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Analytics Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Application Services</fullName>
    </customValue>
    <customValue>
        <fullName>Amazon Web Services Resources</fullName>
    </customValue>
    <customValue>
        <fullName>AI + Machine Learning</fullName>
    </customValue>
    <customValue>
        <fullName>Analytics</fullName>
    </customValue>
    <customValue>
        <fullName>Blockchain</fullName>
    </customValue>
    <masterLabel>Groups</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Practices.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Custom Development</fullName>
        <label>Web Development</label>
    </customValue>
    <customValue>
        <fullName>Cloud Consulting</fullName>
    </customValue>
    <customValue>
        <fullName>Outsourcing</fullName>
    </customValue>
    <customValue>
        <fullName>AWS</fullName>
    </customValue>
    <customValue>
        <fullName>GCP</fullName>
    </customValue>
    <customValue>
        <fullName>DevOps</fullName>
    </customValue>
    <customValue>
        <fullName>Java</fullName>
    </customValue>
    <customValue>
        <fullName>Python</fullName>
    </customValue>
    <customValue>
        <fullName>Architect</fullName>
    </customValue>
    <customValue>
        <fullName>SAP</fullName>
    </customValue>
    <customValue>
        <fullName>SFDC</fullName>
    </customValue>
    <customValue>
        <fullName>Oracle</fullName>
    </customValue>
    <customValue>
        <fullName>CI/CD</fullName>
    </customValue>
    <customValue>
        <fullName>ERP</fullName>
        <isActive>false</isActive>
        <label>ERP</label>
    </customValue>
    <customValue>
        <fullName>CRM</fullName>
        <isActive>false</isActive>
        <label>CRM</label>
    </customValue>
    <masterLabel>Practices</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ServiceRecommendationsSupport.cls
/**
 *  Provus Services Quoting
 *  ServiceRecommendationsSupport
 *  @2021 Provus Inc. All rights reserved.
 */
public with sharing class ServiceRecommendationsSupport {
	public class OpportunityLineItemRequest {
		public List<OpportunityLineItem> opportunityLineItems;
		public Id opportunityId;
		public Id productId;
		public Id pricebookEntryId;
		public NamedRange.NamedRangeDO quoteTotalNamedRange;

		public OpportunityLineItemRequest() {
			this.opportunityLineItems = new List<OpportunityLineItem>();
		}
	}

	public class OpportunityProductServiceQuoteRequest {
		public String name;
		public OpportunityLineItem serviceLineItem;
		public OpportunityLineItem productLineItem;
		public Quote__c serviceQuote;
		public Estimate__c serviceEstimate;
	}

	public static Set<Id> getOpportunityProductIds(Id opportunityId) {
		List<OpportunityLineItem> opportunityProducts = getOpportunityProducts(opportunityId);
		Map<Id, OpportunityLineItem> opportunityProductsByProductId = new Map<Id, OpportunityLineItem>();
		for (OpportunityLineItem opportunityProduct : opportunityProducts) {
			opportunityProductsByProductId.put(opportunityProduct.Product2Id, opportunityProduct);
		}
		return opportunityProductsByProductId.keySet();
	}

	private static List<OpportunityLineItem> getOpportunityProducts(Id opportunityId) {
		QueryRequest queryRequest = new QueryRequest(Schema.SObjectType.OpportunityLineItem.getName());
		queryRequest.requestedFields = new Set<String>{ Schema.OpportunityLineItem.Product2Id + '' };
		queryRequest.setFilterBy(
			new Map<String, String>{ Schema.OpportunityLineItem.OpportunityId + '' => opportunityId }
		);
		return (List<OpportunityLineItem>) SOQLUtility.querySObject(queryRequest);
	}

	public static List<Estimate__c> getEstimatesForServiceProducts(Set<Id> serviceProducts) {
		Map<String, String> orderBy = new Map<String, String>{
			Schema.Estimate__c.Default__c + '' => SOQLConstants.SORT_DESC,
			Schema.Estimate__c.CreatedDate + '' => SOQLConstants.SORT_DESC
		};
		QueryRequest queryRequest = new QueryRequest(Schema.SObjectType.Estimate__c.getName());
		queryRequest.requestedFields = new Set<String>{
			SObjectUtility.FIELD_NAME,
			Schema.Estimate__c.ServiceId__c + '',
			Schema.Estimate__c.RateCardId__c + '',
			Schema.Estimate__c.AccountId__c + '',
			Schema.Estimate__c.Description__c + '',
			Schema.Estimate__c.OpportunityId__c + '',
			Schema.Estimate__c.RateCardId__c + '',
			SystemUtility.getRName(Schema.Estimate__c.ServiceId__c) +
			'.' +
			Schema.Product2.Practice__c,
			SystemUtility.getRName(Schema.Estimate__c.ServiceId__c) +
			'.' +
			Schema.Product2.Group__c
		};
		queryRequest.setFilterBy(
			new Map<String, Set<Id>>{ Schema.Estimate__c.ServiceId__c + '' => serviceProducts }
		);
		queryRequest.fieldBySortOrder = orderBy;
		return (List<Estimate__c>) SOQLUtility.querySObject(queryRequest);
	}

	public static List<Quote__c> getQuotesForEstimates(Set<Id> estimates) {
		Map<String, String> orderBy = new Map<String, String>{
			Schema.Quote__c.IsPrimary__c + '' => SOQLConstants.SORT_DESC,
			Schema.Quote__c.CreatedDate + '' => SOQLConstants.SORT_DESC
		};
		QueryRequest queryRequest = new QueryRequest(Schema.SObjectType.Quote__c.getName());
		queryRequest.requestedFields = new Set<String>{ Schema.Quote__c.TotalAmount__c + '' };
		queryRequest.setFilterBy(
			new Map<String, Set<Id>>{ Schema.Quote__c.EstimateId__c + '' => estimates }
		);
		queryRequest.fieldBySortOrder = orderBy;
		return (List<Quote__c>) SOQLUtility.querySObject(queryRequest);
	}

	public static OpportunityProductServiceQuote__c insertOpportunityProductServiceQuote(
		OpportunityProductServiceQuoteRequest opportunityProductServiceQuoteRequest
	) {
		OpportunityProductServiceQuote__c opportunityProductServiceQuote = new OpportunityProductServiceQuote__c();
		opportunityProductServiceQuote.Name = opportunityProductServiceQuoteRequest.Name;
		opportunityProductServiceQuote.ProductId__c = opportunityProductServiceQuoteRequest.productLineItem.Id;
		opportunityProductServiceQuote.ServiceId__c = opportunityProductServiceQuoteRequest.serviceLineItem.Id;
		opportunityProductServiceQuote.Service__c = opportunityProductServiceQuoteRequest.serviceLineItem.Product2Id;
		opportunityProductServiceQuote.ServiceQuoteId__c = opportunityProductServiceQuoteRequest.serviceQuote.Id;
		opportunityProductServiceQuote.OpportunityId__c = opportunityProductServiceQuoteRequest.serviceQuote.OpportunityId__c;
		if (opportunityProductServiceQuoteRequest.serviceEstimate != null) {
			// if there is an estimate, but there does not have to be one if we have a quote template
			opportunityProductServiceQuote.EstimateId__c = opportunityProductServiceQuoteRequest.serviceEstimate.Id;
		}
		return (OpportunityProductServiceQuote__c) CRUDUtility.insertRecords(
			opportunityProductServiceQuote
		);
	}

	public static List<OpportunityLineItem> upsertOpportunityLineItem(
		OpportunityLineItemRequest opportunityLineItemRequest
	) {
		List<OpportunityLineItem> opportunityLineItems = new List<OpportunityLineItem>();
		for (
			OpportunityLineItem opportunityLineItem : opportunityLineItemRequest.opportunityLineItems
		) {
			Id opportunityId = opportunityLineItemRequest.opportunityId;
			Id productId = opportunityLineItemRequest.productId;
			Id pricebookEntryId = opportunityLineItemRequest.pricebookEntryId;
			if (opportunityId != null) {
				opportunityLineItem.OpportunityId = opportunityId;
			}
			if (productId != null) {
				opportunityLineItem.Product2Id = productId;
			}
			if (pricebookEntryId != null) {
				opportunityLineItem.PricebookEntryId = pricebookEntryId;
			}
			opportunityLineItem.Quantity = 1;
			Decimal totalAmount = 0;
			if (
				opportunityLineItemRequest.quoteTotalNamedRange != null &&
				opportunityLineItemRequest.quoteTotalNamedRange.relatedTotal != null &&
				opportunityLineItemRequest.quoteTotalNamedRange.relatedTotal.totalAmount != null
			) {
				totalAmount = opportunityLineItemRequest.quoteTotalNamedRange.relatedTotal.totalAmount;
			}
			opportunityLineItem.UnitPrice = totalAmount;

			opportunityLineItems.add(opportunityLineItem);
		}
		return (List<OpportunityLineItem>) CRUDUtility.upsertRecords(opportunityLineItems);
	}

	public static List<OpportunityProductServiceQuote__c> getOpportunityProductServiceQuotes(
		Map<String, String> fieldValues
	) {
		Set<String> requestedFields = new Set<String>{
			Schema.OpportunityProductServiceQuote__c.ServiceId__c + '',
			Schema.OpportunityProductServiceQuote__c.ProductId__c + ''
		};
		QueryRequest queryRequest = new QueryRequest(
			Schema.SObjectType.OpportunityProductServiceQuote__c.getName()
		);
		queryRequest.requestedFields = requestedFields;
		queryRequest.setFilterBy(fieldValues);
		List<OpportunityProductServiceQuote__c> opportunityProductServiceQuotes = (List<OpportunityProductServiceQuote__c>) SOQLUtility.querySObject(
			queryRequest
		);
		return opportunityProductServiceQuotes;
	}

	public static OpportunityProductServiceQuote__c getOpportunityProductServiceQuote(
		Map<String, String> fieldValues
	) {
		List<OpportunityProductServiceQuote__c> opportunityProductServiceQuotes = getOpportunityProductServiceQuotes(
			fieldValues
		);

		OpportunityProductServiceQuote__c opportunityProductServiceQuote = null;
		if (!opportunityProductServiceQuotes.isEmpty()) {
			opportunityProductServiceQuote = opportunityProductServiceQuotes[0];
		}
		return opportunityProductServiceQuote;
	}

	public static void deleteOpportunityProductServiceQuote(
		List<OpportunityLineItem> opportunityLineItems
	) {
		Map<Id, OpportunityLineItem> opportunityLineItemById = new Map<Id, OpportunityLineItem>(
			opportunityLineItems
		);
		List<OpportunityProductServiceQuote__c> recordsToDelete = new List<OpportunityProductServiceQuote__c>();

		// services
		QueryRequest serviceQueryRequest = new QueryRequest(
			Schema.SObjectType.OpportunityProductServiceQuote__c.getName()
		);
		serviceQueryRequest.setFilterBy(
			new Map<String, Set<Id>>{
				Schema.OpportunityProductServiceQuote__c.ServiceId__c +
				'' => opportunityLineItemById.keySet()
			}
		);
		recordsToDelete.addAll(
			(List<OpportunityProductServiceQuote__c>) SOQLUtility.querySObject(serviceQueryRequest)
		);

		// products
		QueryRequest productQueryRequest = new QueryRequest(
			Schema.SObjectType.OpportunityProductServiceQuote__c.getName()
		);
		productQueryRequest.setFilterBy(
			new Map<String, Set<Id>>{
				Schema.OpportunityProductServiceQuote__c.ProductId__c +
				'' => opportunityLineItemById.keySet()
			}
		);
		recordsToDelete.addAll(
			(List<OpportunityProductServiceQuote__c>) SOQLUtility.querySObject(productQueryRequest)
		);

		CRUDUtility.deleteRecords(recordsToDelete);
	}
}